### ISSUE TITLE
Features in decluttered layer are above other layer, ignoring zIndex

### ISSUE THREAD

**Issue by M393** [openlayers/openlayers#10096]
**Describe the bug**
Feature in decluttered layer is above feature of other layer with higher zIndex.

**To Reproduce**
https://codesandbox.io/s/priceless-hugle-3fxkb
I set both the layer zIndex and the feature style zIndex to the same value for each layer.
for the layer with decluttering zIndex is set to 1, for the one without it is set to 2.
The feature from the layer with decluttering is drawn above the feature of the other layer with higher zIndex.

**Expected behavior**
Decluttering should not influence the zIndex order and higher zIndex should be above lower zIndex.

**Comment by ahocevar** [comment]
This behavior is caused by an optimization where OpenLayers tries to combine multiple layers on a single canvas. To opt out of this behavior, configure at least one of the layers with a `className` other than `ol-layer`. See my updated codesandbox, where I set the `className` of `otherLayer` to `otherLayer`: https://codesandbox.io/s/exciting-feather-klyyl.

**Comment by M393** [comment]
Thank you, this was indeed the problem.

Is this behaviour documented somewhere? 
I did not see it in the ol.layer.Vector documentation.

**Comment by jahow** [comment]
It has been documented in `ol/layer/Layer`:
https://openlayers.org/en/latest/apidoc/module-ol_layer_Layer-Layer.html

Agreed, it'd be nice to have something mentioned in `ol/layer/Vector` specifically for declutter.

**Comment by mike-000** [comment]
It should also be mentioned in ol/layer/VectorTile https://stackoverflow.com/questions/58442141/openlayers-6-adding-second-vector-tile-layer-causes-base-layer-labels-to-disap
