### ISSUE TITLE
When a map have a heatmap layer, funciton hasFeatureAtPixel will throw a error

### ISSUE THREAD

**Issue by callmegaga** [openlayers/openlayers#10100]
On demo https://openlayers.org/en/latest/examples/heatmap-earthquakes.html

Call function hasFeatureAtPixel, will throw a error

The Error message is "Uncaught AssertionError: Assertion failed. See https://openlayers.org/en/v6.0.1/doc/errors/#66 for details."

But I can't find a way to solve it

On 5.3.3 it's OK

**Comment by jahow** [comment]
There is no hit detection on the heatmap layer. WebGL layers must have specific shaders for the hit detection to happen, which is the case on this example:
https://openlayers.org/en/latest/examples/icon-sprite-webgl.html

**Comment by ahocevar** [comment]
Thanks for reporting this @callmegaga. Since `ol/layer/Heatmap` is part of the official API, the fact that an exception is thrown here is a regression. In v5.3, hit detection did work on the Heatmap layer indeed.

We can either document in the upgrade notes that hit detection is not available for `ol/layer/Heatmap` any more, or implement hit detection for it.

**Comment by jahow** [comment]
> We can either document in the upgrade notes that hit detection is not available for ol/layer/Heatmap any more, or implement hit detection for it.

Implementing it should be straightforward enough, I'll try to make a PR with this ASAP.
