### ISSUE TITLE
Selecting a feature programatically does not apply the selected style to it

### ISSUE THREAD

**Issue by Chris1234567899** [openlayers/openlayers#10165]
**Describe the bug**
It might be possible to select a feature programatically by pushing it to the selection and dispatching the accoring event. This triggers the "select" event. However the style of the feature is not updating.

**To Reproduce**
I have a function like:
```
public selectFeature(featureId) {
    let feature: Feature = this.vectorSource.getFeatureById(featureId)
    console.log("selectedFeature", this.select)
    if (feature) {
      this.select.getFeatures().push(feature)
      this.select.dispatchEvent({
        type: 'select',
        selected: [feature],
        deselected: []
      });
    }
  }
[...]
 this.select.on("select", ev => {
      console.log("on select", ev);
})
```
where this.select is the Select Interaction. Clicking on a feature in the map highlights the feature normally in the selected style. However calling the function to select the according feature, does not. The on select is triggered for both, so I would expect the style to be applied equally.
Seems like a bug to me.

**Expected behavior**
Update the style accordingly.

Using ol 6.0.1

**Comment by ger-benjamin** [comment]
I think I have the same issue. I'll explain it within one of the ol example:

**Describe the bug**:
Same as the post above.

**To Reproduce**
 
- Use the example: https://openlayers.org/en/latest/examples/select-features.html
 - In the js example, create a `const selections = new Collection();`

Then:
 - If you use this `selections` as a option.feature of **one** `Select`, the style is still updated.
 - If you use this `selections` as a option.feature of **multiple** `Select`, the style is never removed.

So this won't work:
```
const selections = new Collection(); 

const selectSingleClick = new Select({
  features: selections,
});

const selectClick = new Select({
  condition: click,
  features: selections,
});
```
(but if you set one of the two `features` option to null, it works)

**Expected behavior**
Update the style accordingly.

Using ol 6.1.1

**Comment by mathudak** [comment]
This issue is still present in the version `ol: ^8.2.0`.
Are there any plans to fix it, or is it not considered important? If so, is there some useable workaround?
