### ISSUE TITLE
“map extent” in Ionic

### ISSUE THREAD

**Issue by arogges** [openlayers/openlayers#10222]
I've a problem with Ionic and OpenLayers: starting from my Angular component (that works well), when I do map.getView().fit(myExtent) inside a Ionic Component the result isn't a good fit, but it seems a wrong zoom calculation. Do you think can be a "resolution" and/or pixel dimension problem?

in component
```
let myExtent = mylayer.getSource().getExtent();
//Angular component and Ionic component on console.log write the same values!

myMap.getView().fit(myExtent);
//in Angular it works correct, in Ionic not
```
in HTML

`<div class="map" id="map"></div>`

in css

```
.map{
height:300px;
width:100%;
}

```

**Comment by bvx89** [comment]
It's kinda hard to understand what is wrong with the extent calculation if you don't describe it properly. Maybe add some screenshots, and show the differences between ionic and angular on the view extent _after_ you've run the `fit`-method.

Also, are you testing the applications on different devices (ionic on phone, angular on desktop/laptop)? If you are using a mobile phone for the ionic version, the map must be zoomed further out in order to show everything inside the extent compared to a bigger desktop/laptop monitor.

Pixel dimensions are taken from the browser Window, ionic shouldn't have an effect on that compared to angular.

**Comment by arogges** [comment]
I'm testing, for now, with browser, but I've found a "big" difference: in Angular I use version 5.3.0 of OpenLayers, in Ionic the version is 6.1.0

**Comment by ahocevar** [comment]
The difference might be because of the new constraint system in v6. See https://github.com/openlayers/openlayers/blob/master/changelog/v6.0.0.md#the-view-extent-option-now-applies-to-the-whole-viewport.

To verify that, configure the `view` in your OpenLayers 6.x map with
```js
{
  constrainCenterOnly: true,
  multiWorld: true
}
```

**Comment by arogges** [comment]
Thks, it works!
