### ISSUE TITLE
This is  more of a procedural question about interaction layer

### ISSUE THREAD

**Issue by Knight2601** [openlayers/openlayers#10220]
Is it possible to draw a layer above an interaction layer?
i've tried this a number of ways and the interaction layer always takes precidence, so im sure i'm doing something wrong.

I have a map layer, followed by three image/line feature layers, the interaction layer, then another layer to use for overlay text and line from center to mouse pointer during the interaction.
the overlay text layer shows a measurement in realtime as the user draws a circle, so thay can see the radius in units of the interaction until the drawend callback is hit.
this text always is being drawn under the interaction, regardless of layer ordering, zIndex setting.

Is this possible?

**Comment by jahow** [comment]
Not 100% positive but you could put the measurement text in another unmanaged layer* with `testLayer.setMap(map)`, hopefully this will get rendered above the draw interaction overlay.

*unmanaged layers are not part of the regular map layers, they are basically overlays. Instead of doing `map.addLayer(myOverlay)`, you have to do `myOverlay.setMap(map)`.

**Comment by Knight2601** [comment]
Thanks for the reply, I fixed it by setting a different class for the overlaid text layer, then in the css, set that layer to z-index:99; bringing to the front of the draw stack 😊

Andy

**Comment by jahow** [comment]
Well, this is an unconvential solution to say the least, but at least you're making good use of the power provided by the new composite rendering in OL6 :)

Cheers
