### ISSUE TITLE
Missing documentation of VectorTileSource#refresh

### ISSUE THREAD

**Issue by RobertOrthofer** [openlayers/openlayers#10317]
VectorTileSource inherits the class `ol/source/Tile`, which has the method `refresh`. This is missing from the documentation.

**Comment by ahocevar** [comment]
This is still an issue. @MoonE, since you have been working on the API docs recently: do you think you could look into this one too?

**Comment by MoonE** [comment]
I don't think it is fixed, the method doesn't show up here:
https://openlayers.org/en/master/apidoc/module-ol_source_VectorTile-VectorTile.html
I believe https://github.com/jsdoc/jsdoc/issues/1725 is related to this

When the jsdoc comment for `ol/source/Tile#refresh` is removed it shows up in the docs, but links to `ol/source/Source#refresh` instead of the direct parent method.
