### ISSUE TITLE
Selected feature not displaying beyond resolution

### ISSUE THREAD

**Issue by Malgier** [openlayers/openlayers#10338]
I've just updated my project to OL6 and previously i was able to view a selected feature on a vectorLayer outside of the maxResolution when the none selected features would disappear, however now with OL 6 all of the features are disappearing once outside of the maxResolution, is this expected behaviour?

**Comment by jahow** [comment]
Yes, the Select interaction does not manage a separate layer any more, it simply manipulates the selected features' style. Thus, if the feature is part of a layer which is not visible because of scale, then the selected feature will not be visible as well.

The simplest solution is probably to give a collection to the select interaction and use this collection for another layer that will be visible at all times. Something like:
```js
const collection = new Collection();
const select = new SelectInteraction({
  features: collection,
  style: null,
  layers: [vectorLayer]
});
const highlightLayer = new VectorLayer({
  source: new VectorSource({
    features: collection,
    style: highlightStyle
  })
});
```

I'm marking this as documentation-related since this block seems out of date:
https://github.com/openlayers/openlayers/blob/e4be8309f7880c322c9850a634dab8b6adc30c62/src/ol/interaction/Select.js#L137-L151
