### ISSUE TITLE
Offscreen Canvas

### ISSUE THREAD

**Issue by delaneyj** [openlayers/openlayers#10404]
I'd liked to use OpenLayers to generate textures to be used in a ThreeJS scene.  Ideally this could be done in an [OffscreenCanvas](https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas) on a separate web worker.  I don't see a way to do this currently.

If that's not possible is there an example of having direct control over the canvas used by the `Map` to render to instead it creating/removing the canvas from a container div (The `target` in the Map constructor)? 

**Describe the solution you'd like**
I don't know if its a situation of lack of documentation/examples or missing features.  Looking more for guidance than anything else at this stage.

**Comment by delaneyj** [comment]
Added a query to the [mailing group](https://groups.google.com/forum/#!forum/openlayers-dev), but doesn't seem to be very activate so reopening here.

**Comment by ahocevar** [comment]
There are examples that show how to render directly to a layer canvas, or where custom content is rendered as layer canvas. See e.g. the following examples:

* https://openlayers.org/en/latest/examples/feature-animation.html
* https://openlayers.org/en/latest/examples/d3.html

Using these techniques (especially from the latter example), you should be able to prepare your content in an Offscreen Canvas, and render that as layer canvas afterwards.

**Comment by delaneyj** [comment]
@ahocevar thanks for the response.  I did see that adding a Canvas based layer to a map instance is very easy but I'm basically trying to do the opposite procedure.  I want something similar to..

`const m = new Map({target:HTMLCanvasInstance||OffscreenCanvasInstance})`.  Instead of openlayers taking control of a div and adding its own canvas I want to say _*do all your final composite rendering to a specific predefined canvas*_.  Right now it appears openlayers will delete/add canvases from the target div and I want known static final target.  

Does this make more sense?

**Comment by jahow** [comment]
You'd essentially have to create the map in the worker, which is most likely to fail since the rendering code relies on APIs unavailable to workers. For a start, `requestAnimationFrame` (see https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Functions_and_classes_available_to_workers).

Although there is an ongoing effort to make part of the library usable outside of the browser main thread (see #8846), having a map actually render this way is currently not possible.

**Comment by delaneyj** [comment]
@jahow so there seems to be two separate issues here.

1. If I stay on the main thread could I set a final target canvas instead of a div that the `Map` class uses to make its own?
2. If the rendering was explicit ala `map.render()` would OffscreenCanvas be possible?

**Comment by jahow** [comment]
>     1. If I stay on the main thread could I set a final target canvas instead of a div that the `Map` class uses to make its own?

The target has to be a div, but the map will render to one or many canvases which you can then reuse in your ThreeJS scene. If you only use default vector and image layers, you will most likely end up with a single canvas which will make things much simpler for you.

>     2. If the rendering was explicit ala `map.render()` would OffscreenCanvas be possible?

There already are `map.render` and `map.renderSync` methods, the issue here is that the whole rendering code relies on a lot of APIs unavailable to workers so you will likely end up with errors everywhere. It would be nice to try it though.

**Comment by delaneyj** [comment]
> Also the target div can be detached from the web page, which means everything will be done "behind the scenes" (although still on the main thread).

Awesome, didn't know this would be ok.  At least detaching will get me most of the way there.  I noticed when toggling layers' visibility that the underlying canvas would get removed and a new one added.  Was mainly trying to avoid losing a canvas context without some kind of events.  Having a way to set the final composite canvas target would make this easier.

**Comment by jahow** [comment]
This is not really possible as it is currently. You will have to work around this one way or another.

**Comment by ahocevar** [comment]
We now have an OffscreenCanvas example. See #10828.
