### ISSUE TITLE
Heatmap : Multiple Javascript VM instance 

### ISSUE THREAD

**Issue by Papasmoi** [openlayers/openlayers#10468]
I have integrated in my Angular project, an openLayer heatmap.

The rendering I get is fine but I noticed that my browser was losing performance and then freezes at each change of « view » (reload the component) .

I searched for the solution to my problem and I noticed that in the Javascript VM instance of Google Chrome, an instance is duplicated each time I reload the heatmap.

<img width="1673" alt="Capture d’écran 2019-12-30 à 14 40 02" src="https://user-images.githubusercontent.com/59365439/71585012-6199d300-2b15-11ea-83f1-e49a9a3fc005.png">

Would you have a way to fix the problem? 

Thanks in advance !

**Comment by jahow** [comment]
This may have been fixed with https://github.com/openlayers/openlayers/pull/10235, what version of OL do you use?

Also the heatmap layer must be disposed using `dispose()`, otherwise the webgl worker will stay around (like in your screenshot), so this depends on how you get rid of your map and layers in your angular component.
