### ISSUE TITLE
does there exist a document/cheatsheet/guide to putting openlayers code into npm? 

### ISSUE THREAD

**Issue by nufosmatic** [openlayers/openlayers#10475]
I am not asking for a new document, just haven't found one, and the search is becoming frustrating.

We implemented an OpenLayers solution some years ago using ol2 (http://www.nufosmatic.com). The results were very satisfactory, and the new mapping capabilities allowed us to expand beyond what our circa 2004 primitive maps allowed.

However, like anything, ol2 will become stale and unusable. But, the leap to ol3+ is a big one, and some of the features of ol2 we settled upon are just simply not there.

We have found some ol3+ examples that seem to address our needs, but the v6.1.1 examples all seem to be abstracted to NPM. Now, we find some features of NPM very interesting (the development server/code and test process is really very nice), but there is this nasty bit of having to re-code all of the function names because of the NPM import process. OK, we've got a lot of re-coding to do anyway, and that's probably not no big a problem.

We have also found some third-party ol3+ examples that address missing features in ol2 that are NOT addressed in the ol3+ examples. However, bringing these examples under NPM has been most frustrating. It seems that eventually we get to "X is not a constructor" or "X is undefined" on examples that clearly work outside of NPM (especially when 'X' is something in ol3 that should be visible and correct).

Is there a doc that gives guidance on migrating a non-NPM ol3+ codebase under NPM?

**Comment by jahow** [comment]
Hi!

Your question is very broad and does not apply to OpenLayers specifically. Besides I think what you are really trying to do is migrate your project *to ES6 modules*.

You can still use OL "the old way" (i.e. through a global `ol` object) by including this in your html (taken from the [quick start](https://openlayers.org/en/latest/doc/quickstart.html)):
```html
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.1.1/css/ol.css" type="text/css">
    <style>
      .map {
        height: 400px;
        width: 100%;
      }
    </style>
    <script src="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.1.1/build/ol.js"></script>
```

Also the API has changed in quite a few places since version 3, so depending on how your third party examples were maintained, your mileage may vary.

Hope that helped

PS: OL6 has a [UFO sighting map example](https://openlayers.org/en/latest/examples/icon-sprite-webgl.html) ;)
