### ISSUE TITLE
cluster distance not correct

### ISSUE THREAD

**Issue by BasieP** [openlayers/openlayers#10530]
Hi there,

I'm using openlayers with lots of joy, but since a member of my team made a change we're kind of flabbergasted by something I can not explain.

Scenario is as follows:

We have a map with features (points) that are in a vectorSource inside a clusterSource inside a vectorLayer.

As styling we have an icon (22 wide, 28 high) which we pin to the coordinate as fraction on .5, 1 (center bottom)
Then we have a text style that sits at the right of the icon.

A while ago we added the option 'declutter' to the vectorLayer, to make sure the labels don't overlap with the icons or other labels and the screen looks prettier.

Now the weird thing: 
We see that we miss markers. So not just labels disapear, but also markers. 

The cluster distance is set to 40, and even with some pytagoras on the biggest numbers of our icons (28) i can't get my calculation to 40, but still they disapear.

Now i took some screenshots of my map (with clusters) and measured in the screenshot, and i noticed that our (cluster)markers are much closer together then the 40 pixels I configured.

What am i doing wrong?
Why are my markers closer together? and if we cannot fix that, how can i detect (in my styling function) if a icon intersects with an other icon or text so i can manually hide it's label?

here an (small) example screenshot.
https://imgur.com/GBx1Pcu

The distance between both cluster markers is not what i expect them to be. As you can see i rotated the map.
When i rotate it a bit further the images will overlap and one of them gets  'decluttered'

**Comment by MoonE** [comment]
Unfortunately the clustering algorithm used by the `ol.source.Cluster` does not guarantee a minimum distance between the individual features.
I changed the cluster source / and its example to better visualize why the features are at the position they are at. Please pull this branch and run the 'cluster' example.
https://github.com/MoonE/openlayers/tree/visualize-clustering

I made the following changes:
- There is a green rectangle showing the area with individual features
- each cluster feature has a rectangle that shows the area where its features are from
- This rectangle's colors are on a gradient from black to white, with black being the first cluster created and white the last.
- When you hover over a cluster its individual features are displayed as small red dots at their original positions.
- Clicking a feature hides it
- By default the clusters are displayed at the average position of all their features.
- There is a second slider below the cluster distance that gradually move the clusters between the average position and the center of the search area.
- There is a checkbox that allows to randomize the order in which the clusters are created.

The algorithm used by the cluster source takes one feature and searches for all features within the search area. The search area is a square with side length 2 * the configured distance and centered on  the current feature.
This is repeated for all features (features already belonging to a cluster are skipped).

You should be able to observe darkest rectangles at the top right and lightest at the bottom left initially and also that the cluster's icon is in the bottom left of its search area. This is due to the way the vector source stores the features (It uses the rbush library to efficiently access features by their positions).

**Comment by BasieP** [comment]
Thanks for the response. It explains a lot, but unfortunately only confirms my suspicion that we can not trust the data when we use both clustering and decluttering.

This will properly be something not only we experience as an imperfection.
I am wondering if we could solve the problem by moving the 'declutter' option to the style instead of the layer.
This way we can not only specify which style gets 'removed' when it overlaps, but also we get the option to change it in the styleFunction based on the content of the feature (or sub-features)


Also (a bit offtopic) you bring up some interesting points in your example branch.
> When you hover over a cluster its individual features are displayed as small red dots at their original positions.
I build some logic to do just that, but i have to do it without modifying the OL code.. I came up with a different layer (without clustering) and then removing features from one source and putting them in the other.
I find it a terrible (slow) solution, and am wondering if there is a way to do that in a more charming way. 
Right now I can't change position of an iconStyle in the styleFunciton, but if i could do that i could solve it in the styleFunction of the clusterlayer (generating a list of styles with there own positions of the non-clustered markers)

**Comment by MoonE** [comment]
> This way we can not only specify which style gets 'removed' when it overlaps, but also we get the option to change it in the styleFunction based on the content of the feature (or sub-features)

According to the api the zindex determines which styles are removed first by decluttering:
> Declutter images and text. Decluttering is applied to all image and text styles of all Vector and VectorTile layers that have set this to true. The priority is defined by the z-index of the layer, the zIndex of the style and the render order of features. Higher z-index means higher priority. Within the same z-index, a feature rendered before another has higher priority.

https://openlayers.org/en/latest/apidoc/module-ol_layer_Vector-VectorLayer.html

> Also (a bit offtopic) you bring up some interesting points in your example branch.
> 
> > When you hover over a cluster its individual features are displayed as small red dots at their original positions.
> 
> I build some logic to do just that, but i have to do it without modifying the OL code.. I came up with a different layer (without clustering) and then removing features from one source and putting them in the other.
> I find it a terrible (slow) solution, and am wondering if there is a way to do that in a more charming way.

You should be able to add the cluster's individual features to a new vector source without removing them from the cluster source. With each call to removeFeature on the cluster source's source the the clustering of the remaining features will be recalculated. It's better to remove / replace the entire source in that case.

The way the individual features are displayed in the linked branch does not depend on OL internal stuff. You could also cache the point styles for a all features of a cluster in the cluster feature when it is first needed.

Maybe a pull request adding an option to change the clusters position to the search area center would be accepted. This should guarantee the clusters to be at least the configured distance apart and It doesn't seem that much work.
