### ISSUE TITLE
Character codes appearing in labels

### ISSUE THREAD

**Issue by mike-000** [openlayers/openlayers#10546]
**Describe the bug**

![image](https://user-images.githubusercontent.com/49240900/72671980-e3ad5580-3a4a-11ea-9e2e-a86c3929158a.png)

Although the name is **Andy&amp;apos;s** in the data it should be decoded in the label.

This is from a KML example but I presume it could happen in any XML based format.  Would it be acceptable if either `ol/style/Text` or the renderer routinely called `decodeURIComponent()` on the supplied text or should it be the responsibility of the parser?

**Comment by ahocevar** [comment]
`decodeURIComponent()` won't help here, because it does not decode XML character entities like `&apos;`. The easiest way to decode these would be by using a HTML element (see e.g. https://stackoverflow.com/a/7394787/2389327). However, since this might incur some overhead, a pre-check with a regular expression might make sense.

Pull request for the scope of KML style function creation accepted.
