### ISSUE TITLE
Method ol.View.fit(ol.Extent) not working well

### ISSUE THREAD

**Issue by mattti-post** [openlayers/openlayers#10554]
**Describe the bug**
From version 6.0.0, the method ol.View.fit(ol.Extent) is not working precisely.  The features are displayed partly behind the edges of the view(they do not fit with the whole size of the image style).

**To Reproduce**
https://codepen.io/mattti/pen/OJPagag

**Expected behavior**

**Comment by mike-000** [comment]
Adding the features via a collection completes asynchronously, it will work if you set a listener to fit when the features are added
```
vectorLayer.getSource().on('addfeature', function(){
	map.getView().fit(vectorLayer.getSource().getExtent());
});

col.push(new ol.Feature({
	type: "vehicle",
	geometry: new ol.geom.Point(ol.proj.fromLonLat([19, 48]))
}));

col.push(new ol.Feature({
	type: "vehicle",
	geometry: new ol.geom.Point(ol.proj.fromLonLat([19.5, 48.5]))
}));

```

**Comment by mattti-post** [comment]
Hi mike. 

I tried your solution and it is still the same. Actualy it corresponds with your answer to my other submitted issue #10556. It really looks like from OpenLayers 6 "the extent of a feature is the extent of it's geometry". It is rely 

I want to point out, as mentioned in my first post, that in the version 5.3.3 the extent means the extent of all styles including the image icon or text style. You can check out the same codepen. I commented version 6.1.1 and added 5.3.3.

I don't know if I am missing something, but this is a huge change or bug, affecting the basic behavior. Even if we consider it a new feature(I did not see anything mentioned in release notes), how am I supposed to achieve the desired behavior to get the extent of all styles as before in version 5.3.3?

Thank you for your time.

**Comment by mike-000** [comment]
The difference between version 5 and 6 is **not** due to the style.  In version 5 `fit` will default to an integer zoom level.  If you override that `map.getView().fit(vectorLayer.getSource().getExtent(), {constrainResolution: false});` you see exactly the same exact fit to the geometry as version 6.  In version 6 use the `constrainResolution` option in the view constructor or `map.getView().setConstrainResolution(true);` to constrain the view to an integer zoom level.  But in both versions if your geometry happens to coincide with a zoom level the styling would be incomplete. See the release notes https://github.com/openlayers/openlayers/releases/tag/v6.0.0

**Comment by mattti-post** [comment]
Thank you very much Mike.

In release notes I did not find any note about the changing default values or explaining this change. But after I have set the constrainResolution value to true, it works as in 5.3.3. 

I tried to set the circle radius to 140px and actually it coincide with the integer zoom value as you pointed out. Strange thing is, that I never noticed, probably because I mostly use small icons.

My last question is: What do you suggest to include the styles into the extent? Is there any method in ol? Once ago I implemented the function which computed smallest circle around the multiple gps coordinates. Maybe this is the way, to find marginal points and include it in extent.

Thanks anyway!

**Comment by mike-000** [comment]
`fit` has size option, which defaults to the map size.  You could specify a size which is the map width and height minus the width/height of your styles.

**Comment by ahocevar** [comment]
Or even easier: use the `padding` option of `fit()`, which is in pixels.

**Comment by mattti-post** [comment]
I already am using padding in option `fit()` for overlapping html panels with static size and position. But that is not solving the issue for dynamic map features with different styles having dynamic sizes and orientation, placed on the map in different positions. Your solution is to set some "safe" padding value, for a price not taking the advantage of the whole viewport in most cases. 

Anyway thanks for your suggestions.

**Comment by namedgraph** [comment]
How come `view.fit(extent)` works as expected but `view.fit(extent, { size: map.getSize() })` does something different and zooms in way too much so that full extent is not visible?

The [documentation](https://openlayers.org/en/latest/apidoc/module-ol_View-View.html#fit) suggests that "Default is the current size of the first map in the DOM that uses this view, or `[100, 100]` if no such map is found." but inspecting the [code](https://github.com/openlayers/openlayers/blob/main/src/ol/View.js#L1398) shows that `size` defaults to `getViewportSizeMinusPadding_()` -- which is something else than map size, right?

**Comment by ahocevar** [comment]
The documentation is indeed outdated. `getViewportSizeMinusPadding_()` should be equivalent to `map.getSize()`, unless the view is configured with a `padding`.

**Comment by namedgraph** [comment]
Specifying `{ size: map.getSize() }` messed up the resolution/zoom, so I had to leave it out.

**Comment by ahocevar** [comment]
@namedgraph Would you be able to create a new issue with a reproduction case? This seems to be a different problem than the one reported here.

**Comment by nobodo** [comment]
I had vaguely similar issue with view.fit(extent) when it was called for the first time for a map that was not yet displayed. It did not zoom in close enough (zoom level was roughly 2.5 smaller than expected), but when the same map was opened again (using identical code path), the view fit perfectly to the extent as is expected. 

After adding the { size: map.getSize() } the issue was fixed.

**Comment by namedgraph** [comment]
@ahocevar is the `map.getView().fit(extent, map.getSize());` signature obsolete? I.e. Passing size as number instead of the options object.

**Comment by M393** [comment]
[`View.fit()`](https://openlayers.org/en/latest/apidoc/module-ol_View-View.html#fit) signature was changed with [v4.0.0](https://github.com/openlayers/openlayers/releases/tag/v4.0.0)

**Comment by pedros007** [comment]
I recently upgraded the version of OpenLayers in an old app I maintain. It looks like the behavior of [view.fit(extent)](https://openlayers.org/en/latest/apidoc/module-ol_View-View.html#fit) changed from version 5 to 6.  In version 5 fit would zoom to the nearest integer zoom level.  After 6, `fit` goes to a floating point zoom level.  I was able to restore the old behavior by a suggestion in this issue: make a map with `constrainResolution: true` and pass an option `view.fit(extent, { size: olMap.getSize(), })`.

However, this causes a different problem documented in #15423: trackpad pinch/two finger zoom would change the view wildly when `constrainResolution: true`.  I now just add some padding to the fit, like `view.fit(extent, { padding: [50, 50, 50, 50] })`. This still yields non-integer zoom levels when with fit, but I can live with that when the trackpad zoom still works the way I desire.
