### ISSUE TITLE
Fix pinch zoom for freehand drawing

### ISSUE THREAD

**Issue by oeway** [openlayers/openlayers#10623]
I would like to use freehand drawing (polygon) on mobile, however when I enter that, pinch zoom doesn’t work and it ends up with messy drawing on the map.

I think the free hand draw interaction should detect the pointer number and still allow pinch zoom and pan.

**Comment by ninaDeimos** [comment]
I haven't tested this with a newer version than 7.3.0, but since this issue is still open, I assume it hasn't been fixed.
Apparently it has not a high enough priority to get a fix...so can anyone point me in the right direction, so I can try to fix it by myself? Not sure if it will be just a fork or a contribution, bit would be nice to get some help, since I haven't worked on ol code before.

**Comment by MoonE** [comment]
Have you tried adding the ol/interaction/PinchZoom after the ol/interactino/Draw?
Events are handled in the order the interactions were added, but in reverse. So the last added interaction tries to handle the event first, and handling stops once one interaction succeeds.

As how to fix it, iol/interaction/Draw probably should not handle events with multiple active pointers.
Though preventing any drawing may be difficult because the first point is drawn immediatly when the first finger touches.

Look in https://github.com/openlayers/openlayers/blob/a793fdc859874ce347c7bb1480b64c1fe25c5b51/src/ol/interaction/Draw.js#L989
This method should return false when event should not be handled, (more than two active pointers).

https://github.com/openlayers/openlayers/blob/f2a26a64456371beb2f5ae9f4452146dcb0c414b/src/ol/interaction/Pointer.js#L82-L97
