### ISSUE TITLE
Latitude lines disappearing on Graticules when using Sphere Mollweide projection

### ISSUE THREAD

**Issue by HerrCraziDev** [openlayers/openlayers#10647]
**Describe the bug**
When using the Sphere Mollweide projection ([Ref. on epsg.io](https://epsg.io/53009)), the horizontal lines of a Graticule layer disappears if none of the poles are visible in the view. As soon as you pan the map so either one of the poles are within the view, the lines are back.

**To Reproduce**
Simply go to the official Sphere Mollweide example :
1. Go to [https://openlayers.org/en/latest/examples/sphere-mollweide.html](https://openlayers.org/en/latest/examples/sphere-mollweide.html)
2. Zoom and pan the map so none of the poles are visible
3. Latitude lines disappears. Pan any of the poles back in the view, and they appear normally.

**Expected behavior**
Graticule lines should always be visible no matter how the view is panned.

**Screenshots**
![image](https://user-images.githubusercontent.com/28117703/74352021-35ca6800-4db8-11ea-94a6-a4abeeea9e6f.png)
![image](https://user-images.githubusercontent.com/28117703/74352077-4a0e6500-4db8-11ea-983d-babe6225b20c.png)

**Comment by mike-000** [comment]
It looks like the length is being miscalculated (possibly by proj4).  If you zoom in on the Greenwich meridian they can be seen for a short distance either side of the meridian
![image](https://user-images.githubusercontent.com/49240900/75092428-4c6a7f00-556f-11ea-87be-d601a6c664d3.png)

**Comment by mike-000** [comment]
It's not proj4, the problem is because the world extent `[-179, -89.99, 179, 89.99]` transforms into an ESRI:53009 extent `[-59107.77479262598, -9009905.592261266, 59107.77479262598, 9009905.592261266]` which is only 118214 meters wide.  Transforming extents between projections can give meaningless results because splitting the world extent into two parts `[-179, 0, 179, 89.99] `and `[-179, -89.99, 179, 0]` transforming them and then combining the results would give `[-17919798.60504378, -9009905.592261266, 17919798.60504378, 9009905.592261266]`

**Comment by HerrCraziDev** [comment]
Aloha, 
I noticed that partial rendering when playing around too. 
Thank you very much for your feedback !
