### ISSUE TITLE
 the intermediary zoom levels are still allowed when constrainResolution is true

### ISSUE THREAD

**Issue by MukeZ** [openlayers/openlayers#10659]
**Describe the bug**
I'm using v6.2.1 and v6.2.0 also has this issue.

From the document:  
constrainResolution: If true, the view will always animate to the closest zoom level after an interaction;false means intermediary zoom levels are allowed.

Does it mean intermediary zoom levels shouldn't allowed when constrainResolution is true?

Because there are still intermediary zoom levels after I scroll on the map, it just animate to the closest zoom level

**To Reproduce**
I just set up a map normally
```
self.olMap = new Map({
                target: 'map',
                logo: false,
                interactions: interactions.extend([dragAndDropInteraction]),
                moveTolerance: 2,
                view: new View({
                    projection: newProj,
                    constrainResolution: true,
                    resolution:280,
                    resolutions: Config.Resolutions,
                    center: [474200, 5350629],
                    extent: Config.EXTENT,
                    zoom: 1
                })
            });
```

**Expected behavior**
Mouse scroll with the resolutions I set up to the view.

Thanks

**Comment by MukeZ** [comment]
Hi 
I just check my code and read releases document again.
I was set ```constrainResolution: true ``` in ```MouseWheelZoom ```,
But It's not working properly after I upgraded it to v 6.2.0 and set it in `View` class. 

Thanks

**Comment by jahow** [comment]
Hi,

Could you maybe be more explicit about the behaviour you were expecting and the actual behaviour you experienced? With the `constrainResolution` option the view will still sometimes be 'inbetween' resolutions during animation and interaction. Thanks

**Comment by ahocevar** [comment]
I noticed that after #9565, the options `duration` and `maxDelta` on `ol/interaction/MouseWheelZoom` have no purpose any more. For `duration`, I think the removal makes sense (but needs to be documented), because the view is now responsible for controlling all animations. For `maxDelta`, there might still be a purpose, but I'd let @fredj chime in here because he introduced that option.

I think what @MukeZ wants is that when `constrainResolution: true` is set on the view, a single wheel tick animates the map immediately to the target integer zoom, without stopping after a short zoom change, and then animating slowly to the target zoom.

**Comment by MukeZ** [comment]
> I think what @MukeZ wants is that when constrainResolution: true is set on the view, a single wheel tick animates the map immediately to the target integer zoom, without stopping after a short zoom change, and then animating slowly to the target zoom.

Yes, it's exactly what I mean, and I did try `duration ` on `ol/interaction/MouseWheelZoom` and it's not working.
v6.1.x is fine.
Thanks
