### ISSUE TITLE
Support for Cloud Optimized Geotiff (COG)

### ISSUE THREAD

**Issue by olivierdalang** [openlayers/openlayers#10733]
**Is your feature request related to a problem? Please describe.**
Despite being an awesome format, Cloud Optimized Geotifs (COG) are not supported by Openlayers. For those not familiar with the format, COG are basically regular Geotiffs, that store overviews in such a way that they can be retrieved using HTTP GET range requests. Server side, it's awesome, as it's just one file to host, and the same file can be downloaded as a whole too. Client side, it's even better than regular xyz tiles as you also get some metadata (extents, etc...).

**Describe the solution you'd like**
We could add a new source very similar to XYZ, where the user would just have to set the remote url. The `geotiff.js` library seems to provide all the difficult implementation.

Alternatively (or as a staging step), this could probably be an extension.

Cheers !

References :
- More info on COG : https://www.cogeo.org/
- [OpenAerialMaps](https://openaerialmap.org/) : they store their rasters as COG
- Issue asking for better docs on how to use COG with Openlayers : https://github.com/cogeotiff/www.cogeo.org/issues/36

**Comment by jahow** [comment]
Hi,

I agree, to me there are many interesting use cases for having the raw raster on the client side. Being able to change the styling on the fly is one thing, and raw data could also be used to do animated visualizations such as wind or current maps. I think there is a parallel to be drawn with vector data:

| service type | vector data | raster data | summary |
|---|---|---|---|
| server-side rendering | WMS | WMS | easy to consume, does not require client processing |
| data download | WFS | WCS | hardly suited for visualization (complex API, too much data) |
| client-side rendering | vector tiles | COG | heavy client processing, much more rendering possibilities |

One issue to solve is that this may add a lot of complexity to the library API since it would require a completely different styling system.

Related discussion: https://github.com/openlayers/openlayers/issues/8965

**Comment by olivierdalang** [comment]
Client-side styling is really nice, but COG are already useful just to display regular RGB tiles, as it doesn't require anything special server-side (you can host in on S3 for instance).

**Comment by sirmspencer** [comment]
How is COG different from requesting a tiff tile from a wms server?

**Comment by davidoesch** [comment]
any ETA? marvelous feature!

**Comment by davidoesch** [comment]
Hi all
From a swiss federal mapping agency view: we are still very keen for this feature

**Comment by ahocevar** [comment]
The smart folks at https://eox.at/ have successfully done cloud optimized geotiff with OpenLayers already. See https://eox.at/2018/05/explore-landsat-8-scenes-with-cog-explorer/.

**Comment by olivierdalang** [comment]
not stale, we still long for this feature

**Comment by mortac8** [comment]
Does anyone need help with this other than the great contributions by https://github.com/IvanSanchez/openlayers/commits/webgl-wip ?

**Comment by ahocevar** [comment]
@IvanSanchez's work looks good!

**Comment by IvanSanchez** [comment]
@ahocevar I feel that the work in that branch is not done, though. A few items missing:
- 32-bit data types
- One-geotiff-per-tile functionality
- How to put COGs in the examples? The sample files I'm working with are 15MiB big *at least*
- Some subclasses for the standard photogrammetric interpretations

**Comment by ahocevar** [comment]
Regarding examples, maybe @schpidi would be able and willing to provide an example GeoTiff on a CORS enabled server that we could use?

**Comment by Schpidi** [comment]
sure, would be happy to. @IvanSanchez let's coordinate directly which examples to provide.

**Comment by davidoesch** [comment]
We do still long for this feature here at map.geo.admin.ch ...

**Comment by IvanSanchez** [comment]
The state of affairs after the changes in my branch at https://github.com/IvanSanchez/openlayers/commit/f0fcf4e3f66b2eaeb6247b2e503b494df42805ff looks good - I plan on sending a PR next week.

**Comment by davidoesch** [comment]
A pity if we would not have this in OL—-

**Comment by ahocevar** [comment]
This pull request is replaced by #12008, which is still work in progress.
