### ISSUE TITLE
VectorTile source cacheSize and tile load endless loop

### ISSUE THREAD

**Issue by sookoll** [openlayers/openlayers#10742]
**Describe the bug**
In v6-beta there was possibility to disable tile caching by setting source cacheSize=0. I need it, as my vector tiles are updated frequently. In v6.2.1 if I set it to 0, tile requests are made but no tiles are rendered on map. If I remove cacheSize it sometimes work but most of the time it run endless loop of loading tiles. I'm not able to reproduce latter in fiddle, so I have to dig further.

**To Reproduce**
1. Add VectorTile layer and set source cacheSize to 0
2. Nothing rendered on map

**Expected behavior**
There should be layer on map, as cacheSize shouldn't mean how many tiles got rendered.

https://jsfiddle.net/psh74cv5/1/

**Comment by ahocevar** [comment]
Thanks for reporting this @sookoll. In v6 beta, the cache size was automatically increased to accommodate at least as many tiles as there are needed to render a complete map image. That code was removed in 5a8df1d4e298b901b0b7b6ad5d4ca0a2c864582c, because it *should* not be necessary any more. Looks like there is a bug still.

If you're able to find out more about this, please post your findings here.

**Comment by sookoll** [comment]
So You actually didn't fix the problem, just went around. Why can't I change cacheSize to 0 so that it wont cache tiles in browser? ol should render all tiles despite cache size, but not to store tiles in cache more than cacheSize allow. This is how user understand this property.
