### ISSUE TITLE
wrapX on Graticule layer does not work for labels

### ISSUE THREAD

**Issue by mike-000** [openlayers/openlayers#10789]
**Is your feature request related to a problem? Please describe.**
A consequence of #10713 is that graticule labels only appear in the central world when using wrapped global projections

Labels which previously were repeated in each world https://codesandbox.io/s/graticule-wrapped-old-4wkqk now end at the dateline which is not ideal for maps of the Pacific region https://codesandbox.io/s/graticule-wrapped-new-6djd4 

#10723 handles world extents crossing the dateline so a workaround is to set the projection's world extent to start and end at, for example, Greenwich and use a non-wrapped graticule.  The parallel labels are also better positioned (at the edge of the view instead of at the dateline) https://codesandbox.io/s/graticule-wrapped-offset-z7q5i

**Describe the solution you'd like**
Changing the world extents of built-in projections does not seem to be good practice as the same effect could be achieved by a graticule option such as `offsetGlobal` used to shift the graticule extent +/- offset degrees from the normal world extent.

**Comment by ahocevar** [comment]
So it looks like #10713 introduced a bug. Instead of having the user specify a new `offsetGlobal` option, it would be desirable if the Graticule layer could repeat them. That could be achieved with a technique similar to the one used in the tile renderer: https://github.com/openlayers/openlayers/blob/608d515f1f113920822574a1b3cede7a69f774bf/src/ol/renderer/canvas/VectorLayer.js#L186-L207

**Comment by richnic** [comment]
I have noticed the following behaviour:

1. Open https://openlayers.org/en/latest/examples/draw-and-modify-features.html .
2. Zoom out to minimum zoom level to see as much from the world as possible.
3. Click into the map to place a point, then drag the map to the right, so that the point goes out on the right edge und comes in at the left edge.
4. Repeat step 3 for a while. After a few iterations only, a click into the map does not draw a visible point anymore. Instead it places something invisible which cannot be seen but responds to snap-interactions.

Is that behaviour related to the problem described in this issue?

**Comment by ahocevar** [comment]
@richnic That's unrelated.
