### ISSUE TITLE
Declutter flickering vector features - Android webview

### ISSUE THREAD

**Issue by robbitt** [openlayers/openlayers#10819]
**Describe the bug**
Using releave v6.2.1 in a webview on Android.  Adding a vector layer with declutter.  Initially, features render on the map as expected, but on pan/zoom, the features flicker rapidly and disappear.

**To Reproduce**
`var vectorLayer = new ol.layer.Vector({
    source: new ol.source.Vector({
    url: '...some url',
    format: new ol.format.GeoJSON()
    }),
    declutter: true
});`

A style function is applied after the layer is added, that could be a problem too.  If I set declutter: false, then everything works as expected.

**Comment by ahocevar** [comment]
It does not matter when the style function is applied. But you need to make sure you group your styles correctly. Important: if you have labels and point symbols for a feature, use a single `Style` with `image` and `text`, not two separate styles.

**Comment by ahocevar** [comment]
I am currently looking into this.

**Comment by lzp0070007** [comment]
is there any new idea with this issue???

**Comment by ahocevar** [comment]
There is probably something wrong with the grouping of icons and text for decluttering. I don't have any details yet, but I'm working on it.

**Comment by djibarian** [comment]
I’m experiencing the same problem. Just upgraded from 5.3 as I saw the same behaviour when trying to upgrade to 6.0 time ago, so it has to be a 6.x problem. If it helps, I’m using a single style for image and text, tried to remove all the styling for text keeping only the name but still flickers. It flickers in Safari macOS and iOS, by the way, so is not an Android specific problem. Flicker happens when panning and seems to be dependent on even/odd pixel coordinates. Also seems to flicker when new tiles are loading.

**Comment by ahocevar** [comment]
This was fixed by #11148
