### ISSUE TITLE
Enable declutter just for Text (labels) and not Images

### ISSUE THREAD

**Issue by MrMisterG** [openlayers/openlayers#10849]
**Is your feature request related to a problem? Please describe.**
Our points need to be depicted on the map using images with labels (text). When we enable declutter, both of those disappear because decluttering affects both images and text. But actually we only want the text to declutter.

**Describe the solution you'd like**
We would like the option to enable declutter just for text and not images.

**Comment by ahocevar** [comment]
Decluttering can be set on a per-layer basis. In your scenario, you would use two different layers with the same source. One for points, one for labels. Only the one for the labels has `declutter: true` configured.

**Comment by MrMisterG** [comment]
Hello @ahocevar,
thanks for your suggestion!
We investigated it as a possible solution. It would work but we are concerned about our performance requirements, especially in case a lot of geometries (10000+) are added, since this effectively doubles the number of features?
BR
Stuart

**Comment by ahocevar** [comment]
If you use the same source for both layers, the number of features is not doubled. The number of render instructions is also the same, although it is divided into two instruction sets.

However, if you have 10000+ features and render all of them (i.e. if you do not declutter the point symbols), you will likely see unsatisfying performance. You could use `ol/layer/VectorImage` instead of `ol/layer/Vector` for the layer with the point symbols to get better panning performance.
