### ISSUE TITLE
Canvas layer reprojection still has (small) anomalies

### ISSUE THREAD

**Issue by pjsg** [openlayers/openlayers#11043]
**Describe the bug**
The display of a uniform canvas layer reprojected should still be uniform. 

If you use 6.3.1, then there are still the terrible drawing issues with reprojection. The current version (6.3.2-dev.1589259231810) shows some black dots. If you pan/zoom around, then it throws errors which are, I think, due to issues in proj4js (which should be fixed by https://github.com/proj4js/proj4js/pull/342). I couldn't find an easy way of using that version in CSB.

Also, it appears that what you see is browser and OS specific. 

**To Reproduce**
1. Go to 'https://codesandbox.io/s/dev-ol-canvas-reproj-ylso5'
2. See that the display area is not (quite) uniform. There are little black dots in places.

**Expected behavior**
The display should be uniform.

**Comment by mike-000** [comment]
Possibly related to #10987 although that affected the color values (a difference of 1 in the red value is over 6000 meters in a DEM), but your problem is only affecting the opacity https://codesandbox.io/s/dev-ol-canvas-reproj-dqnwh (specifying `imageSmoothing: false` in the sandbox will fix it by forcing your brokenDiagonalRendering method)

**Comment by pjsg** [comment]
Indeed it does -- thank you. I'll see if I can find something to fix in the non-broken diagonal rendering -- it could, of course, be a browser rendering bug as well. In which case, it probably makes sense to improve the detection of broken rendering to include this case,
