### ISSUE TITLE
Cascade dispose from map to layers to sources

### ISSUE THREAD

**Issue by tschaub** [openlayers/openlayers#11052]
Now that layers can only be used with a single map, I'm wondering what people think about calling `dispose` on a map's layers when the map is disposed.  It could also be convenient to call `dispose` on a layer's source when we call `dispose` on the layer.

**Comment by ahocevar** [comment]
Not sure. We always discouraged the use of `dispose()` in applications, and `dispose()` is not `@api` in any of our classes.

Ideally, just removing all references to an instance should allow it to get garbage collected. However, I understand that this is not possible with `ol/source/Raster` because of the worker that needs to be unregistered.

I remember when we started the same effort in OpenLayers 2, we opened a can of worms. That said, I think it is better to leave things as they are. When someone creates a raster source, it is their responsibility to dispose of it when it is no longer needed.

**Comment by tschaub** [comment]
Yeah, I agree.
