### ISSUE TITLE
Listeners on Layers

### ISSUE THREAD

**Issue by 1Map** [openlayers/openlayers#11068]
How can I listen on layers when it is re-ordered (Moved up or down in the order)?
Also what listeners are there when a layer was added / removed from a map or layer group?

**Comment by tschaub** [comment]
You can listen for `add` and `remove` on the layers [collection](https://openlayers.org/en/latest/apidoc/module-ol_Collection-Collection.html).

**Comment by 1Map** [comment]
Thanks.  Will this listen also kicks in when a layer is reorder in the layer group ?  Where can I find an example of this?

**Comment by tschaub** [comment]
@1Map - what are you calling to reorder layers?

**Comment by 1Map** [comment]
The order in which layers are drawn, for example if you have a layer control.  Re-order will be when you drag your layers up / down the hierarchy.

**Comment by 1Map** [comment]
How do you, for example by code move a layer up/down in the group during runtime, and my question was is there a listener for when this happen?

**Comment by tschaub** [comment]
By "what are you calling to reorder layers" I meant to ask about the specific method(s) are you calling in your application to reorder a layer.

If you are reordering layers by calling [`layers.remove(layer)`](https://openlayers.org/en/latest/apidoc/module-ol_Collection-Collection.html#remove) and [`layers.insertAt(index, layer)`](https://openlayers.org/en/latest/apidoc/module-ol_Collection-Collection.html#insertAt), then you could listen for the [`add`](https://openlayers.org/en/latest/apidoc/module-ol_Collection.CollectionEvent.html#event:add) event.

Here you can see that the `insertAt` method dispatches the `add` event: https://github.com/openlayers/openlayers/blob/v6.3.1/src/ol/Collection.js#L181-L189

That `index` is available to listeners of the event: https://github.com/openlayers/openlayers/blob/v6.3.1/src/ol/Collection.js#L19-L49

So you could do something like this:
```js
const layers = map.getLayers();
layers.on('remove', event => {
  console.log(`layer removed from index ${event.index}`);
});
layers.on('add', event => {
  console.log(`layer added at index ${event.index}`);
});
```

Because these two events are independent, it is awkward to reconstruct "reorder" from "remove" and "add" - but it sounds like "reorder" is something that is specific to your application.  An alternative would be for you add a callback to whatever code you are already running that does the removing and inserting.
