### ISSUE TITLE
Add a padding option to ol/control/ZoomToExtent

### ISSUE THREAD

**Issue by gilles-crealp** [openlayers/openlayers#11115]
It would be great to have the possibility to add a padding (in pixel) to [`ol/control/ZoomToExtent`](https://openlayers.org/en/latest/apidoc/module-ol_control_ZoomToExtent-ZoomToExtent.html), same as [`ol/View.fit()`](https://openlayers.org/en/latest/apidoc/module-ol_View-View.html#fit).

**Comment by mike-000** [comment]
Maybe the option should apply the view so it works with other controls such as zoom buttons and rotate.  You can get that effect by offsetting the map with hidden overflow https://codesandbox.io/s/simple-m4lu8 acts at 1/3 visible width and 1/3 visible height instead of the visible center but that is inefficient as tiles are loaded for the hidden areas.
