### ISSUE TITLE
Cypress trigger() not working on canvas

### ISSUE THREAD

**Issue by LeviDeang29** [openlayers/openlayers#11113]
**Describe the bug**
After upgrading from 5.3.x to 6.x.x cypress' `trigger()` no longer works. Events such as `click()` to select a feature works but `trigger('pointerdown')` and `trigger('pointerup')` doesn't. Any thoughts about this?

Also, what CSS selector do I need to use to directly access the canvas object?

**Comment by ahocevar** [comment]
OpenLayers now uses a smaller and simpler Pointer Events polyfill. It may have to do with that. But it is hard to guess without seeing the problem live in a minimal reproduction case.

Regarding CSS selector for the canvas object: the map is now composed from several canvas objects. See e.g. https://openlayers.org/en/latest/examples/export-pdf.html for how these canvases are accessed.

**Comment by ryanconry** [comment]
I was facing a similar issue.  My trigger looked something like this
`.trigger('pointerdown', { clientX: 900, clientY: 300, force: true, pointerId: 1 })`

I believe the issue is that OL was receiving an `Event` rather than a `PointerEvent`, the main difference being that the `Event` did not contain a `pointerId`.  Once the `pointerId` was provided, the issue was resolved.  Hope that helps :slightly_smiling_face:

**Comment by jaure96** [comment]
@ryanconry Can you please share you test implementation?
Tthis is my attempt, but I can't get it to move.

` 
cy.get('.ol-layer canvas')
    .trigger('pointerdown', 500, 500, {
      force: true,
      pointerId: 1,
    }) 
    .trigger('pointermove', 500, 300, {
      force: true,
      pointerId: 1,
    })
    .trigger('pointerup', 500, 300, {
      force: true,
      pointerId: 1,
    })
`
