### ISSUE TITLE
Impossible to use WebGLPointsLayerRenderer with a tiled vector source

### ISSUE THREAD

**Issue by FractalWire** [openlayers/openlayers#11137]
Not sure if it's a bug or a feature request here.

When using  `WebGLPointsLayerRenderer` in combination with a tiled vector source I've got this error:

```
PointsLayer.js:345 Uncaught (in promise) TypeError: source.forEachFeature is not a function
    at CustomRenderer.WebGLPointsLayerRenderer [as constructor] (PointsLayer.js:345)
    at new CustomRenderer (CustomRenderer.js:38)
    at CustomLayer.createRenderer (ais.js:76)
    at CustomLayer.getRenderer (Layer.js:296)
    at ais.js:99
```

And indeed a `VectorTile` source does not implement `forEachFeature`.
Thus, the renderer fail.

The question is should `forEachFeature` be implemented for `VectorTile` source or should a new WebGL renderer be created specifically for tiled source ?

In the meantime, as I want to use tiled vector source with WebGL for my project, I'd be more than happy to have a solution to circumvent this issue

**Comment by jahow** [comment]
A webgl renderer for tiled vector source would probably have a different structure than the existing one, so I'd go with your 2nd solution.

IMO this is the next big step in adding webgl capabilities to OpenLayers, but there's no plans or funding for now that I know of.

**Comment by Benjaki2** [comment]
@jahow Has there been any movement on this issue? If you or anyone else has any direction on how to go about implementing this WebGL tile render, that could be helpful. I might be able to allocate some time into working on this if it isn't too large of an undertaking.

**Comment by jahow** [comment]
Hi @Benjaki2 and thanks for offering your help! not much movement on this front unfortunately.

The current webgl renderer has a very straightforward approach: it reads all features given by the source and transform their geometries into a couple of `ArrayBuffer` structures (one for vertices, one for indices) which are then fed to the WebGL API. All features are then rendered in just one pass, using shader programs which are built programmatically based on the provided `style` object.

The buffers creation happens regularly (after every view change), which is not great because it can block the main thread noticeably. This was mainly to avoid precision issues across zoom levels, and also to let the source decide which features are visible where.

Implementing a webgl renderer for vector tiles would require a different logic when creating `ArrayBuffer`s. In my view the idea would be essentially to create one "mesh" per tile, a mesh being the association of a vertices and indices buffer.

The buffers creation would then happen every time a tile is loaded, which is given by the source object. There is probably a simple way to create buffers and meshes as new tiles are loaded, and discard/release them when tiles are unloaded, thus offloading the tile loading logic to the source as much as possible, but I'm writing this from memory so this has to be looked into further.

Then at render time the renderer can ask for a render pass of each currently loaded tiles. This is where things can get tricky: using vector tiles implies mixing tiles of different zoom levels, showing higher-detailed tiles when available and falling back to lower zoom levels if need be. I personally anticipate this part to be the hardest one.

Please note that many existing parts can definitely be reused, for example:
* transforming geometries to vertices/indices buffers
* generating shader programs from style objects
* hit detection
* probably others

The existing canvas-based renderer would be a good starting point for this work IMO.

Hope that helped, please let me know if you need additional/more precise pointers.
