### ISSUE TITLE
Draw Interaction removeLastPoint not acting as expected

### ISSUE THREAD

**Issue by WernerRaath** [openlayers/openlayers#11140]
**Describe the bug**
When enabling the Draw interaction and calling the removeLastPoint function, the draw layer does not update.

**To Reproduce**
1. Add the Draw Interaction to the map with `type: 'Polygon'`
2. Draw a polygon and mid draw, call the `removeLastPoint` function
3. Observe that the polygon you were drawing does not update
4. Call `removeLastPoint` again and find that the line segment that was supposed to be removed in the 1st call is now removed.
5. Click on the map again to resume drawing and see that the segment of call 2 is now removed and drawing has commenced as expected

**Expected behavior**
On `removeLastPoint` call, update the map with the original geometry with the last drawn segment removed

**Relevant Code**
https://github.com/openlayers/openlayers/blob/v6.3.1/src/ol/interaction/Draw.js#L817

**Comment by t-muko** [comment]
I encountered this problem too. This seems to be an issue with touch use. When used with mouse, the last coordinate in "sketchCoords_" is continuously updated when the mouse is moved. With touch devices, the last coordinate is not updated, so the removeLastPoint operation in fact removes the second last coordinate, but for the user it looks like nothing is done as the last pointer coordinate is the same and the drawing does not seem to change. However, if you now click to another point, this last point is behaving correctly.

Possible workaround would be to fake a pointer move event to the last accepted coordinate after the removeLastPoint operation, so that for example in polygon draw the closing line would be updated to the last coordinate too. With mouse the next movement of mouse would update this anyway. 
Another possibility would be to delete two last coordinates in case a touch device is used. Maybe this could be detected by comparing the two last coordinates in sketchCoords_ as they should be equal if a touch device is used. I am not sure if this would update the sketch-lines, though.

**Comment by WernerRaath** [comment]
This is still an issue and shouldn't be closed if it's still a problem

**Comment by WernerRaath** [comment]
This is still an issue and shouldn't be closed if it's still a problem

**Comment by ahocevar** [comment]
Did you try v6.5.0? What exactly is the remaining issue you are seeing?

**Comment by JackD83** [comment]
This is still somehow broken in v6.6.0.
The drawn geometry does update, but the last point is altered wrong until you move the mouse. Then the geometry is correct again.

I traced it down to this line: https://github.com/openlayers/openlayers/commit/0bd04eafe015e61e1df28b1c3c7d52239c9a57ca#diff-91329c8a038835b6a5e7bae5e13f15e7fa5499b3414f0e094a5bfe347efc5a32R912

And the same for polygons. I guess it was an attempt to fix the removal of points with touch.

I made a simple example here: https://8c2mi.csb.app/, right click removes the last point

**Comment by ahocevar** [comment]
The position of the draw vertex is intentional the way it is now. To make it visually more apparent what was changed.

**Comment by JackD83** [comment]
I think this problematic if I remove the second point of a line or polygon. If I have a style that does not draw single points and remove the second point, the whole feature disappears until I move the mouse. This was seen as error by the users.

**Comment by ahocevar** [comment]
The cleanest solution is probably to render the sketch point in some way, but with a modified `condition` you could make the sketch point appear at the last clicked location:
```js
condition: (event) => {
      if (
        event.originalEvent.pointerType === "mouse" &&
        event.originalEvent.button === 2
      ) {
        draw.removeLastPoint();
        const moveEvent = new MapBrowserEvent("pointermove", map, event.originalEvent);
        draw.handleEvent(moveEvent);
        draw.handleEvent(moveEvent);
        return false;
      }
      return true;
    }
```
