### ISSUE TITLE
»npm run build« with index.html <script src="../xxx

### ISSUE THREAD

**Issue by jbarth-ubhd** [openlayers/openlayers#11166]
If I have an `index.html` containing

```html
<script type="module" src="../xyz.js"></script>
```
then `npm run build` deletes `node_modules/ol`, overwrites `package.json` with a very short json and exists with crude error messages (mostly because of missing `node_modules/ol`)

The point is that if creating a symlink from `../xyz.js` to `xyz.js` and change `index.html` accordingly, `npm run build` works.

**Comment by jbarth-ubhd** [comment]
Is this a `parcel`-specific bug? Should I post there?

**Comment by ahocevar** [comment]
You'll need to provide more context to get help here. Also, what makes you think that OpenLayers is the culprit? At first glance I'd say you either use scripts with `module` type, or a bundler. With the remark that the former does not work with OpenLayers because some of its dependencies that are not provided as ES modules.

Feel free to post your repository here. But I think the solution is to remove `type="module"` from your script tag.

**Comment by jbarth-ubhd** [comment]
> At first glance I'd say you either use scripts with `module` type, or a bundler. 

Thanks a lot! That's it! But I'm still astonished that with `type="module"` and `src="../"` `node_modules/ol` vanishes etc.

**Comment by jbarth-ubhd** [comment]
PS: Problem exists with `<link rel="stylesheet" href="../xyz.css">`, probably because **cssnano**. `ln -s ../xyz.css .` with modified `href=` does the trick.
