### ISSUE TITLE
Angular 10 lazy load route accessed directly from url can't load map

### ISSUE THREAD

**Issue by digoburigo** [openlayers/openlayers#11335]
**Describe the bug**

When i try to lazy load the route directly from the url that contains the map, using my logic to load the map in version 6.3.1 works properly, but when i upgraded to version 6.4.0 the map it is not working anymore  

**To Reproduce**
1. Go to https://stackblitz.com/edit/angular-ivy-ev3aln
2. On version 6.3.1 Click on button "go to map"
3. Reload the application, that works like expected
4. Change the version to 6.4.0 in dependencies and do the same in 2 and 3
5. See error that occurs ```ERROR Error: Cannot read property 'length' of null```

**Expected behavior**
I expected that the map loads normal like in version 6.3.1

**Comment by ahocevar** [comment]
Thanks for reporting this, @digoburigo. I have created #11337 with a fix. In the meantime, please make sure that you do not set a `target` on a map that does not exist.

**Comment by digoburigo** [comment]
@ahocevar Sorry for my ignorance, but how can i set a target on a map that don't exist if i have to call the ```setTarget``` method in a instance of ```Map``` itself?

**Comment by ahocevar** [comment]
@daliborjanak In your example, you configure the map with `{target: ''}`. That won't give the map a target element, because `document.getElementById('')` returns undefined.

**Comment by digoburigo** [comment]
Oh I see, thanks for the explanation. So the fix it's going to resolve this issue? And in future updates this condition ```{target: ''}``` is going to be allowed?

**Comment by ahocevar** [comment]
The fix is going to make work again what you have been doing. But it would be better to not set an inexistent element id as the map's target. In addition to `''`, you also set the `id` that the `map-service` was called with as `target`.

Here is a cleaned version of your stackblitz, which works with v4.0 and does not set any inexistent html element ids as `target` any more: https://stackblitz.com/edit/angular-ivy-ea8ksa?file=src%2Fapp%2Fmap%2Fmap.service.ts
