### ISSUE TITLE
Issues in KML example

### ISSUE THREAD

**Issue by ahocevar** [openlayers/openlayers#11344]
ff980077eed459c6a2a9e3525e0a555f9d9ffeae broke the `kml.html` example. Looks like that change broke something for rendering of features that are not decluttered: some features disappear and reappear as the user zooms in or out.

**Comment by M393** [comment]
So I'm using olms to render place label and what I notice before ff98007 was that the rendered labels were not stable.
with each call to `map.renderSync()` it would flip between two states where one or the other label would show up.
I kind of expected it to always show the same labels, the behaviour in the kml.html example seem to be similar. When the map is rerendered the icons disappear.

**Comment by ahocevar** [comment]
We have a very different issue here @M393. It has to do with incorrect flat coordinate arrays in the instruction groups, cased by incorrect handling of point geometries (and maybe texts) when the coordinates have more than two dimensions. I'm currently looking into this. All I can say so far is that it is a huge rabbit hole. The change in ff98007 just revealed an issue that is caused somewhere else.

**Comment by jipexu** [comment]
since 6.2 ?

**Comment by ahocevar** [comment]
@jipexu No, the regression happened after 6.3.1

**Comment by jipexu** [comment]
ok thanks

**Comment by mike-000** [comment]
It is not specific to KML and with 4 dimensions it can result in "ghost" features  https://codesandbox.io/s/dreamy-haslett-0i4k6  There should be fish at [0, -20] and [-30, 10] but nothing at [0, 0]  If you delete the extra dimensions from one feature the ghost icon disappears, and delete the extra dimensions from the other and the ghost label disappears, (Also why are the codesandboxes opening with titles such as dreamy-haslett and runtime-silence instead of the name of the example?)

**Comment by jipexu** [comment]
i see sometimes the fish go under the water it seems  ...

**Comment by ahocevar** [comment]
See #11346 for a fix.
