### ISSUE TITLE
Hit detection and rendering issue with negative icon scale

### ISSUE THREAD

**Issue by M393** [openlayers/openlayers#11394]
**Describe the bug**
When the scale is negative and the rotation is 0
- Hit detection does not work
- Icon is not rendered at the edge of the map

**To Reproduce**
1. Go to https://codesandbox.io/s/hitdetection-icon-scale-bd12q
2. Click the penguin / pan the map
3. See result message below map / watch the icon disappear instead of getting cut off at the edge

**Expected behavior**
The hit should register anywhere on the icon / Icon should be rendered in part when it is at the map edge.

**Comment by ahocevar** [comment]
It is indeed broken for negative scales. This is something that @mike-000 might be interested in fixing, since they made the change that introduced negative scales. There is another issue with negative scales that can be seen in the above codesandbox: when panning the map, the icon disappears.

For other scales, just make sure to configure your vector layer with a `renderBuffer` big enough to cover your symbol size. In the codesandbox you provided, `500` might be a good value. Also, to get hit detection for the drawn icon and not just its bounding box, configure the icon style with `crossOrigin: anonymous`.

**Comment by mike-000** [comment]
I cannot see either of those issues in https://openlayers.org/en/latest/examples/icon-scale.html (observe change of cursor during pointermove on the lower fish, or click for a popup) - but even if I replace the penguin with the fish the the codesandbox both problems persist.

**Comment by M393** [comment]
Thanks, @ahocevar, I updated the sandbox with your suggestions. I'm using more reasonably sized icons hosted on the same server.
I noticed the hit detection not working with some icons in my application and the negative scale is the reason.
I hadn't noticed the disappearing icons, but it is also happening in my application.

I want to add thought that both worked with 6.4.2.

**Comment by M393** [comment]
@mike-000, Seems like the rotation in your example makes it work, if I remove it, the same problems occur.

**Comment by M393** [comment]
As a workaround i added `rotation: Number.EPSILON` to the scaled icons then it works like it should.

**Comment by mike-000** [comment]
Defining
```
  const rotatedOrFlipped = (
    rotation !== 0 ||
    scale[0] < 0 ||
    scale[1] < 0
  );

```
in `replayImageOrLabel_` and replacing both of the existing  `rotation !== 0` with `rotatedOrFlipped` seems to fix the problem for the icon, but there is still no hit detection on the flipped label in https://openlayers.org/en/latest/examples/icon-scale.html  when rotation is removed.

**Comment by ahocevar** [comment]
@mike-000 I think this requires a different fix, i.e. in `render/canvas.js`.`drawImageOrLabel`. There should be no extra case needed for rendering flipped images, at least no `translate` transform. This would require a different `originX` and `originY` calculation.
