### ISSUE TITLE
internationalization  of the interface

### ISSUE THREAD

**Issue by jipexu** [openlayers/openlayers#11393]
Hi
As i need full multilang support for the interface so i am working about this.
I look for in examples, api, search engine and found only very old ressources about this (ol v2 time)...
I known is very few occurence concerned by this translation because in fact they are mainly titles of the map interface icons..

So my question is : this internationalization  of the interface is totally abandoned or it is some plan to give some support for that in the core ?? Or i have miss something to do it ?

For now i just make some local js to change the occurence according with a lang tag from the target of the map...
And i think an hosted example about this will be interesting and welcome. ( i will do if you think is necessary and useful)

Thanks for your light

**Comment by ahocevar** [comment]
@jipexu You are right that the only thing that holds human readable text in OpenLayers are `title` attributes for a few control buttons. And all of these should be customizable through JavaScript. Example: the `zoomInTipLabel` and `zoomOutTipLabel` config options of `ol/control/Zoom`.

Not sure if it is worth having an example for that. It boils down to configuring the map with a set of controls, instead of using the defaults, and configure all controls with the appropriate labels.

**Comment by jipexu** [comment]
@ahocevar Thanks for the answer. 
Yes i saw the config options for the various Tiplabel and dont take this way because  in our case of cms multilang site where is différent map in different pages i think is more simple to do it after with another js to keeep the code of the map by itself more clear ...and do it only one time according with the class of the controls buttons ... 

- but true i agrre with you is no need an example for customize the lang via  the various Tiplabel  !
