### ISSUE TITLE
Custom GPS accuraccy (circle style) broken från 6.3.1 -> 6.4.1

### ISSUE THREAD

**Issue by kobbe** [openlayers/openlayers#11497]
**Describe the bug**
I have a custom gps accuracy feature and style. Up until 6.3.1 it have worked great but in 6.4.1 the gps accuracy circle jumps (i.e moves to a different location in the map) when zooming. I have not pinpointed to exactly where the problem is.

**To Reproduce**
Working in 6.3.1: https://jsfiddle.net/se2k3t6y/
Broken in 6.4.1: https://jsfiddle.net/mscb4qgd/

An image of how it looks like in 6.4.1 when zooming in:
![bild](https://user-images.githubusercontent.com/4288653/91714427-04668d80-eb8c-11ea-9772-84366b8ae96b.png)

**Expected behavior**
As in 6.3.1

How it should look like:
![bild](https://user-images.githubusercontent.com/4288653/91714555-53142780-eb8c-11ea-82c9-e262e2e6e7f2.png)

**Comment by mike-000** [comment]
It looks like the pixelRatio isn't being used when the circle style is re-rendered after calling setRadius() so on a mobile device a smaller circle appears in the top left of the extent the correct size circle should occupy, and is probably related to #11277.  It is not a GPS problem.

**Comment by ahocevar** [comment]
@sbrunner, can you please take a look at this?

**Comment by mike-000** [comment]
If you copy the code from the circle-style rendering test and change the map pixelRatio option to 2 it shows it is not the pixelRatio being ignored but when the ratio is not 1 the style is not updated again after the first call to setRadius(), and all three circles take the radius of the first feature.  

It is because render() creates a canvas only for pixelRatio 1 but getImage() creates the canvas for other pixelRatio values and assumes that once created a canvas never changes. For a circle radius can change and `this.canvas_` would need to be indexed by both pixelRatio and radius.

**Comment by ahocevar** [comment]
Thanks for your investigation @mike-000. A pull request would be appreciated. I like the idea of simply emptying `this.canvas_` in `render()`. Another simplification might be to also remove the indexing by `pixelRatio`.

**Comment by sbrunner** [comment]
@mike-000 are you working on a pull request?
