### ISSUE TITLE
WebGLPointsLayer does not update dimensions when browser viewport dimensions change.

### ISSUE THREAD

**Issue by ablakey** [openlayers/openlayers#11514]
**Describe the bug**
When the canvas (context?) re-sizes (eg. resize browser window) the WebGL layer does not resize. The result is that in some cases the rendered view can be very pixellated, as if a tiny context is being upscaled by a lot.

**To Reproduce**
1. Go to https://openlayers.org/en/latest/examples/webgl-points-layer.html
2. Scale your browser window ZOOM down to like 10% (Ctrl -).
3. Refresh the page, which renders the canvas context at that zoom level
4. Zoom back to 100%
5. Notice the blue circles are very low resolution

**Expected behavior**
Changes in viewport size should cause an update to the WebGL layer's size.

**Thoughts**
I am guessing that the opposite might also be true: when zooming down to 10% you end up with a positively colossal WebGL frame size.  I think the above demo is simplistic enough, but when I apply the same workflow to my own, more complex app,  Zooming out basically crashes the browser.

**Comment by jahow** [comment]
Hi,

When changing the zoom level in your browser you're affecting the viewport size but also the device pixel ratio. As such, loading the page at 10% means your initial pixel ratio will be 0.1. If I'm not mistaken, when a `Map` is created the pixel ratio is "baked in" and if it changes later on the new value will not be taken into account for the different renderers.

The behaviour you're describing also happens on regular canvas-based layers.

Not sure what would be the right course of action here; making it so that a map could handle varying pixel ratio sounds like quite a piece of work. On the other hand, assuming that the pixel ratio is always fixed is reasonable, since I believe most users use a zoom level close to 100%.

**Comment by ablakey** [comment]
Thanks for the response. You're right, it happens on canvas layers too. I missed it because silly me, the layer in question was nice square polygons that scale really well without jagged edges.

I imagine that the act of changing the viewport size (and pixel ratio) is not likely to be a common one. One remedy is to wire into that happening (MutationObserver?) and just destroy and rebuild the Map when necessary. This is probably something the developer, not the library, can worry about.
