### ISSUE TITLE
Marketplace

### ISSUE THREAD

**Issue by hutch120** [openlayers/openlayers#11524]
Hi Community Leaders! @tschaub @ahocevar @mike-000 @jahow @fredj @MoonE 

I hope everyone is doing well in these difficult Covid-19 times. It is more important than ever to have this amazing community.

I have outlined a proposal below that aims to enhance funding, strengthen the OpenLayers community, and create more commercial connections and opportunities for members.

I'd love to hear thoughts from the project leaders mentioned above in particular, and also the wider OpenLayers community.

# Introduction

I have been working with the OpenLayers platform for many years, I'm an open collective sponsor and have contributed code to the project. I'm an independent contractor as I'm sure are many using the OpenLayers platform. 

After building commercial addons with the OpenLayers platform for many years and reselling them though my channels, I realise this is repeating work done tens if not hundreds of times by others, and that there is already a community right here that has the ability to resell their work and naturally fund the project that makes this possible.

I have closely followed the debate about opensource funding, the [knowledge economy](https://en.wikipedia.org/wiki/Knowledge_economy), [3 Sided Marketplaces](https://medium.com/breakdowns/3-sided-marketplaces-c1ac4d06cb6f), and the various implementation models. In particular I put skin in the game this year when Covid-19 hit and I built a monetisation platform called [sparkstreams.tv](https://sparkstreams.tv/) for individuals in the arts, entertainment and education industries that has a lot of crossover.

I've also looked into other industries such as gaming asset stores like [sketchfab](https://sketchfab.com/) and code stores like [codester](https://www.codester.com/) who have empowered individuals to generate income from their creative work. 

Advancements in code distribution such as webpack/parcel/etc and amazing projects for UI components like [Storybook](https://storybook.js.org/) have meant contributions big and small can be easily created, demonstrated, understood and distributed.

# Proposal

I propose that I will build (at my cost) and operate a vendor neutral marketplace, where OpenLayers community members can generate income where a percentage of that income is funnelled directly back to the OpenLayers project.

The only change for the OpenLayers code is to approve a PR to add some unobtrusive links to the marketplace (E.g. Github Readme and site header) so that developers and commercial interests can find the marketplace.

# Benefits

By implementing this proposal, funding for OpenLayers would be increased by enabling the community to resell commercial addons in a marketplace and distributing profits from those sales between the developer and the OpenLayers platform.

The marketplace would also aim to enable commercial interactions between those looking to do work and those needing work done which can only result in a stronger community.

# Risks

Issue: Marketplace does not meet expectations. 
Resolution: Links from the OpenLayers project to the marketplace can be removed if deemed no longer appropriate.

Issue: Commercial conflict where contributions to the platform and commercialisation clash. 
Resolution: The games industry have struck a balance by providing common assets under a free for personal use licencing model. Licencing can also mandate that common code must be available for use in the platform without restriction if it is deemed a core feature.

# Thanks

OpenLayers developers, like me, are already engaging in the [knowledge economy](https://en.wikipedia.org/wiki/Knowledge_economy) and creating services with high value thanks to OpenLayers, lets embrace this movement and support each other.

Thanks for the consideration, I look forward to hearing thoughts from the community, in particular the project leaders mentioned above. Also feel free to connect on the socials linked below.

Regards,
Simon Hutchison
https://stackoverflow.com/users/1550587/simon-hutchison
https://au.linkedin.com/in/simonhutchison1

**Comment by tschaub** [comment]
Hi Simon - Thanks for your ongoing support of the project, and for the thought you are putting into proposals like this.

My initial reaction from the project perspective is that this sounds interesting.  I don't have a good sense for the market for commercial addons and would be curious to hear more of your thoughts on this.

I can imagine that it would be beneficial to have a central place to connect those looking for custom application development or support and people able to provide these services.  Are you envisioning some sort of self-service marketplace where consumers and suppliers advertise their own needs and capabilities?

I'll be interested to hear what @ahocevar and others might have to say.

**Comment by hutch120** [comment]
Thanks @tschaub for the quick response, feedback and great questions!

Initially the aim would be to work toward the following goals and features.

- Provide a website where a [business network](https://en.wikipedia.org/wiki/Business_network) can thrive. `... a complex network of companies, working together to accomplish certain objectives ... that help small and medium-sized enterprises (SME) to become more competitive and innovative`.

- Provide a means on the website to engage in commercial discussion. In its simplest form this could be a member based forum.

- Provide the ability for Sellers to promote their products and services and for Buyers to advertise their needs. Initially this could be a fairly basic article/post style, but if there is enough interest, then work toward a multi-vendor store.

- Generate financial support for the OpenLayers Platform from the commercial interests that benefit by being community members. There are a few approaches such as reselling code and membership fees for non-contributors, I also have some other ideas around this, but I'd like to see some traction before imposing any sort of payment structure.

There are clearly many other features that are relevant to a Marketplace, but I think this should evolve naturally from member feedback, like the OpenLayers Platform itself.

I feel very fortunate to have to have worked as an independent contractor in the tech industry for many years and have support from both sides of the marketplace, the OL community and innovative companies, but I realise that I am in a commercial bubble. A question was asked only yesterday on Hacker News (re. health industry, but relevant) [Ask HN: We have the expertise but no clients. How to reach them?](https://news.ycombinator.com/item?id=24397821) which resulted in an interesting discussion. There are also many other examples of [similar questions](https://hn.algolia.com/?q=find+clients) on HN.

**Comment by jipexu** [comment]
Hi
Sorry at first I am always affraid when i see the dollars or euros coming in a opensource project... I still have a sour experience with goggle map API who start with the work of the goggle engineers but also with a great community of free developers who worked hard on this ... what is the result (slowly addons by addons, api call by api call) now even the api are not free...

The question : We have the expertise but no clients. How to reach them? Yes it  is a good question for an enterprise but is it really the good question for a project like OL  ? I am not sure..

The question is OL need found ? The answer is probably yes ?
@hutch120 thank for your proposal because it can be a way, but can be also an open door to transform the project where finally (following a slow but logic progression, the users (even developper contributor) will be in fine considered only as clients instead of users ...)
To stay positif i can believe, hope that the community leadership will be enough strong to control such evolution...

Hope this comment is not to dark but it is my feeling ..

**Comment by ahocevar** [comment]
I had not responded yet because this is a tough topic. My first thought is that this proposal takes a sustainable core project (OpenLayers) for granted, which generates interest for commercial services around it.

OpenLayers sees many contributions, but contributions take time to review. Also maintenance of the project infrastructure and incorporating new technologies takes time that barely gets contributed. So this is time that people like @tschaub and I invest, which is usually not paid for. Fortunately, at the moment, @planetlabs and another customer of mine cover a small fraction of these costs.

Being a one-person small enterprise myself, with projects that more or less all rely on OpenLayers, I always have the core project in mind and invest a significant amount of my time/income in maintaining the core.

If a platform like the one @hutch120 proposes can help generate maybe 10 times the funds we currently receive from sponsors and supporters through OpenCollective, then the core maintenance would maybe be covered.

That said, I am not opposed to such a proposal, but I also do see @jipexu's point that it may lead to the development of proprietary add-ons with functionality that would benefit a broader community and draw attention to the OpenLayers project if it was open. Again, a tough topic, and I don't really know what to think about it.

**Comment by hutch120** [comment]
Hi @jipexu Thank you for your thoughtful response.

I am familiar with the recent [massive price increases](https://www.inderapotheke.de/blog/farewell-google-maps) from Google Maps, it affected some of my contracts. Looking back nearly 10 years Google seems to have had a policy of pricing their products toward enterprise, so perhaps not unexpected behaviour from them. [Ask HN: Alternatives to Google's Static Maps API?](https://news.ycombinator.com/item?id=3593921)

I do take your point about Google Maps Addons, a good lesson to learn from, and one which could be addressed by ensuring the Marketplace approach does not take away from core contribution, perhaps though a licencing model.

**Comment by hutch120** [comment]
Hi @ahocevar Thank you for you honest and open response! I'm blown away by the passion, I'm not sure if this is said enough but thank you for your work and thanks to all the contributors.

I also love this platform and my only wish is that it could be financially stable, no strike that... financially thriving!

So the hard truth, most people do take OpenLayers for granted, but it's not just OpenLayers, it's all opensource. When is the last time anyone gave a single thought to the maintainers of Material-UI when doing a `yarn add material-ui`... which is no doubt why they are trying anything they can think of to sell services around the core platform; a [Store](https://material-ui.com/store/items/devias-kit-pro/) for premium themes, advertising for [sponsors](https://material-ui.com/discover-more/backers/#diamond), offering [contract services](https://material-ui.com/getting-started/support/#professional-support-premium), and you've got to dig pretty deep but they still even have their [Open Collective Page](https://opencollective.com/material-ui).

I can't promise a silver bullet... but I can offer my time and resources to give it a crack.

**Comment by hutch120** [comment]
I've been reflecting on the discussion so far, and it seems like the main issue raised is in relation to code contribution. Would it make sense to focus on the Business Network side rather than a Marketplace?

So instead of reselling code, non-contributing members would pay a membership fee and in return have access to a centralised network of business opportunities.

Are you guys familar with how [BNI](https://www.bni.com/about/history) approached this problem?
