### ISSUE TITLE
Question on custom rotation transform

### ISSUE THREAD

**Issue by hyeokjoo** [openlayers/openlayers#11533]
I was looking at [this example on using OffscreenCanvas](https://openlayers.org/en/latest/examples/offscreen-canvas.html) and found it really useful; Thank you @ahocevar for your effort to make this great example. While following this example, I found that there is no extra transform implemented for rotated views (in this range of codes below):

```js
    // Skip the extra transform for rotated views, because it will not work
    // correctly in that case
    if (!rotation) {
      compose(
        transform,
        (renderedCenter[0] - center[0]) / resolution,
        (center[1] - renderedCenter[1]) / resolution,
        renderedResolution / resolution,
        renderedResolution / resolution,
        rotation - renderedRotation,
        0,
        0
      );
    }
```

However I'm working on `OffscreenCanvas` to render `.pbf` tiles with lots of features and I need to take into account rotated views.

I searched elsewhere if there are any related issues or code snippets but I haven't been able to find any. Could anyone help me?

**Comment by ahocevar** [comment]
Actually the reason why that example falls back to frame-by-frame rendering for rotated views is because I was not able to figure out the correct transform in the short time I had available for that example.

**Comment by hyeokjoo** [comment]
@ahocevar thank you for your prompt response. Would it be an easy task? If so, would it be possible for you to give me some guidance or examples of codes please? Your assistance would be greatly appreciated. Thank you.

**Comment by ahocevar** [comment]
@hyeokjoo A good tutorial on affine transforms is https://docs.geotools.org/latest/userguide/tutorial/affinetransform.html. The problem with the transform for rotated views is that you need to account for the center change. As you can see, when you remove the `if (!rotation) {}` restriction, the map will jump because of the missing center adjustment.

In addition to the `ol/transform.compose` function, you can also use the `scale`, `translate` and `rotate` functions.

If you're able to figure out the correct transform, please submit a pull request with your improvements.

**Comment by hyeokjoo** [comment]
@ahocevar thank you for your response.

By the way, I am also working on changing the opacity of vector tile layer stored in a web worker, but simply calling .setOpacity (inside web worker) and triggering map.render in the main thread does not work. Do you have any clue why it does not work?
