### ISSUE TITLE
Simple OpenLayers map as emailed/attached file not opening in IOS

### ISSUE THREAD

**Issue by Gnorkus** [openlayers/openlayers#11585]
Hi!

I'm quite new to the forum.  I have an issue that has stymied me for the past 2 years.  Something changed either in IOS or OpenLayers such that an html file containing the following code will not open in IOS.  I don't know why.  Any clues?  All that is contained is a simple map interface using the latest greatest OpenLayers.  It doesn't matter which version I use.  I save the below lines as an HTML file, attach it to an email, and the try to open in IOS from the IOS email app.  Bupkis, nada, nope!  Won't show a map.  PC, Mac, and Android are fine, however.  

I zipped the HTML file into the below attachment.  Just unzip it, open in a text editor to view it, and then try to send it as an attachment in an email to an IOS device.  Mac, Windows, and Android have no problem.  IOS has no joy.

Thx!
gnorkus

[BasicMap3.zip](https://github.com/openlayers/openlayers/files/5276051/BasicMap3.zip)

**Comment by Gnorkus** [comment]
Hi again.  Just so I made it clear, the attempt being made is to open the file locally on the machine it is emailed to.  It is NOT a weblink that is being sent.  Thanks ahead of time for anyone who responds with a solution, and thanks for any other responses too!

**Comment by ahocevar** [comment]
I don't think this is an OpenLayers issue. It is probably because you are requesting external resources. Speaking of, if you think you need to use the legacy build, please don't use the github url, but the cdn url from the Quick Start doc (https://openlayers.org/en/latest/doc/quickstart.html).

The safest way to create such a self-contained page would probably be a properly built JavaScript file with all the code (using parcel or webpack), and use it as data uri in the html.
