### ISSUE TITLE
Broken Projections when using proj4js definitions

### ISSUE THREAD

**Issue by weskamm** [openlayers/openlayers#11632]
OpenLayers produces broken projections when using ol 6.4.3 and proj4js 2.6.2 for (at least) geographic CRS.
Adding a new definition in proj via `defs` with the official strings (from epsg.io or spatialreference.org) works nicely in proj4js.
But using the `register` function of `ol.proj.proj4` then creates an invalid projection.
Invalid means that required parameters like `units` are undefined and `axisOrientation` is set to wrong default values.

Example:

```
proj4.defs('EPSG:4258', '+proj=longlat +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +no_defs');
ol.proj.proj4.register(proj4);
```
![image](https://user-images.githubusercontent.com/1381363/95451713-7a6acb00-0968-11eb-973a-4b5d8e3cd12f.png)
![image](https://user-images.githubusercontent.com/1381363/95451752-88205080-0968-11eb-8326-c0f51ef62e8d.png)

The map display / projection is broken when using this ol.Projection.

**Expected behavior**
When having a proj4js definition which does not have a unit set, the default should be "degrees" instead of undefined.
In fact, all EPSG definitions for proj4js are missing the unit for geographic projections and there are only "m", "ft" and "us-ft".

Besides, the axisOrientation needs to be configured correctly in order to render a map correctly.
The broken definition from above needs to have a 'neu' order, but the definition has no axis given and openlayers defaults to 'enu'.
There are only 28 definitions for proj4js out of 3910 which have an axis given ("+axis=wsu")

Am i doing something totally wrong or is this somehow unusable for geographic projections in the current state?

**Comment by ahocevar** [comment]
OpenLayers only takes what it gets from proj4. In your above example, there is no axis order specified. If the above projection definition had an axis order and units specified, it would look like this:

    +proj=longlat +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +axis=neu +no_defs

For the above definition, OpenLayers will correctly store the axis orientation as property in the projection definition derived from proj4, but internally it always uses x, y order.

For reprojecting coordinates, the units are not used. The proj string above does not specify any units, and the projection definition generated from the string does not have units. So OpenLayers does not get any units from proj4.

However, since units are not used for reprojecting coordinates, this should not be a common problem.

In which case do you see an incorrectly rendered map? It would be good if you could provide a working example that shows the issue.

**Comment by weskamm** [comment]
Well the problem is, that commonly used sources like epsg.io and spatialreference.org do not serve that information (no axis and no unit).

I prepared a fiddle:
https://jsfiddle.net/45ukp0wj/

That fiddle should but will not display a map. Look at the console to see the ol.Projection output, its missing units and defaulting to wrong axis.

Then uncomment line 9-15 and replace the projectionstring in line 29 with the variable `projection`.
The map will appear.

**Comment by ahocevar** [comment]
Welcome to axis orientation hell, introduced with WMS 1.3. To make your application work stock definitions from epsg.io, I'd recomment two things:

* Use the WKT definition Instead of the proj4 definition from epsg.io. It contains the units information for all projections.
* Use WMS version 1.1.1 instead of the default (1.3.0), by adding `'VERSION': '1.1.1'` to the WMS source's `params`. That way, you don't need to know the axis orientation, because x,y will be assumed, like everywhere in OpenLayers.

See https://jsfiddle.net/btdx04r6/ for an update fiddle with these changes.

I also did some research about proj strings. Maybe we can assume `degrees` as default for the units if no `+axis` parameter is specified and the projection name is `longlat`. #11649 makes this change, after which you'll be able to continue using proj strings for defining projections.

**Comment by weskamm** [comment]
Very nice! I did not know that proj4js also handles "other" definition strings, this becomes very handy here.
And yes i think you are right about assuming degrees for longlat definitions should be ok, i had a look at this collection:

https://github.com/yuletide/node-proj4js-defs/blob/master/epsg.js

and it appears that they all miss the units parameter.

So thanks for the solution and the PR!

**Comment by ahocevar** [comment]
@weskamm:

> Well the problem is, that commonly used sources like epsg.io and spatialreference.org do not serve that information (no axis and no unit, e.g. http://epsg.io/4258 or http://epsg.io/4326).

Correct. You can use the official EPSG database API instead, e.g. https://apps.epsg.org/api/v1/CoordRefSystem/4258/export/?format=wkt&formatVersion=1. I just published new versions of `wkt-parser` and `proj4js` that support their WKT format.
