### ISSUE TITLE
Split Control

### ISSUE THREAD

**Issue by bjornharrtell** [openlayers/openlayers#1165]

**Comment by 1Map** [comment]
Same here, OL3 is really lacking a lot of Spatial Editing Features which use to be in OL2, like Snapping (They only done it now), Splitting and Merging of Features, Freehand Drawing and creating Holes in Polygons (MultiPolygon - Donut)

**Comment by bartvde** [comment]
No one said ol3 implements all of OpenLayers 2 functionality

**Comment by ahocevar** [comment]
As stated above, snapping is currently being worked on: #3109.

**Comment by ahocevar** [comment]
Splitting of features is something you can do on the application level with third-party libraries, e.g. with http://turfjs.org/.

For freehand drawing and donat holes, pull requests should not be too complicated. If someone wants to take that on, I'll be willing to review and provide some guidance.

**Comment by probins** [comment]
turfjs has some useful features, but afaik it can only splice a line at a vertex, so it's nowhere near as versatile as the OL2 split tool which could split at multiple arbitrary points on multiple lines at once.

**Comment by probins** [comment]
as mentioned in https://github.com/openlayers/ol3/pull/3461#issuecomment-116145836, you can split lines with the modify interaction, especially so with the new ability to add a vertex with a click. There's no need for Turf, which doesn't really add all that much to what ol already provides.

Assuming a vector source called 'source', a select interaction called 'select', and a modify interaction called 'modify' that works on `select.getFeatures()`, the user would select the linestring feature to split, and then click on the point at which it is to be split. Code like the following should do the trick:
```
var origCoords;
select.on('select', function(evt){
  // convert original coords to an array of strings
  if (evt.selected[0]) {
    origCoords = evt.selected[0].getGeometry().getCoordinates().join(' ').split(' ');
  }
});
modify.once('modifyend', function(evt){
  var f = evt.features.item(0);
  var modCoords = f.getGeometry().getCoordinates();
  var i = 0;
  // convert each coord in the new array to string and compare with original until find non-match
  while (origCoords.indexOf(modCoords[i].join(',')) !== -1) {
    i++;
  }
  var part1 = modCoords.slice(0, i+1); // include the new coord in both parts
  var part2 = modCoords.slice(i);
  var f1 = new ol.Feature({
    geometry: new ol.geom.LineString(part1),
    name: "I'm the 1st bit"
  });
  var f2 = new ol.Feature({
    geometry: new ol.geom.LineString(part2),
    name: "I'm the 2nd bit"
  });
  select.getFeatures().clear();
  source.addFeatures([f1, f2]);
  source.removeFeature(f);
});
```
I'm not aware of any way of using indexOf with an array, so you have to fiddle about converting to strings so you can find out which is the new coordinate at which the split should be made. Once you've worked out what you have to do, it's not that much code. I'm using `once` assuming the user would do a split and then do other modifications.

As also mentioned in #3461, this could be simplified if the modify event were to return the newly added vertex feature, as you would then not need `origCoords`. Even better would be for it to return the index of the new vertex (`insertVertices[0][0].index+1` in the start event, and `segmentData.index+1` in the end event) as then you could simply slice at that index.

Alternatively, splitting could be included in the modify interaction by adding a `splitAtClick` or similar boolean option, with `get` and `set` so you could turn it on and off. If this were true, somewhere around https://github.com/openlayers/ol3/blob/master/src/ol/interaction/modifyinteraction.js#L759 you would split the feature instead of splicing in the new coordinate. Probably in this case, you would copy the attributes from the original feature to both the new parts, and then apps would give users the opportunity to edit the new parts as appropriate.

Either way, I don't think there's any need for a separate control just for line split.

Join is also quite simple: modify the 2 lines so the join point on both is roughly in the same place, then select both lines and have a button event:
```
  var f1 = select.getFeatures().item(0);
  var f2 = select.getFeatures().item(1);
  var f3 = new ol.Feature({
    geometry: new ol.geom.LineString(
      f1.getGeometry().getCoordinates().concat(f2.getGeometry().getCoordinates().slice(1))
    ),
    name: "I'm the joined geom"
  });
  select.getFeatures().clear();
  source.removeFeature(f2);
  source.removeFeature(f1);
  source.addFeature(f3);
```
though it's a bit more complicated, as you might have to reverse the coords on one or both features so you're joining the correct ends. Not sure it makes sense to have a separate control/interaction for this either - perhaps an example?

**Comment by probins** [comment]
my code assumes that the user clicks on a new point to split. If the click is on an existing vertex, then it will by default be deleted. This can be avoided by setting deleteCondition to never, but my code still won't work because the split point is already in the geometry. The only way around this that I can see is to return the vertex/index in the event as mentioned (or require that the user makes a slight drag instead of just clicking).

**Comment by JackWangXiaoer** [comment]
@1Map @ahocevar 
About holes of features, I have achieved this, the following code
```javascript
var source = new ol.source.Vector();
var draw = new ol.interaction.Draw({
        source : source,
        type : 'Polygon'
});
map.addInteraction(draw);
var hole;
draw.on('drawstart',function(evt){
        var coordinate=evt.feature.getGeometry().getFirstCoordinate();
        hole=map.forEachFeatureAtPixel(map.getPixelFromCoordinate(coordinate),function(feature){
                if('Polygon'==feature.getGeometry().getType()){
                        return feature;
                }
        });
});
draw.on('drawend',function(evt){
        if(hole){
                var coordinates= evt.feature.getGeometry().getCoordinates()[0];
                hole.getGeometry().appendLinearRing(new ol.geom.LinearRing(coordinates));
        }
});
```
With the hole in the ol2 some different, this does not remove the last drawing polygon.

**Comment by msurya231209** [comment]
Hi probins,
I have implemented your code for splitting of a line string, but it is not working at the existing vertex(i.e. splitting not happening when I select the existing vertex) and on drag of the vertex splitting is working.
But I also want to split at the existing vertex selection. Can you please suggest me how to modify the code for my requirement.

**Comment by msurya231209** [comment]
The below is my code....
map.addInteraction(interactionSelect);
                    interaction = new ol.interaction.Modify({
                        features: interactionSelect.getFeatures(),
                        //insertVertex: false,
                        //deleteCondition: function (event) {
                        //    return ol.events.condition.never(event);
                        //},
                        //split: function (click) {
                        //    return ol.events.condition.splitAtClick;
                        //}
                        //splitAtClick: true
                        //splitAtClick
                        //deleteCondition: function (event) {

                        //    var key = event.originalEvent.keycode || event.originalEvent.charCode;
                        //    if (key == 46) {
                        //        return ol.events.condition.always(event);
                        //    } else {
                        //        return ol.events.condition.never(event);
                        //    }
                        //}

                    });
                    //interaction.splitAtClick;
                    map.addInteraction(interaction);
                    map.addInteraction(interactionSnap);

                    var origCoords;
                    var part1;
                    var part2;
                    interactionSelect.on('select', function (evt) {
                        // convert original coords to an array of strings
                        if (evt.selected[0]) {
                            origCoords = evt.selected[0].getGeometry().getCoordinates().join(' ').split(' ');
                        }                       
                        
                    });   

                    interaction.once('modifyend', function (e) {
                        //console.log("feature id is", e.features.getArray()[0].getId());
                        //var selectedCollection = new ol.Collection();
                        var f = e.features.item(0);
                        var featureProperties = f.getProperties();
                        //delete featureProperties.boundedBy;
                        var modCoords = f.getGeometry().getCoordinates();
                        //var modCoordsTest = f.getGeometry().getCoordinates().join(' ').split(' ');
                        //var modCoordsTest = e.mapBrowserEvent.coordinate.push(0);
                        //modCoords.insert(2,e.mapBrowserEvent.coordinate)
                        var i = 0;
                        // convert each coord in the new array to string and compare with original until find non-match
                        //for (var j = 0; j < origCoords.length; i++) {
                        //    if (origCoords[j] == modCoordsTest) {

                        //    }
                        //}

                        while (origCoords.indexOf(modCoords[i].join(',')) !== -1) {
                            i++;
                        }
                         part1 = modCoords.slice(0, i + 1); // include the new coord in both parts
                         part2 = modCoords.slice(i);
                        //featureProperties["geometry"] = part1
                        //var f1 = new ol.Feature(featureProperties);
                        //f1.getProperties().geometry = part1
                        var f1 = new ol.Feature({
                            geometry: new ol.geom.LineString(part1),
                            //name: "I'm the 1st bit"
                            ID: parseInt(featureProperties.ID) + 1,
                            idsurface: featureProperties.idsurface,
                            Note: featureProperties.Note
                        });
                        //featureProperties["geometry"] = part2
                        //var f2 = new ol.Feature(featureProperties);
                        //f2.getProperties().geometry = part2
                        var f2 = new ol.Feature({
                            geometry: new ol.geom.LineString(part2),
                            //name: "I'm the 2nd bit"
                            ID: featureProperties.ID,
                            idsurface: featureProperties.idsurface,
                            Note: featureProperties.Note
                        });

                        interactionSelect.getFeatures().clear();
                        //sourceWFS.addFeatures([f1, f2]);
                        transactWFS('delete', f);
                        //transactWFS('insert', e.feature);
                        transactWFS('insert', f1);
                        transactWFS('insert', f2);
                        //sourceWFS.removeFeature(f);
                    });
