### ISSUE TITLE
Tile display issue on panning

### ISSUE THREAD

**Issue by Antoninum** [openlayers/openlayers#11680]
Hi!

**Describe the bug**
I discovered a problem with tiles display on panning.
When I pan quickly from a location to another, tiles are displayed after a white square is showing, even if I have already network loaded those tiles.
This behavior was not present in ol 6.3

**To Reproduce**
1. Go to [https://codesandbox.io/s/panning-bug-ol-64-io2uv](https://codesandbox.io/s/panning-bug-ol-64-io2uv)
2. Click on the "Pan" button in the bottom on the left. You may have to do this 2 times to ensure that tiles are downloaded from the network
3. Even if tiles are downloaded, they are stil displayed after a white square is showing, like a non-downloaded tile.

**Expected behavior**
Tiles that have already been downloaded from the network should be displayed without any delay.
To compare, go to the same sandbox but with OL 6.3 here [https://codesandbox.io/s/panning-bug-ol-63-r19nb](https://codesandbox.io/s/panning-bug-ol-63-r19nb)

Thank you very much for your work, OL is amazing ! :heart:

Edit: corrected expected sandbox link

**Comment by M393** [comment]
This is caused by https://github.com/openlayers/openlayers/pull/11268 (v6.3.2-dev,1594634340433 on codesandbox)
The tile cache is by default only big enough to hold all tiles in the current view, new tiles are loaded from the browser cache if possible, but will display with transition. Before OpenLayers cached some tiles on its own, which can be configured by the `cacheSize` option.

You can influence the behavior by configuring the `transition` and `cacheSize` for the tile source.
```js
var osm = new TileLayer({
  source: new XYZ({
    attribution: '&#169; <a href="https://www.openstreetmap.org/copyright" target="_blank">OpenStreetMap</a> contributors.'
    url: 'https://{a-c}.tile.openstreetmap.org/{z}/{x}/{y}.png',
    cacheSize: 100, // Default is 0
    transition: 50,
  })
});
```
The transition option is missing from `ol/source/OSM` so I used its parent class `ol/source/XYZ` here. To add this the option should simply be passed through the call to the super constructor.

Maybe the transition should be skipped if the tile is loaded within one animation frame. (If that is how fast the tiles are loaded from cache), @ahocevar?

**Comment by ahocevar** [comment]
I think skipping the transition won't improve the situation much, because the tile queue won't start loading within a single animation frame. Setting a larger `cacheSize` is the way to go here. And if the cache size is large enough, there is no need to set a shorter `transition`.

That said, I think it would be worthwhile revisiting tile queue and tile cache and make them play together better. But that would be a huge effort. If anyone would be willing to take that on, I'd be available to provide some guidance.

**Comment by Antoninum** [comment]
I'm late, but thank you for your replies.

`cacheSize` was indeed the way to go!

I have nor knowledge of OL nor time to help with revisiting the tile queue unfortunately.

@ahocevar I'm letting you close the issue since I don't know if you wanna keep this one to keep a reminder of the queue problem or not.
