### ISSUE TITLE
Possible to use multi-touch to draw a line between two fingers?

### ISSUE THREAD

**Issue by MarByteBeep** [openlayers/openlayers#11700]
This is a question, which could be a feature request if it turns out to be unsupported. 

I'm using OpenLayers 6.4.3 and am trying to use the draw interaction on a touch device. I'd like to be able to simply draw a line between my two fingers. There are a number of examples concerning the draw interaction, but none seem to describe this. And none seem to support multi touch. 

They all seem to be focused on drawing a line from a fixed starting point (which is set at the `drawstart` event). But in the case of two fingers, the starting point isn't fixed. 

Any help would be greatly appreciated. Thanks!

**Comment by jahow** [comment]
Hi,

I don't think the built-in draw interaction would be of much help here since the logic you describe is quite different. Probably a custom interaction with some logic on the `down` and `up` event handlers would allow achieving this? Although I'm not sure this could warrant a new type of draw interaction altogether, it would be an interesting example to add in my opinion.

**Comment by MarByteBeep** [comment]
Count me in for that example! As I really wouldn't have a clue on where to start with this one.
