### ISSUE TITLE
Style clone function doesn't copy the renderer function

### ISSUE THREAD

**Issue by changqingom** [openlayers/openlayers#11860]
I find this:

The new style options don't have a renderer property.

https://github.com/openlayers/openlayers/blob/1a952e7a41a030791780af6086ca4ad91e30e6f0/src/ol/style/Style.js#L213-L226

**Comment by mjjurkoic** [comment]
Someone correct me if I'm wrong, but wouldn't this require a deep copy of the renderer property?

The obvious solution, of course, would be to just add `renderer: this.getRenderer() ? this.getRenderer() : undefined,` into the properties of the new Style, but that would create issues because it would only pass the renderer function by reference.

To properly clone the renderer function, I think a deep copy of the renderer function object would be needed.  Core JavaScript doesn't provide a good way of creating a deep copy of an object that contains functions, so a true solution would require either a custom deep copy function to be added to OpenLayers, or the use of a third-party library that provides a deep copy function.  A third-party library would add another dependency, since I don't believe any of the current OpenLayers dependencies provide deep copy functions.

**Comment by changqingom** [comment]
I've wondered before whether a deep copy of a function is necessary.If a function is defined and used according to the standard specification, there is no need for a deep copy.I understand that many circumstances need to be considered for the convenience of deep copy of the function. In this case, I suggest some supplementary instructions on style.clone in the API documentation to make it clear that no copy will be carried out for the renderer function.

**Comment by mike-000** [comment]
There seems to be no attempt to deep clone functions in the library.  If `geometry` is a function there is also no deep clone.  The `style` of a feature is not deep cloned, regardless of whether it is a function.

**Comment by mjjurkoic** [comment]
In that case, taking a cue from how `clone()` handles the geometry property, we should be able to do `renderer: this.getRenderer()` to get the same kind of copy as geometry would get if it were a function.

Would that be an appropriate fix for this issue, or would it be better to leave `clone()` as is and simply state in the API that the renderer function is not copied?

**Comment by mjjurkoic** [comment]
I created PR #11893 to move the issue forward.
