### ISSUE TITLE
Browser compatibilty issues

### ISSUE THREAD

**Issue by mike-000** [openlayers/openlayers#11866]
**Describe the bug**
The latest mapbox-gl-style-spec appears to have broken OpenLayers compatibility with older browsers by its use of Spread syntax https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax

**To Reproduce**
Try any of the 6.5.0 examples on IE.

**Expected behavior**
Eventually old browsers will go out of support but when that happens it should be documented.

**Comment by ahocevar** [comment]
Since ol-mapbox-style is the dependency that depends on mapbox-gl-style-spec, this should only be a problem in builds that include `ol/layer/MapboxVector`. For the examples, this is probably always the case because the `common.js` build artifact is used by all examples. For the examples, this could be fixed by configuring webpack to transpile the mapbox-gl-style-spec dependency when building the examples.

**Comment by mike-000** [comment]
The legacy build is also affected (e.g. the quick start example) and presumably the ol-mapbox-style legacy build will also be affected?  If there are any other dependencies on Mapbox components there could be other potential future issues as mapbox-gl-js 2.0.0 has dropped support for IE.

**Comment by ahocevar** [comment]
I think we should drop support for IE soon too.

**Comment by ahocevar** [comment]
#11872 should fix the legacy build on IE11. Can anyone who has an IE11 instance available please test that?
