### ISSUE TITLE
set projection option on OSM source not work

### ISSUE THREAD

**Issue by tltk90** [openlayers/openlayers#11883]
**Describe the bug**
pass an `projection` to OSM source not change the projection even that `OSM` inherit from `XYZ`

**To Reproduce**
1. Go to [stackblitz](https://stackblitz.com/edit/openlayers-test)
2. Click on `console`
3. See the osm projection

**Expected behavior**
the projection will be `EPSG:4326`

**Comment by MoonE** [comment]
I guess the assumption is that the OSM source is always in the same projection. It does not work because the projection option for the OSM source is not read.

Do you have have a OSM server that serves tiles in a different projection?
If you want to display the Map in a different projection you need to set the projection option of the View, not the source.

**Comment by tltk90** [comment]
ok. thanks.
