### ISSUE TITLE
Loading module from “http://localhost:80/static/js/node_modules/ol/ol.css” was blocked because of a disallowed MIME type (“text/css”).

### ISSUE THREAD

**Issue by swiss-knight** [openlayers/openlayers#11935]
I just copy-pasted the example shown here: https://openlayers.org/en/latest/examples/epsg-4326.html into a Flask template (jinja2) html.page.

And my Firefox 84.0.2 (64-bit) is telling me that:

```
Uncaught TypeError: Error resolving module specifier “.ol/ol.css”. 
Relative module specifiers must start with “./”, “../” or “/”.
```

Okay, then I felt I have to adapt the paths of the imports to something like:

```
import './node_modules/ol/ol.css';
import Map from './node_modules/ol/Map.js';
import TileLayer from './node_modules/ol/layer/Tile.js';
import TileWMS from './node_modules/ol/source/TileWMS.js';
import View from './node_modules/ol/View.js';
import ScaleLine from './node_modules/ol/control/ScaleLine.js';
```

because I installed OL using the `npm` way in a `app/static/js/node_modules` folder.

And now Firefox is telling me:

```
Loading module from “http://localhost:80/static/js/node_modules/ol/ol.css” was blocked 
because of a disallowed MIME type (“text/css”).
```

Is there something I do wrong? Is OL not intended to be imported this way in the simplest application?

Edit:

And if I simply remove the first line containing the `ol.css` import, then I got:    

```
Uncaught TypeError: Error resolving module specifier “rbush”. 
Relative module specifiers must start with “./”, “../” or “/”. BaseVector.js:18:18
```
But I did not even load `BaseVector` (I guess that it was maybe requested by one of my imports?).

Thanks for you hints.

**Comment by ahocevar** [comment]
You need to use a bundler (e.g. Webpack or Parcel) to build your application. Using script type module directly in the browser does not work yet because, as you found out, rbush, one of our dependencies, is not available as ES module yet.

Regarding the css, in the browser you'll have to load the css through the html, using e.g. `<link rel="stylesheet" href="ol.css">`.

The code snippets in the official examples (main.js, index.html, package.json) give you a working configuration for the Parcel bundler.

**Comment by jipexu** [comment]
Hi
I again just exactlty experimented what @swiss-knight wrote (before i read this topic) ... and the clear answer of @ahocevar.
..."Using script type module directly in the browser does not work yet because, as you found out, rbush, one of our dependencies, is not available as ES module yet."...

Also my question as a neophyte :  is rbush the only problem to use script type module directly in the browser and is it a big work to solve this ?
As my js are writing by php and the data are from mysql i dont use a local environnement to develop is more simple for me. However i  wanted to rewrite using the modules to reduce the load weight of ol.js...

Thanks
