### ISSUE TITLE
Popup opens on the wrong marker

### ISSUE THREAD

**Issue by ChristianKohler** [openlayers/openlayers#11953]
**Describe the bug**
Popup opens on the wrong marker.

![recording](https://user-images.githubusercontent.com/4374178/105968318-3a4e6600-6087-11eb-9cfa-a38c0f36f4eb.gif)

**To Reproduce**
1. Go to https://openlayers.org/en/latest/examples/icon.html
2. Move worldmap till you see the marker again
3. Click on the marker
4. Notice that the popup opens on the main marker

**Expected behavior**
Popup should open on the clicked marker

**Comment by mike-000** [comment]
There is only one feature, you are clicking on the same feature in a wrapped world.  You could use `evt.coordinate` to determine which world was clicked on and adjust the overlay position accordingly.

**Comment by ChristianKohler** [comment]
So that means that this is the expected behaviour as we see it on https://openlayers.org/en/latest/examples/icon.html? 

Imho it is a bug from a users perspective. If it's not a bug in the library, it's definitely a bug in the example. Wdyt?

**Comment by mike-000** [comment]
If the vector source was set up with `wrapX: false` and had two distinct features at lon lat values [0, 0] and [360, 0] it would work as you expected.  Otherwise you would need to adjust the feature's real world coordinate into the world where you clicked the copy https://codesandbox.io/s/icon-forked-icvll

**Comment by ahocevar** [comment]
Why so complicated, @mike-000?

@ChristianKohler Thanks for reporting this behavior. It can indeed be considered a bug in the example. From a UX perspective, it is better to show the popup at the exact location clicked by the user, and doing so makes the code simpler, because we do not need to get the coordinate of the feature, but simply use the event coordinate. See #11954 for a fix. Preview of the example: https://deploy-preview-11954--ol-site.netlify.app/examples/icon.html.

**Comment by ChristianKohler** [comment]
Wow, great to see that openlayers is such an active community 🤩 Thank you both @mike-000 @ahocevar 

Would be nice if openlayer handles the "wrapped world". As a user of the tool I just want to enable the feature and not think of all the issues I have to fix in every single map.

Although @mike-000 workaround works I am pretty sure ppl stumble over this issue over and over again. Would it be possible to return the coordinates of the clicked pointer when calling `feature.getGeometry().getCoordinates();`?

**Comment by ahocevar** [comment]
That would not work @ChristianKohler. The coordinates of the geometry and a clicked coordinate on the map are two separate things.

**Comment by ChristianKohler** [comment]
Ok. What I mean, atm the dev has to fix the wrapped world problem. Can't we move that into the library itself? When I click on a marker the library could figure out that the user clicked on a feature in the wrapped world and make sure to do the calculations to make sure the `feature.getGeometry().getCoordinates()` returns the correct coordinates.

**Comment by ahocevar** [comment]
Did you take a look at the approach in https://deploy-preview-11954--ol-site.netlify.app/examples/icon.html? No need for the application to check and re-calculate anything.

**Comment by mike-000** [comment]
> Why so complicated, @mike-000?
 
Not only complicated but if the feature was sufficiently close to the dateline that the icon overlapped it it would not have worked, but this does https://codesandbox.io/s/icon-forked-vws63
