### ISSUE TITLE
Typo in xml namespace

### ISSUE THREAD

**Issue by MoonE** [openlayers/openlayers#11997]
**Describe the bug**
There is the `http://openstreemap.org` namespace without the second `t` in the two files below.
https://github.com/openlayers/openlayers/blob/8c6dd4c24477c40b49e7d6f2e1daa8b6146cb196/examples/vector-wfs-getfeature.js#L51
https://github.com/openlayers/openlayers/blob/8c6dd4c24477c40b49e7d6f2e1daa8b6146cb196/test/spec/ol/format/gml/osm-wfs-10.xml#L3-L5

The server at https://ahocevar.com/geoserver/wfs seems to expect it like this and returns an error when the `t`is added.
Though it does look like a typo.

**Comment by ahocevar** [comment]
Yes, this is a typo I took over from demo.boundlessgeo.com/geoserver when it became unavailable. i could change it, but then all examples from previous versions would stop working. I could also publish a second version of the featuretype under a different namespace, but I don't think it would be worth the effort because it's just a namespace uri, which is not meant to match a web reachable url.

**Comment by MoonE** [comment]
That's fine, just thought I'd report it here.
