### ISSUE TITLE
Modify interaction with hitDetection and RegularShape only makes part of feature hittable

### ISSUE THREAD

**Issue by perliedman** [openlayers/openlayers#12068]
When using `hitDetection` for the `Modify` interaction in a layer with point features, styled as `RegularShape`s, only part of the rendered shape is used as hit area.

**To Reproduce**
1. Go to https://codesandbox.io/s/crimson-currying-ohztg
2. Hover the rectangle feature
3. When close to the center, and somewhere approximately half the way out to the border, you can interact and drag the feature
4. When close to the border, the feature is no longer draggable, and attempting to drag will only pan the map

**Expected behavior**
Ability to drag the box as long as the pointer is inside it.

**Comment by M393** [comment]
You need to increase the `renderBuffer` of your `ol/layer/Vector` to match the size of the rectangle.
```js
const layer = new VectorLayer({ 
  source,
  renderBuffer: 240,
});
```
https://openlayers.org/en/latest/apidoc/module-ol_layer_Vector-VectorLayer.html

**Comment by perliedman** [comment]
@M393 thanks, I suspected this might be a problem in my configuration.

Should this be mentioned in the docs somehow? It was quite easy to find the `hitDetection` option, but I think it would be nearly impossible for me to make the connection to the `renderBuffer` option without asking here or on Stackoverflow.

**Comment by ThomasHalwax** [comment]
@M393 I have similar problem with hitDetection for styled/aligned text. When the text is aligned left (or right, does not matter) the problem is worse than for a ```Regularshape``` because the user needs to know that the anchor point is at the left center of the text: https://codesandbox.io/s/jovial-feather-pvgiy

Setting a higher value for ```renderBuffer``` is not an option for us because the text is provided by the user and it's width is unknown upfront.
