### ISSUE TITLE
Example "MapGuide" not working due to "Mixed Content" (https/http)

### ISSUE THREAD

**Issue by rowild** [openlayers/openlayers#12233]
Not sure if this is an issue - please feel free to delete this issue.

This example page

https://openlayers.org/en/latest/examples/mapguide-untiled.html

does not work, because the protocol of the individual map agent uses "http" only.

Would love to know and see what it does. Also: there is a "Library://" protocol – never seen that before. Is that an official protocol or for internal usage only?

**Comment by mike-000** [comment]
Modern browsers don't support mixed content, so the http only server will need to be upgraded to https.  Old browsers (e.g. IE11) will still work, but for IE you will need https://openlayers.org/en/v6.4.3/examples/mapguide-untiled.html or https://openlayers.org/en/main/examples/mapguide-untiled.html as there was an IE compatibly problem with 6.5.0

**Comment by mike-000** [comment]
138.197.230.93 is the example creator @jumpinjackie's demo server (see https://github.com/openlayers/openlayers/pull/9574).  If there is no https available for that it would be simple to set up a proxy to it on any available https host which simulates the real mapagent url for the purposes of the example https://codesandbox.io/s/mapguide-untiled-forked-vxe9l

**Comment by ahocevar** [comment]
Maybe @jumpinjackie can help here by making their demo server available through https.

**Comment by jumpinjackie** [comment]
When I have time I'll buy an actual domain to front that demo server. In the meantime, if it helps you could momentarily pull the MapGuide examples and I'll reintroduce them later through a PR with the updated demo server domain over https instead of IP

@rowild The "Library://" protocol is an internal custom URI scheme used by MapGuide to identify/address various resources
