### ISSUE TITLE
Question: Is it feasible to use the openlayers canvas renderer with a NodeJS canvas implementation?

### ISSUE THREAD

**Issue by pineapplemachine** [openlayers/openlayers#12303]
I work on an application where users are given a map interface in a web client using openlayers, and the users can use this interface to input different sorts of geographical data.

Later, on the server side, there is a need to generate static raster images showing these map data inputs given earlier in the client. It would be convenient if I can replicate the same layers and styling and such the user saw when inputting their data, and direct openlayers to draw essentially the same view again using a NodeJS [canvas implementation](https://www.npmjs.com/package/canvas).

This definitely doesn't seem to be a use case made to be doable out-of-the-box, unless I'm missing something. It does seem like it could be manageable, though, given that the canvas rendering code in the repo appears to be pretty modular?

Is this possible currently, and how can it be done? Specifically, using openlayers with a NodeJS canvas implementation to generate static map images server-side, reproducing what users previously saw rendered in their browser. If it's not possible currently, can I get some direction on what would need to be added or changed to make it happen?

Thanks!

**Comment by pineapplemachine** [comment]
I appreciate the response, thanks!

Would you be able to point me in the direction of what parts of the API I'd
be concerned with if I went with that canvas rendering context suggestion?

Serialization the style is not really an issue in this case. Ideally the
server would just share or replicate the same code the client uses to
decide how to style the map view, and that will be enough.

Can you recommend any particular printing solution that would have similar
layer and styling options as openlayers?

I don't need the client and server images to be fully 100% identical.
Reusing the same styling code for openlayers on the backend as in the
client would certainly make my life easier, though.

**Comment by petrovicz** [comment]
I have the same desire here. Currently I'm using OL on the client side for any data modification by the user, then I use MapServer to generate a complex single image output, which contains multiple layers with filtered features and everything.
The issue with my current solution is that the final image on the server side slightly differs from the client side due to the fact it was generated by a completely different engine. Also, I cannot get any vector tile layers displayed via MapServer, which would be an easy task with OL.

I would really appreciate a rendering API for OL which takes a list of layers/filters/properties and compiles it into a single image without the need to simulate a dummy html site.

If anyone knows any alternatives, or how to use vector layers with MapServer, I beg you reach out to me!
Thanks!

**Comment by simonseyock** [comment]
Hey, maybe you can use https://geostyler.org/ for conversion of styles, it supports OpenLayers Styles and for example SLD styles. I suppose that it will not match 100%, but maybe it is close enough?

**Comment by petrovicz** [comment]
> Hey, maybe you can use https://geostyler.org/ for conversion of styles, it supports OpenLayers Styles and for example SLD styles and mapserver mapfiles. I suppose that it will not match 100%, but maybe it is close enough?

Definitely helps me bringing the styling closer. Thank you!
