### ISSUE TITLE
Add OGC API - Features support

### ISSUE THREAD

**Issue by MartinOver2** [openlayers/openlayers#12387]
Support of OGC API Features as layer type would be great.

https://ogcapi.ogc.org/features/

**Comment by mprins** [comment]
see #10963 and https://github.com/opengeospatial/ogcapi-code-sprint-2021-05/issues/1#issuecomment-838610721

**Comment by ahocevar** [comment]
#10963 is about OGC API - Tiles. To support OGC API - Features, we have everything in place already: the format (GeoJSON), and an API to tell a vector source how to load data incrementally (tiled and bbox [loading strategy](https://openlayers.org/en/v6.5.0/apidoc/module-ol_loadingstrategy.html). Similar to a [WFS layer](https://openlayers.org/en/v6.5.0/examples/vector-wfs.html).

If someone can point me to a publicly available and maintained server providing OGC API - Tiles, I'd be happy to create an example.

**Comment by MartinOver2** [comment]
Here we go: https://ogc-api.nrw.de/  OGC API Features of the state North Rhine Westphalia (Germany)

**Comment by ahocevar** [comment]
@MartinOver2 Nice, but that server does not send CORS headers, so it cannot be used. Also, even if it would send CORS headers, it does not seem to support the `bbox` Parameter for `items`. So an example with a bbox or tile strategy would not work.

Anyway, since OGC API - Features uses GeoJSON as payload format, it would be easy to use e.g. the `landcoverunit` collection with a plain vector source that loads all items of the collection:
```js
new VectorSource({
  url: 'https://ogc-api.nrw.de/inspire-lc-fb/v1/collections/landcoverunit/items?f=json',
  format: new GeoJSON()
});
```
But again, since the server does not send CORS headers, this will not work.

**Comment by MartinOver2** [comment]
Thanks, works for me! The issue could be closed.
