### ISSUE TITLE
Question: is there a 6.5.1 version planned soon?

### ISSUE THREAD

**Issue by nboisteault** [openlayers/openlayers#12404]
Hi,
I'd like to know if there is a 6.5.1 version planned soon?
Also do you have a schedule for bugfix versions?
Thanks

**Comment by ahocevar** [comment]
@nboisteault You can always use the dev channel, i.e. `npm install ol@dev`. Those versions run the same tests as an official release. The two thing that an official release adds is release notes and hosted versioned API-docs. This is a manual process, and especially writing meaningful release notes is time consuming.

The next official release will be v6.6.0, because we have additions to the API. I myself don't have time right now to create a release (would change my mind if someone is the first to make use of my [https://github.com/sponsors/ahocevar](sponsor options) on GitHub). Not sure about the other core committers.

**Comment by nboisteault** [comment]
@ahocevar Many thanks for your answer!

**Comment by marcjansen** [comment]
Ping @ahocevar I'll send you a private message in this regard.

**Comment by ahocevar** [comment]
Thanks @marcjansen and [terrestris](https://terrestris.de/) for sponsoring my OpenLayers work through https://github.com/sponsors/ahocevar!

As soon as [milestone 6.6.0](https://github.com/openlayers/openlayers/milestone/42) is complete, I'll be creating a 6.6.0 release.

**Comment by abigstupidbear** [comment]
> Thanks @marcjansen and [terrestris](https://terrestris.de/) for sponsoring my OpenLayers work through https://github.com/sponsors/ahocevar!
> 
> 
> 
> As soon as [milestone 6.6.0](https://github.com/openlayers/openlayers/milestone/42) is complete, I'll be creating a 6.6.0 release.

Hi Sir.Can next version support dem data ,or 2.5D view？ if not ，in next next version,do you have plan to support this？ hope to get your reply!thanks😜
