### ISSUE TITLE
How to define my own grid class?

### ISSUE THREAD

**Issue by iteayyy** [openlayers/openlayers#12547]
I have some tiles to be added into the map with OpenLayers, but it can't work with WMTS or WMS in OL (the tiles do not fit in XYZ tile coordinate) . So I want to define a new kind of grid class to load these tiles, while I find it hard to do this.
I would appreciate if there are some examples introducing how to define a grid class.

**Comment by simonseyock** [comment]
Hello, this example uses a custom tilegrid for a vector tile source: https://openlayers.org/en/latest/examples/mapbox-vector-tiles-advanced.html
For `TileWMS` it works the same. The `WMTS` class accepts a `WMTSTileGrid` with some more options. Both parameters are named `tileGrid` in the options.

https://openlayers.org/en/latest/apidoc/module-ol_tilegrid_TileGrid-TileGrid.html
https://openlayers.org/en/latest/apidoc/module-ol_tilegrid_WMTS-WMTSTileGrid.html

Note for WMTS you can use the `WMTSCapabilities` format to read a WMTS capabilites document. You can then find the needed values and create a TileGrid from that.

**Comment by simonseyock** [comment]
Here are some example for WMTS:
https://openlayers.org/en/latest/examples/wmts-layer-from-capabilities.html
https://openlayers.org/en/latest/examples/wmts.html

Maybe we could add a new tag grid to all relevant examples.

**Comment by iteayyy** [comment]
Thank you so much.@simonseyock

**Comment by mike-000** [comment]
The source used in https://openlayers.org/en/latest/examples/print-to-scale.html is a good example of a non-standard tile grid because it is based on Ordnance Survey paper maps which use scales such as 1:10000, 1:25000, 1:50000, 1:100000, etc.  It could be defined as an XYZ source by copying the resolutions from https://tiles.arcgis.com/tiles/qHLhLQrcvEnxjtPr/arcgis/rest/services/OS_Open_Raster/MapServer to the resolutions array of a tile grid.  However using the WMTS link allows it to be set up as a WMTS source without needing to know that detail.  Also it could possibly be set up as a tile json (although currently OpenLayers does not support the ESRI json format).

**Comment by iteayyy** [comment]
Thanks guys, I am grateful to all your suggestion!
I have another question that if there are some map tiles, can I just pass certain parameters such as extent and image URL ? 
I mean this way is similar to ImageStatic API in OpenLayers, which is allowed to add a PNG image to the map. But if more other images are added, the images will be placed in different layers, not in the same layer.
So I wonder if there is a way or API or base class for users to define their own API to load different pictures ( PNG format ) in the same layer to a specific location.
