### ISSUE TITLE
Webgl style parsing incorrectly parses string as color in conditional operator

### ISSUE THREAD

**Issue by sebakerckhof** [openlayers/openlayers#12564]
**Describe the bug**
If you use strings that are colors (e.g. `red`) in conditional operators, the parsing of the expression fails.

**To Reproduce**
Have a webgl point layer with a style that includes a conditional like:
```js
['==', ['get', 'someProperty'], 'red'],
```

You get an error like: `Unexpected expression 'red' (expected type 6)`. Even though 'red' is exactly type 6 (meaning string or color)
The same would be true for number arrays of length 3 or 4.
The issue is that the `expressionToGlsl` function in `src/ol/style/expressions.js` doesn't deal with ambiguous typeHints. 

**Expected behavior**

The `expressionToGlsl` could either make a deterministic choice when this happens. E.g. prefer strings over colors if something can be both a string or a color.
Alternatively the syntax of the conditionals could be expanded to haven an optional 4th operator where the user can force a certain value type.

**Comment by mike-000** [comment]
I think the underlying problem is the use of the `isStringColor` function - its use elsewhere in the library is correct, but in `expressions.js` it can return false positives.  Just because a string can represent a color does not mean it is being used as a color - strings such as `'red'` and `'blue'` could be used in attributes such as names, and hex strings which represent colors could also have other uses.  An alternative function which only considers valid `rgb`/`rgba` and` hsl`/`hsla` strings which are unambiguously colors might more appropriate in `expressions.js`.
