### ISSUE TITLE
Problem with the difference in handling of click events between version 5 and version 6

### ISSUE THREAD

**Issue by koba-ninkigumi** [openlayers/openlayers#12606]
Here is a sample created by Google that works fine.  
https://github.com/google/open-location-code/blob/main/tile_server/example.html

If you look at this file, you will see that the version of the openlayers library is v5.1.3.  
→ https://cdn.rawgit.com/openlayers/openlayers.github.io/master/en/v5.1.3/build/ol.js
Of course, if you change it to v5.3.0, it works fine.
However, when I change to v6.0.0, the click events no longer work correctly.  
→ https://cdn.rawgit.com/openlayers/openlayers.github.io/master/en/v6.6.1/build/ol.js. 
If I change to the latest version, v6.6.1, the click events do not work properly as well.

I've looked at the list of destructive changes from openlayers v5 to v6 and can't find anything that seems relevant.  
Is this an intended change?  
If so, what would be the best practice to get this sample to work properly?

**Comment by tschaub** [comment]
It looks like the [vector tile selection](https://openlayers.org/en/latest/examples/vector-tile-selection.html) example provides similar functionality.

The relevant code is something like this:
```js
map.on('click', function(event) {
  layer.getFeatures(event.pixel).then(callback);
});
```

**Comment by koba-ninkigumi** [comment]
Thank you very much for posting the sample.

> ```js
> map.on('click', function(event) {
>   layer.getFeatures(event.pixel).then(callback);
> });
> ```

But ↑ with this code, only a part of the tiles are selected.

```js
var featureOverlay = new ol.layer.Vector({
  renderMode: 'vector',
  source: new ol.source.Vector(),
  map: olVectorMap,
});
olVectorMap.on('click', (e)=>{
  featureOverlay.getSource().clear();        
  olVectorMap.forEachFeatureAtPixel(e.pixel, (feature)=>{
    featureOverlay.getSource().addFeature(feature);
  });
});
```
This seems to be the best way to select all clicked areas.
However, with this code, once selected and then expanded, I can't select small areas properly.

**Comment by tschaub** [comment]
The [vector tile selection](https://openlayers.org/en/latest/examples/vector-tile-selection.html) example handles features that span multiple tiles by creating a lookup in the `callback`.  I won't post the complete code here since it is in the example, but you can have a layer that styles features based on whether their id is in the lookup.  Instead of adding/removing features from another source, use the same source for two layers and style the features differently depending on whether they are selected.

**Comment by koba-ninkigumi** [comment]
Thanks for the answer.

But this is what happens when I do what you say, right?

[https://user-images.githubusercontent.com/1291966/128806371-5beaa4ee-f647-450b-a4af-14eee195b8d9.mp4](url)

**Comment by boeckMt** [comment]
Here is a **codesandbox** https://codesandbox.io/s/vector-tile-selection-new-test-style-tfvem?file=/index.js
I first thought it could be due to the tiles of the vector layer, similar like the this issue https://github.com/openlayers/openlayers/issues/11107 but it seems everything is working fine.

@koba-ninkigumi maybe this sample can help you, the different colors are showing the boundaries of the tiles and the labels are `feature.getId`.
