### ISSUE TITLE
Crashes on iOS 15

### ISSUE THREAD

**Issue by bojanbizjak** [openlayers/openlayers#12908]
When using polygons filled with a canvas pattern, WebView crashes after a few moves of the map.

If we do not set map.pixelRatio: 1 then crashes occur even if the polygons are not filled with a pattern.

On Chromium 91 (macOS 11.6, Window 11 arm) and Android (tested on 5.1 and 11) WebView, crashes do not occur (even if map.pixelRatio: 3)

---
iPhone 12 Pro Max
iOS: 15.0.2
WebView: Mozilla/5.0 (iPhone; CPU iPhone OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148

An example of an image we use to fill a polygon:
![155](https://user-images.githubusercontent.com/12731463/138239012-3e80525c-7a52-416d-914b-32565cb9fa63.png)

Err Detail:

[Process] 0x10c5decd8 - GPUProcessProxy::didClose:
[Process] 0x10c5decd8 - GPUProcessProxy::gpuProcessExited: reason=crash
[Process] 0x10aecc900 - [PID=8847] WebProcessProxy::gpuProcessExited: reason=0
[Process] 0x104e0e0b8 - WebProcessPool::gpuProcessDidExit: GPU Process has crashed more than 2 times in the last 30 seconds, terminating all WebProcesses

**Comment by boomdrak** [comment]
Dont know if its related. But we have noticed that if we set map.contrains.enableRotation = false, crashes happen less often..

**Comment by boomdrak** [comment]
I have also try'd disabling "GPU Process: Canvas Rendering" in Safari iOS 15, but the same browser crash occurs.

ref: https://developer.apple.com/forums/thread/684843

**Comment by boomdrak** [comment]
Tested with iOS 15.2 beta, and same problem

**Comment by ahocevar** [comment]
I'm afraid we cannot do much about this at the moment. See https://twitter.com/rikschennink/status/1442443774748082185. It is up to the application developer to use as few layers as possible, and render the map with a lower `pixelRatio` if need be.

The reprojection example linked above needs several canvases for the raster reprojection, and I think (but haven't checked) we do not use the canvas pool for reprojection canvases. So the specific case of raster reprojection could maybe be improved. But not much else we can do.

**Comment by ahocevar** [comment]
Also see https://developer.apple.com/forums/thread/689071. For me, disabling the experimental "GPU Process: Canvas Rendering" feature made crashes in an application go away.

**Comment by boomdrak** [comment]
Our browser crash was related to pixels over 4096*4096

Its a shame that iOS does not give any human message about the crash/error and just reloads the browser. But thats another discussion.

We first pinpointed the error by lowering the screen resolution on an iPhone or using a iPhone SE with lower screen/pixel size.
After that we applyed `map.pixelRatio = 1;` on all map objects.

`Disabling GPU Process: Canvas Rendering` for us just made the map really slow, and did not have any affect on the crashes.

Hope this helps someone else :)
Thanks for the support, @ahocevar

**Comment by jeroenvheel** [comment]
@boomdrak We now also have a user with iOS 15 on a iPad the application keeps crashing.
We treid everything and now we have installed Edge brwoser ont he ipad the app is now working without crashing.
Maybe this will also work for you?

**Comment by bdon** [comment]
Take a look at https://bugs.webkit.org/show_bug.cgi?id=231157 - one workaround I've had success with outside of OL is to limit the total # of vertices in a single Canvas `fill()` or `stroke()` call to roughly 5000.

**Comment by Dominikosseqq** [comment]
I've found workaround that works for me (only for safari) on iPhone 13.
```
   let isSafari = /^((?!chrome|android).)*safari/i.test(platform.ua);
   if (isSafari) {
      HTMLCanvasElement.prototype.getContext = function (orig) {
         return function (type) {
            return type !== "webgl2" ? orig.apply(this, arguments) : null
         }
      }(HTMLCanvasElement.prototype.getContext)
```
Source: https://stackoverflow.com/questions/69073328/flutter-web-with-canvaskit-on-ios-15-beta

**Comment by t-muko** [comment]
Whoa! After long days without success, I have finally managed to get my multi-layer map application to work in IOS 15.2!
I have several raster image tile maps and multiple vector layers in my map (up to 10-15). Everything has worked in Chrome, Firefox and Android browsers all the time. IOS has been the villain. 

The first step was to start using the WebGLTile instead of the canvas based Tile for raster image rendering.
I replaced
`import { Tile as TileLayer } from 'ol/layer';`
with
`import TileLayer from 'ol/layer/WebGLTile';`

Luckily the class is almost drop-in replacement.

The trick that solved the IOS problem was to lower the WebGL TILE-cache size (not the similarly named source cacheSize). 
`new TileLayer({
      cacheSize: 128,
      ....`

The default is surprisingly high 512, but lower number 128 is more than enough to cache tiles for two zoom layers. I wonder if the default should be changed or if it can be made somehow dynamic?

I assume the 512 value was exhausting IOS Safari memory and the white screen crash & reload was not related to the canvas size limit at all. Just like happened with the canvas renderer.

Extra tip: In the old iPhones & iPads, you can manually enable WebGL 2.0 and WebMetal from Safari settings. Seems to work well with Openlayers 6.12.

**Comment by munenari** [comment]
I found a version with no crashing on same code that is 6.9.
(6.13 is still crashing)

**Comment by munenari** [comment]
I thought there was a problem with the layer's opacity.
This looks like a bug, but can't it be fixed to behave like it was at 6.9.0?
Unfortunately I don't know where to fix ol in this regard.

Below is an example of a crash on iOS.
https://github.com/munenari/olcrashtest

There are three ways to avoid the crash in this repo.
- Set opacity to 1
- Change layerNum to a smaller number
- Import the ol version in 6.9.0 (instead of 6.10.0 or later)

Thank you

**Comment by ahocevar** [comment]
I did a `git bisect`:
```
58806aaec1a414dd4b5903581b7567b12e8d164a is the first bad commit
commit 58806aaec1a414dd4b5903581b7567b12e8d164a
Author: Andreas Hocevar <andreas.hocevar@gmail.com>
Date:   Fri Nov 5 11:34:32 2021 +0100

    No context sharing when layer opacity is set

 src/ol/renderer/canvas/Layer.js       |  6 +++---
 src/ol/renderer/canvas/VectorLayer.js | 13 -------------
 2 files changed, 3 insertions(+), 16 deletions(-)
```
This is not a surprise. Previously, we had incorrect rendering when stacking layers with transparency. #12962 fixed that by turning off context sharing in such cases. The result of that is the need for multiple canvases, which triggers the crash in Safari on iOS.

My advice to work around this is to not use layer level opacity for VectorTile layers. Instead, use feature level opacity.

**Comment by munenari** [comment]
Thank you for your answer.
I have confirmed that it can be displayed well on iOS using array [r, g, b, opacity] of the color option of ol/style/Style~Fill and Stroke.

However, with this method, if many features overlap, the layer below will not be visible due to the overlap of opacity.
In the previous behavior, renderOrder was set and opacity was set for each layer, so I didn't have this problem.

(Furthermore, fill and stroke will also overlap, so it will be a different color than before)

Is there any other good way to do 'feature level opacity' ?

**Comment by ahocevar** [comment]
Other than avoiding such overlaps, I'm afraid not.

Another thing you could try is continue using layer opacity, but use `renderMode: 'vector'` on the VectorTile layers. This would also reduce the amount of canvas usage.

**Comment by boomdrak** [comment]
Before ios 15.4.1 map.pixelRatio = 1 made our application stable again.

But after ios 15.4.1 and new webkit/safari we experience same crashes of safari.
Unable to pinpoint cause of crash. Safari tab just freezes and becomes unresponsive :/

**Comment by boomdrak** [comment]
@bojanbizjak have you got the same old / new issues with ios v 15.4.1?
My whole safari tab freezes and crashes

**Comment by bojanbizjak** [comment]
No, we don't notice any problems on iOS 15.4.1.
More than 50 vector layers with large number of features are used (canvas patterns is also used).
In addition to vector layers, the map also includes several WMTS and WMS layers.
(Capacitor platform, map.pixelRatio = 1)
