### ISSUE TITLE
How to wrap text outside the polygon range

### ISSUE THREAD

**Issue by abigcivet** [openlayers/openlayers#13099]
![e26c5dbd4b99456db3a01f90b2512efd](https://user-images.githubusercontent.com/33509213/145357580-72320b0b-6eaa-4185-984b-480f774a5e9d.png)

**Comment by mike-000** [comment]
There is no automatic wrapping of labels unless you use `ol-mapbox-style` or `ol/layer/MapboxVector` with a style that specifies wrapping.  Otherwise you must use a function similar to `stringDivider` in https://openlayers.org/en/latest/examples/vector-labels.html (in your case where there are no spaces you might want to divide before upper case characters).

**Comment by AugustusKling** [comment]
Depending on what you want to achieve you can either introduce line breaks in your application code as shown in the already linked example or you need to draw on the canvas directly if more control is required. The example in https://openlayers.org/en/latest/examples/custom-circle-render.html shows how to do this.

I tend to find myself drawing labels with the canvas API sooner or later because the default label placement is not suitable for all polygons. Also the default placement cannot take other drawing elements into account - for example icons to be placed along with the labels. Regarding positioning you might want to look at Mapbox's excellent library: https://github.com/mapbox/polylabel

Recently, I've experimented with line breaks in labels and finding positions based on the polygons' pixels (biggest horizontal rectangle in polygon area). It's still very rough but shows a different spin on the problem. Basically, the code generates some candidates with different line break variants, checks which are feasible, and picks a hopefully decent placement for drawing. Maybe this is of use for somebody.
https://stackblitz.com/edit/typescript-5a1vki?file=index.ts

**Comment by abigcivet** [comment]
Thank you very much for your help ！！！😀
