### ISSUE TITLE
Dependency categorising: ol-mapbox-style 

### ISSUE THREAD

**Issue by eFrane** [openlayers/openlayers#13143]
**Is your feature request related to a problem? Please describe.**
A while back, when support for Mapbox Vector Tiles [was added](https://github.com/openlayers/openlayers/commit/4d9975754f92a8b87f1907400f93fe82f5e66b80#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519), `ol-mapbox-style` was moved from `devDependencies` to `dependencies`. 

**Describe the solution you'd like**

I don't see any good reason why this dependency which is only needed for specific use cases should be installed by default. Can it be moved back to `devDependencies`?

**Comment by ahocevar** [comment]
`ol/layer/MapboxVector` uses `ol-mapbox-style`. So when you use a bundler, it won't be included in the build unless you use `ol/layer/MapboxVector`.

**Comment by eFrane** [comment]
But if I never use Mapbox Vector Layers I still have to deal with tools like Dependabot (or manual upgrading if you like) trying to upgrade `ol-mapbox-style` from time to time. My point is, since this Dependency is not required at all to be able to use OpenLayers, it should not be forced into the dependency chains of ol users. Instead, the documentation for using vector layers should inform about requiring this side-dependency. It may also/alternatively be a good idea to list it as [peer dependency](https://docs.npmjs.com/cli/v6/configuring-npm/package-json#peerdependencies).

**Comment by ahocevar** [comment]
Well, that's like if you never use Vector layers you don't need `rbush`, and you still accept that it is a dependency of OpenLayers. Maybe the confusion comes from the fact that `ol/layer/MapboxVector` is quite a new module, and its `ol-mapbox-style` dependency was previously used in an example, which is why it was previously a dev dependency.

Note that since a module of the `ol` package (`ol/layer/MapboxVector`) in this case depends on `ol-mapbox-style`, this has to be a dependency. not a dev dependency and not a peer dependency.

May I ask why using a tool like Dependabot causes you headache?
