### ISSUE TITLE
Cannot read properties of null (reading 'getStyleFunction')

### ISSUE THREAD

**Issue by lklepner** [openlayers/openlayers#13213]
**Describe the bug**
I've got vector tiles generated from QGIS which I have successfully loaded Mapbox GL but when I load them in a simple OL setup I get the error "Cannot read properties of null (reading 'getStyleFunction')". 

https://codesandbox.io/s/vector-tile-info-forked-hbivu?file=/main.js

I'm new to OL so its quite possible I'm doing something wrong. I've tried applying a style property to the VectorTileLayer without success. Any recommendations would be greatly appreciated.

**Comment by ahocevar** [comment]
It looks like at least one of your tiles contains incorrect data. A quick debugging session showed that the https://s3.amazonaws.com/net.livefeed.public.data/tiles/nysdot-accidents/9/150/188.pbf tile contains a feature with `type === 0`, which is not handled properly in the MVT format. `MVT.prototype.createFeature_` returns `null` in this case, and `readFeatures()` adds that `null` feature to the `features` array instead of skipping it.

The fix should be an easy pull request if you want to give it a try.

**Comment by lklepner** [comment]
Thank you for debugging @ahocevar and for the fix @EvertEt. I can confirm this fix resolved the problem I was experiencing -
https://codesandbox.io/s/vector-tile-info-forked-hbivu?file=/package.json

I prepared a branch with the fix @ahocevar suggested last night ( https://github.com/lklepner/openlayers/tree/prevent-null-features ) but I had trouble figuring out how to run my branch after running `yarn build-package`. 

The `DEVELOPING` doc doesn't have any references to this part of the lifecycle. 
https://github.com/openlayers/openlayers/blob/main/DEVELOPING.md

Is there another doc which describes a way to manage this workflow? If not can/should we add something to the existing dev doc?

**Comment by ahocevar** [comment]
The `ol` package is published from `build/ol`. So when you `cd` into `build/ol` and run `npm link`, then `np link ol` in your project, you should be all set for testing your branch. If you feel that some information along these lines could be added to the docs, a pull request would be welcome.

**Comment by lklepner** [comment]
Thanks @ahocevar. I just submitted a PR with these notes - 
https://github.com/openlayers/openlayers/pull/13228
