### ISSUE TITLE
Interpolation of TileLayer does not work in Firefox after adding VectorImage layer

### ISSUE THREAD

**Issue by lysek** [openlayers/openlayers#13234]
**Describe the bug**
This only happens in Firefox, Chrome seems to be OK.

**To Reproduce**
1. Open Firefox (I used 95.0.1 under Linux Mint)
2. Go to https://jsfiddle.net/oxdLycwn/1/
3. See the map interpolated nicely ("blur effect")
4. Click on the button to add VectorImage layer
5. Move the map a little by dragging the map
6. The map is not interpolated now and you can see individual pixels

**Expected behavior**

**Comment by mike-000** [comment]
Chrome is also affected for me.  I think #13221 should also have been applied to Vector source (or interpolation made an option for Vector source where it is used in a VectorImage layer).

This also demonstrates there is an additional problem if two layers with different interpolation settings share a 2d canvas, as interpolation will then be disabled for both layers.

**Comment by ahocevar** [comment]
> This also demonstrates there is an additional problem if two layers with different interpolation settings share a 2d canvas, as interpolation will then be disabled for both layers.

I think interpolation should always be set per tile, then this won't be a problem. Then it would also be consistent to always use the `interpolate` tile option, instead of the source option, which we could deprecate entirely.

**Comment by mike-000** [comment]
What about Image sources?  This has been an unnoticed issue that goes back to v6.4.0. https://openlayers.org/en/v6.4.0/examples/reprojection-image.html  Ensure browser zoom is off so the pixel ratio is one then zoom in to where the edge of the image is close to some text and turn off interpolation.  Both layers change.  Switching interpolation back on does not undo either layer - in this case the image layer will appear interpolated but that is due to interpolation during scaling and reprojection, not the final render.

![image](https://user-images.githubusercontent.com/49240900/149378018-1a0ae184-525e-4442-a847-4099b745b8b1.png)

**Comment by mike-000** [comment]
The underlying problem seems to be that when `imageSmoothingEnabled` is set false at the start of the Tile and Image layer renderers' `renderFrame` methods it is never reset, on the assumption that would never be necessary. https://github.com/openlayers/openlayers/blob/89f632fa7e5a06efe35e47eaaace7cfa9a10ac0f/src/ol/renderer/canvas/TileLayer.js#L321-L323 https://github.com/openlayers/openlayers/blob/89f632fa7e5a06efe35e47eaaace7cfa9a10ac0f/src/ol/renderer/canvas/ImageLayer.js#L188-L190 

That would be easy to fix.
