### ISSUE TITLE
Async calls for FeatureFormat

### ISSUE THREAD

**Issue by MagicCrazyMan** [openlayers/openlayers#13296]
**Is your feature request related to a problem? Please describe.**
I'm currently working on achieving a simple Shapefile(under zip-compressed) parser.
But while those unzip libs using async to decompress file and i'm planning to use Web Worker for decoding Shapefile,
it seems not to be a good idea by implementing `FeatureFormat` without async calls.

Before implementing a `VectorSource` with a custom `loader`, 
i wanna know is it possible to transform those write and read functions to async functions in `FeatureFormat`.

**Describe the solution you'd like**
Transform write and read functions to async functions in `FeatureFormat`.

**Comment by ahocevar** [comment]
The FeatureFormat write and read methods you mention are synchronous by design, and they run once the asynchronous part of the process, i.e. the source loading the data that the format is about to parse, is completed.

If you really want to make such a synchronous function asynchronous, you could do something like this:
```js
function readFeaturesAsync(features) {
  return Promise.resolve(featureFormat.readFeatures(features));
}
```

**Comment by MagicCrazyMan** [comment]
Thanks for your reply.

After continue working on Shapefile parser, i found that using `FeatureFormat` wasn't a good idea for the parsering procedure is not stateless. It is better to load it via a custom `loader` of `VectorSource`.

i will close this issues soon, thanks so much
