### ISSUE TITLE
Cannot read properties of null (reading 'forEachFeatureAtCoordinate')

### ISSUE THREAD

**Issue by EvertEt** [openlayers/openlayers#13436]
**Describe the bug**
`forEachFeatureAtPixel` errored in our application. `Cannot read properties of null (reading 'forEachFeatureAtCoordinate')`
I would expect (not 100% sure) that it was on a map where the target had just been removed. 

https://github.com/openlayers/openlayers/blob/main/src/ol/PluggableMap.js#L635
**To Reproduce**
```
map.renderSync();
map.setTarget(undefined);
map.forEachFeatureAtPixel([1, 2], () => {});
```

**Expected behavior**
No error. Would it make sense to guard again a null `renderer_` in PluggableMap or is it unsupported to call functions on the map when it has no target?

**Comment by ahocevar** [comment]
Guarding agains `renderer_` being null does make sense, and adding `|null` too. This would mean that `forEachFeatureAtPixel` et al. would not return features when a map does not have a renderer (which happens when it does not have a target), which makes sense because without target, we don't have a way to know how a pixel translates to a coordinate.

Would you be able to create a pull request, @EvertEt?

**Comment by EvertEt** [comment]
Will do, 1 question:
What would be the preferred way to handle a nulll renderer_ in `renderFrame_`?
`    this.renderer_.renderFrame(frameState);`

**Comment by ahocevar** [comment]
`renderFrame_` won't be called when there is no renderer. So a type cast should be fine.
