### ISSUE TITLE
V6.13.0 regression - Color-manipulation example flickering with #13398 fix

### ISSUE THREAD

**Issue by imagoiq** [openlayers/openlayers#13459]
**Describe the bug**
Color-manipulation example map get flickering when panning and zooming.

It was introduced with this fix: https://github.com/openlayers/openlayers/pull/13398
I tried to reproduce the bug mentioned in https://github.com/openlayers/openlayers/issues/13397, but I wasn't able (here is my patch to use it as an example in the repo: https://gist.github.com/imagoiq/b4b8d2c9be516018300973a42f2ff5da). 

The flickering is induced by `reprojectedImage_` in `source/Image` getting null initially when zooming or panning, which is incompatible with https://github.com/openlayers/openlayers/pull/13398 fix. I would love to help, but I have no idea what would be the fix, perhaps looking for projection's change?

**To Reproduce**
1. Go to https://openlayers.org/en/latest/examples/color-manipulation.html
2. Zoom in

**Comment by ahocevar** [comment]
I think the right fix would be to keep one image per projection, i.e. `this.image_[projectionCode]` instead of `this.image_`.

As a quick fix, I'd be inclined to revert the changes made in #13398. If @yonda-yonda can provide a test case that fails without the changes in #13398, we can work a fix for that.

**Comment by oliamb** [comment]
Thanks a lot for the fix ❤️
