### ISSUE TITLE
WebGlTile in a group always visible 

### ISSUE THREAD

**Issue by jcarbou** [openlayers/openlayers#13507]
See https://codesandbox.io/s/wms-image-custom-proj-forked-dfc1vm?file=/main.js

The map contains a single layer of type Group (ol/layer/Group).
The group contains a single layer of type WebGlTile  (ol/layer/WebGlTile ).

After 3 seconds the code change the visibility of the group (from true to  false)

=> The WebGlTile layer is still visible !

Note : If I change the type of the layer from WebGlTile  to Tile (ol/layer/Tile), the layer is hidden when the group visibility is set to false. The issue is only for WebGlTile

**Comment by tschaub** [comment]
It looks like this was introduced in #13212.  During rendering, the layer states are calculated so that group visibility is applied to a layer's "own" state.  For WebGL tile layers after #13212, calling `layer.getSourceState()` [now calls](https://github.com/openlayers/openlayers/pull/13212/files#diff-e6aa1bc5744c53b52762df50d5018adadcf0ac8be998c596f064e38801e5351eR353-R358) `layer.getLayerState()` which modifies the layer's own state so that it again represents its own visibility.

Generating layer states tries to avoid unnecessary allocation, but the resulting code is fragile due to all of the mutability.  Digging around for a fix...

**Comment by tschaub** [comment]
Proposed fix in #13509.

**Comment by jcarbou** [comment]
Thanks for the quick fix !
