### ISSUE TITLE
COG example in react do not render

### ISSUE THREAD

**Issue by geogeek11** [openlayers/openlayers#13526]
I have tried to reproduce the [COG example](https://openlayers.org/en/latest/examples/cog.html) using react, The code only works after hot reload after a code change it displays 2 maps using duplicated `ol-viewport` div tag, and it gives a blank page after a normal page reload.

Please check [this sandbox](https://codesandbox.io/s/exciting-panini-xuhj16?file=/src/App.js)

**Comment by ahocevar** [comment]
This is not specific to the COG example, but applies to any OpenLayers map you use in React: Instead of configuring the map with `target: "map"`, you need a `useEffect()` function to set the target when React has finished building the page structure:
```js
useEffect(() => map.setTarget("map"));
```
See this updated codesandbox for the working example: https://codesandbox.io/s/quizzical-meadow-5y7v14?file=/src/App.js
