### ISSUE TITLE
Interactions in a popup are disabled when the parent window is hidden.

### ISSUE THREAD

**Issue by NoriSte** [openlayers/openlayers#13567]
**Describe the bug**
Interactions in a popup are disabled when the parent window is hidden.

**To Reproduce**
1. Go to the ["External map" example](https://openlayers.org/en/latest/examples/external-map.html)
2. Open it in CodeSandbox
3. Modify the `main.js`'s `updateOverlay` function as following
```diff
function updateOverlay() {
+return // disables handling the 'visibilitychange' event
```
4. Click the  "Open external map" button rendered in the app
5. Wait for the map to be loaded in the popup
6. Send the popup full screen or minimize the main window

Then, the map doesn't handle interactions anymore.

**Expected behavior**
I expect the map to correctly handle interactions when the window that contains it is visible, even if the parent window that opened the popup is hidden.

Thanks for the hard work.\
Stefano

**Comment by MoonE** [comment]
Currently the child window is still using its parent to trigger animation frames. When the parent is hidden timeouts are suspended and the child will no longer redraw, that's why it is implemented like this in the example.

This has been brought up before in https://github.com/openlayers/openlayers/pull/12893#issuecomment-948284350 and an attempt at a solution was made in #12988, though solving it in a consistent manner seems tricky.

**Comment by NoriSte** [comment]
Thanks for your support, @MoonE 🙂
