### ISSUE TITLE
iOS 15.6 - VectorLayer setMinZoom, setMaxZoom - zooming past min/maxZoom breaks map interactions

### ISSUE THREAD

**Issue by forth-eorlingas** [openlayers/openlayers#13725]
**Describe the bug**
On iPhone with iOS 15.6 developer beta 1 and 2 we get following behaviour:

When setting a minZoom or maxZoom on a VectorLayer and zooming past the limit that was set, map interactions break and one can no longer zoom and pan normally.

**To Reproduce**
1. Go to
        https://codesandbox.io/s/vector-layer-forked-fhcbkr
        or
        https://codesandbox.io/s/cluster-forked-5yg6d9
2. Zoom in/out past max/min zoom limit
3. See error

**Expected behavior**
Map can be interacted with normally after zooming past min/maxZoom limit

**Comment by jak983464779** [comment]
Ios15.5 suffers from the same problem

**Comment by ahocevar** [comment]
What happens if you add the following to your css?
```css
#map {
  touch-action: none
}
```

**Comment by jak983464779** [comment]
> What happens if you add the following to your css?
> 
> ```css
> #map {
>   touch-action: none;
> }
> ```

IT IS LOADED WITH MVT TYPE DATA. IT WAS NORMAL IN IOS 15.4 BEFORE. THIS BUG WAS FOUND AFTER THE MOBILE PHONE SYSTEM WAS UPGRADED.

**Comment by Skizu** [comment]
I added `touchend` and `touchstart` listeners to `ol/MapBrowserEventHandler.js`, creating `pointerup` events for each `trackedTouches_` which was not active within `event.touches`. This resolved the "sticky finger" bug; however, with a large caveat whenever the event was fired the maps' touch events were unresponsive for a second or so. The easiest way to mitigate this issue is by reverting [#12792](https://github.com/openlayers/openlayers/pull/12792/files).

**Comment by forth-eorlingas** [comment]
Duplicate of #13746
