### ISSUE TITLE
Property 'setCoordinates' does not exist on type 'Geometry'.

### ISSUE THREAD

**Issue by nharshavreddy** [openlayers/openlayers#13839]
HI,
I am using open layers 6.14.1 in angular 
i am trying to add coordinates using below function 
multiLineFeature.getGeometry().setCoordinates([])
it is throwing the below error

Property 'setCoordinates' does not exist on type 'Geometry'.

**Comment by ahocevar** [comment]
If you use generics to give your feature the type `Feature<MultiLineString>` instead of just `Feature`, it will work. The reason for this error is that there is also a `GeometryCollection`, which is a subclass of `Geometry`, but does not have a `setCoordinates` method. And without using generics for the `Feature` instance, TypeScript does not know what kind of geometry you're dealing with.

**Comment by nharshavreddy** [comment]
It worked.
Thank you
