### ISSUE TITLE
Can't get the latest openlayers version.

### ISSUE THREAD

**Issue by SNoiraud** [openlayers/openlayers#14055]
I used to get the following two files:

https://openlayers.org/en/latest/build/ol.js
https://openlayers.org/en/latest/css/ol.css

It no longer works since 7.0.0 was released. I get a 404 error.

**Comment by mike-000** [comment]
It has moved to
https://openlayers.org/en/latest/legacy/ol.css
https://openlayers.org/en/latest/legacy/ol.js

but instead of linking directly to the site you should have been using the jsdelivr CDN which is now
https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@main/dist/en/latest/legacy/ol.css
https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@main/dist/en/latest/legacy/ol.js

or better still download the files to your own site from the release page https://github.com/openlayers/openlayers/releases/tag/v7.0.0

**Comment by SNoiraud** [comment]
Websites are dynamically created by gramps (gramps-project.org)
I didn’t want to add these files to our repository. This is why I used those files.
