### ISSUE TITLE
Double placement of map on both hemisphere with custom projection

### ISSUE THREAD

**Issue by pakb** [openlayers/openlayers#14135]
**Describe the bug**
I don't know if I'm doing something wrong, but I've added a map using some custom projection (Swiss LV95), and I can see my tiles two times. One time is fine, where it should be. The other one is on the other side of the world, by New Zealand 🤷 

**To Reproduce**
have a look here : https://codesandbox.io/s/weird-map-placement-with-epsg-2056-iprrpb?file=/src/index.js

**Expected behavior**
No tiles requested on the southern hemisphere, as the declared extent shouldn't allow that.

**Comment by mike-000** [comment]
That also happens when Swiss Topo is selected as the overlay in the https://openlayers.org/en/latest/examples/reprojection.html and would also happen for British National Grid if a layer extent was not set for that layer.  It is a limitation of the transforms being used, see the comment "Example how to prevent double occurrence of map by limiting layer extent"  in that code .  A downside of setting a layer extent in that way is that the layer would appear on only one world in a wrapping view.  When using a wrapped view you could instead set the extent in a reprojection grid (see https://openlayers.org/en/latest/apidoc/module-ol_source_XYZ-XYZ.html#setTileGridForProjection) as in https://codesandbox.io/s/weird-map-placement-with-epsg-2056-forked-fypfwt?file=/src/index.js

**Comment by pakb** [comment]
Ok thanks a lot!
I thought defining the extent on the TileGrid would be enough so that OL wouldn't requests tiles outside of it. Thanks for the insight
