### ISSUE TITLE
Heatmap: same opacity for any weight

### ISSUE THREAD

**Issue by TheRulisp** [openlayers/openlayers#14394]
Hello. I'm using Heatmap for visualization of calculation results. 

Everything works fine, except one thing that I noticed: for small values heatmap becomes mostly invisible and I really need them to be visible.

Is there any chance to set same opacity for any weight?

I've tried to override Heatmap class and its function `createRenderer`. But I don't know WebGL at all, so all my attempts failed.

![Sample](https://user-images.githubusercontent.com/1313049/208906034-a81d1c6d-fc32-49ac-904b-8e49bee15946.png)

**Comment by mike-000** [comment]
I think you could acheive what you need without a custom class by ensuring the layer weight function returns values between (for example) 0.5 and 1 instead of 0 and 1, and setting a gradient to match if necessary.

If you still want  a custom renderer you could set only the layer opacity at https://github.com/openlayers/openlayers/blob/main/src/ol/layer/Heatmap.js#L293 while within the hit detection range https://codesandbox.io/s/heatmap-earthquakes-forked-23qd5u?file=/main.js

**Comment by TheRulisp** [comment]
@mike-000 thank you for your answer. 

Solutions didn't work separately, but when I combined them (minimal weight restriction to 0.1 and changed `gl_FragColor.a` in `postProcess`  to `color.a < 0.05 ? color.a * u_opacity : u_opacity;`) it started to show exactly what I needed. 

Thank you again
