### ISSUE TITLE
Static Image extent by different width/height

### ISSUE THREAD

**Issue by murimere** [openlayers/openlayers#14514]
Hello, i use the Static Image function to display static images as a overlay in a map. The images are loaded by click OL feature points in the map. The problem is, the images have different width/height. Current, i have put the static image overlay map functions in a `image.onload` event and get the width/height inside of this. By this, the images are loaded at two times. The good one is, the browsers requests the images at the second time from the cache. But im common sense, the two time loading is not so good.

Have anyone an idea to get the image with/height for `imageExtent` with only one image loading?

Here is the example: https://openlayers.org/en/latest/examples/static-image.html

**Comment by matomoto** [comment]
A solution was found, but has a bad performance, is also not really a solution:
https://gis.stackexchange.com/questions/452593/ol-static-image-with-dynamic-extent

**Comment by jahow** [comment]
Can't you provide the image to the layer source as base64, or maybe as a local url using `createObjectURL`? This would avoid having to load it again from its remote url.

**Comment by murimere** [comment]
@jahow , the website is online in the internet and the images are on the server. It is a publicly accessible website for everyone. There are several thousands of different images. There is no file input. Each image is loaded into a new map in an OL popup by clicking on an OL feature point. This is the current version. A previous version used a CSS image zoom script. But the performance was bad. The use of a tile server is not an option. Convert the image into a base64 string has also a bad performance, see the linked solution on stackexchange.

**Comment by jahow** [comment]
I made an experiment here: https://codesandbox.io/s/static-image-forked-ronyo6?file=/main.js

Basically you can load an image data manually using `fetch` and then storing the resulting Blob. Creating an image out of the blob will let you know the dimensions of it, and then you can create a static image source out of it as well, thus not requesting the image a second time. The main drawback is that the images need to allow cross-origin usage through CORS headers.

There are probably other solutions. you could for instance have a service worker keeping a cache of images on the client in order to request them as often as you need.

**Comment by murimere** [comment]
@jahow , whit your code example it loads further at two times in my script. After change `img.src = src` to `img.src = objectUrl` it works fine with only one image load. Many thanks for the hint!

**Comment by jahow** [comment]
Oh right, sorry for that! Glad it could help either way :)
