### ISSUE TITLE
Label that is numeric fails on a split() call

### ISSUE THREAD

**Issue by tlepkowski** [openlayers/openlayers#14532]
When we set a label that is all numeric, such as "234567" , ol/render/canvas/Executor.js createLabel function throws an exception on text.split.  Looks like javascript sets to a numeric type, but the code is making assumption it's a text/string type, which split() function, but not numeric type.  Exception is: **"Uncaught TypeError: t.split is not a function "**

**Comment by mike-000** [comment]
You probably need to ensure the value is passed as a string as in  `text: size.toString(),` in this example https://openlayers.org/en/latest/examples/cluster.html

**Comment by tlepkowski** [comment]
Of course, but this is not a clean solution. It's a compromise. A temporary patch.

**Comment by mike-000** [comment]
The docs specify `text` must be `string | Array.<string> | undefined`.  If you supply anything else an error is to be expected.  OpenLayers could try to convert invalid arguments to strings e.g. `'' + argument` but that would be inefficient.  Similarly errors can occur if values such as coordinates are passed as strings instead of numbers.

**Comment by tlepkowski** [comment]
Yeah, it hides behind the docs. Agreed. In our code design we have an opportunity to decide what should be liberal on input, and what should be conservative on input. Plenty of these examples in OL.  Projections, Style , etc. Why should a thing like label be so lofty?
