### ISSUE TITLE
Icons Flashing on & off constantly 

### ISSUE THREAD

**Issue by GokhanIrmak** [openlayers/openlayers#14573]
I have edited Open Layer's ["Icon Symbolizer" example](https://openlayers.org/en/latest/examples/icon.html) for my case and latest code is different until layer definition part(line 35 on example code). Rest of the code will be same with the example.

Question is: When I put too much different colors with different features I get flashing points instead of showing all points constantly.

**To Reproduce**
```js
function getRandForCoordinates(from, to, fixed) {
  return (Math.random() * (to - from) + from).toFixed(fixed) * 1;
}

function GetVectors() {
  let icons = [];
  for (let i = 0; i < 850; i++) {
    
    icons[i] = new Feature({
      geometry: new Point([getRandForCoordinates(-180, 180, 3)*500, getRandForCoordinates(-180, 180, 3)*5000]),
      name: 'Null Island',
      population: 4000,
      rainfall: 500,
    });
  }

  return new VectorSource({
    features: icons,
  });
}

function StyleBuilder() {
  var MyColor =
    'rgba(' +
    Math.floor(Math.random() * 254) +
    ',' +
    Math.floor(Math.random() * 254) +
    ',' +
    Math.floor(Math.random() * 254) +
    ',' +
    1 +
    ')';
  return new Style({
    image: new Icon({
      color: MyColor,
      crossOrigin: 'anonymous',
      src: 'data/icon.png',
    }),
  });

}

const vectorLayer = new VectorLayer({
  source: GetVectors(),
  style: StyleBuilder,
});
```

**Expected behavior**
Flashing Icons

****
I have tried to give style on feature definition. It is resolving the issue but using with clusters as well and needing style on layer definiton is a problem it seems.

**Comment by mike-000** [comment]
You can set random styles on a cluster source by calculating it once for each new cluster when the cluster is added https://codesandbox.io/s/cluster-forked-mqml5h?file=/main.js  Each cluster can have a random color even if the clusters contain the same number of features.

**Comment by MoonE** [comment]
Icons are flashing because you are creating new icons with each animation frame and OpenLayers by default only caches 32 icons for your convenience.

Loading icons takes a few ms during which they cannot be drawn to the map. If you exceed the maximum cached amount some needed icons are evicted from the cache to make room. And each time an icon has been loaded OpenLayers will redraw the map automatically.

You can increase the [IconImageCache](https://openlayers.org/en/latest/apidoc/module-ol_style_IconImageCache-IconImageCache.html) size ...
```js
import {shared as iconImageCache} from 'ol/style/IconImageCache.js';
iconImageCache.setSIze(maxIcons);
```
... or, as in @mike-000's example you can cache the style/icon objects yourself (on the Feature objects, or in an array) to avoid creating style objects on each render.

**Comment by GokhanIrmak** [comment]
Both solves my problem, thank you so much.
