### ISSUE TITLE
Return Last SnapTo Feature

### ISSUE THREAD

**Issue by fmg-lydonchandra** [openlayers/openlayers#14675]
**Is your feature request related to a problem? Please describe.**
ol.interaction.Snap to return last snapTo feature. 
see https://stackoverflow.com/questions/32194030/how-to-get-feature-which-is-snaped-by-ol-interaction-snap

**Describe the solution you'd like**
ol.interaction.Snap to return last snapTo feature alongside existing result object 

```
return {
            vertex: closestVertex,
            vertexPixel: [
              Math.round(vertexPixel[0]),
              Math.round(vertexPixel[1]),
            ],
            feature: closestFeature,
          };
```

**Comment by mike-000** [comment]
As you suggested in Stack Overflow you can use `forEachFeatureAtPixel`.  That could be done in a `condition` function for any interaction, as well as `drawstart` and `drawend`, and done using only documented API methods as in https://codesandbox.io/s/draw-and-modify-features-forked-enrgqv?file=/main.js  If the Snap interaction was constructed with `features: snapFeatures` instead of `source: snapSource` just replace `snapSource.getFeatures().includes` with `snapFeatures.getArray().includes`.

**Comment by ahocevar** [comment]
I think the best way to add an API for getting information about what was snapped would be a new Snap event, dispatched by the Snap interaction, in its `handleEvent` function when there is a `result`. The event could have the desired `vertex`, `vertexPixel` and `feature` properties.

**Comment by fmg-lydonchandra** [comment]
hi @ahocevar & @mike-000  feedback / review please, https://github.com/openlayers/openlayers/pull/14676

**Comment by fmg-lydonchandra** [comment]
hi @ahocevar , PR re-review please https://github.com/openlayers/openlayers/pull/14676

**Comment by fmg-lydonchandra** [comment]
hi @ahocevar  , PR re-review please https://github.com/openlayers/openlayers/pull/14676
