### ISSUE TITLE
useGeographic() and WebGLVectorLayerRenderer are not fully compatible

### ISSUE THREAD

**Issue by vitalus** [openlayers/openlayers#14811]
Simply,

        const layer = new WebGLLayer({
            source: new VectorSource({
              url...
              format: new GeoJSON(),
            })
          }

is working, but

        const layer: WebGLLayer = new WebGLLayer({
            source: new VectorSource({
                features
            })
        },
        style);

is not.

Tested  with same JSON in EPSG:4326, loaded by OL (first case) and preloaded and passed as Feature[] (second case).
In first case data comes to the renderer in EPSG:3857 (internal reprojection is done when data is loaded), in second case it comes in EPSG:4326 and rendering does not work at all.

**Comment by mike-000** [comment]
Also applies to WebGLPointsLayer.  The first case is incorrect as the feature geometry should be in the user projection, not the view projection - it is only working because of the issue in the second case.  Both WebGLVectorLayer and WebGLPointsLayer are still experimental, so full support might not be expected.

But the Heatmap layer which uses WebGLPointsLayer is not experimental and therefore would be expected to support features in a user projection - but it does not https://codesandbox.io/s/heatmap-earthquakes-forked-es3mvf?file=/main.js

**Comment by tschaub** [comment]
After #15118, you can call `useGeographic()` and the WebGL vector renderer will transform geometries with geographic coordinates before rendering.
