### ISSUE TITLE
ol/proj transformExtent returns bad data

### ISSUE THREAD

**Issue by PatchesMaps** [openlayers/openlayers#14961]
**Describe the bug**
Transforming specific extents using proj.transformExtent near Antarctica from EPSG:4326 to EPSG:3031 (or to EPSG:4326) generates `[Infinity, Infinity, -Infinity, -Infinity]`. This behavior is inconsistent and certain extents will fail to be transformed while other nearby extents will transform without issue.

**To Reproduce**
```
import { transformExtent } from 'ol/proj

console.log(transformExtent([-157.6938, -72.6479, 82.6547, -80.291], 'EPSG:4326', 'EPSG:3031')) // returns [Infinity, Infinity, -Infinity, -Infinity]

console.log(transformExtent([-157.6938, -72.6479, 82.6547, -80.291], 'EPSG:4326', 'EPSG:4326')) // returns [Infinity, Infinity, -Infinity, -Infinity]

console.log(transformExtent([[-141.5768, -78.6318, 46.8319, -77.539], 'EPSG:4326', 'EPSG:3031')) // returns [-844611.0275765229, -1064747.955111334, 991233.1220461084, 929791.8549741994]
```

**Expected behavior**
It is expected that the extents should be transformed to the specified projection-like. If the input extent cannot be transformed to the target projection-like then an error should be thrown. Transforming an extent where the source and destination projection-likes are the same should return the input extent unchanged.

**Workaround**
```
import { fromExtent } from 'ol/geom/Polygon'

const extentPolygon = fromExtent([-157.6938, -72.6479, 82.6547, -80.291]);
const crsCorrectedExtentPolygon = extentPolygon.transform('EPSG:4326', 'EPSG:3031');
const crsCorrectedExtent = crsCorrectedExtentPolygon.getExtent();
```

**Comment by mike-000** [comment]
`[Infinity, Infinity, -Infinity, -Infinity]` represents an empty extent.

That is because `[-157.6938, -72.6479, 82.6547, -80.291]` is also empty (it is invalid) as it should be botton left, top right with the top always above the bottom, i.e. `[157.6938, -80.291, 82.6547, -72.6479]`.  Transforms between non-parallel projections are not reversible because all four corners are transformed and the resulting extent is taken to include all of those, so each transform will increase the coverage.  If there is a bug anywhere it is that polygon `fromExtent` does not recognise an invalid extent.
