### ISSUE TITLE
Update Stamen source

### ISSUE THREAD

**Issue by tschaub** [openlayers/openlayers#14963]
Stamen tiles are moving: https://docs.stadiamaps.com/guides/migrating-from-stamen-map-tiles/

This will be a breaking change since the tiles will require an API key or registered domain to work.

**Comment by ianthetechie** [comment]
Hey @tschaub, Ian from the Stadia Maps team here. I'd be happy to help with a PR for this. I'm already working with the Leaflet Providers team on a similar PR (https://github.com/leaflet-extras/leaflet-providers/pull/520), and a similar question came up about semver breaking changes.

If the OL team is OK with making this a semver breaking change, it might make sense to rename the source and add our other styles as well. Otherwise it's technically possible to patch the existing provider in a way that will work (our domain auth doesn't need an API key or any other config from the OL side). Let me know your thoughts on how to proceed and I'd be happy to contribute.

**Comment by tschaub** [comment]
Thanks for reaching out, @ianthetechie.  We have some other breaking changes queued up, so I think it would be ok to go with a renamed source.  Curious to hear if others have thoughts (@openlayers/core).

**Comment by ianthetechie** [comment]
I know this issue is closed, but just wanted to check on the status of the OL 8.0 release. We originally planned to start serving a certain proportion of "warning tiles" letting users on the old endpoints to upgrade starting in early September, but might need to shift our timeline if the major libraries still don't have a clear migration path.

**Comment by ahocevar** [comment]
We can definitely publish v8.0.0 by September 1st. This means @openlayers/core have 1 week to create pull request for removal of deprecated things etc.

**Comment by ianthetechie** [comment]
Cool; thanks. I'll keep an eye on progress both here and in other libs, and both we and Stamen will do some more comms to make sure as wide an audience as possible has a chance to do a disruption-free migration.
