### ISSUE TITLE
ImageArcGISRest Default Ratio Bug: Layer-Map Mismatch in OpenLayers 7.4

### ISSUE THREAD

**Issue by sunyuely** [openlayers/openlayers#14990]
In OpenLayers version 7.4, an issue has been discovered related to the ImageArcGISRest source. The problem lies with the default value of the ratio parameter in ImageArcGISRest, which is set to 1.5. When the computer's zoom or scaling ratio is not 100% (e.g., 150%), the following issues may occur:

Layer-Map Mismatch: Loading ArcGIS MapServer layers with a ratio value other than 1 or 1.5 (e.g., 2) can result in a mismatch between the layer and the map. This can cause misalignment or incorrect rendering of the layer.

Layer-Map Mismatch after Map Rotation: Even when the ratio is set to 1.5 or any other value other than 1, a layer-map mismatch issue can occur after map rotation. The rotated layer may not align correctly with the rotated map.

Currently, the workaround solution is to forcibly set the ratio to 1 to address these issues.

**Comment by mike-000** [comment]
Is the problem similar to #14718 ?

**Comment by sunyuely** [comment]
The problem is not the same as #14718. You can visit this webpage https://sunyuely.github.io/ol7.html. When you perform a zoom operation, you can see that the content of the ArcGIS MapServer is not in the correct position.

**Comment by ahocevar** [comment]
This issue can also be reproduced with the https://openlayers.org/en/latest/examples/arcgis-image.html example. Changing the ration to `2` will show the problem.

**Comment by ahocevar** [comment]
It turns out that this is not a problem of OpenLayers, but of the used server. Looking at the request produced by the example in https://sunyuely.github.io/ol7.html:

* With a ratio of 1, the request URL is https://sampleserver6.arcgisonline.com/arcgis/rest/services/PoolPermits/MapServer/export?F=image&FORMAT=PNG32&TRANSPARENT=true&SIZE=2616%2C1516&BBOX=-13080427.29732658%2C4012702.6303838133%2C-13067929.843201954%2C4019945.0388138336&BBOXSR=3857&IMAGESR=3857&DPI=180. So the expected size of the response image, according to `SIZE=2616,1516`, would be 2616 by 1516 pixels, which is the actual size of the image.
* With a ratio of 2, the request URL is https://sampleserver6.arcgisonline.com/arcgis/rest/services/PoolPermits/MapServer/export?F=image&FORMAT=PNG32&TRANSPARENT=true&SIZE=5232%2C3032&BBOX=-13086676.024388893%2C4009081.426168803%2C-13061681.116139641%2C4023566.243028844&BBOXSR=3857&IMAGESR=3857&DPI=180. So the expected size of the response image, according to `SIZE=5232,3032`, would be 5232 by 3032 pixels. But the returned image is only 4096 by 2373 pixels.

So the issue here is that we don't get from the server what we expect.

**Comment by mike-000** [comment]
@ahocevar That limit is documented but there is a similar undocumented issue if `params: {'FORMAT': 'SVG'},` is specified.  Even on a small map with `ratio: 1,` the returned image can be larger than the requested size expected by the renderer.  You might want to investigate that as part of #14945 as SVG format for ArcGIS would be expected to work as well as it does with WMS.

**Comment by sunyuely** [comment]
@ahocevar I apologize for not noticing that earlier. You are correct that the ArcGIS MapServer service properties include maxImageHeight and maxImageWidth, which have a default size of 4096. It is easy to exceed the limit of 4096 by 4096 when the aspect ratio of the map goes beyond a certain threshold.Perhaps we can directly use the maxImageHeight and maxImageWidth properties of the MapServer to limit the parameters of the requested image.

**Comment by mike-000** [comment]
@sunyuely Any fix for the SVG format issue above should also fix your issue https://codesandbox.io/s/arcgis-image-forked-9jfzx9?file=/main.js (change `if (false)` to `if (true)` to apply a patch - a permanent fix would need to be compatible with changes in #14945).   Basically if the renderer cannot rely on the returned image (either an oversize PNG request, or any SVG request) being the expected resolution it must determine the true resolution from the requested extent and the size of the image which was received.

**Comment by sunyuely** [comment]
Yes, this indeed resolved my issue. Thank you very much for your help, @mike-000  and @ahocevar !

**Comment by ahocevar** [comment]
@mike-000 It looks like for SVG, the server ignores the DPI setting we provide, and uses the default.

**Comment by ahocevar** [comment]
#14945 will make the ArcGISRest images work, even if the returned size does not match the requested size.

**Comment by mike-000** [comment]
> @mike-000 It looks like for SVG, the server ignores the DPI setting we provide, and uses the default.

Yes, the SVG is sized in pt, so browser will set an image size in px based on the default.
