### ISSUE TITLE
Canvas gradient example no longer works

### ISSUE THREAD

**Issue by M393** [openlayers/openlayers#15085]
**Describe the bug**
CanvasGradient cannot be used in style object.

**To Reproduce**
1. Go to https://openlayers.org/en/latest/examples/canvas-gradient-pattern.html
2. See empty map

**Expected behavior**
The map should render without error.

**Comment by ragolodc** [comment]
Hello, I would like to exchange a suggestion. Maybe it helps. According to the documentation, the  fill-color  property is of type string, while the  gradient  variable represents an object of the  CanvasGradient  class. I could recommend using the previous code: 
   style: new Style({ 
    fill: new Fill({color: gradient}), 
    stroke: new Stroke({ 
      color: '#333', 
      width: 1, 
    }), 
  }),  
At least until the bug is resolved. 
Best regards.

**Comment by tschaub** [comment]
Thanks for the report, @M393.  And thanks for fixing the example in #15086, @ragolodc.

It was an oversight to not update this example to to use the `Fill` constructor, and the breaking change to flat styles should have been documented as part of the 8.0 release.

Going forward, we are working on a styling solution that is not restricted to the Canvas renderer (i.e. one that also works with WebGL).  Using a `CanvasGradient` is not going to be a general solution for rendering gradients.  But for now, the `Fill` constructor can continue to be used.
