### ISSUE TITLE
The style icon use canvas is correct in 7 but incorrect in 8

### ISSUE THREAD

**Issue by menghany** [openlayers/openlayers#15252]
**Describe the bug**
https://codesandbox.io/embed/animated-gif-forked-qwwy7c?fontsize=14&hidenavigation=1&theme=dark
version:8.1.0
![image](https://github.com/openlayers/openlayers/assets/13767186/28678293-0fa9-4b23-a096-867faf2e756c)
version:7.5.2
![image](https://github.com/openlayers/openlayers/assets/13767186/e0f5b27a-4d1d-4f4f-a0a5-320c2b15eeef)

**To Reproduce**
change ol version to 7.5.2 is correct

**Comment by ahocevar** [comment]
The `imgSize` property of ol/style/Icon has been removed in v8, so it is now important to provide a properly sized canvas. 

So instead of specifying `imgSize: [150, 150]`, you now have to do
```js
canvas.width = 150;
canvas.height = 150;
```

See https://codesandbox.io/embed/animated-gif-forked-qwwy7c?fontsize=14&hidenavigation=1&theme=dark for an updated codesandbox.

**Comment by menghany** [comment]
thx!
