### ISSUE TITLE
Keep showing WebGl tiles when the source changes

### ISSUE THREAD

**Issue by marousekJakub** [openlayers/openlayers#15310]
We use the library to show raster tiles with weather-related data in the foreground, with a background consisting of OpenStreetMap tiles. The user can select tiles for different timestamps. Switching the timestamp switches the URL via the method TileImage.setUrl.

The problem is that when using setUrl, the weather-related tiles disappear immediately and only the OSM background is shown before the new tiles are downloaded. This is contrary to an older OpenLayers version, where old WebGl tiles were shown even after running setUrl, before being replaced by the new tiles.

I am not completely sure whether this can be considered a bug, because the behavior is not specified in the documentation. However, it complicates things when upgrading from version 6.9.0 to 8.1.0.

**Comment by marousekJakub** [comment]
@ahocevar Would you have an idea on how to solve this?

**Comment by ahocevar** [comment]
@marousekJakub I don't know about the WebGL renderer, but for `ol/layer/Tile` combined with `ol/source/Tile`, `setUrl()` will cause the exact behaviour you desire. See https://openlayers.org/en/latest/examples/wms-time.html.

**Comment by mike-000** [comment]
If you simply change `ol/layer/Tile.js` to `ol/layerWebGLTile.js` in the example it does flicker for a while when playing - until it cycles back to the start of the time sequence, after which tiles for each time will have been cached.  To avoid the user seeing that you could add an extra step to preload all the tiles before making the layer visible https://codesandbox.io/s/wms-time-forked-fqhmch?file=/main.js (use `opacity: 0` instead of `visible: false` so tiles will load).

**Comment by marousekJakub** [comment]
@ahocevar Thanks a lot, it kicked me in the right direction. We replaced the WebGL renderer with the basic one (`ol/layer/Tile` and  `ol/source/Tile`) and now it works the way we want.
