### ISSUE TITLE
view.then is not a function at Map.setView

### ISSUE THREAD

**Issue by grallewellyn** [openlayers/openlayers#15474]
**Describe the bug**
When trying to set the view for a map, I get
```
MapWrapperOpenlayers.createMap: TypeError: view.then is not a function
    at Map.setView
```
If I pass in the view into the map constructor, then I get
```
MapWrapperOpenlayers.createMap: TypeError: options.view.then is not a function
    at new Map
```

**To Reproduce**
Create an open layers map like 
```
import Ol_Map from "ol/map";
import Ol_View from "ol/view";

let vectorLayer = new Ol_Layer_Vector({
                source: new Ol_Source_Vector({ wrapX: true }),
                style: this.defaultGeometryStyle,
                extent: [-540, -90, 540, 90]
            });

new Ol_Map({
     target: container,
     layers: [vectorLayer],
     controls: [],
     view: new Ol_View({
                  maxZoom: 16
                  minZoom: 2,
                  projection: getProjection("EPSG:4326"),
                  maxResolution: 0.5625
              }),
      interactions: defaultInteractions({
                  altShiftDragRotate: false,
                  pinchRotate: false,
                  shiftDragZoom: false,
                  keyboard: false
              })
          });
```
Or set the view after creating the map like 
```
temp.setView(new Ol_View({
                maxZoom: 16
                minZoom: 2,
                projection: getProjection("EPSG:4326"),
                maxResolution: 0.5625
            }));
```

In my code, this prints true, 
```
let newView = new Ol_View({
                maxZoom: 16,
                minZoom: 2,
                projection: getProjection("EPSG:4326"),
                maxResolution: 0.5625
           });
console.log(newView instanceof Ol_View);
```

The problem is that for some reason ol isn't registering that my view is a proper View instance and is skipping the first if statement in ol/Map.js
```
  setView(view) {
    if (!view || view instanceof View) {
      this.set(MapProperty.VIEW, view);
      return;
    }
    this.set(MapProperty.VIEW, new View());

    const map = this;
    view.then(function (viewOptions) {
      map.setView(new View(viewOptions));
    });
  }
```
I also tried making the view passed into setView a promise so that it has a .then function, but that didn't work. I also tried adding `center: [0,0]` and `zoom: 2` fields to the Ol_View constructor in case those were necessary and this didn't work 
I am using openlayers v7.0.0 and tried v6.13.0. The code above only works with openlayers 4.6.4, but I would like to upgrade openlayers. 

**Expected behavior**
A map is successfully created

**Comment by tschaub** [comment]
This could be caused by there being two versions of the the `ol/View.js` module in your application - one used where you create the view and a different one imported by the `ol/Map.js` module.

Are you using a bundler?

Are there any dependencies in your application that also depend on OpenLayers?

If you are using `npm` to manage dependencies, what is the output from `npm ls ol`?

**Comment by grallewellyn** [comment]
The import in the code is `import Ol_View from "ol/view";` and the import in `ol/Map.js` is `import View from './View.js';`. How could there be 2 versions of `ol/View.js`? 

We are using Webpack 

No other dependencies in the application depend on OpenLayers 

`npm ls ol` gives 
```
cmc-core@2.0.0 /Users/.../aqacf-mapper
└── ol@7.0.0
```

**Comment by tschaub** [comment]
@grallewellyn - Maybe webpack isn't deduplicating things due to the difference in case that you are using.  The module and filename is uppercase `View.js`.  So the most explicit import would be `import View from 'ol/View.js';` (uppercase `V`, `.js` extension).  Everything else (accepting lowercase, adding `.js` extension) is non-standard and unspecified behavior from the bundler - so that could be causing problems.
