### ISSUE TITLE
ScaleLine Control reports incorrect distance when not on equator

### ISSUE THREAD

**Issue by weskamm** [openlayers/openlayers#15542]
The `ol/control/ScaleLine` does not report correct measurements when not used on the equator.
The differences in measurement become huge, a feature with 10000 meters length is reported to have ~6000m when drawn near england.
I prepared a jsfiddle  here:

https://jsfiddle.net/43ev0nfc/12

There are two features on the map, both are rectangles with 10km side length. One feature is at the equator, one between france and england. The scaleline reports correct values for the feature at equator:

![image](https://github.com/openlayers/openlayers/assets/1381363/184a8d90-4c7c-45e9-ae4e-2f929e9a2c4b)

But the feature near england looks like this:

![image](https://github.com/openlayers/openlayers/assets/1381363/4b58c8d3-bb0f-4af5-a2b1-27326841b655)

The documentation states that the measurement is not exact, but those differences are really huge.
I identified the `setGetPointResolution` function to be the cause / or solution to this problem.

In the fiddle you can uncomment the last line to override that function to just return the input value:

`map.getView().getProjection().setGetPointResolution(r => r);`

When using this override, the measurement becomes correct for the "england" polygon:

![image](https://github.com/openlayers/openlayers/assets/1381363/9e3305ef-3021-485c-a66c-bf9e25ca6e6a)

The measurement at equator keeps correct with this override.
So to me it seems we always have to override the default function to just return the same value that has been given as argument.

The issue behaves the same for different projections, i tried 4326, 3857, 25832, 31467.
Everything works as expected with the override from above.

Seems like a bug to me?

**Comment by ahocevar** [comment]
I'm surprised to read you're having trouble with EPSG:4326 and EPSG:3857, because these should work fine out of the box, without any modifications to the Projection instance. Do you have code examples for both that show the problem?

For other projections, you need to set up the projections's units correctly, and for non-cartesian projections also the `getPointResolution` function.

**Comment by weskamm** [comment]
I thought the same :-) In the fiddly from above there is a projection switcher at the bottm (which seem to work only if you use it at least twice).

I thought that at least for the default projections, users of the scaleline would not need to setup custom complicated functions for the scalebar to work correctly?

**Comment by M393** [comment]
The two polygons are bother 10000 * 10000 units in EPSG:3857, but in vertical direction these are only meters at the equator. At England latitude its off by about `cos(50°) ~ 0.643`. The point resolution used by ScaleLine is the average of the lon and lat resolutions.
https://github.com/openlayers/openlayers/blob/0d1b442b425c6cd3c91f9f061f6ea3f5cbb469aa/src/ol/proj.js#L216-L240

**Comment by ahocevar** [comment]
@weskamm The problem is not the scale line, it's your polygons. 10000 distance units in EPSG:3857 (or any mercator projection) in longitudinal direction are nowhere on Earth 10 km except at the equator. To help you understand, look at the circles in https://openlayers.org/en/latest/examples/tissot.html - especially the one around Great Britain. All the circles in that example have the same diameter.

**Comment by weskamm** [comment]
I would have expected that openlayers draws a polygon with 1km side length to actually have a length of ~1km when measured by the scalebar, as it should be able to use the map projection for projection maths. Of course features get distorted and may appear bigger or smaller, but the scalebar should take the distortions into account. Besides, the same issue happens with non global projections like EPSG:25832 or EPSG:31467

**Comment by ahocevar** [comment]
@weskamm:

> I would have expected that openlayers draws a polygon with 1km side length to actually have a length of ~1km when measured by the scalebar

Drawing a "rectangle" with a "side length of 1km" on a sphere (assuming you're happy with this abstraction of the surface of the planet) is something you cannot really do, except for selected latitudes or longitudes, depending on the projection. In general, projections can either properly represent angles (e.g. Mercator) or areas (e.g. Mollweide), but not distances. To help understand, let's look at a soccer stadium rather than a hypothetical rectangle:

<img width="1058" alt="Untitled" src="https://github.com/openlayers/openlayers/assets/211514/10fe3391-6248-4e76-b2c0-9a029abb301f">
(https://codesandbox.io/p/sandbox/link-forked-rfnthf?file=%2Fmain.js)

As you can see in the log, there is a significant difference in measuring the cartesian distance (which is what you do when you say you're drawing a rectangle with a specific side length), and the spherical distance, which is approximately what you get when you measure the stadium at the ground, when you're there.

The scaleline shows the spherical distance. It does take these distortions into account. It uses the center of the map viewport as reference for its calculation. So when you're looking at the map at a low zoom level, the calculation will not be suitable for for a feature close to the scale line.

I hope it is clearer now.

**Comment by ahocevar** [comment]
@weskamm 

> So to conclude, does the "override" i mentioned change the scalebar to use cartesian calculations?

Exactly.

> Maybe its just a matter of detailed explanation in the docs or a specific property like geodesic, which was available on some controls in the past in openlayers if i remember correctly to control the behaviour.

Yes, OpenLayers 2 had a `geodesic` option. But the history of that was the opposite: it started with (incorrect) cartesian measurements, and the `geodesic` option to fix that did not default to `true` for backwards compatibility. Regarding docs, we are always glad to receive pull requests with improvements. The topic of map projections is quite complex though, so caution has to be used, because providing a deep-dive into that might be more confusing than helpful for the average user who only uses the defaults (EPSG:3857).

**Comment by weskamm** [comment]
I added a short notice to the docs on how to use cartesian measurements

**Comment by weskamm** [comment]
Just wanted to say sorry for the confusion i had here. Of course, using coordinates instead of meters is a huge difference and explains the behaviour.
Just a little more explanation how i got on the wrong track:
My issue originated from creating a circle with a given radius. For circles, the documentation states the radius used for creation is in units of the projection, which in my case, was meters. So i created a circle with a radius of 10 kilometers and used the scaleline to measure its diameter. Then i realized that the numbers did not line up.
For making this behaviour better visible / measureable, i created a polygon and falsely had the idea that i could simply use "units of the projection". Well, using coordinates is a different thing of course and thanks again @ahocevar for the detailed explanations.
So this is a heads up if anyone else is getting it wrong like me, that one should do the math before creating the geometry.
