### ISSUE TITLE
tabindex on map leading to non-working interactions when map el in shadowRoot

### ISSUE THREAD

**Issue by chrismayer** [openlayers/openlayers#16076]
**Describe the bug**
I have the following situation:

- OL map's target element is inside of a `shadowRoot` of a custom DOM component
-  `tabindex="0"` is set on the map's target element in order to gain accessibility according to the corresponding[ official OL example](https://openlayers.org/en/latest/examples/accessible.html)
- Now the map interactions, like pan and zoom stop to work

I did some investigations and for my understanding the following happens:

-  `defaultInteractions` on the map have `onFocusOnly: true` as default
- [focusWithTabindex](https://github.com/openlayers/openlayers/blob/main/src/ol/events/condition.js#L97C14-L97C31) detects that there is a tabindex attribute on map's target and calls the `focus` method
- [focus](https://github.com/openlayers/openlayers/blob/main/src/ol/events/condition.js#L85) method tries to detect if the map target has the focus, but the current approach does not detect map focus correctly if in inside `shadowRoot`, since the `contains` functions used there does not reflect elements as `shadowRoot` children.

A possible solution could be using an extended `contains` functions, which iterates down to `shadowRoot` elements or there might be another approach to detect focus at all.

**To Reproduce**
1. Create an OL map and set its target to an element inside a [shadowRoot](https://developer.mozilla.org/en-US/docs/Web/API/ShadowRoot) 
2. Ensure map target has an `tabindex="0"` attribute
3. Check map and see that map interactions do not work anymore.

**Expected behavior**
The  map interactions should work if the map has the focus, so the map can be panned and zoomed with mouse and keyboard.

**Comment by ahocevar** [comment]
Thanks for the bug report. Maybe when using shadow DOM, a better approach would be to handle the focus on the custom element instead of the map's target. So looking at the https://openlayers.org/en/latest/examples/es2015-custom-element.html example, that would be
```html
    <ol-map tabindex="0" id="map" class="map"></ol-map>
```
If I understand you correctly, you tried to set the `tabindex` attribute on the map's target element *inside* the shadow DOM. That would only make sense if all focusing / tab switching takes place inside the shadow DOM. Is that what you're aiming for? That would be quite unusual, as opposed to having native and custom elements in the `document`, and one of these native or custom elements has the focus.

**Comment by chrismayer** [comment]
Thanks for your feedback @ahocevar. You are right, the `tabindex` should be on the outside component, so one element in the "main" document has the active element. But the keyboard interactions like `KeyboardZoom` and `KeyboardPan` don't seem to work without a `tabindex` attribute on the map's target element. Do I miss something?

**Comment by chrismayer** [comment]
@ahocevar thanks for code and yes, I can take over and start today, but may take some time to finish fully fledged due to vacations...
