### ISSUE TITLE
ESM implementation does not work

### ISSUE THREAD

**Issue by quinn** [openlayers/openlayers#16142]
I am cross-posting this issue here because the original issue is over a year old:

https://github.com/openlayers/ol-skypack/issues/1

**Comment by jahow** [comment]
It looks like the named exports of geotiff.js are lost in the process, see:
https://cdn.skypack.dev/-/geotiff@v2.1.3-XiUuyJgTAAAacz3e80uR/dist=es2019,mode=imports/optimized/geotiff.js

There is only one default export.

You can probably work around this error as long as you don't need the GeoTIFF source, by simply not importing it (e.g. import ol/source/OSM instead of ol/source).
