### ISSUE TITLE
Drag and Drop GeoTiff

### ISSUE THREAD

**Issue by WillieMaddox** [openlayers/openlayers#16317]
Is there a way to drag and drop geotiffs into OL?

I was thinking I could just extend the DragAndDrop interaction to handle geotiffs but maybe there is a better way?

**Comment by mike-000** [comment]
The current interaction handles vector data, I do not think it would be appropriate to add GeoTIFF support to that.  The code is needed is simple enough and a new example may be sufficient, here is one from StackExchange https://jsfiddle.net/qdL5uw8f/  Only small files could be handled due to the memory requirements.  For that reason GeoTIFF viewers such as https://geotiffjs.github.io/cog-explorer/ or https://app.geotiff.io/load typically allow the user to enter a URL as well as load/drop a file.

**Comment by WillieMaddox** [comment]
This answer is sufficient for my needs.
