### ISSUE TITLE
Add removeFeatures method to ol.source.Vector

### ISSUE THREAD

**Issue by atsolberg** [openlayers/openlayers#2011]
Removing features one by one takes a significant amount of time when more than ~15000 features are removed. Use case discussed here: https://groups.google.com/forum/#!topic/ol3-dev/LjHVWy3AHO0

Examples: http://codepen.io/atsolberg/pen/Dvnzw, http://jsfiddle.net/atsolberg/NC4vh/

**Comment by adrelino** [comment]
+1! For people migrating from ol2 to ol3 just like me, it would be nice to add a removeFeatures method to the ol3 API, to make it more compatible with the ol2 API, which had a [removeFeatures method on Vector Layer](http://dev.openlayers.org/releases/OpenLayers-2.13.1/doc/apidocs/files/OpenLayers/Layer/Vector-js.html#OpenLayers.Layer.Vector.removeFeatures).

- as a start maybe just a dumb slow one that iteratively calls removeFeature
- or as discussed in #4997 by setting spatialndex to false and using ol.Collection (but only internally, I don't want to change all my js Arrays in which I store features to ol.Collection in my app!)

**Comment by ahocevar** [comment]
Bulk insert and remove should be supported now by rbush.

**Comment by tsauerwein** [comment]
> Bulk insert and remove should be supported now by rbush.

Bulk insertion, yes (we are already using it in ol3). But bulk removal? I think it is not supported.

**Comment by ahocevar** [comment]
You are right @tsauerwein. An alternative would be to `clear()` the r-tree and bulk-insert the remaining features.

**Comment by tsauerwein** [comment]
> An alternative would be to clear() the r-tree and bulk-insert the remaining features.

... depending on how many features are removed and how many still remain in the source.

**Comment by aalbericio** [comment]
Regarding this "batched" operation, is there any way to freeze (do not render on map any update) the Collection, apply any update (add/remove/update) to the Collection and then "reactivate" the Collection to re-render updates?

**Comment by ahocevar** [comment]
@aalbericio Collection? Is your source configured with an `ol.Collection` of features? If so, then consider using an array of features instead. Will be much, much faster.

**Comment by aalbericio** [comment]
@ahocevar I'm using an Array of ol.Feature. But regarding my original concern, If I ever mutate this Array by using "removeFeature, addFeature, etc" I guess there's an instant visual update and map rendering. My question is: since there is not a "removeFeatures" method, if I loop and removeFeature like 200 times, will the Map re-render 200 times?

Is there any way to freeze rendering, then loop and mutate the Array and then tell the Map to re-render with all updates already pushed into the Array? I'm just trying to avoid 199 renders.

I'm not sure if that makes sense or I'm misunderstanding something from the docs, sorry.

**Comment by ahocevar** [comment]
Rendering in OpenLayers works based on render frames. So when you remove 200 features within say 16 milliseconds, the map will only redraw once. If you remove features often, you may want to configure your vector source with `spatialIndex: false`, because removing features from the spatial index is quite expensive.

**Comment by aalbericio** [comment]
@ahocevar Aha, that's really cool then. So if I manage to update 500 features in, let's say, 48ms, then the map will only redraw 3 times aprox, right?

Some of my layers are elegible to handle thousands of features so I will have to test wether to use spatialIndex or not in a per-layer strategy.

Thanks for your help!

**Comment by ahocevar** [comment]
> So if I manage to update 500 features in, let's say, 48ms, then the map will only redraw 3 times aprox, right?

Right.

**Comment by kramcore** [comment]
@ahocevar Is there another way to remove selected features in bulk without using `clear()` as that will clear all the features from the vector.source? and using `removeFeature()` is very slow when removing a lot of features from the source.

**Comment by ahocevar** [comment]
@kramcore When you are removing and adding features a lot, with a relatively small total of features, I'd suggest constructing the source with `spatialIndex: false`.
