### ISSUE TITLE
Draw and modify interaction interoperability

### ISSUE THREAD

**Issue by tsauerwein** [openlayers/openlayers#2228]
The current ["Draw and modify feature" example](http://ol3js.org/en/master/examples/draw-and-modify-features.html) has (at least) two little issues:

If the geometry point of the draw interaction is set to points, and if you get close to an existing geometry, you will see two points: The point of the draw interaction and the snapped sketching point of the modify interaction. To only show one point, the idea came up of using something like a [`dontHandleMapBrowserEvent`](https://github.com/openlayers/ol3/pull/2114#issuecomment-45346620) function, so that the modify interaction will stop the event and the draw interaction can remove its point.

But this only partly solves the problem. The expected behavior would be like this:
I am close to a line, the point is snapped to the line and I only see one point. Now, I start dragging the point and the existing line is modified. But then also, if I see the snapped point on the line, and I click, I would expect that the new point is created at the position of the snapped point. But for this, the draw interaction would have to know about the snapped point of the modify interaction.

The other issue is when drawing a line or polygon. Let's say I started a line, get close to an existing geometry and see the snapped point. Now, when I start dragging, I can modify the existing geometry, and after that continue drawing the line. Modifying should be disabled while drawing a line or polygon.

To realize the described behavior, modify and draw must be tightly coupled. So maybe it would make sense to combine the two interactions into one. And this interaction would support snapping to existing geometries when drawing new points.

**Comment by probins** [comment]
I've found several other issues with this, but have got round them by making sure that the draw and modify interactions are not active at the same time - the user is using either one or the other. Are there situations where you need to use both at once?

**Comment by tsauerwein** [comment]
> I've found several other issues with this, but have got round them by making sure that the draw and modify interactions are not active at the same time - the user is using either one or the other. 

That's what we usually do as well. In this ticket I just wanted to document the issues that exist with the modify-draw example.

**Comment by probins** [comment]
The main issue I found with this example is deleting a vertex on a linestring. The source mentions that the modify interaction is configured with shift-click to delete, but the problem is that the draw interaction thinks a click means draw a new line, so the example deletes the vertex correctly, but also starts a new line. These issues go away if the example is changed to have modify as a selection in the dropdown: you can either draw or modify, not both at the same time. ISTM this is the common use case. If there are situations where you need both active at the same time, then you need to make sure the events are differentiated so that each interaction knows which events it needs to handle. This should be documented somewhere (not sure where).
