### ISSUE TITLE
map.getPixelFromCoordinate Only works on some screens

### ISSUE THREAD

**Issue by 1Map** [openlayers/openlayers#2904]
map.getPixelFromCoordinate(myCoordinate) works fine on my screen, but the moment it is run on a different monitor it has a wrong offset.  The problem is:

On my screen the ol.has.DEVICE_PIXEL_RATIO = 1, but on the screen that has a wrong offset, the ol.has.DEVICE_PIXEL_RATIO !== 1 (Something like 1.1xxxx), so whenever I use map.getPixelFromCoordinate(myCoordinate), I have to use it like:

myPixel = map.getPixelFromCoordinate(myCoordinate) \* ol.has.DEVICE_PIXEL_RATIO

which I believe should be part of the getPixelFromCoordinate() function.

The specs that works correctly (ol.has.DEVICE_PIXEL_RATIO == 1) are as follows:

OS: Windows 7 - 64bit
Browser: Google Chrome 38.0.2125.111 m
Monitor: Samsung SyncMaster P2770 (27")
Screen Resolution: 1920x1080

The specs that does not work correctly (ol.has.DEVICE_PIXEL_RATIO  !== 1) are as follows:

OS: Windows XP - 32bit
Browser: Google Chrome 38.0.2125.111 m
Monitor: LG E2341V (23")
Screen Resolution: 1920x1080

Please let me know the moment you fixed this.

**Comment by icholy** [comment]
Has there been any progress on this?

**Comment by Benjaki2** [comment]
+1

**Comment by sookoll** [comment]
Any update on this? I run into same issu, plus zooming map in and out lost its center and in one case, wms start to request tiles with 128px or 64px instead of 256px (with `<body style="zoom: 1.6">` for example).

**Comment by christopheblin** [comment]
+1

This is very annoying to explain to end users as, most of the time, they do not understand "browser zoom" / "map zoom" clearly and the ctrl+0 is not easy to explain either ...

**Comment by ejschoen** [comment]
I don't know if this is related, but it's very similar.  Using OL 4.6.5, on Chrome 65 on a Mac (but my users have reported same on Windows 10).  Initial browser zoom is 100%.  Initial device pixel ratio as reported by ol.has is .899999...  When my map initially appears, it is fuzzy and stretched horizontally:

![screen shot 2018-04-10 at 8 47 57 am](https://user-images.githubusercontent.com/10605666/38560884-4c6118ea-3c9c-11e8-9e8b-4793dc013793.png)

The canvas actual size as seen in Google's debugger is 627x473 px, even though its container div (div.ol-viewport) is 845.5x400 px.  Zooming via Ctrl + to 110% resolves stretch and fuzziness:

![screen shot 2018-04-10 at 8 48 24 am](https://user-images.githubusercontent.com/10605666/38560925-61d4d7fc-3c9c-11e8-94d2-5233ba04e4d2.png)

The canvas is now 845x400 px, which makes more sense.  Zooming back out to 100% via Ctrl - looks good:

![screen shot 2018-04-10 at 8 48 34 am](https://user-images.githubusercontent.com/10605666/38560963-7635e128-3c9c-11e8-833a-8750b9bfbe31.png)

On the other hand, when the browser starts at 90% zoom, the initial fuzziness and stretch is the same,  the initial canvas renderer size is 627x473 px, but zooming to 100% doesn't fix the issue.  However, zooming out, back to 90% , does resolve the issue.  I checked, and ol.has.DEVICE_PIXEL_RATIO remains at .899999... when I do this.

For what it's worth, we don't see this problem with Safari.

**Comment by ejschoen** [comment]
And for what it's worth, I may have the resolved the issue in my case.  It turns out the `div` that is the `target` of the map in the `new ol.Map({ target: ... })` parameters had an initial CSS styling width (we're using bootstrap and the div had class `col-sm-9`, not sure why...), causing its declared size to be different than its ultimate size.  Some code somewhere--I don't think it's mine because I can see the smaller size in the initial `ol.PluggableMap.setSize()` call--changes the target's height and width to 100%, and doing that seems to be related to the distortion and fuzziness. Removing the Bootstrap responsive layout classes resolved the issue for me.

**Comment by 1Map** [comment]
@ejschoen Your problem is not related to this thread.

Try calling https://openlayers.org/en/latest/apidoc/ol.Map.html#updateSize after you set your map or after the div changes size.

**Comment by ejschoen** [comment]
Thanks, but I had read that hint previously and I did have code that called `updateSize`, but it made no difference.  Ultimately, I think what was going on was that the map's container was in the process of resizing (a Bootstrap animation), and this was affecting the canvas.  Since [resize events](https://developer.mozilla.org/en-US/docs/Web/Events/resize) are now only sent to handlers registered on the window, I couldn't figure out how to catch this case.  Ultimately, I ended up using a jQuery promise completion function after a call to [$(container).show()](http://api.jquery.com/show/) to trigger creating the map canvas, so that I can be sure the container elements are at their ultimate size before making the map.

**Comment by 1Map** [comment]
@ejschoen Put it on a delay and fire updateSize after your div was rendered.  Problem is that updateSize is getting fired too earl (while the div is still painting).

Something like (**not tested**):

```
jQuery(document).ready(function () {
      setTimeout(updatemap, 200);
      function updatemap() {
            mymap.map.updateSize();
      }
});
```

**Comment by ejschoen** [comment]
Correct.  That's basically what I did by using jQuery.show's after-animation completion method.  Thanks for the help.
