### ISSUE TITLE
Very poor performance when zooming over large resolution difference

### ISSUE THREAD

**Issue by deadpassive** [openlayers/openlayers#3330]
I've got a map with the resolutions [1000, 500, 200, 0.125]. When zooming from 200 to 0.125 the page freezes.

Based on my initial investigations, the problem seems to be in ol.renderer.canvas.TileLayer.prepareFrame where there is the following for-loop

```
for (x = tileRange.minX; x <= tileRange.maxX; ++x) {
    for (y = tileRange.minY; y <= tileRange.maxY; ++y) {

        tile = tileSource.getTile(z, x, y, pixelRatio, projection);
        tileState = tile.getState();
        if (tileState == ol.TileState.LOADED ||
            tileState == ol.TileState.EMPTY ||
            (tileState == ol.TileState.ERROR && !useInterimTilesOnError)) {
                tilesToDrawByZ[z][ol.tilecoord.toString(tile.tileCoord)] = tile;
                continue;
        }

        fullyLoaded = tileGrid.forEachTileCoordParentTileRange(
            tile.tileCoord, findLoadedTiles, null, tmpTileRange, tmpExtent);
        if (!fullyLoaded) {
            // FIXME we do not need to clear the tile if it is fully covered by its
            //       children
            tilesToClear.push(tile);
            childTileRange = tileGrid.getTileCoordChildTileRange(
                tile.tileCoord, tmpTileRange, tmpExtent);
            if (!goog.isNull(childTileRange)) {
                findLoadedTiles(z + 1, childTileRange);
            }
        }
    }
}
```

In my case this was looping over these ranges and taking a VERY long time while continuing to eat up memory (into the gigabytes).

minX = 10290
maxX = 14753
minY = 7557
maxY = 10547

**Comment by deadpassive** [comment]
I've created a jsfiddle reproducing the issue.

http://jsfiddle.net/vzytmqL5/1/

**Comment by elemoine** [comment]
Thanks for the good test case.

I don't know what the problem is right now, but note that the problem goes away if you don't pass a `tileGrid` to the `TileWMS` constructor.

**Comment by elemoine** [comment]
@deadpassive's jsfiddle uses v3.2.0. I just tried with master, which includes the patch attached https://github.com/openlayers/ol3/pull/3246, but I discovered a bug: an [assertion error](https://github.com/openlayers/ol3/blob/master/src/ol/imagetile.js#L167) at tile disposal time. This bug is related to https://github.com/openlayers/ol3/pull/3248, which added the `ol.ImageTile#disposeInternal` function and the call to `unlistenImage_`. With a local patch I can see that #3246 does improve the situation, but there still is a big performance problem. I still need to investigate the problem but it looks like we're creating a lot of unnecessary garbage (`ol.ImageTile` objects probably).

**Comment by tschaub** [comment]
We could improve things by calculating a tile coord instead of creating a tile (and the underlying image) and then checking the cache to see if the tile has been created/loaded.  It would be good to rework things so we're not creating and caching tiles (and images) when we only need a tile coordinate.  I think it could make sense to only cache tiles when we load them, but this may be a bigger change.

**Comment by elemoine** [comment]
> We could improve things by calculating a tile coord instead of creating a tile (and the underlying image) and then checking the cache to see if the tile has been created/loaded. It would be good to rework things so we're not creating and caching tiles (and images) when we only need a tile coordinate. I think it could make sense to only cache tiles when we load them, but this may be a bigger change.

Yep, but in that case the problem is also related to « big » tile range, and the associated « big » loops.

@deadpassive, any reason for passing a specific `tileGrid` to the `TileWMS` constructor?

**Comment by tschaub** [comment]
I'd be interested in comparing the time with and without image creation (no call to getTile).  Clearly the memory issue sout be improved without caching all those unused images.

**Comment by deadpassive** [comment]
@elemoine My map is EPSG:27700 and based loosely on:

https://astuntechnology.github.io/osgis-ol3-leaflet/ol3/01-OSGB-MAP.html

Without the tileGrid the map appears slightly blurry.

**Comment by elemoine** [comment]
The problem is related to the tile resolution we use for a given `viewState` resolution. The renderer may indeed choose a tile resolution that implies a very big tile range. This is because the `tileGrid.getZForResolution` function may return a resolution that is actually lower that the `viewState` resolution. This patch fixes the performance problem:

```diff
diff --git a/src/ol/tilegrid/tilegrid.js b/src/ol/tilegrid/tilegrid.js
index e24e8e0..ace9d27 100644
--- a/src/ol/tilegrid/tilegrid.js
+++ b/src/ol/tilegrid/tilegrid.js
@@ -394,7 +394,7 @@ ol.tilegrid.TileGrid.prototype.getTileSize = function(z) {
  * @return {number} Z.
  */
 ol.tilegrid.TileGrid.prototype.getZForResolution = function(resolution) {
-  return ol.array.linearFindNearest(this.resolutions_, resolution, 0);
+  return ol.array.linearFindNearest(this.resolutions_, resolution, 1);
 };
```

> I'd be interested in comparing the time with and without image creation (no call to getTile). Clearly the memory issue would be improved without caching all those unused images.

We're not talking about interim tiles here, but tiles we plan to load. So I don't quite see how we can avoid calling `getTile` without a major refactoring.

**Comment by elemoine** [comment]
> Without the tileGrid the map appears slightly blurry.

You could try using `[1000, 500, 200, 0.125]` as the view resolutions, and (much) more intermediate resolutions for the `tileGrid`. For example:

```
[1000, 500, 250, 200, 100, 50, 25, 12.5, 6.25, 3.125, 1.5625, 0.78125, 0.390625, 0.1953125, 0.125, 0.09765625]
```

This should prevent the performance issue from happening, while still allowing for sharp images (because the `tileGrid` resolutions include the view resolutions).

**Comment by deadpassive** [comment]
@elemoine Yes that's pretty much what I've done to get around this issue. My application allows users to arbitrarily set the map resolutions and I process the selected resolutions to add in intermediate resolutions. This works fine for my needs.

**Comment by elemoine** [comment]
I've just worked on a patch that defer the creation of the `Image` until the tile is loaded (`tile.load` is called). See https://github.com/openlayers/ol3/compare/master...elemoine:deferimage. I don't know if this patch improves things.

**Comment by elemoine** [comment]
> I've just worked on a patch that defer the creation of the Image until the tile is loaded (tile.load is called). See master...elemoine:deferimage. I don't know if this patch improves things.

It certainly is not going to help @deadpassive's case.

**Comment by spiess-demos** [comment]
This issue still persists in ol@5.3.3. Is there any way to get around it?

**Comment by ahocevar** [comment]
v6.2.0 has been released today, and should improve performance here. Can you please check if that satisfies?

**Comment by spiess-demos** [comment]
@ahocevar Thanks for your quick reply! 

In my test case, jumping from 1:500.000 to 1:2000 (scales) took about 16s with 5.3.3. v6.2.0 slightly improves the situation (11s).

However i spotted another cause for the massive performance lag, that does not relate to openlayers but the integration with Vue, so i'll focus on fixing that first.
