### ISSUE TITLE
WMS layer disappears after PinchZoom (iPad)

### ISSUE THREAD

**Issue by ArlenPoort** [openlayers/openlayers#3512]
Hello,
After zooming in and out several times on an iPad (Air 2, OSx 8.2), the WMS layer of a map disappears. This can be reproduced with <A HREF="http://openlayers.org/en/v3.4.0/examples/wms-image-custom-proj.html">this example</A>.
OpenLayers still sends out requests to my WMS server (MapServer) and it still receives new tiles. But these tiles are not displayed. 
Best regards,
Arlen Poort

**Comment by urshensler** [comment]
Same issue on my iPad 4 (iOS 8.3)

**Comment by richardjr** [comment]
Same issue here. As per @ArlenPoort I can see in the debugger tiles are being requested and no console errors are present but map is white and no tiles rendered. If I toggle another layer into play that layer will work but then white out will happen again why I try to zoom out.

Also I note this always happens when you zoom to your top resolution, it is as though the pinch zoom is allowing the map to try and render past the max resolution. I'll start looking at the code in this area but has anyone found any possible fixes?

**Comment by ArlenPoort** [comment]
It seems that reprojecting the wms layer causes the problems. I use a wms from my own MapServer, and this was reprojected from EPSG28992 to 900913, on top of an OpenStreetmap base layer. After I set MapServer to send the map in 900913, the problem disappeared.
But this will only work if you have control over the wms server.

**Comment by richardjr** [comment]
Interesting, I am serving all our titles from mapserver as EPSG:27700 and the map is running EPSG:27700 but I'll double check we aren't doing any reprojection thanks.

Some looking though the code revealed that the pinch zoom does indeed seem to allow zooming out of the constraints:

```
// scale, bypass the resolution constraint
  map.render();
  ol.interaction.Interaction.zoomWithoutConstraints(
      map, view, resolution * scaleDelta, this.anchor_);
```

So maybe that + projection is causing the issues although I'm not familiar with the ol3 code so I could be talking rubbish ;)

**Comment by richardjr** [comment]
Well in my case this appears to have been an issue in the 'canvas' renderer. I moved to 'dom' for ipad devices and the issue goes away and the map seems a lot more responsive as a result. Some reading around of other bugs suggests that the canvas renderer has some issues on iPad.
