### ISSUE TITLE
Function names shouldn't expose implementation details

### ISSUE THREAD

**Issue by cffk** [openlayers/openlayers#4033]
I am looking into improving the routines used by OpenLayers3 for
measuring distances and areas by using the [JavaScript port of GeographicLib](http://geographiclib.sourceforge.net/scripts/geographiclib.js).
But I'm running into a problem of badly named routines.

Sphere.geodesicArea doesn't measure the area of a polygon whose edges
are geodesics but one whose edges are straight lines on a cylindrical
equal area projection.  Perhaps the name should be changed to 
Sphere.projectedArea?

Sphere.haversineDistance returns the great-circle distance.  However,
why expose the implementation as part of the function name?  It turns
out the the haversine formula is inaccurate for nearly antipodal points
and there's [a much better formula](https://en.wikipedia.org/wiki/Great-circle_navigation#cite_note-2)
that works everywhere.  I recommend deprecating the name,
haversineDistance, and using greatCircleDistance instead.

Ellipsoid.vincenty{Distance,{Initial,Final}Bearing} similarly exposes
implementation details.  The use of Vincenty's name is, in any case,
inappropriate since the basic algorithm Vincenty coded up in his 1975
paper goes back at least to [Helmert, 1880](http://geographiclib.sourceforge.net/geodesic-papers/helmert80-en.html).
I recommend deprecating these names and substituting "geodesic" for
"vincenty".

**Comment by tschaub** [comment]
Another option would be to remove these `ol.Sphere` methods entirely.

We only use `sphere.haversineDistance()` in `projection.getPointResolution_()` - and this could be implemented in a simpler way.  The logic in `sphere.offset()` could be moved to `ol.geom.Polygon.circular()`, which is the only place where it is used.

**Comment by cffk** [comment]
Ah, I see you've purged ellipsoid.js.

If openlayers does need the capability to compute geodesics paths and
areas accurately and quickly, then I believe that using the JavaScript
port of GeographicLib will be your best bet:

* Unlike Vincenty's method (which fails for nearly antipodal points), it
  converges everywhere.

* It's accurate to round-off (for |f| < 1/50)

* Path calculations (several points on the same geodesic) are probably
  about 2-3 times faster than a blind application of direct method.

* The area calculations compute the true ellipsoidal area of geodesic
  polygons.  Polygons are allowed to encircle a pole (so you can
  calculate the area of Antarctica).

For a preview of this package see

* http://geographiclib.sourceforge.net/scripts/geod-calc.html
* http://geographiclib.sourceforge.net/scripts/geod-google.html

**Comment by bill-chadwick** [comment]
I really think that ol3 itself should have a function to return the geodesic length of linestrings in metres for linestrings with coordinates in a specified projection. This is needed for things like the length of a GPX hike/bike route. Accurate area measurements are perhaps a bit more suited to an external to ol3 library. As straight lines on Web Mercator maps are Rhumb Lines (of constant bearing) then perhaps a method for returning Rhumb length should be considered to.

I would still like to see a bit more detail in the docs for the geometry getArea, getLength and setRadius methods etc so that non GIS expert users don't assume that distances and areas are in metres or metres*metres even if the units of the projection are metres (which they questionably are for EPSG:3857) 

IMHO the measure example here http://openlayers.org/en/v3.8.2/examples/measure.html?q=measure is a bit misleading. If you measure the width of a big square field with and without the geodesic option checked you get labels of 1.6 km and 2.0 km. The difference is down to the latitude of the EPSG:3857 coordinates not earth curvature. I think the use of getLength and getArea by the example should be dropped.

There is a good starting point for the plotting of geodesics in ol3 in geodesicflatgeom.js. This is used by the graticule code to draw meridians e.g. on the Sphere Mollweide example. 

I did a PR for a getLength returning metres some months ago which is now out of date. It would perhaps be good to get a consensus on a way forward in this area (pun).

**Comment by wallw-bits** [comment]
GeographicLib is by far the best library out there for these computations both for geodesics and rhumb lines. We have a project at https://github.com/ngageoint/opensphere-asm that takes that library and compiles it to a WebAssembly and asm.js module for use in a browser. The results are available on npm.

Maybe could have named it a little better but we originally thought more stuff would go in there than just GeographicLib. We are using it in https://github.com/ngageoint/opensphere to interpolate line/polygon segments in addition to computing distances and bearings between points.

We opted not to use the Javascript port because it is only a partial port and does not include support for rhumb lines. Plus the WebAssembly version is much faster.
