### ISSUE TITLE
Option to enforce Featureload in ol.source.Vector

### ISSUE THREAD

**Issue by weskamm** [openlayers/openlayers#4170]
As discussed on the dev-Mailinglist (https://groups.google.com/forum/#!msg/ol3-dev/Wfe1uvTEw5M/u5RM-kXpBQAJ) it could be useful to extend the ol.source.Vector class to allow the (re-)loading of features, when the extent has changed.
Simple example: Using server-side clustered features. These have to be requested on every change of extent, as the clustering may change when zooming in.

Currently the method `loadFeatures` only requests features, which are not already loaded:
https://github.com/openlayers/ol3/blob/master/src/ol/source/vectorsource.js#L768-L793

Maybe some kind of flag like 'alwaysRequestFeatures' could be used which should be checked where currently only `alreadyLoaded` is checked.

**Comment by wulfsberg** [comment]
The aggressive "alreadyLoaded" check is problematic if, say, a WFS request has run up against a maximum-number-of-features limit, or if the server has otherwise done some processing based on the area requested (say, simplifying geometry).

I would very much like an option to disable the "alreadyLoaded" R-tree, and reload on any bounding box changes.
