### ISSUE TITLE
ol3 should use WebWorkers where possible

### ISSUE THREAD

**Issue by twpayne** [openlayers/openlayers#426]
[WebWorkers](https://developer.mozilla.org/en-US/docs/DOM/Using_web_workers) can provide a massive performance boost where they are supported. However, they are [not supported on several key platforms](http://caniuse.com/#search=WebWorkers), notably IE<10 and Android.

We should use WebWorkers where possible. Some areas are:
- [ ] Tile loading
- [ ] Post-render functions
- [ ] WebGL texture uploads

**Comment by BasieP** [comment]
@twpayne Wtf man, did you ever look at the performance of openlayers?
A 10 minute check would tell you that when you have like 1000+ features with some icons in a cluster i spend 99% of my zoomtime on javascript computations..

Not file downloading, not real rendering.. no just simple math...
how is that for a justification?

**Comment by Turbo87** [comment]
@BasieP no reason to be rude. if you want to add WebWorker support feel free to open a PR.

**Comment by richorama** [comment]
I'm seeing performance problems with a vector layer with a modest number of points on (less than 1000). The rendering slows down, causing the user experience to feel sluggish.

I believe that rendering of vector data onto a canvas could be achieved in a web worker, as is shown in my mandlebrot viewer which is performing the math and canvas rendering in this way (albeit that it's using leaflet.js).

https://richorama.github.io/frac-js/

I'm not familiar enough with openlayers internals to know how this could work, but we shouldn't dismiss this idea out right.

**Comment by ahocevar** [comment]
@richorama We are currently investigating using web workers in the library. But web workers are not a catch-all cure for performance problems. In your case I suggest you post a live example (e.g. on https://codesandbox.io/), because what you're reporting sounds like a performance issue on the application level. From our experience, even 20000 vector features should still allow smooth rendering on any device.

**Comment by richorama** [comment]
thanks @ahocevar, I'll attempt to reproduce.

**Comment by richorama** [comment]
@ahocevar I switched to ` renderMode: 'image'` and my problems were resolved. Thanks.

**Comment by taviroquai** [comment]
Hi,

I'm trying to use **ol/format/kml** inside a web worker but **ol/xml.js** complains about document not found. I'm trying to use inside a web worker because the parsing operation is the one that takes longer for, let say, a 50Mbytes file.

I'm using it inside a app that uses webpack to bundle dependencies.

See the error:

![ol_error_webworker](https://user-images.githubusercontent.com/498409/52560976-ee4e7c00-2df1-11e9-8c65-2183cd4f56aa.png)

This is the Web Worker file:
![ol_webworker](https://user-images.githubusercontent.com/498409/52560993-fad2d480-2df1-11e9-85a6-4a8b2ea66e14.png)

It seems that **ol/xml** needs the document to be available. I did not investigate further. Is it possible to use **ol/format/kml** inside a Web Worker?

Thanks.

**Comment by ahocevar** [comment]
XML in a web worker would only work when using a JavaScript XML parser. The browser's XML parser (which all our XML formats use) cannot be used in workers. You might be able to get it to work with the [JSDom](https://www.npmjs.com/package/jsdom) library.
