### ISSUE TITLE
Replace Resemble.js with Pixelmatch

### ISSUE THREAD

**Issue by mourner** [openlayers/openlayers#4288]
Thought you guys should know since you use Resemble.js for rendering tests — I just created a much much better image comparison library, https://github.com/mapbox/pixelmatch. Check it out! We're now using it for Mapbox GL rendering tests and it works very well.

cc @tsauerwein @tschaub @elemoine @marcjansen

**Comment by tschaub** [comment]
Nice.  Thanks @mourner.

**Comment by ahocevar** [comment]
Planning to work on a pull request for this. Who's in favour?

**Comment by tsauerwein** [comment]
> Planning to work on a pull request for this. Who's in favour?

It's definitely worth a try!

**Comment by bartvde** [comment]
+1

**Comment by marcjansen** [comment]
BTW: Am I supposed to run the current rendering test suite with the following command (on `master`):

```
node tasks/test-rendering.js
```

? Because if I do that (and it may be just me) on my machine, I get:

![image](https://cloud.githubusercontent.com/assets/227934/10943466/c7fed0c6-8314-11e5-9e12-e0f223d210de.png)

And on the command line it says:

```
Gecko error: it seems /path/to/ol3/node_modules/slimerjs-edge/lib/slimer/xulrunner/xulrunner is not compatible with SlimerJS. See Gecko version compatibility.
```

Can anyone reproduce? If so I#ll create an issue.

**Comment by tsauerwein** [comment]
Can you try with `make test-rendering`?

**Comment by marcjansen** [comment]
Notat the moment, will do once I have access to a computer again.

**Comment by marcjansen** [comment]
It now works for me regardless of I do `node tasks/test-rendering.js` or `make test-rendering`. Not sure what broke it.

**Comment by marcjansen** [comment]
🎉🎉🎉 cool, we finally switched!
