### ISSUE TITLE
Graticule Labelled

### ISSUE THREAD

**Issue by fito1987** [openlayers/openlayers#4307]
Hi There,

I am trying to use the graticule control in my project using Open Layers 3.10.1, however since upgrading from Open Layers 2, I cannot seem to get graticule to display labels. There use to be a "labelled" flag in the control which would allow for this to work.

Is there any chance that this could be added to the graticule control?

Cheers
Rod

**Comment by eblondel** [comment]
I've been working on improving the work initiated by @Brictarus and according to feedback provided in #4369: https://github.com/openlayers/ol3/pull/4369#issuecomment-155069958

Since this work is quite old now, i'm currently updating the code so it fits with current OL master, but also following all developing/contributing guidelines. If i understand well, the OL3 team should first accept according to https://github.com/openlayers/ol3/blob/master/CONTRIBUTING.md#pull-request-guidelines

Also please let me know how to proceed. My initial path was to create a pull request to @Brictarus fork,  so it can be appended to initial pull request #4369, but it remains unanswered.

Looking forward to OL3 team feedback on this
Best

**Comment by ahocevar** [comment]
Fixed with #6737.
