### ISSUE TITLE
ol.animation.rotate does not take shortest path.

### ISSUE THREAD

**Issue by icholy** [openlayers/openlayers#4310]
When using `ol.animation.rotate` it does not always take the shortest direction to the desired rotation. Whenever the shortest direction crosses `0` then it goes around the long way.

**Comment by klickagent** [comment]
Are there any news on this issue?

**Comment by ahocevar** [comment]
We are still accepting a pull request to fix this.

**Comment by Advialance** [comment]
I wanted to make a Pull Request for this issue since it's easy to solve and I don't see any reason why the rotation shouldn't animate into the shortest direction by default.
But since the freshly checked out Openlayers throws errors after a make without changes I won't be able to make a pull request with changes either.
I'm totally new to the Openlayers Code. Did I forget something?
```bash
> make check-deps
Program git OK
Program node OK
Program python OK
Program java OK
```
```bash
> make check
Running eslint...
node tasks/build.js config/ol.json build/ol.js
info ol Parsing dependencies
ERR! Unsatisfied dependency "ol.ext.rbush" in script: /home/openlayers/src/ol/structs/rbush.js 
Makefile:271: die Regel für Ziel „build/ol.js“ scheiterte
make: *** [build/ol.js] Fehler 1
```

**Comment by fredj** [comment]
`ol.ext.rbush` must be installed by npm. Can you run `npm install` and see if an error is reported?

**Comment by Advialance** [comment]
@fredj Thank you very much. Indeed: npm threw a warning I overread when I installed the dependencies.
Coming up with a solution soon. It's pretty tedious when you have a navigation running and a change of 5° at the course of the road causes a map rotation by 355°.
That's why I implemented my own animation in our App but I thought other people might have the same issue.

**Comment by Advialance** [comment]
Oh darn I thought the rotation values could just be between 0 and 2*PI but you can chose negative values and multiples of that, too.
If you calculate the correct value for the map rotation and pay attention that the rotation doesn't end up being at like 10 * PI you have no problems to continiously chose the correct rotation direction.
