### ISSUE TITLE
Overlay stopping event propagation conflicts with top level event handlers like Ember JS

### ISSUE THREAD

**Issue by bjornharrtell** [openlayers/openlayers#4400]
I've been using OpenLayers 3 with Ember JS recently and noticed that Ember JS cannot handle events if a component is used with `ol.Overlay`. I think the reason is because Ember JS expects events to bubble up to the top level.

The default is that `ol.Map` stops propagation of `ol.Overlay` events. The issue here is that events will never reach Ember JS and actions will not work.

If `ol.Overlay` is configured with `stopEvent: false` events will pass through to the top level and work with Ember JS but they will also be handled as map events by `ol.Map` which might not be wanted.

To be more friendly for top level event handlers perhaps `ol.Map` should filter out and ignore instead of stopping propagation.

**Comment by bjornharrtell** [comment]
Another solution might be to be more restrictive in general what a map event is. Prototype PR #4411.

**Comment by JulienPradet** [comment]
Hi,

Has this issue/PR any chance to be adressed in a near future ?
I've got this exact same usecase, except it's with React. And I believe that anyone actually using modern front-end libraries/framework will come up with the same problem.

Avoid using stopPropagation sounds like a good idea to me.
If it's not such a common use case, wouldn't it be possible to add a configuration like "stopMapEvent" instead of "stopEvent" that would trigger this behavior ?

**Comment by bjornharrtell** [comment]
I have no short term plan to put more time into this issue.

In the particular case I had I came up with another design avoiding the use of an overlay.
