### ISSUE TITLE
KML layer shows unwanted yellow pushpin (OL2.X vs OL3.X) --> ExtractStyles = true

### ISSUE THREAD

**Issue by SamOxyPlot** [openlayers/openlayers#4460]
Hi devs

Currently I'm upgrading from OL 2.11 to OL 3.11.1.

However I do have problems adding a KML layer. 
In OL 2.X there is no icon visible, but in OL 3.X I get the (unwanted) default yellow pushpin. <br /><b>What do I need to do to have the same result in OL3?</b>
<b><u>ExtractStyles = true</u></b>

![image](https://cloud.githubusercontent.com/assets/8522340/11271491/5b5cc23a-8ec6-11e5-8977-b4f57c1beb0d.png)

I've included also the KML file (see below, http://earth.google.com/kml/2.2). There is no icon href defined. However that shouldn't result in showing a default icon. <br /><b>Is there a way to override this behaviour?</b>

[TESTKML.kml.txt](https://github.com/openlayers/ol3/files/38945/TESTKML.kml.txt)

**Comment by SamOxyPlot** [comment]
Any updates on this?

**Comment by marcjansen** [comment]
Can you try to set `showPointNames` to `false`?

**Comment by SamOxyPlot** [comment]
Nope.

I got this allready in my original code:

<code>
var format = new ol.format.KML({
                    extractAttributes: true,
                    extractStyles: true,
                    showPointNames: false
                });
</code>

**Comment by adrelino** [comment]
Hi, 

I am having the same issue. What I want is to show a small circle as was default in ol2 when no style is defined for a KML Point geometry. In ol3, I get the small circle only when I set `extractAttributes:false`. When I set `extractAttributes:true`, ol3 somehow wants to render an image instead of a small circle for a KML Point geometry and defaults to the pushpin.

I found out that it is referenced [here](https://github.com/openlayers/ol3/blob/master/src/ol/format/kml.js#L196) in the ol3 src:

`ol.format.KML.DEFAULT_IMAGE_STYLE_SRC_ = 
'https://maps.google.com/mapfiles/kml/pushpin/ylw-pushpin.png';`
