### ISSUE TITLE
ZoomSlider initialization error

### ISSUE THREAD

**Issue by jackaiwang** [openlayers/openlayers#4494]
![zoomslider](https://cloud.githubusercontent.com/assets/12510042/11387176/ff425e1e-9362-11e5-8521-46af0f3a7874.png)
Sometimes when I load the map, the zoomslider not properly initialized, as shown in the picture above.
It can not automatically repair, I usually have to remove it and re-add it.

**Comment by marcjansen** [comment]
Can you show us a complete example how you add the zoomslider in the first place?

**Comment by adube** [comment]
I happened to be once too.  I'll explain the circumstances.  Here goes.

It happened in an example while using the [OL3-Google-Maps library](https://github.com/mapgears/ol3-google-maps/), more specifically [in this example](http://dev5.mapgears.com/ol3-google-maps/examples/vector.html). The zoomslider is added in the array of controls at the creation of the map.

    var map = new ol.Map({
      //...
      controls: ol.control.defaults().extend([
        new ol.control.ZoomSlider()
      ]),
     //...
    });

The exact same problem occurred because the zoomslider does some calculation using the map size, but while it happened, in my case, the map size was not yet defined because it was being tossed over the place while Google Maps is being activated, which puts the ol3 map div inside Google Maps as a control.  To fix the issue, I had to do the following, see the [code snippet from OLGM](https://github.com/mapgears/ol3-google-maps/blob/master/src/herald/layersherald.js#L112-L131), i.e. I had to wait for the map to be rendered and for a center to be set as well.

Hope that can help understanding the core of the issue.

**Comment by marcjansen** [comment]
So https://github.com/openlayers/ol3/blob/master/src/ol/control/zoomslidercontrol.js#L147 seems to be the cause of the hassle. I do not have time to look into this right now, sadly.

**Comment by adube** [comment]
Yes, the issue came from there indeed.

**Comment by JackWangXiaoer** [comment]
yes,because the limits after being initialized with a wrong value, will not be modified.
thank you @adube provided the detailed examples
