### ISSUE TITLE
kml icon with url relative path

### ISSUE THREAD

**Issue by topwood** [openlayers/openlayers#4503]
I have a kml file,a part of this:

```
<IconStyle><Icon><href>GroundStation.png</href></Icon></IconStyle>
```

this kml file is in my 'data' floader:

```
var vector = new ol.layer.Vector({
  source: new ol.source.Vector({
    url: 'data/facilities.kml',
    format: new ol.format.KML()
  })
});
```

and i put my GroundStation.png in my 'data' floader too.

But in this way ,my icon can't be requested rightly,because the url is 'GroundStation.png' but not expected 'data/GroundStation.png'.

**Comment by dermoench42** [comment]
This is because the URL which is used to reference relative Paths is the url of the including html file not of the loaded kml file. I don't know a way to switch the path to a subdir where the kml lives to fix that, maybe someone does? The other option is to parse the kml and replace the relative paths ...

**Comment by mike-000** [comment]
I think this would need something like an iconUrlFunction option for the KML constructor.  If provided by the application code it would it could replace a relative path with the appropriate full path.  It could also be useful if the KML format was subclassed by a custom format such as KMZ to return data urls for icons extracted from the kmz file.
