### ISSUE TITLE
selected feature doesn't disappear

### ISSUE THREAD

**Issue by rniederer** [openlayers/openlayers#4729]
Hello

I have a problem with a selected feature. I can't remove it from the vector layer. It means the feature is removed from the layer, but still visible.
1. register select interaction on map
2. select feature
3. count number of features (ex. 32) - for test
4. remove feature from layer
5. count number of feature (ex. 31) - for test

So, the feature is removed from the layer, but still visible on the map. When I click someplace, the feature disappears.

With the following steps it works
1. register select interaction on map
2. select feature
3. unregister select interaction
4. remove feature from layer
5. register select interaction on map

it shows like a selected feature can't remove from layer resp. the map doesn't refresh the view.

**Comment by ahocevar** [comment]
This is because the feature is copied to the Select interaction's internal layer when it is selected, and it does not get notified when the feature is removed from its original layer.

I have experienced similar issues like this, all related to the fact that features are added to another layer by the Select interaction, and masked by the skipFeatureUid object on the map.

If we want to maintain this architecture, then a fix would be to register listeners for the original layer's remove event that removes features from the selection layer.

A related issue with the current approach is that features with the same id (feature.getId()) as an already selected feature from a different layer will disappear when selected, because a vector source can only have on feature with the same id.
