### ISSUE TITLE
ol.interaction.Modify: Uncaught TypeError: a.b[e] is undefined

### ISSUE THREAD

**Issue by camue2016** [openlayers/openlayers#5127]
Hi,
 I want to modify a simple LineString geometry by using the modify ineraction. However everytime I click on the blue circle a few times in a row the above error is occurring. How can it be? Everything else is working fine.

Here is my code:

var lineFeature =  new ol.Feature({
     geometry: new ol.geom.LineString([ol.proj.fromLonLat([11.5, 45.1245]), ol.proj.fromLonLat([5.5,50.52465])]),
    });

var features = new ol.Collection();

features.push(lineFeature);

var featureOverlay = new ol.layer.Vector({
        source: new ol.source.Vector({features: features}),
        style: styleFunction
      });

var modify = new ol.interaction.Modify({
      features: features,
       });

var map= new ol.Map({
        target: 'map',
        layers: [ raster, featureOverlay],
        interactions: ol.interaction.defaults().extend([ modify ]),
        view: new ol.View({
          center: ol.proj.fromLonLat([10.5, 52.458]),
          zoom: 7
        })
      });

featureOverlay.setMap(map);

**Comment by bartvde** [comment]
Can you show the stack trace with the debug version? Also a jsFiddle might help here.

**Comment by bruceceng** [comment]
I had this same issue. I think the problem is that if you have "shift" as the delete condition, sometimes when you shift-click on a node to delete it, it accidentally initiates a node drag event. Then the delete takes place and the node drag event is still going on. When the node drag event finishes, it tries to update the position of a node that was deleted which leads to the error. I'm not familiar enough with the code to fix it, but I think you would need to somehow complete all node drag events prior to the delete or prevent a delete if a node drag is taking place.

A separate issue is that you can shift-click on a linestring before you really start editing it which leads to a this.dragSegments_.length being undefined.
