### ISSUE TITLE
Disappearing line crossing IDL only in few situations

### ISSUE THREAD

**Issue by gejgalis** [openlayers/openlayers#5262]
We found strange bug related to rendering LineString crossing IDL. It happens only in following situations:
- only from some zoom level
- only on right side of IDL
- only on earths on left side from earth 0

Following Video presents the bug: https://www.youtube.com/watch?v=Q2nKuLX_F7k

Failing RED and working good GREEN areas are presented on following picture:
![fail-area](https://cloud.githubusercontent.com/assets/1484705/14742532/098b2432-089d-11e6-9865-6cb1a45ba7dd.png)

You may try [fiddle](http://jsfiddle.net/0582j5qq/2/). Try to deep zoom in on right side of the line. Try to do it on RED areas from picture above and GREEN areas.

**Comment by ahocevar** [comment]
This might be a coordinate range issue and only be an issue on certain browsers and platforms. I couldn't reproduce on Mobile Safari right now. What browser and OS are you seeing this issue on?

If it is a coordinate range issue, a workaround would be to add vertices along the line string to get shorter segments.

**Comment by gejgalis** [comment]
I could reproduce on all Windows browsers and Android Chrome.
I found the problem is with coordinates:
```javascript
// BAD:
var line = [
  [220, 0],
  [120, 0]
];

// GOOD
var line = [
  [220 - 360, 0],
  [120 - 360, 0]
];
```

I improved example: http://jsfiddle.net/0582j5qq/3/ so you may try to switch between those two coordinates.

Now I may use workaround with shifting all coordinates with `-360` degrees

**Comment by ahocevar** [comment]
@gejgalis Thanks for the investigation. Do you think you'd be able to provide a test case or a fiddle that shows the issue without user interaction, so it is easier to reproduce the problem?

**Comment by ashchurova** [comment]
I have experienced this issue as well. Please look at my sample: 
https://codepen.io/ashchurova/pen/rwXjzP?editors=1011
No user iteration involved. Last time you said this issue is caused by line segment length. I found another sample of the line and the issue only appears if you start panning to the right in the world 1, 2, 3 .. etc and it is consistently reproduced. Try panning to the right in my sample and watch line disappear when it hits right border of the map bounds. I hope this will help to fix this. It has been an issue for us for a while.

**Comment by raiyni** [comment]
As seen in https://github.com/openlayers/openlayers/issues/6088

There isn't a reasonable fix without damaging another part of the library. You can fix it by switching to vector map tiles or making the custom changes I made but not using extent loading.

You will experience this problem in ESRI too.
