### ISSUE TITLE
Prioritise tiles from top to bottom of the layer stack in the tile queue

### ISSUE THREAD

**Issue by morabitowoolpert** [openlayers/openlayers#5323]
~~Tiles should render immediately when they're loaded, regardless of z order. When a faster tile layer is displayed over a slower tile layer, tiles in the above layer do not render until the corresponding tile in the layer below finishes loading. This effectively slows down all tile layers to the speed of the slowest service displayed on the map.~~

**Comment by ahocevar** [comment]
I don't see anything in the code that causes the behaviour you are describing. See https://github.com/openlayers/ol3/blob/v3.15.1/src/ol/map.js#L945-L950. What makes you think so?

**Comment by morabitowoolpert** [comment]
Upon further testing I've realized that this behavior is due to the volume of network requests, not OpenLayers's tile rendering.

**Comment by morabitowoolpert** [comment]
Have individual tile queues for each layer, so slower layers don't "clog up" the queue with pending requests

**Comment by ahocevar** [comment]
If a server responds faster than another, its tiles will be available (and rendered) sooner than those from a slow server. No matter whether the tile queue is per map or per layer. There are also browser limits to the number of requests that can be made at the same time. Can you point to an application where you think that slow layer sources prevent layers from fast sources from being rendered as soon as their tiles are available?

**Comment by morabitowoolpert** [comment]
I have an application where I'm using a CartoDB basemap tiles with a layer of aerial imagery on top of it. The CartoDB basemap tiles take longer to return (sometimes as long as several seconds) than my imagery tiles.

As you pan across the map, the queue eventually fills up with pending basemap tile requests, and requests from other layers are stuck in the tile queue until the slow requests complete.

Here's my example:
[http://run.plnkr.co/P0D87XuivPdUVu9A/](http://run.plnkr.co/P0D87XuivPdUVu9A/)

**Comment by ahocevar** [comment]
The link you provided is invalid, but I get what you are saying. This can indeed happen when the total number of tiles in the map viewport from all layers exceeds the limit of 16 loading tiles. On a smaller map viewport with less than 16 tiles total, the queue would be reprioritized to load the tiles closest to the view focus with the highest resolution.

One thing that could help would be to give tiles from layers higher on the layer stack a higher priority, which can be done by changing https://github.com/openlayers/ol3/blob/v3.15.1/src/ol/map.js#L945-L954. This appears to be a better option than having per-layer tile queues, because that would cause an increasing number of requests with an increasing number of layers, which would cause performance problems because the browser's request slots would be filled up.

I think it makes sense to accept a pull request for this improvement. Would you be willing to provide one?
