### ISSUE TITLE
Labels that follow a curve/linestring

### ISSUE THREAD

**Issue by simon1389** [openlayers/openlayers#5441]
It would be a helpful feature if it's possible to draw some text into a linestring, i.e. as a description of the linestring.
Attached a screenshot of a leaflet map which supports this feature:

![23329](https://cloud.githubusercontent.com/assets/9256689/15848409/2158e91e-2c8d-11e6-9a32-5597090b692c.png)

**Comment by ahocevar** [comment]
This is planned, but not yet available. We'd also accept a pull request for this if someone wants to work on it.

**Comment by ke5stl** [comment]
yes please!  this would be a huge win for being able to render the vector tiles with street names following the street paths, for example

**Comment by plepe** [comment]
Yes, this would be a really important addition. I'm currently working on a map of public transportation and this is the only missing feature which keeps me on Leaflet (again, I started a project with Leaflet, but found it not powerful enough).

If you (or someone else - I don't have the capacity in the near future) implement it, this additional options would be great considering:
* Repeated labels (with configurable distance)
* Upright labels (labels are turned, because they are hard to read upside-down; optional: e.g. on isolines you don't want to turn labels)
* Alternative text for turned labels (if you want to indicate directions, e.g. for river directions)

Also see the options for [TextSymbolizers in Mapnik](https://github.com/mapnik/mapnik/wiki/TextSymbolizer).

**Comment by anzeznidarsic** [comment]
This would be an awesome addition to ol3.

Note on original post: I don't believe Leaflet has this, the screenshot above looks like basemap generated on the server-side.

**Comment by plepe** [comment]
I don't know if the original post has been generated on the server-side, but Leaflet indeed has an extension for text along paths: http://makinacorpus.github.io/Leaflet.TextPath/

It has it's limitations (almost none of the features that I mentioned above are implemented), and performance is rather poor, but still, it works :-) (I'm using it actively)

**Comment by tglander** [comment]
Have you seen the extension in OL3-ext?
http://viglino.github.io/ol3-ext/examples/map.style.textpath.html

**Comment by plepe** [comment]
That looks pretty good! Thanks for pointing me to that extension.

**Comment by simon1389** [comment]
I'm using the extension (http://viglino.github.io/ol3-ext/examples/map.style.textpath.html) with OL4.0.1 now and it works pretty good so far.
The only problem i can't solve, is the great lack of performance when using it on a mobile device with android. Has anyone an idea what may be the reason for that?
Iphone with Safari is pretty fast and smooth.

**Comment by QuantaSoftTechnology** [comment]
Hey guys OL3-ext is awesome but I think the textpath plugin only works on ol.layer.Vector.
Does anyone have a shot on ol.layer.VectorTile ?

**Comment by qtgis** [comment]
Hey guys OL3-ext is awesome but I think the textpath plugin only works on ol.layer.Vector.
Does anyone have a shot on ol.layer.VectorTile ?

**Comment by nsands** [comment]
This is so needed in OL.  Currently the lines in my Geoserver WMS/TMS/WMTS all look great in OpenLayers with labels generated on the server.  But lines in WFS look quite ordinary because the labels cannot be made to follow the lines.  They really stand out as sub-par.

**Comment by ke5stl** [comment]
It looks awesome!  I’m looking forward to it being released.

 

Thank you very much for adding this!

 

Best regards,

Peter

**Comment by fredj** [comment]
fixed with #7239
