### ISSUE TITLE
Option to re-render vector tiles at zoom levels not in source in hybrid render mode

### ISSUE THREAD

**Issue by bjornharrtell** [openlayers/openlayers#5580]
As far as I know with `renderMode` set to `hybrid` tiles will only be rendered at the zoom levels existing in the source. When zooming to a level not existing in the source rendered tiles will be rescaled.

While this can make sense as vector tiles can/should be generalized to fit the zoom level, I also think it would be useful to allow tiles from the closest zoom level to be re-rendered at zoom levels not available in the source.

**Comment by bjornharrtell** [comment]
Looked into on how to achieve this and it does not seem trivial to decouple the source tilegrid from what the tile renderer works with. @ahocevar, do you think this option would be worthwhile and do you have any input on how it could be achieved?

**Comment by ahocevar** [comment]
@bjornharrtell I experimented a lot with rendering tiles at different resolutions. First when I did the initial implementation, and again when I added the hybrid rendering mode. I found that in the first case, caching became inefficient, and in the second case, rendering got actually slower. Why? Because stitching 512x512 or 1024x1024 or even bigger tile images is more expensive than stitching 256x256 images. So if you look at the mapbox-vector-tiles-advanced example, which skips tiles from every other zoom level and does not use hybrid mode, you will see that it does not really feel slower than the mapbox-vector-tiles-example, which does use hybrid mode and uses tiles from all zoom levels.

**Comment by bjornharrtell** [comment]
My thoughts were only about rendering quality and to be able to use lower resolution vector tile data (partial) to render higher resolution 256x256 images, at zoomed in levels beyond the vector tile source.  As mapbox vector tiles can contain 4096x4096 units of precision it can be useful for one or two more zoom levels. I don't quite follow why you would necessarily need to deal with bigger raster tile sizes to be able to use vector tile data at other resolutions than the intended.

As a side point about performance I've found that on mobiles canvas performance is lacking so hybrid mode is especially important there.

**Comment by ahocevar** [comment]
@bjornharrtell:

> My thoughts were only about rendering quality and to be able to use lower resolution vector tile data (partial) to render higher resolution 256x256 images

This would be indeed a non-trivial change, because it would mean we'd have to maintain two tile grids: one for the vector tiles, and another for the generated raster tiles used in hybrid and raster mode. If you're willing to accept the challenge and create a pull request, I'll gladly review.

> I don't quite follow why you would necessarily need to deal with bigger raster tile sizes to be able to use vector tile data at other resolutions than the intended.

My attempts did not involve maintaining two separate tile grids. So in my context, If you have a vector tile at zoom level 0 (256x256px) that you want to use at zoom level 4, hybrid or image mode would have to render the tile into a 4096x4096px canvas. This is 1) slow and 2) a bigger canvas size than many mobile devices allow.

**Comment by bjornharrtell** [comment]
Spent a few hours with `ol.renderer.canvas.VectorTileLayer` and friends and while educational I'm not getting anywhere. Realized that even if two tile grids could be managed, a vector tile won't easily be "split" from a higher grid level to be partially rendered at lower level so perhaps this does not make much sense. The most sensible thing in hybrid mode is probably to generate additional vector level(s).

**Comment by ahocevar** [comment]
> The most sensible thing in hybrid mode is probably to generate additional vector level(s).

Do you mean additional resolutions where images are made available from vector tiles from a different resolution?

**Comment by bjornharrtell** [comment]
No, I no longer think that would be a good idea which is why I closed the issue. If higher rendered resolution is needed in hybrid mode I think the only sensible path is to simply create more actual levels of vector tiles to be used as is.

**Comment by ahocevar** [comment]
Ok, understood. Thanks for the clarification @bjornharrtell.

**Comment by ahocevar** [comment]
I created a pull request that solves this issue for most use cases: #6454.
