### ISSUE TITLE
how to handle features with no geometry but with a bounds

### ISSUE THREAD

**Issue by bartvde** [openlayers/openlayers#566]
so in GML this is allowed, having a feature without a geometry but with a boundedBy element. In OL2 we had a bounds property at the feature level to deal with this.

Discussed this briefly with @ahocevar and he suggested: "I'd rather see ol.Feature accept an ol.Extent as geometry, in addition to ol.geom.Geometry."

Opening up this ticket for further discussion.

**Comment by computerchemist** [comment]
Can I add a use case to this? Norway. It's got literally hundreds of thousands of polylines/vertices even when simplifying with mapserver. If all I want to do is zoom to the country extent based on other criteria I am searching on (or indeed any other subset with a vast number of returned coords) then WMS wins hands down in a render in terms of bandwidth/time to pass/time to compute (I was literally waiting for 5 minutes wondering what was going on), but I still would like to parse the gml:boundedBy returned from a "geometryless" but fast WFS call based on wanting to zoom to the area. Again, gazetteer is another valid use case when dealing with complex polygons. I'd love to see the extent passed back if it is valid; why would gml:boundedBy exist if not for this?

**Comment by tomchadwin** [comment]
My use-case is similar. I have a click-to-select-features kind of interface, for which I had to use WMS not WFS, because the geometries are too complex and large in filesize. I therefore use WMS `GetFeatureInfo` to query MapServer. I then need to be able to zoom to the extent of all feature bboxes combined.

In other words, I need an equivalent for `layer.getExtent()` when the layers caontains features with no geometry, but with `gml:boundedBy`.
