### ISSUE TITLE
Any plan to include ol.format.ogc.filter in WMS ?

### ISSUE THREAD

**Issue by AlAlavi** [openlayers/openlayers#5691]
Hi
In recent version(3.17.1), i have seen a familiar filter object of OpenLayers 2. Documentation says that it can be used for WFS. Is there any plan to include it for WMS, as well?

According to this [link](http://stackoverflow.com/questions/10071349/how-filter-points-in-wms), It could be done in v2. I couldn't find suitable parser for that in v3. Is there a way to do that in v3?

**Comment by AlAlavi** [comment]
Hi
It sounds very confusing. Today I understood that i can use the same mechanism of WFS GetFeature for WMS Filtering as well.
Changing OpenLayers's example leads to:

`var f = ol.format.ogc.filter;
featureRequest = new ol.format.WFS().writeGetFeature({
	srsName: 'EPSG:4326',
	featureNS: 'http://localhost:8080/wms',  // Why it is a required parameter?
	featurePrefix: 'ws',
	featureTypes: ['City'],
	filter: f1.equalTo('NAME', 'New York')
	
});

var fea= new XMLSerializer().serializeToString(featureRequest);
layer1 = new ol.layer.Image({
	title: 'Ostan',
	source: new ol.source.ImageWMS({
		url: 'http://localhost:8080/geoserver/wms',
		params: {
			LAYERS: 'ws:City',
			VERSION: '1.3.0',
			FILTER: fea
			
		}
	})
});
`
If OGC filtering is not restricted to WFS, so why it is available and documented under WFS class? It makes user confused that he can only use OGC filtering for WFS Filtering.
Regards

**Comment by ahocevar** [comment]
This is because you are actually using a WFS GetFeature request which GeoServer understands because of its enhanced filter support. See http://docs.geoserver.org/2.8.x/en/user/services/wms/vendor.html#filter. The same will not work on other WMS servers.

That said, it would be nice to have an `ol.format.ogc.writeFilter()` convenience function, which would more or less just wrap the `ol.format.WFS.writeFilterCondition_` functionality. If anyone wants to work on that, we'd accept a pull request.

**Comment by AlAlavi** [comment]
Thanks for your hint.
It was my fault. I was thinking that filter parameter is part of standard WMS, as defined by OGC.

**Comment by fredj** [comment]
FYI, mapserver will also support WMS filters: http://mapserver.org/development/rfc/ms-rfc-118.html

**Comment by adube** [comment]
FYI, the convenience method has been added in #6614.
