### ISSUE TITLE
Permalink Control

### ISSUE THREAD

**Issue by bartvde** [openlayers/openlayers#589]

**Comment by Matthias84** [comment]
I don't think that this should just be part of the application itself. The OL framework should provide best practises for GIS related standards, which IMHO also includes permalink url shortcuts. V 2.x had also this feature, is there a good reason to keep it seperated and to force devs to code their own implementation?

**Comment by elemoine** [comment]
> I don't think that this should just be part of the application itself. The OL framework should provide best practises for GIS related standards, which IMHO also includes permalink url shortcuts. V 2.x had also this feature, is there a good reason to keep it seperated and to force devs to code their own implementation?

I think there is a good reason: there are many ways to implement permalinks. For example, the map state may be encoded in the query part of the URL, or in the hash part of the URL (after the `#` sign). Also, one may want to use the history API, or think that it does not make sense that forward/backward buttons navigate through the map history. There are many different use-cases. So I don't think OpenLayers 3 can/should have an opinion on the way the map state should be encoded in the URL and, more generally, on the way permalinks are created and behave.

See http://openlayers.org/en/master/examples/permalink.html for an example.

**Comment by Matthias84** [comment]
It's true, as you write there are a lot of ways to accomblish this features. So customization is a must.

BUT I see also good reasons to include a ready-to-use feature for permalinks:
* interoperability - e.g. you can easily share views across multiple plattforms as a lot of OSM pages with OL v2 do
* it saves time for people not that familar with JS coding
* it was included in v2.

**Comment by probins** [comment]
I agree with @elemoine. The OL2 permalink dates from the early days of web mapping, when maps were much simpler than they are now. OSM still has a simple model, with just a couple of tile layers, no vectors, and not much 'map state' to store. It now uses Leaflet, though this doesn't provide a permalink either; its link share is site-specific. You're assuming that all maps have such a simple structure, but an OL3 map can have layers with different opacity/visibility/brightness/etc; it can have numerous vector layers, which may be clustered, have different styling, and/or be labelled; the vector data may be volatile, in which case you probably want some kind of caching or storage rather than a link. How much of all this you want to reproduce when sharing maps is going to be application-specific, and probably impossible to define in a simple link anyway. Personally I use a JSON object to store map definitions.
