### ISSUE TITLE
Tile fading

### ISSUE THREAD

**Issue by bartvde** [openlayers/openlayers#594]

**Comment by anzeznidarsic** [comment]
+1

**Comment by KlemenSpruk** [comment]
+1

**Comment by regiodata** [comment]
+1

**Comment by roy46** [comment]
+1

**Comment by cs09g** [comment]
Any updates on this? It is nice feature

**Comment by dovs** [comment]
+1

**Comment by ThomasG77** [comment]
@dovs  Please vote using new functionality instead of +1 everywhere https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments
Thanks

**Comment by giohappy** [comment]
how much would it take to implement it? Time and money.
Anybody willing to contribute and who could implement it?

**Comment by klickagent** [comment]
+1

**Comment by DCdeBrabander** [comment]
+1

**Comment by TDesjardins** [comment]
I think it is not much effort to implement this. But let's be honest... tile fading is ugly. A good designer will never use this. It is more a bauble.

**Comment by tremby** [comment]
If only we were all so lucky to work with good designers...

But seriously, that's entirely subjective. Google Maps (at least the JS
API), Open Street Map, Leaflet, Mapquest, and Wikimapia all fade tiles.

**Comment by TDesjardins** [comment]
@tremby I didn't want to offend somebody ;-) Thanks for listing. I know all of the projects. Mapquest and Wikimedia use Google Maps API. Have you ever ask yourself why Google Maps don't use tilefading although its API provides it? Because it is "subjective" bad design ;-). Fading the tiles lasts longer than loading it. It slows down the image rendering and makes the map navigation noisy (flickering). This is only a tip. No one wants to stop you from doing tilefading 😄 .

**Comment by tremby** [comment]
> Have you ever ask yourself why Google Maps don't use tilefading although its API provides it?

The API is older. Trends change. But that's all they are.

> This is only a tip. No one wants to stop you from doing tilefading

I'm aware. I just don't see how it's useful here to give opinions on whether it's bad design or not. I don't care whether tiles fade or not. Designers I work with do.

**Comment by hccampos** [comment]
Actually, Google Maps does fade the vector tiles in/out. And it presents several levels of satellite tiles as they get loaded, which makes it feel faster than simply loading the full resolution tiles for the current zoom level.

**Comment by giohappy** [comment]
It may seem ridiculous but I've talked with lot of people thar moved to
Leaflet and one of the reasons was tilefading, mostly for its effect on
zoom transitions.

These are opinions of course. I can't put resources in this but if I could
I would.

giovanni

Il 13 set 2017 19:23, "Hugo Campos" <notifications@github.com> ha scritto:

Actually, Google Maps does fade the vector tiles in/out. And it presents
several levels of satellite tiles as they get loaded, which makes it feel
faster than simply loading the full resolution tiles for the current zoom
level.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/openlayers/openlayers/issues/594#issuecomment-329238368>,
or mute the thread

**Comment by TDesjardins** [comment]
> The API is older. Trends change. But that's all they are: trends.

Trends change, but bad design keeps bad design.

> I just don't see how it's useful here to give opinions on whether it's bad design or not. I don't care whether tiles fade or not. Designers I work with do.

This is software development, right? You can discuss if a feature is useful or not. If you know it's bad design, you can put your effort in useful things. Why should you implement a feature which your designers wants you to disable later.

> Actually, Google Maps does fade the vector tiles in/out. And it presents several levels of satellite tiles as they get loaded, which makes it feel faster than simply loading the full resolution tiles for the current zoom level.

Are you sure you are not speaking about digital zooming and progressive image loading? Digital zoom makes it feel faster when navigating in the map and this makes navigating in OpenLayers enjoyable.

Have a look at Leaflet. It "clears" the whole screen when zooming in or out only for fading every new tile in. This is a break in machine user communication. OpenLayers simply uses digital zoom for this purpose without clearing the whole screen. Because of this you rarely see in OpenLayers the background(-color). It focuses on the important part of a map viewer which is the map and not the background. Not so in Leaflet, where you can see the background(-color) with every zoom action.

**Comment by giohappy** [comment]
@TDesjardins I think digital zoom + fadein is a nice solution. Instead of clearing the previuos tile you can fadin above it.

**Comment by hccampos** [comment]
That is exactly what needs to happen: cross-fading tiles. Clearing the previous tile to show the new one is just silly. However, you basically need to have the two tiles available and render them together rather than handling one tile at a time. Should not be too hard in theory but I am not familiar enough with OL's codebase to know for sure.

**Comment by tschaub** [comment]
![fade](https://user-images.githubusercontent.com/41094/30515331-ac75f14e-9ae2-11e7-97ef-0e0ce6f71e1b.gif)

I've started on a branch to support tile opacity transitions.  This feels way overdue, and I think it should be the default.  We can make it possible to disable per layer.  There will be edge cases to work out, but I hope to have something people can experiment with in a day or two.

The animation above is the [reusable source example](http://openlayers.org/en/master/examples/reusable-source.html) (clicking between Jan and Jan w/ bathymetry) with a 250 ms linear transition in opacity.

**Comment by giohappy** [comment]
It sounds great Tim!
So tiles crossfading on zoom change will be included, right?

Il 16 set 2017 21:31, "Tim Schaub" <notifications@github.com> ha scritto:

**Comment by tschaub** [comment]
> So tiles crossfading on zoom change will be included, right?

Yes.  New tiles fade in over old tiles.

Watch #7267 for progress.  Rendering tests need work still, but you can try out that branch if you are interested.

**Comment by TDesjardins** [comment]
@giohappy @hccampos Agree!
@tschaub Thanks! I will have a look at your branch.

**Comment by AdnanBoota** [comment]
Hi Guys,

I have searched a lot about this, Tile Fading Zoom Effect and came to this link.

I am using Humanitarian version of open street map.
http://www.openstreetmap.org/

What i want is, Tile fading (zoom in, zoom out) effect like the above link, i think its leaflet.js?
but with openlayers.js i am not sure if i can do it or not?

Please let me know, how to have achieve this tile fading  (zoom in, zoom out)?

Thanks in advance!

**Comment by marcjansen** [comment]
It should work with the currently unreleased master, or with the next release.
