### ISSUE TITLE
Allow more types of shapes to be drawn

### ISSUE THREAD

**Issue by tschaub** [openlayers/openlayers#5983]
Currently, the draw interaction is configured with a `type: ol.geom.GeometryType` option.  This makes sense as a way to give people control over the geometry type returned (e.g. `ol.geom.MultiPolygon` instead of `ol.geom.Polygon`).  However, it makes it less convenient to use the draw interaction to create shapes that don't have a corresponding geometry type (e.g. square, box, clover, etc.).

If people really want to draw these additional shapes, it could be a reason to add them as first class geometry types.  On the other hand, it could also make sense to allow these non-geometry types to be drawn, but to make it more convenient than providing a custom geometry function.

What do others think about extending the `type` option for the draw interaction to include non-geometry types (e.g. `'Box'`)?  How about the idea of adding additional geometry types (e.g. `ol.geom.Box`)?

See #5977 for the motivation.

**Comment by ahocevar** [comment]
I'd favor an extended type, and make it so string types are also accepted, so e.g. `'MultiPolygon'` in addition to `ol.geom.MultiPolygon`.

**Comment by tschaub** [comment]
To be clear, `'MultiPolygon'` is already an accepted `type`.  The suggestion is to allow things that are not one of the `ol.geom.GeometryType` enum (e.g. `'Box'`).

**Comment by ahocevar** [comment]
Ah sorry, I thought we confiture `type` with geometry constructors. So when it's strings already, even better. +1 on the suggestion to allow things that are not in the `ol.geom.GeometryType` enum.

**Comment by mzur** [comment]
I think this is a great idea. Currently we have to maintain a fork with our "rectangle hacks" which implement a new `Rectangle` geometry type so rectangles can be conveniently drawn and modified. But since a rectangle is just a polygon this is not a very elegant solution. The ability to implement a custom rectangle "shape type" for the polygon geometry would be great. But this should affect both the draw and modify interaction.
