### ISSUE TITLE
ol.source.VectorTile does not support reprojection

### ISSUE THREAD

**Issue by to-kr** [openlayers/openlayers#6059]
Tiles are not loaded if source tilegrid is in the different projection then ol.View. 

```
var key = 'Your Mapzen API key from https://mapzen.com/developers';

var layers = [
  new ol.layer.Tile({
    source: new ol.source.OSM(),
  }),
  new ol.layer.VectorTile({
    source: new ol.source.VectorTile({
      format: new ol.format.TopoJSON(),
      tileGrid: ol.tilegrid.createXYZ({maxZoom: 19}),
      url: 'https://tile.mapzen.com/mapzen/vector/v1/roads/{z}/{x}/{y}.topojson?api_key=' + key,
      projection: 'EPSG:3857'
    }),
    style: new ol.style.Style({
      stroke: new ol.style.Stroke({
        color: '#ff0000'
      })
    })
  })
];

//var proj = 'EPSG:3857'; // WORKS
var proj = 'EPSG:4326';   // PROBLEM

var map = new ol.Map({
  layers: layers,
  target: 'map',
  view: new ol.View({
    center: ol.proj.fromLonLat([14.5, 48.5], proj),
    projection: proj,
    zoom: 5
  })
});

```

**Comment by kevinstadler** [comment]
This was already the case in 3.*, where in #4491 @ahocevar argued that this is appropriate because vector tiles only 'work' for the projection they were made for. I think the argument is that, because vector tiles contain geometry and content adjusted for the local resolution (which might differ for a given tile depending on the projection), a vector tile for one projection might contain too many or too few details for that same location rendering in another projection.

While I understand this caveat, I don't think it's in principle wrong to support displaying reprojected vector tiles: if I want to show one of the readily available Web Mercator tile sets in a slightly projection such as Gall-Peters, both the tile content and level of detail would be fully appropriate.

The workaround in #4491 using a Vector source seems a bit cumbersome, I'll probably give writing my own reprojecting `tileLoadFunction` a try, unless you found another solution to this @to-kr?

**Comment by ahocevar** [comment]
@kevinstadler As long as the tile grid is in the view projection, vector tiles can be reprojected when they are not in pixel coordinates. See the `osm-vector-tiles.html` example, where the view is in Web Mercator, and the tiles are TopoJSON with geographic coordinates. The tile grid is a standard Web Mercator XYZ tile grid.

**Comment by kevinstadler** [comment]
Aaah I see that's what you meant, thank you for clarifying! So if we wanted vector tiles split into a different tile grid than that of the view to load correctly through a `VectorTile` source, one would have to fiddle with `TileGrid`'s `getTileRange*` functions to first reproject the visible extent of the map to the source projection and then create the necessary list of tiles from that.

I just saw in the [`reprojection-by-code`](https://openlayers.org/en/latest/examples/reprojection-by-code.html) example that doing exactly that seems to be supported for raster tiles using the [`setTileGridForProjection()`](https://openlayers.org/en/latest/apidoc/ol.source.TileImage.html#setTileGridForProjection) function, is there any argument against doing the same thing for vector tiles?

**Comment by ahocevar** [comment]
I'd say it's not worth the effort. In the corner case where the reprojected tile boundaries are rectangular and straight, it would work. For all other cases you'd have to calculate perfectly aligning clip paths. And even if they align, you'll see the tile clip paths because of the antialiasing that you cannot turn off.

There are many tools out there for vector tile creation, and they do not take up much disk space. So I'd strongly recommend to create pbf vector tiles in the projection that you need. This will give you the best performance and visual appearance.

**Comment by kevinstadler** [comment]
I'm working on the rather unusual case of rendering in an orthographic projection *centered on whatever the current view is*, so reprojecting in advance is unfortunately not an option.

I'm still not sure I understand why non-straight boundaries (relative to the tile grid of the vector tile source) are a problem. Isn't it just a matter of reprojecting the view to vector tile coordinates, see which of the underlying tiles intersect with the projected view (which might not be a rectangle in this projection), and then load those tiles (reprojecting all features to the view projection on the fly)?

The rendering doesn't have to be high quality, so I think I can live with overlap. Maybe I'm misunderstanding something, but the same appears to work for raster tile reprojection: here's two example reprojections from OSM (Web Mercator) tiles done in the `reprojection-by-code` example, a polar-centered stereographic reprojection (obviously only works below 85° because of available tiles):
![openlayers](https://user-images.githubusercontent.com/7602414/28238297-f4c714d2-6950-11e7-8c10-7b01e322794f.png)
and an Albers conic:
![openlayers2](https://user-images.githubusercontent.com/7602414/28238530-343a00ca-6956-11e7-9fec-96e38b5cd589.png)
Neither of these should have tile boundaries parallel to the view though, so maybe I'm getting something wrong here...

**Comment by ahocevar** [comment]
The VectorTile renderer clips the original vector data to avoid overlaps. This is because geometries are not cut off at tile boundaries in the original data, but have an overlap. If you do not clip that at render time, you'll get problems whenever a geometry has a transparent style. The clipping is done by extent (strictly rectangular) here: https://github.com/openlayers/openlayers/blob/7739239e898f9a22da88979c9fe1a9ab7747728b/src/ol/renderer/canvas/vectortilelayer.js#L153-L154.

Maybe I don't get what you have in mind exactly, but to me it seems that adding support for reprojection of vector tile layers in a generic way (i.e. so it would work for all projections) would add a ton of code and complexity to the library.

That said, a shortcut you might be able to take for your application would be to use the rendered images (VectorImageTile) when the VectorTile layer's render mode is set to `image`. These could then be raster reprojected with what's already implemented.

**Comment by kevinstadler** [comment]
Yes I'm starting to grasp why vector tile reprojection support might not be a good idea as part of the library, so thanks a lot for your help of finding a workaround!

I might try out the approach you said -- do I understand correctly that I will need two `Map`s for this, one (invisible to the user) in which the vector tiles are rendered to same-projection images, and then a second one which has a reprojecting `TileImage` source hooked up to the `VectorImageTile`s created by the first map?

**Comment by ahocevar** [comment]
That would probably be the easiest way, yes.

**Comment by kevinstadler** [comment]
I've had a look at pursuing a different route, namely wrapping individual vector tiles in a `vector.Source` so that I can make use of the existing reprojection code there. However when I use code like:

      var reprojectingTileSource = new ol.source.Vector({
        format: new ol.format.MVT({
          featureClass: ol.Feature
        }),
        url: 'http://localhost/0.0.0.vector.pbf'
      })

      var map = new ol.Map({
        interactions: ol.interaction.defaults({
            dragAndDrop: false,
            keyboardPan: false,
            pointer: false,
            select: false
        }),
        layers: [
          new ol.layer.Vector({
            source: reprojectingTileSource,
            style: ...
            })
          })
        ],
        target: 'map',
        view: new ol.View({
          center: ...
          zoom: 1,
        })
      });
I end up with a tiny map that's rendered upside down. I understand that this is because the vector tile is in pixel coordinates (with origin at the top left) and does not have any projection info on it. Is there an easy way to transform the pixel coordinates to source projection coordinates immediately on loading? I would've assumed that there must be some code doing exactly this for proper VectorTile sources, but I can't seem to find any related transformations in either the `ol.(Vector)Tile`, `ol.source.(Vector)Tile` or `ol.layer.(Vector)Tile` classes...

**Comment by craigsnyders** [comment]
@kevinstadler I don't know of a library which does that off the top of my head, but by default the MVT tiling scheme uses mercator (EPSG:3857) and there are well known formulae to convert to and from lat/long and ZXY e.g. http://wiki.openstreetmap.org/wiki/Slippy_map_tilenames#ECMAScript_.28JavaScript.2FActionScript.2C_etc..29

Also check out https://github.com/mapbox/awesome-vector-tiles if you haven't come across it yet. 

You might have most luck with something like https://github.com/mapbox/vector-tile-js if you're trying to reproject incoming VectorTiles
