### ISSUE TITLE
Geometry crossing dateline disappears in wrapped view.

### ISSUE THREAD

**Issue by illogicz** [openlayers/openlayers#6088]
![ol-dateline-wrapx](https://cloud.githubusercontent.com/assets/731636/20094247/b1398282-a5a0-11e6-9435-23c2c7246be3.gif)

I unwrap the coordinates so that they extend past the -180, 180 range. Seems like an issue with checking geometry extents.

**Comment by illogicz** [comment]
![ol-dateline-wrapx-large-extent](https://cloud.githubusercontent.com/assets/731636/20095234/fdf8a78e-a5a4-11e6-95e3-c2984444b65a.gif)

Also some issues with geometry being clipped when extent gets large.

**Comment by ahocevar** [comment]
You should add a at the 0 meridian crossing to every segment that crosses it. Then everything should work as expected.

**Comment by illogicz** [comment]
Add a ... coordinate? I think you skipped a word. I tried adding a coordinate right at the crossing, but it makes no difference. It's a single feature, and the line is a single piece of geometry. The only solution I see at the moment is to split it up into multiple features / geometry. But this complicates things with interactions and more complicated polygon geometries that I also use.

What to do in this situation for example:
![ol-dateline-wrap-x-poly](https://cloud.githubusercontent.com/assets/731636/20101060/91dd3cce-a5c0-11e6-88cb-0eeea603d733.gif)

**Comment by ahocevar** [comment]
Sorry, I meant you have to split the geometry at the 180 meridian crossing. You can still have it in a single feature, but with a MultiLineString geometry.

**Comment by illogicz** [comment]
I'm a novice at the internals of the openlayers source, but I've partially fixed this by using the extent of the source instead the extent of the projection when calculating the wrapped replays inside the renderer composeFrame method. It seems to assume all geometry lies within the projection extent, which in my situation is not the case.  I have no idea what other consequences this might have.

**Comment by illogicz** [comment]
Here's my solution to all the issues I'm having, https://github.com/illogicz/ol3/commit/c87a8398b2446223ffb8dd24009dcbfae364dba1

**Comment by raiyni** [comment]
This bug is a little bit more extensive. 

Crossing the left dateline, if you are plotting points from <180 to >180, it hides the line. If you are plotting points >-180 to <-180, it doesn't hide line.

Crossing the right dateline, the issue is reversed. So you would be able to see the >180 plotted line. But not the <-180 plotted line.

Creating a multiline geometry with points at the meridians doesn't help. Nor does just adding the points. 

MultiLineString: https://codepen.io/anon/pen/EwgpPP?editors=1011
LineString: https://codepen.io/anon/pen/pWEZeM?editors=1011

Zoom in on the -180 meridian and the top line will disappear.
Zoom in on the +180 meridian and the bottom line will disappear. 

![Top then bottom](https://streamable.com/xkqv5)

if you convert the top line into a >-180 to <-180 line, it will show on the left meridian but not the right when you zoom in.

https://codepen.io/anon/pen/ZXpjjW?editors=1011

![Both](https://streamable.com/nremf)

**Comment by ahocevar** [comment]
@raiyni I had to revert your pull request, because it caused a severe regression.

Here is how you properly split your geometries at the 180 meridian: https://codepen.io/ahocevar/pen/gXJeqQ.

**Comment by raiyni** [comment]
Sure but that doesn't help with polygons and circles. What about adding an option to do look behinds and aheads defaulted to false?

**Comment by ahocevar** [comment]
Vector tiles do not have this issue, so you might want to consider using those.
