### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by romanzoller** [openlayers/openlayers#6152]
As far as I understand from the [website](https://openlayers.org/), the licensing of ol3 is:

> Code licensed under the 2-Clause BSD. All documentation CC BY 3.0.

But there are a bunch of other licenses in the [licenses subfolder](https://github.com/openlayers/ol3/tree/master/licenses) of the repo root. Can they be removed?

**Comment by bartvde** [comment]
I don't even recall what that 5 year old folder was for, so I'm inclined to say that it can go.

Anybody @openlayers/core remember?

**Comment by fredj** [comment]
It was a simple copy from ol2: https://github.com/openlayers/ol2/tree/master/licenses

+1 to remove

**Comment by genofire** [comment]
Could you open this issue again and fix `LICENSE.md` ?

**Comment by ahocevar** [comment]
@genofire What’s wrong with `LICENSE.md`?

**Comment by genofire** [comment]
There is not written, that this is a BSD License.


At the first look, github show it like a own created (maybe not opensource) license:
![a](https://user-images.githubusercontent.com/6905586/54122258-dbcd5f80-43fc-11e9-9c06-2b430bff8263.PNG)


Here a example, how it look, if it is correct formated:
![b](https://user-images.githubusercontent.com/6905586/54122279-ea1b7b80-43fc-11e9-8aa9-745d423be271.PNG)

**Comment by ahocevar** [comment]
This is because our license is closer to the [BSD-2-clause-FreeBSD](https://spdx.org/licenses/BSD-2-Clause-FreeBSD.html) license than the [BSD-2-clause](https://spdx.org/licenses/BSD-2-Clause.html) license. You are right that this is not ideal.

@tschaub @elemoine @bartvde Should we switch to a plain BSD-2-clause license? It would mean to get rid of the last paragraph:

*The views and conclusions contained in the software and documentation are those
of the authors and should not be interpreted as representing official policies,
either expressed or implied, of OpenLayers Contributors.*

I think it would be reasonable to remove that paragraph, and maybe add a code of conduct to the repository instead.

Opinions?

**Comment by bartvde** [comment]
I guess this is an artefact from the Metacarta days? I wouldn't be opposed to making the change, but would we need to get permission from all contributors?

**Comment by ahocevar** [comment]
Our [previous license change](https://github.com/openlayers/openlayers/commit/b6b11f560a377d18143ba2f14de6eb9e87d14ed8), wich removed the clause about patents, did not require permission from all contributors, as far as I remember. Maybe @crschmidt knows more?

**Comment by tschaub** [comment]
We did have a vote last time (see [the motion](https://lists.osgeo.org/pipermail/openlayers-dev/2011-May/007555.html) on the old dev list).  That was a vote to change what we had previously (MetaCarta's custom modified BSD) to the BSD 2-Clause License (also known as the FreeBSD License).

This doesn't change anything about what the project's license requires, permits, or prohibits, but I added "The 2-Clause BSD License" to the top of the `LICENSE.md` file in #9319 to clarify what license template the project uses.
