### ISSUE TITLE
VectorTile with CanvasPattern styling causes strange rendering

### ISSUE THREAD

**Issue by akkunchoi** [openlayers/openlayers#6210]
Hi, I want to use VectorTile with CanvasPattern styling.
But it causes to render strange.

Here is the code.
https://jsfiddle.net/akkunchoi/7ycfb739/

Thanks.

**Comment by ahocevar** [comment]
Bug confirmed. This is probably because the transform of the target canvas is reset in https://github.com/openlayers/ol3/blob/v3.19.1/src/ol/render/canvas/replay.js#L207. It is also reset in other places, which could cause problems as well.

That said, a pull request to replace these transform resets with transforms applied on top of the existing transform would be welcome.

**Comment by fredj** [comment]
fixed with #8210
