### ISSUE TITLE
forEachFeatureAtPixel strange behavior for VectorTile layer

### ISSUE THREAD

**Issue by drnextgis** [openlayers/openlayers#6254]
I've made two examples, in the [first](https://jsfiddle.net/_DR_/32b7b6dv/5/) hit detection works fine, but in [second](https://jsfiddle.net/_DR_/32b7b6dv/3/) example hit detection is broken. Try to click outside feature and  forEachFeatureAtPixel callback will be called.

**Comment by ahocevar** [comment]
Zoom level 40? This is a corner case, but what's happening is this: At zoom level 40, the tile for zoom level 22 will be rendered and scaled (because none is available for zoom level 40). For the hit detection, the circle will be much bigger than it is rendered on the map. You can see that when you configure the VectorTile layer with `renderMode: 'image'`.

To fix this, we'd need to make a distinction between render modes. When the replay is rendered to an image, the current code is correct. When the replay is rendered as vectors, we'd need to use the tile resolution instead of the view resolution.

If someone wants to work on a pull request, I'd be happy to review.
