### ISSUE TITLE
ol.feature.getExtent result when source is ol.source.VectorTile

### ISSUE THREAD

**Issue by aberenyi** [openlayers/openlayers#6321]
Given an `ol.layer.VectorTile` with an `ol.source.VectorTile` containing Polygon features. 
How could one get the projected centre coordinates (i.e. the centre of the extent) of a single feature (e.g. using `map.forEachFeatureAtPixel`)?  In other words how should one interpret the result of `feature.getExtent()` in such cases? What are those coordinates representing exactly?

[Demo](https://jsfiddle.net/aberenyi/b2dbm4tm/)

The documentation does not say much about this.

**Comment by ahocevar** [comment]
When the format uses`pixels` as units (which is the case for MVT tiles), the coordinates you get are not very useful outside the context of a style function, because they are pixels relative to the tile origin. If you really need to, you can convert them to projected coordinates with the known tile origin and pixel ratio.

What is your use case here, i.e. what do you want to use the extent's center for?

**Comment by aberenyi** [comment]
@ahocevar many thanks for the clarification, basically this is what I've suspected. 

The use case here is a dirt simple feature info tooltip/popup - at least for the time being.

**Comment by ahocevar** [comment]
@aberenyi Why do you need the extent's center for the tooltip/popup? I'd use the pointer position.

**Comment by aberenyi** [comment]
@ahocevar That was my initial thinking as well, however, the tooltip jumps around as you move the pointer which is not ideal for large polygons.

Of course using the extent's centre is not ideal either as it calculates the 'centre' of the partial polygon - that is displayed on the particular tile, not to mention the 'meta-tile' part - and not the whole feature which could be also misleading on high zoom levels.

**Comment by ahocevar** [comment]
I guess that depends on how you implement the positioning in the listener, but that's a separate discussion. Can we close this?

**Comment by aberenyi** [comment]
As I was working on this I might have found a documentation bug though - it looks like `node tasks/generate-info.js` does not include [ol.source.VectorTile#getTilePixelRatio](https://github.com/openlayers/openlayers/blob/master/src/ol/source/vectortile.js#L109) in the output. Should I open a separate issue for this?

**Comment by aberenyi** [comment]
I'd be interested to know what do you mean by that. Is it possible to get the whole feature using `map.forEachFeatureAtPixel`?

**Comment by ahocevar** [comment]
`ol.source.VectorTile#getTilePixelRatio` is not exportable, i.e. not part of the API. It isn't for other tile sources either. Since the vector tile source has the tile pixel ratio you configure on it, it should not be necessary to have a getter for it.

It is not possible to get the whole feature using `ol.Map#forEachFeatureAtPixel`. However, you can highlight the whole feature (using the style function) if each vector tile with that feature uses the same `id` for that feature. But I do not see how that would be related to a jumping tool tip if you position the tool tip at the pointer location.

**Comment by aberenyi** [comment]
`ol.source.VectorTile#getTilePixelRatio`: makes sense.

Don't worry too much about the tooltip, I have other ideas how to get around this.

I'm gonna close this, thanks again for your help.

**Comment by aberenyi** [comment]
Maybe it's worth mentioning that you cannot get the `getTilePixelRatio` value of a layer's source if you're using a custom or a minified build of `ol.js`.

**Comment by ahocevar** [comment]
> Maybe it's worth mentioning that you cannot get the getTilePixelRatio value of a layer's source if you're using a custom or a minified build of ol.js.

That's intentional - you're not supposed to use it at all because it's not part of the API.

**Comment by aberenyi** [comment]
Ah, okay, good to know.
