### ISSUE TITLE
v3.20.1 mouse click 

### ISSUE THREAD

**Issue by yzun** [openlayers/openlayers#6335]
there is a bug：when i click the map twice, the map will moved fellow my mouse move, and the console get an error 
![image](https://cloud.githubusercontent.com/assets/3615557/21756352/3eda76c4-d65b-11e6-915a-990da4be0a44.png)

**Comment by yzun** [comment]
otherwise, i try other version, only the v3.13.1 is not this problem

**Comment by ahocevar** [comment]
Can you provide a working JSFiddle or a link to an official example, along with information on which browser and device you are using, so others can reproduce the issue?

**Comment by DavidHequet** [comment]
I think this is because mouseclick start moving the map from this version, another strange behavior i noticed on simple click is that the view trigger a center change event

look at this jsfiddle:

Step to reproduce: 
1) Click on the map
2) change:center is called but center didn't change.

https://jsfiddle.net/qs7y5f8s/2/

Ps: didn't have this event handler with < 3.19.1
don't know about 3.20.0 , i jumped from 3.19.1 to 3.20.1

**Comment by probins** [comment]
the center change is definitely an issue, from 3.20. You can reproduce this on examples, such as simple example, and do `map.getView().on('change:center', function(evt){console.log(evt)})`, and single click fires event.

I can't reproduce the reported issue though.

**Comment by ahocevar** [comment]
I cannot reproduce the reported issue either.

**Comment by DavidHequet** [comment]
ps: my jsfiddle will not reproduce the reported issue, it just show the "change:center" event triggered by just clicking on the map:

With ol.3.19.1: click on map (without dragging) doesn't trigger changer:center event
https://jsfiddle.net/Lak07nwo/1/

With ol.3.20.1: click on map (without dragging) trigger changer:center event
https://jsfiddle.net/qs7y5f8s/2/

**Comment by ahocevar** [comment]
@DavidHequet Then maybe you should report the issue shown in your fiddle in a separate ticket? Also, what makes you think that the unconfirmed issue is caused by the one shown in your fiddle?
