### ISSUE TITLE
Raster Reprojection causes black lines in latest build

### ISSUE THREAD

**Issue by pksorensen** [openlayers/openlayers#6342]
Just noticed after upgraded our application to latest build that the reprojected layers are causing black lines.

It can also be seen in the official example: https://openlayers.org/en/master/examples/reprojection.html

Our users has not reported it before we upgraded, but I do not know at what release it was added. We upgraded from 3.16 to latest.

btw, what happened with ol3 group on google groups?

**Comment by ahocevar** [comment]
> It can also be seen in the official example: https://openlayers.org/en/master/examples/reprojection.html

Are you observing this in Chrome only? What you are seeing is probably related to #4123 and the fact that the issue mentioned there was "fixed" in Chrome. So this is not because of an OpenLayers update, but because of a Chrome update.

> btw, what happened with ol3 group on google groups?

It has been renamed to openlayers-dev@googlegroups.com. See https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/openlayers-dev/CS1RZnIBLnE/EALCP5DPDwAJ. However, note that group is not for usage questions anyway.

**Comment by pksorensen** [comment]
Thanks for finding the other issue, didnt find it by googling. 

Yes, i see it in chrome. I will close and continue my questions in the other issue.

**Comment by ahocevar** [comment]
Pull request created: #6344.

**Comment by pksorensen** [comment]
Awesome stuff :) I will buy you a beer if you visit copenhagen.

**Comment by hajjimurad** [comment]
It seems that this is not completely resoved. I use Zoomify as a source and I still see the gray lines for the non-square tiles the layer (For normal, i.e. square tiles it's no longer an issue)

You can see it here http://jsfiddle.net/sk5cLj4n/42/
And also the screenshot: https://screenpresso.com/=z5ANc
