### ISSUE TITLE
Add a "scale" control from OL2 

### ISSUE THREAD

**Issue by tbarsballe** [openlayers/openlayers#6409]
Open Layers 2 had a rather useful `OpenLayers.Control.Scale()` control, that would display the current "scale" relative to the projection bounds / zoom level.

Such a control would also be useful in OL3.
Likewise, a control that showed the current zoom level would also be useful.

I have a sample implementation that I have put together for GeoServer [here](https://github.com/tbarsballe/geoserver/blob/705e7cb22ed58e6359ac6963c7b5446d9b664901/src/web/wms/src/main/resources/org/geoserver/wms/web/data/ol-load.ftl) (based on [this](https://github.com/boundlessgeo/composer/blob/master/app/components/editor/olmap/olmap.js#L150) implementation in Boundless Composer), and would be interested in tidying this up and contributing it to OpenLayers.

**Comment by raiyni** [comment]
there already is one?

https://openlayers.org/workshop/en/controls/scaleline.html

**Comment by tbarsballe** [comment]
That control gives a scale line which represents a distance on the map.

This is rather different from the `OpenLayers.Control.Scale()` control, which shows the map scale as a ratio: http://wiki.openstreetmap.org/wiki/Zoom_levels

Note that OL2 did have a ScaleLine control separate from the scale control.

**Comment by ahocevar** [comment]
Hey @tbarsballe, thanks for considering a pull request. Since the concept of scale is questionable in a web map (because of unknown dpi), I think we'd gladly accept an example pull request that shows how to display the scale (and zoom level), but be hesitant to make an `ol.control.Scale` part of the library..

**Comment by sebalaini** [comment]
we are migrating from OL2 to OL4 and we also used Scale to create the tile in the Mapserver and have performed imgs to load but now we have switched to Resolution.
It's really different OL4 to OL2 and requires a lot of work to migrate.

**Comment by nboisteault** [comment]
@ahocevar : So if the concept of scale is questionable in a web map, does that mean that scaleline might display incorect values ?

**Comment by ahocevar** [comment]
@nboisteault Yes and no. The concept of scale (as in 1 : 2000) on a web map is questionable because of the unknown display resolution. A scale line does not have this problem. But depending on the projection, it has another problem: the scale may be completely different in the center of the map and in the corners. The scale line shows the scale for the center of the map. This is the thing to keep in mind.

**Comment by nboisteault** [comment]
@ahocevar Thank you for your explanation. What I don't understand is why it is impossible to calculate correctly the scale but possible to display a correct scale line (correct for the center) whereas the display resolution is unknown.
In this screenshot, how OL knows it has to display a `div` with `width: 144px;` for 500 m.

![image](https://user-images.githubusercontent.com/2145040/49158251-000ba180-f322-11e8-923e-c24b4ffdece1.png)

**Comment by nboisteault** [comment]
To get the scale we would need to know how 144px are physically represented on the screen and we can't know in javascript... Did I understand correctly ?
