### ISSUE TITLE
Raster Reprojection causes grey lines for non-square tiles

### ISSUE THREAD

**Issue by hajjimurad** [openlayers/openlayers#6527]
The issue I'm talking about is partly resolved here https://github.com/openlayers/openlayers/issues/6342
But I still see the gray lines for the non-square tiles the layer (for normal ones, i.e. square tiles it's no longer an issue)

You can see it here http://jsfiddle.net/sk5cLj4n/42/
And also the screenshot: https://screenpresso.com/=z5ANc
(OpenLayers v4.0.0)

**Comment by ahocevar** [comment]
Your tiles have a tile size of 256x256 pixels. So they are square. Am I missing something?

**Comment by ahocevar** [comment]
Ah, I see what you mean. The edge tiles show this problem when they are not square.

**Comment by hajjimurad** [comment]
Yes, exactly. Is there any temporary workaround for that?

**Comment by ahocevar** [comment]
@petrsloup, do you have an idea or an advice?

**Comment by petrsloup** [comment]
I'm not sure at the moment (the jsfiddle linked above does not work anymore unfortunately).

@hajjimurad You can try settings different tilegrid using https://openlayers.org/en/latest/apidoc/ol.source.TileImage.html#setTileGridForProjection, but I'm not sure it will help.

The problem is (probably) that the browsers do the edge antialiasing differently for angles different than 45° (which is the case for the square tiles) so the two neighboring triangles do not stitch seamlessly anymore.

**Comment by hajjimurad** [comment]
@petrsloup, sorry, now jsfiddle is restored. You can access it here http://jsfiddle.net/sk5cLj4n/42/
I'll check what I can do with tilegrid, but any other ideas are also appreciated
