### ISSUE TITLE
Support tile loading priority for different layer

### ISSUE THREAD

**Issue by exotfboy** [openlayers/openlayers#6585]
Hi:

Suppose there are two layers A and B, both are `WMTS` layer.

Is it possible to make sure that the tiles for `B` is always requested before that for `A`  without changing their z-index?

**Comment by ahocevar** [comment]
Tiles are only prioritized using their distance from their pointer focus and zoom level. Tiles from layers are requested by iterating backwards through the layers collection. So if you want the loading order to be different from the top-to-bottom visibility of layers, you need to use z-index to define the visible layer order.

**Comment by banaari** [comment]
I have a use case where the load priority needs to be made explicit.
We have X number of data layers sourced locally, overlaid over the top of various 3rd party providers.
Problems with any of the 3rd party infrastructure can render the application unusable as the less-important background tiles max out the number of available parallel requests.

**Comment by ahocevar** [comment]
You can achieve this with a custom `tileLoadFunction`, by adding a timeout or custom error handling. So to give a tile a maximum of 500 ms to load, you could do something like this:
```js
new XYZSource({
  // ...
  tileLoadFunction(imageTile, src) {
    const image = imageTile.getImage();
    const timer = setTimeout(() => {
      imageTile.setState(TileState.ERROR)
    }, 500);
    image.addEventListener('load', () => clearTimeout(timer));
    image.addEventListener('error', () => clearTimeout(timer));
    image.src = src;
  };
});

**Comment by banaari** [comment]
Thank you! Gives me some options to pursue :)

**Comment by domiSchenk** [comment]
@ahocevar 
I Just have the same problem.
We are using a WMTS (swisstopo) for background and on top we show a TileWMS. Unfortunately the WMS isn't the fastest, and the requests takes some time.

would there be a way to solve this?

**Comment by ahocevar** [comment]
@domiSchenk You could switch from TileWMS to ImageWMS, or configure the tileWMS with a bigger `tileSize` (e.g. `512`. If you do the former, loading of the WMS images will be decoupled from the tile queue. If the latter does not improve the situation, you can increase the queue size by configuring the map with something like `maxTilesLoading: 64`. The default value is 16, so with 64 your WMS should not cause tile queue congestions any more.

**Comment by domiSchenk** [comment]
well i already change to 512 :-D
but forgot about maxTilesLoading, will try it out.

**Comment by alinscodes** [comment]
Is there a way to do this?
I have a map and then some third party layer, I want every time for the map to load first, before the third party layer.

**Comment by sebakerckhof** [comment]
I also stumbled upon this.
Here's a couple of different ways to approach this:

1. In case you're dealing with only tile layers, what you could do is override the getTilePriority function of the map, so something like:
```
class CustomMap extends Map {
  getTilePriority(tile, tileSourceKey, tileCenter, tileResolution) {
    ...Calculate the priority
  }
}
```

The ugly part is that you'll probably will need to inspect the private `src_` on the tile to know which layer it's from.

2. As mentioned in  https://github.com/openlayers/openlayers/issues/6585#issuecomment-287031054 changing the z-index will also do it, but obviously this isn't always possible since it also changes the view

3. As mentioned in https://github.com/openlayers/openlayers/issues/6585#issuecomment-884877768 , you could use a custom load function that re-enqueues all the requests in a different order. If you then put `maxTilesLoading` to a very large number, you're effectively ignoring the original priority.
