### ISSUE TITLE
empty areas on map when reprojecting OSM  - when cache is full ?

### ISSUE THREAD

**Issue by KlemenSpruk** [openlayers/openlayers#6590]
When zooming in panning the map areas without image appear.
Layer on the map is OSM reprojected to WGS84.

tileCache isnt default value 2048 but 16. This also happens if tileCache value is default

Maybe related to #4594

Example:
https://codepen.io/klemensp/pen/ryzENR?&editors=1010

![image](https://cloud.githubusercontent.com/assets/8971677/23941330/b21da5f8-0968-11e7-8056-c414c64f5d49.png)

![image](https://cloud.githubusercontent.com/assets/8971677/23941341/bc038e48-0968-11e7-9fb2-81bee353b913.png)

**Comment by ahocevar** [comment]
There is a general problem with small tile caches. See #4961. Closing this as duplicate.

**Comment by KlemenSpruk** [comment]
Hello!

Also with default tileCache size setting the same thing happens:

![image](https://user-images.githubusercontent.com/8971677/28775314-89ed65fa-75f1-11e7-9561-853138ce7dc4.png)

Any advice?

**Comment by ahocevar** [comment]
Strange. @petrsloup, do you have an idea? Layers without reprojection work fine with small or zero cache sizes in the latest release, so I suspect this must really be related to the reprojection code.

**Comment by eagerWolf** [comment]
@ahocevar we (@KlemenSpruk) have done some test and hacks and those are results:

First we determinate layer cache size for all reprojected XYZ layers and if is used more than 80% we add custom parameter to url using setTileUrlFunction and in next tick we reset layer source by simply doing:

`layerSource.setTileLoadFunction(layerSource.getTileLoadFunction());`

By that we ensure than cache size is reset to 0 and that new parameter is not added for each request after this one.

Of course this is an ugly solution but after short test I can confirm now this is working. We have set cache size to 128 but if smaller value is used than problem still occurs. @KlemenSpruk will do some additional tests and also provide details.

**Comment by KlemenSpruk** [comment]
Hello!

Currently we use solution which eagerWolf mentioned above we only inreased cacheSIze to 4096 so that cache does not get cleared so often.

**Comment by ahocevar** [comment]
Interesting workaround. Thanks for reporting back. I'll leave this open, because the underlying issue still needs to be investigated.

**Comment by petrsloup** [comment]
I think I tracked down the issue to `ol.source.TileImage#expireCache`. 
The method correctly expires the reprojected tiles, but it also expires the underlying, original, unreprojected tiles, ***but*** there is no information about which tiles are still being used:
https://github.com/openlayers/openlayers/blob/d19dfa077526b3653ee20966d3c43232db22bc31/src/ol/source/tileimage.js#L117

Therefore, I think it's possible (especially with smaller caches) that the `ol.reproj.Tile` instance waits for all the original tiles to load, but some of them are expired before the rest loads (since there is no mechanism to ensure these are not freed until reprojected).

Not sure how to fix this though...
