### ISSUE TITLE
Vector tile load labels from pbf file

### ISSUE THREAD

**Issue by cmortazavi** [openlayers/openlayers#6645]
It seems like ArcGIS allows for loading labels from pbf.  Normally located as
 resources\fonts\{font}\{range}.pbf

It would be helpful if Openlayers could consume these files and use them to display labels.  it would help with conflict detection among labels.

Thanks,
Cameron

**Comment by ahocevar** [comment]
These files do not contain labels, only fonts. Since OpenLayers uses TrueType fonts instead of glyphs, it does not make sense to load them.

If you want to support automatic loading of fonts, and use styles from Maobox Style objects in general, you may want to try https://npmjs.com/package/ol-mapbox-style.
