### ISSUE TITLE
Clicking on a vertex of a polygon when selecting, adds a Point to the Select interaction's feature collection (and draws it on the map) even though there was never a Point in the vector layer.

### ISSUE THREAD

**Issue by elimau** [openlayers/openlayers#6646]
This problem arrises when you have a map with just polygons and you are trying to select multiple polygons by using shift key. If you click on a vertex of a polygon, then that creates a new 'Point' geometry which gets added to the select interaction's feature collection.

Here is a screen recording to demonstrate the problem.
https://drive.google.com/open?id=0B9k0vBBhbpeHdDZjT01yQW42UFk

You will notice in the video's console log, that a 'Point' gets added to the 'selectedFeatures' collection. Also you can see the Point visible on the map (see 00:17 mark of the video).

The demo code I used to create the problem and with the debugging console logs is found here. 
https://embed.plnkr.co/bLzRvXvOeW6hHC2jsaX1/

Adding the Point to the selected feature collection is very unexpected and is buggy/incorrect behaviour because there was never a Point in the vector layer.
Thanks.

**Comment by ahocevar** [comment]
Looks like a bug in `ol.interaction.Modify`.

**Comment by SoroTrestal** [comment]
Hello, any idea when this bug is going to be fixed?

Thank you

Regards

**Comment by elimau** [comment]
Here is a workaround which we used:
```
ol.structs.RBush.prototype.update = function update(extent, value) {
  const item = this.items_[ol.getUid(value)] || {};  // <- add default Object when undefined
  const bbox = [item.minX, item.minY, item.maxX, item.maxY];

  if (!ol.extent.equals(bbox, extent)) {
    this.remove(value);
    this.insert(extent, value);
  }
};
```

**Comment by senritsu** [comment]
Can confirm that this is still an issue.

It happens specifically when using shift-selection on any part of a currently selected geometry when having the Modify interaction enabled. In this case the cursor is always over the Modify "preview" point, and is apparently not filtered out from the valid selection objects.

According to the docs for the Select interaction with regard to the `layers` option:
>  If the option is absent, all visible layers will be considered selectable.

This, paired with the change a while back that overlays and regular vector layers were unified, may have lead to the "overlay" point from the Modify interaction being considered a "normal" point on the map.

Since [`forEachFeatureAtCoordinate`](https://github.com/openlayers/openlayers/blob/6e3d3d4877f586a5b39b01018a4627e479a1d997/src/ol/renderer/Map.js#L102)  which is used internally from `forEachFeatureAtPixel` gets the layer list from the renderer `frameState`, it stands to reason that it does not care (or check) if the layer is actually bound to the map or unbound (an overlay).

One solution might be to specifically exclude unbound layers from selection via a default layer filter, but (especially when using custom layer filters) this gets a bit problematic, since it is not possible to guess if the user may actually want overlays to be considered as selectable. It is also hard to just generally check for layers associated with interactions, because custom interactions are a thing and it gets muddy real fast to determine what should actually be selectable and what shouldn't be.

**Comment by senritsu** [comment]
I should add that the easy workaround is just using a layer filter via the `layers` option for the Select interaction.

For the linked demo project (since i can't figure out how to fork it):
`layers: x => x.get('isCustomLayer'),` for the interaction constructor and `vectorLayer[i].set('isCustomLayer', true);` for each created layer further down solves the problem.

**Comment by Osmiogrzesznik** [comment]
I can confirm that this is still occurrence that confused me and maybe an intuitive solution would be  to create unselectable overlay
