### ISSUE TITLE
"Icon Colors" example is not working

### ISSUE THREAD

**Issue by mathiasleroy** [openlayers/openlayers#6652]
When you go to https://openlayers.org/en/latest/examples/icon-color.html
and click on codepen you don't see any of the 3 dots (using latest Chrome 56)

When you comment the `color` property if the icon it works :  
cf. https://codepen.io/Tardigrad/pen/ryqXrj?&editors=1110

    london.setStyle(new ol.style.Style({
      image: new ol.style.Icon(/** @type {olx.style.IconOptions} */ ({
        // color: '#4271AE',
        src: 'https://openlayers.org/en/v4.0.1/examples/data/dot.png'
      }))
    }));

![image 3](https://cloud.githubusercontent.com/assets/2870437/24458029/1430bdd6-1498-11e7-987f-f163cc63c6c8.png)

**Comment by ahocevar** [comment]
This is because when you edit the example in a codepen, the icon does not come from the same origin any more. To fix this, you need to configure the `ol.style.Icon` with `crossOrigin: 'anonymous'`. See https://codepen.io/anon/pen/bqQddd?&editors=1110 for an updated, working codepen.

We'd accept a pull request that adds `crossOrigin: 'anonymous'` to the example source, so it works in a codepen out of the box.

**Comment by fredj** [comment]
`crossOrigin: 'anonymous'` should also be added to the icon-negative example
