### ISSUE TITLE
Documentation for zIndex in regards to ol.layer.Group needs clarification

### ISSUE THREAD

**Issue by PatchesMaps** [openlayers/openlayers#6654]
It is unclear in the documentation as to how `zIndex` is handled when rendering `ol.layer.Group` objects with sub layers.

After digging into the source code a little, it appears to me that [`zIndex` set on the parent layer (`ol.layer.Group`) will not be inherited by the child layer](https://github.com/openlayers/openlayers/blob/ac84e560bc4a2b7e0e37cf306decf0e676a9cf05/src/ol/layer/group.js#L208).  So if no `zIndex` is set on the child layers, their `zIndex` will default to zero (even if the parent layer has a `zIndex` set to 100) and any non-group layer that is added to the map with a non-zero `zIndex` will be rendered in front of them.  Is `zIndex` on `ol.layer.Group` ever respected in the rendering context?  If so can we clarify how it interacts with the child layers and other layers on the map?

https://jsfiddle.net/wajxb9eb/1/

**Comment by ahocevar** [comment]
I think the current behavior is unexpected. Layers should inherit `zIndex` from their parent, unless a `zIndex` is already set on the layer.

Are you willing to create a pull request?

**Comment by Patchez** [comment]
Sure, I can see what I can do.

**Comment by Patchez** [comment]
@ahocevar Do you have any input on this PR?

**Comment by bryantevans00** [comment]
Could this be reopened as the issue is still present?

@ahocevar:
> I think the current behavior is unexpected. Layers should inherit zIndex from their parent, unless a zIndex is already set on the layer.

Another way to think about nested z-indices would be to consider layer groups with z-index set to act like [DOM stacking contexts][1]: if a layer group has a set z-index, then the z-indices of its children would only have an effect to the relative ordering of the group layers. That way layer groups could act as an useful mechanism to enforce a specific z-index for multiple layers at once while still having the ability to control the stacking of the group contents. What do you think?

[1]: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context
