### ISSUE TITLE
Stroke composition issue

### ISSUE THREAD

**Issue by fredj** [openlayers/openlayers#6679]
See https://codepen.io/anon/pen/vxqNKp

The color composition at the crossing of the two lines is incorrect; the two opacity must add up.

**Comment by tschaub** [comment]
We stroke only once for many lines (paths) as a rendering optimization.  It would be good to quantify the benefit of this.  And if it is significant, we could provide an option that lets users opt in or out (depending on what we decide should be the default behavior).

**Comment by fredj** [comment]
The problem is in `ol.render.canvas.LineStringReplay`: a `stroke` instruction is added only if the stroke style has changed:
https://github.com/openlayers/openlayers/blob/v4.1.1/src/ol/render/canvas/linestringreplay.js#L118-L124

**Comment by crisley2016** [comment]
We rely on the current stroke "behavior", but I can see how the behavior could be considered a bug.  If you have multiple lines all with the same (color, opacity) and you want to see the overlap you cannot.  Also, if you have multiple linestrings on the same layer with different sets of (colors, opacities), depending on the order of the features you will see different results.

See https://codepen.io/anon/pen/jwbeZB

Perhaps the documentation should be updated to explain the behavior.  In order to take advantage of the current behavior in a consistent manor, a client who is using multiple colors and opacities must ensure the order the linestrings are drawn in is consistent.
