### ISSUE TITLE
Street name isn't rendered correctly on Bing Maps of OpenLayers

### ISSUE THREAD

**Issue by jengeb** [openlayers/openlayers#6708]
The street name 'Goethestraße' (52.51623 13.51613) is not rendered correctly on Bing Maps (Göthestraße) of [OpenLayers](https://openlayers.org/en/latest/examples/bing-maps.html).

![](https://i.stack.imgur.com/ijmVz.png)

Does OpenLayers point to the correct data? Because Bing Maps shows the proper street name:

![](https://i.stack.imgur.com/91VbX.png)

**Comment by ahocevar** [comment]
Have you tried to configure your `ol.source.BingMaps` with `imagerySet: ''RoadOnDemand'`?

Next time, please don't ask on [Stack Overflow](http://stackoverflow.com/questions/43286704/openlayers-with-bing-maps-where-does-the-data-come-from/43289119?noredirect=1#comment73728801_43289119) and here, especially not since you got an answer there already. Just ask on Stack Overflow, unless you have really found a bug in OpenLayers.
