### ISSUE TITLE
Option for adjusting move distance tolerance

### ISSUE THREAD

**Issue by itjope** [openlayers/openlayers#6831]
If a users pan the map when clicking the click will be parsed as a move instead of a click. A group of our mobile users have problem with clicking on the map without triggering a move. Our suggested solution is to make the `moveTolerance` variable in `ol.MapBrowserEventHandler` configurable via a `moveTolerance` option in `ol.Map`.

Proposed implementation:
https://github.com/notnotse/openlayers/tree/move-tolerance-option

**Comment by fredj** [comment]
is it related to #6776 ?

**Comment by nagytech** [comment]
It is the same issue, however Jonas has provided a means for configuring the move tolerance instead of relying simply on the device pixel ratio.

@itjope Can you read through the [developer guidelines](https://github.com/openlayers/openlayers/blob/master/CONTRIBUTING.md) for creating a pull request?

**Comment by itjope** [comment]
@nagytech I have read the guidlines and created a pull request here https://github.com/openlayers/openlayers/pull/6834
