### ISSUE TITLE
ol.render.toContext returns an error when applying an Icon

### ISSUE THREAD

**Issue by tomhuntley** [openlayers/openlayers#7092]
I cannot apply an Icon image to the canvas when using ol.render.toContext:

https://codepen.io/huntleth/pen/WEpYWR

This returns the error: 

```
Uncaught TypeError: Cannot read property '0' of null
    at ol.render.canvas.Immediate.setImageStyle (VM2559 ol-debug.js:23157)
```
- [x] I have searched GitHub to see if a similar bug or feature request has already been reported.
- [x] If reporting a bug, I have tried with the latest version of OpenLayers (see 'LATEST' on https://openlayers.org/)
- [x] If reporting a bug, I have created a [CodePen](https://codepen.io) or prepared a stack trace (using the latest version and unminified code, so e.g. `ol-debug.js`, not `ol.js`) that shows the issue.

**Comment by ahocevar** [comment]
The problem with your CodePen is that the Immediate API renders immediately, so the image whose `src` you specified is not yet loaded. To get the code working, you need to configure the `ol.style.Icon` with an `img` and `imgSize` instead of an `src`. See updated CodePen: https://codepen.io/ahocevar/pen/jLmWwY.

We'd accept a documentation improvement pull request that makes this clear in the API docs.
