### ISSUE TITLE
EPSG-3826 to Polar Stereographic re-projection does not work with OL4 

### ISSUE THREAD

**Issue by inaki-ortizdelandaluce** [openlayers/openlayers#7115]
Hi,
I have a code performing client-side re-projection from EPSG-3826 to polar stereographic working with OL3 (3.4.0) and wanted to migrate to the latest OL4 (version 4.2.0) but it is not working. Unfortunately I do not see any error message in the Javascript console.

Please find attached both samples, the one working is called antartic_ol3.html

[antartic_ol3.txt](https://github.com/openlayers/openlayers/files/1219780/antartic_ol3.txt)
[antartic_ol4.txt](https://github.com/openlayers/openlayers/files/1219781/antartic_ol4.txt)

UPDATE: I have checked and the issue seems to be there since version 3.6.0, so doesn't seem something specific to OL4 as such.

**Comment by ahocevar** [comment]
Does it work when you use v2.4.4 of proj4 instead of v2.4.3, and OpenLayers v4.3.0 instead of v4.2.0?

**Comment by inaki-ortizdelandaluce** [comment]
No, it doesn't same code but replacing OpenLayers to 4.3.0 and proj4 to 2.4.4 shows a blank screen (see attachment)
<img width="1440" alt="screen shot 2017-08-15 at 00 07 00" src="https://user-images.githubusercontent.com/9471654/29294076-db4573f4-814d-11e7-845b-b3df5ecea8d9.png">

**Comment by ahocevar** [comment]
OpenLayers v3.4.0 did not have raster reprojection, and ignored the `projection` configuration in the source. This means that the image was requested from GeoServer in the view projection. Whereas in OpenLayers v4.x, the images are requested in EPSG:4326, and OpenLayers tries to raster reproject. Which fails, because your extent configuration is wrong. So either remove the `projection: 'EPSG:4326'` line, or the `projection.setExtent(extent)` line. If you do the former, images from the WMS will be requested in the view projection (which is what you have in OpenLayers v3.4.0). If you do the latter, OpenLayers will raster-reproject data that comes from the WMS in `EPSG:4326`.

**Comment by inaki-ortizdelandaluce** [comment]
Dear Andreas,
Many thanks for your prompt and detailed response. Unfortuntalely, your former suggestion (remove source projection from WMS) does not work. The later it does but I would like to apply an extent of -45 to -90 longitude degrees rather than a bounding box. Is there any mean to apply such extent in the View itself?
Many thanks in advance
