### ISSUE TITLE
Hello! When I use cluster layer, I add a style with image and text. Image‘s behavior is good, but text's not. Text's zIndex is higher than image and it'll cover other featuer. 

### ISSUE THREAD

**Issue by dupeiduo** [openlayers/openlayers#7177]
That's what it looks like.
![image](https://user-images.githubusercontent.com/15188363/29647869-fabe0774-88bd-11e7-9d7c-bf74e5dc6b99.png)

I am trying to add zIndex prop to the style, then the blue circle image will cover too. That is not what I want.

![image](https://user-images.githubusercontent.com/15188363/29647974-946466ac-88be-11e7-9246-958106e5d538.png)

I have already given zIndex to the layer. I hope the text and blue circle image will under the picture which zIndex is higher than the cluster layer below.

**Comment by ahocevar** [comment]
Please use Stack Overflow for usage questions. This has been asked and answered before: https://stackoverflow.com/questions/30332948/openlayers-3-image-and-text-style-zindex.

**Comment by dupeiduo** [comment]
@ahocevar  Oh, I know that. The condition is different. My layer is cluster.

**Comment by dupeiduo** [comment]
@ahocevar Simple layer behaves well, but cluster layer not.

**Comment by dupeiduo** [comment]
@ahocevar  I'm sorry,  my English is poor. I do not know if I have made it clear.

**Comment by ahocevar** [comment]
Anyway, Stack Overflow is the place for usage questions.

**Comment by peteresteris** [comment]
This time I think this is the right place because it seems more a behaivor than a programmer mistake.
I have the same trouble with an icon feature and a circle feature with text. I use declutter true and each style has its own z-index.
When I use text, when icon passed through text is hidden but when I removed text from the style, the behaivor is as I expected.
