### ISSUE TITLE
Map freezing with iOS 11 on ipad mini

### ISSUE THREAD

**Issue by alallo** [openlayers/openlayers#7202]
I was testing an app on iOS11 beta and noticed some performance issues with rotation. Then I tried some websites that are using opnelayers and most of the time the maps are freezing as soon as there is an interaction (zoom in, rotate).

Here is an example: https://wow.metoffice.gov.uk/

So I'm just wondering if there is an issue with the new version of iOS.

Thanks,
Alessandro

**Comment by ahocevar** [comment]
Performance issues with rotated maps were an issue in old versions of OpenLayers, because of canvas sizes that were too big. I'd recommend you try and see if things improve with the latest version.

**Comment by alallo** [comment]
Just tried with the official examples and is doing the same (map freezing)

this for example https://openlayers.org/en/latest/examples/drag-rotate-and-zoom.html

**Comment by ahocevar** [comment]
Thanks for testing. Maybe there is an issue with iOS11 Safari indeed. Can you ticket the problem there?

**Comment by alallo** [comment]
I will try to update another device to iOS 11 beta first just to make sure is not a device related issue

**Comment by alallo** [comment]
After updating to the latest version of iOS (11 beta 8) the main problem with map freezing is now solved.

There are still some issue with the map rotation and performance after rotating but it looks very specific to clusters. Example: https://openlayers.org/en/latest/examples/cluster.html

**Comment by ogo-adp** [comment]
Humm, just checked with an ipad air 2 with IOS 11 final, and the freeze is there (visible on official samples on then openlayers website). You can pan and pinch-zoom for something like one second and after that you can't anymore. There is no crash it seems. Sometimes it works again after a few seconds, but freezz again.

**Comment by matthewladams** [comment]
I'm seeing this on iOS 11 GM with an iPhone 6S. Not always, but often, the map will stop responding to drags or pinch to zoom. Double tap to zoom and controls still work. Happens in Safari, Chrome and a webview.

**Comment by ogo-adp** [comment]
Same here on IOS 11 final. Some devices do it for a few sessions (ipad air 2), and then magically work forever and some others (like iphone 6s) will never work. Happen on samples on openlayers web site and in our app.
It could very well be an ios bug, I will try to investigate this further.

**Comment by ogo-adp** [comment]
I investigated and could understand the problem.

This codepen show where the problem is (and gives a fix) : https://codepen.io/anon/pen/qPNwBy?editors=0011

In IOS11, in ol.interaction.Pointer.prototype.updateTrackedPointers_, the code "if (event.pointerId in this.trackedPointers_)" does not always work when pointerId is negative. In my understanding it is valid to access properties of an object with negative integer property names, but safari does not like that (I think it is a bug in safari). Simply transforming pointerId in a string in this function will make the code work again.

In the code pen alternating the two lines "works" and "don't work" will repro or fix the problem ...

**Comment by RobertSmart** [comment]
I've been seeing this exact thing as well and can confirm that this fix, does indeed seem to fix it.

**Comment by ogo-adp** [comment]
Thanks for testing @RobertSmart 

After further research this is clearly an IOS bug. Sometimes, Safari loose the content of updateTrackedPointers (!). For the fix it is sufficient to make pointerId positive or change it to a string to make it work again. 

I've been unable to repro the problem in a simple js test to submit this to apple ... Not sure I will be able to attract their attention with the codepen because it does involve a large codebase (and they will ask for a simple repro I can't provide).

@ahocevar could it be possible to include a patch with a fix in OL ? The fix is very simple (make pointerId positive or convert it to string) and will not have any impact on performance ?

**Comment by RobertSmart** [comment]
By the way, this was tested on an Ipad Air 2 running latest iOS 11

**Comment by tschaub** [comment]
Thanks for the help on this.  I've created @7285 with the fix suggested by @ogo-adp.  Please comment there if you are able to confirm whether this addresses the issue.

**Comment by wayofthefuture** [comment]
We have dozens of users experiencing the problem. Checking 7285...

**Comment by tschaub** [comment]
Please reopen if #7285 doesn't fix the issue.

**Comment by ogo-adp** [comment]
@tschaub Thanks for including the fix :) Would it be possible to make an official 4.3.4 build including the fix ?

Just as a sidenote for this ios bug. It does only happen when pointerId is negative. Some devices don't have the bug just because for them the pointerId is positive not negative. If you restart your device, pointerId will be positive, and after some time it will possibly become negative then triggerring the bug. IOS 10.3 does not have the bug with negative pointerId (I didn't check if ios 10.3 generates negative pointerId however) ...

**Comment by tschaub** [comment]
The [`ol@4.3.4`](https://www.npmjs.com/package/ol) release is out with the fix.

**Comment by ogo-adp** [comment]
Thanks @tschaub , what a relief for our ios11 users

**Comment by alallo** [comment]
Hi guys,

thanks for releasing the fix so quickly. Unfortunately this will not fix the original issue I reported. 
If you open this [Cluster example](https://openlayers.org/en/latest/examples/cluster.html) in an iPad with iOS 11 you can see a performance issue. Try to:

1 - Rotate the map
2 - Move the map to the right (or to the left)

The map will move very slowly making it almost unusable. If you try with a map without clusters everything is working well.

Any thought on this? 

Thank you

**Comment by tschaub** [comment]
@alallo - it looks like there were multiple issues.  Could you please open a new ticket that is specific to the cluster example on iOS 11?  Perhaps this was your original issue, but it got conflated.

**Comment by kmurph92** [comment]
I can further confirm the fix in @ogo-adp codepen worked. Thanks much!

**Comment by aleksandrmelnyk** [comment]
OL 4.6.5, IOS 11.3.1 Ipad Mini. Touch interactions almost not working:
1. any two finger guesture causes zoom in, zoom out not working
2. rotation not working
3. click/touch event fires even if I do 2-finfer gesture.

**Comment by aleksandrmelnyk** [comment]
4. also panning not working
