### ISSUE TITLE
Move getType() from geometry subclasses to ol.geom.Geometry in API docs

### ISSUE THREAD

**Issue by TDesjardins** [openlayers/openlayers#7226]
To improve the API the function getType() from geometry subclasses  should be "moved" to ol.geom.Geometry. The subclasses could then override it.

See for example:

[ol.geom.Point.getType()](http://openlayers.org/en/latest/apidoc/ol.geom.Point.html#getType)
[ol.geom.Polygon.getType()](http://openlayers.org/en/latest/apidoc/ol.geom.Polygon.html#getType)

- [x ] I have searched GitHub to see if a similar bug or feature request has already been reported.
- [x ] If reporting a bug, I have tried with the latest version of OpenLayers (see 'LATEST' on https://openlayers.org/)

**Comment by ahocevar** [comment]
Not sure what you mean, because this it the case already. The abstract method is defined in [ol.geom.Geometry](https://github.com/openlayers/openlayers/blob/4b4f383043d8426eddef177f2a83b1d4cbc62a94/src/ol/geom/geometry.js#L202-L207), and subclasses implement with the correct type, e.g. [ol.geom.Point](https://github.com/openlayers/openlayers/blob/4b4f383043d8426eddef177f2a83b1d4cbc62a94/src/ol/geom/point.js#L82-L88).

**Comment by TDesjardins** [comment]
Ok, I see. Then this issue is related to the API docs:

See: http://openlayers.org/en/latest/apidoc/ol.geom.Geometry.html
and http://openlayers.org/en/latest/apidoc/ol.geom.Point.html#getType

There you can't see the inheritance.

**Comment by ahocevar** [comment]
That's because `ol.geom.Geometry` does not make `#getType()` exportable, because it is an abstract method, and the abstract `ol.geom.SimpleGeometry` class does not implement it. May I ask why knowing about the inheritance would be important here?

**Comment by TDesjardins** [comment]
Yes, I am using the API docs to implement the typesafe OL Java wrapper [gwt-ol3](https://github.com/TDesjardins/gwt-ol3). It is a little bit confusing when looking to the API. Because on most methods you have the info that they are inherited (for example [ol.geom.Geometry.html#get](http://openlayers.org/en/latest/apidoc/ol.geom.Geometry.html#get)). On subclasses of ol.geom.Geometry you don't have the info that method getType() is inherited/extended.

**Comment by ahocevar** [comment]
Understood. I think the way we handle inheritance in the docs works for the majority of our users. Would it be ok for you to build a custom documentation for your purpose? All you'd have to do is remove a single line in `config/jsdoc/api/conf.json`:
```diff
--- a/config/jsdoc/api/conf.json
+++ b/config/jsdoc/api/conf.json
@@ -20,8 +20,7 @@
         "../../config/jsdoc/api/plugins/inheritdoc",
         "../../config/jsdoc/api/plugins/typedefs",
         "../../config/jsdoc/api/plugins/events",
-        "../../config/jsdoc/api/plugins/observable",
-        "../../config/jsdoc/api/plugins/api"
+        "../../config/jsdoc/api/plugins/observable"
     ],
     "markdown": {
         "parser": "gfm"
```
You should only use the generated documentation for resolving inheritance paths, because it will contain everything, even things that are not part of the official OpenLayers API.

**Comment by TDesjardins** [comment]
Ok, if this is the expected result for the users I don't have any objection. I will not have a problem with that because I can also look into the code ;-)
My intention is to support the official OpenLayers API only.

Thanks!
