### ISSUE TITLE
Is there any reason to depend on jsdoc, instead of devDepend?

### ISSUE THREAD

**Issue by Ailrun** [openlayers/openlayers#7310]
Thank you for your interest in making OpenLayers better!

To keep this project manageable for maintainers, we ask you to please check all boxes below before submitting an issue.

- [x] I am submitting a bug or feature request, not a usage question. Go to https://stackoverflow.com/questions/tagged/openlayers for questions.
- [x] I have searched GitHub to see if a similar bug or feature request has already been reported.
- [x] I have verified that the issue is present in the latest version of OpenLayers (see 'LATEST' on https://openlayers.org/).
- [ ] If reporting a bug, I have created a [CodePen](https://codepen.io) or prepared a stack trace (using the latest version and unminified code, so e.g. `ol-debug.js`, not `ol.js`) that shows the issue.

Is there any point to use jsdoc as dependency? If there are, could you let me know?

**Comment by tschaub** [comment]
@Ailrun the `openlayers` package provides utilities for building custom profiles of the library.  The build script [relies on `JSDoc`](https://github.com/openlayers/openlayers/blob/d4540c693dab7bb538d17432c1dd83c9b8323f4a/tasks/generate-info.js#L27) for extracting `@api` annotations from the sources.  It would be nicer if the published package included the `build/info.json` instead of requiring JSDoc as a dependency, but this would require reworking the package publishing and the build scripts.

We're working away from the current custom build script (which depends on [`closure-util`](https://www.npmjs.com/package/closure-util)) in favor of using mainstream module bundlers (e.g. `webpack`).  You are encouraged to use the [`ol` package](https://www.npmjs.com/package/ol) if you are not using the Closure Library.  The `ol` package has a much more reasonable set of dependencies (libraries that our code actually depends on).

In the next major release, we will be dropping support for custom builds with `closure-util` in favor of ES Module based bundling (and we will provide solutions for CJS bundlers like Browserify).  So I doubt there will be much effort put toward reducing dependencies or improving the experience with the existing [`openlayers` npm package](https://www.npmjs.com/package/openlayers).  Of course, pull requests are welcome.
