### ISSUE TITLE
Please add ol.View.getExtent()

### ISSUE THREAD

**Issue by ahmadazimi** [openlayers/openlayers#7361]
Is there is possible to add **getExtent** method to ol.View class?

**Comment by fredj** [comment]
You can use the [calculateExtent](http://openlayers.org/en/latest/apidoc/ol.View.html#calculateExtent) function to get the current extent.

**Comment by ahmadazimi** [comment]
I don't need current extent, I need the extent which I've passed via options when initializing ol.View instance!
Please tell me how I can get that option!

**Comment by TDesjardins** [comment]
@ahmadazimi If you pass your extent via options you already have the information, right? Where is the problem?

**Comment by ahmadazimi** [comment]
@TDesjardins Yes, I have it in a different scope, but I need it in another scope.
Note: I have some different views in some different classes, and sometimes I need to do some checks with each view original passed extent. So if I have no chance to obtain view options (`view.getOptions()`) I should save them in global scope which is not good and clean!

**Comment by TDesjardins** [comment]
@ahmadazimi I see. For the moment (as a workaround) you could set your infos (extent) by using get/set of class Object because class View extends Object.

**Comment by ahmadazimi** [comment]
@TDesjardins Is there any chance to have that functionality in the next update?

**Comment by TDesjardins** [comment]
@ahmadazimi I am the wrong person for this question 😉

**Comment by ahmadazimi** [comment]
@fredj Is there any chance to have that functionality in the next update?

**Comment by tschaub** [comment]
@ahmadazimi - there are a number of options that you can pass to the `View` constructor that are not set as view properties, but are instead used to configure other aspects of the view.  In this case, the extent option is used to configure a center constraint.

Adding a `view.getExtent()` method would cause a lot of confusion - since a reasonable assumption would be that the method would return the current extent of the view.

Can you give us more detail on what you are doing that requires the originally passed extent?  Perhaps someone could suggest an alternative solution.

It is worth noting that you also cannot call a method on the view to get the original values passed for these options:

 * center
 * constrainRotation
 * enableRotation
 * resolution
 * rotation
 * zoom
 * zoomFactor

**Comment by ahmadazimi** [comment]
@tschaub Thank you for deep explanation and It convinced me 👍 .
As I mentioned before, I use some different views for some purpose. Fortunately @TDesjardins solution helped me and I found a good solution for myself.
