### ISSUE TITLE
Some fields in a map that were private are now public.

### ISSUE THREAD

**Issue by jmekaelthas** [openlayers/openlayers#7412]
I can see that fields: **interactions** and **controls** are now publicly seen in the map object for the minified version of the ol.js.

Unfortunately they are not mentioned in the API docs.
Previously they were private members and had underscores at the end of their names. Now, when the map derives from pluggablemap, those fields appeared.

In the pluggable map I can see they are marked as protected so I am guessing it is a bug that they are seen publicly.

But if I am wrong, and those fields should be public now, then it would be nice if they are described in the API documentation.

**Comment by ahocevar** [comment]
The API that we support is what the API doc shows. Whether non-API properties are mangled or not is a technical detail you should not worry about. Feel free to take advantage of such non-mangled properties, but use at your own risk and expect extra effort when upgrading because they might change or go away any time.

**Comment by jmekaelthas** [comment]
Actually I worry about it, because I extended the map with some publicly available fields and I had a name conflict. I supposed the map will never have public fields (only methods) so it is safe to do it this way.

But if this is expected and not a bug, then I'll need to rearrange my project a little bit.

Anyway thank you for a quick answer.
