### ISSUE TITLE
Browser freezes at big data initial processing

### ISSUE THREAD

**Issue by yaugenka** [openlayers/openlayers#7459]
I have a vector layer with about 30k polygons and serve them to openlayers via WFS.
It weighs about 5mb and it takes about 7 sec to download it when the layer is added to the map for the first time. During the download everything is ok but at the very last moment the browser gets freezed for a couple of seconds before the data is finally drawn on the map.
If I remove the layer and add it again there is no such freeze, so I guess it happens when the data is processed for the first time after download.

**Comment by ahocevar** [comment]
Parsing the data and generating features from it is an expensive process. You might be able to gain some performance by delivering the data in the view projection of your map. But 30.000 polygons is a lot of data. The fact that your download takes 7 sec shows that you'd probably better use a different technique for loading your data. Since you're saying you're using WFS, you might consider using a tile strategy. If you can get vector tiles from your server, it would even be better.

**Comment by yaugenka** [comment]
Waiting for data to get parsed and features generated is not an issue here. It is only about the freeze which is annoying. If the processing could be done somehow in the background it would make much difference for user experience.
