### ISSUE TITLE
Remove interactions from ol.interaction.defaults

### ISSUE THREAD

**Issue by fredj** [openlayers/openlayers#7470]
For the next major release, I propose to remove:
 * `ol.interaction.DragRotate`
 * `ol.interaction.KeyboardPan`
 * `ol.interaction.KeyboardZoom`

From the default interactions added to the map, and only keep the (in my opinion) essential ones.
What do you think?

**Comment by fredj** [comment]
@openlayers/core any thought about this ?

**Comment by ahocevar** [comment]
I agree on `KeyboardPan` and `KeyboardZoom`, but I'd like to keep `DragRotate` in the defaults.

**Comment by tschaub** [comment]
I think it is pretty nice that we are keyboard accessible by default.  I don't have direct experience with this, but my assumption is that it is a benefit.

I see benefit in getting rid of uncommon things that bloat people's builds, but I think these interactions are not the biggest offenders.

![image](https://user-images.githubusercontent.com/41094/41800858-a334c64a-7634-11e8-8611-b50034fc8c83.png)

That gigantic picture shows contributions to a build that includes only a tile layer with an XYZ source.  The keyboard interactions account for 0.4% of the build.  The `geom` package accounts for > 10% of the build and is not used (but included because of the immediate rendering API).

**Comment by tschaub** [comment]
In the interest of getting 5.0 released, I'll remove this from the milestone and close the issue.  But let's definitely work on getting rid of unnecessary code for the next release.
