### ISSUE TITLE
Issue with ol.source.raster and sampling of pixel values

### ISSUE THREAD

**Issue by pksorensen** [openlayers/openlayers#7502]
Thank you for your interest in making OpenLayers better!

To keep this project manageable for maintainers, we ask you to please check all boxes below before submitting an issue.

- [x] I am submitting a bug or feature request, not a usage question. Go to https://stackoverflow.com/questions/tagged/openlayers for questions.
- [x] I have searched GitHub to see if a similar bug or feature request has already been reported.
- [x] I have verified that the issue is present in the latest version of OpenLayers (see 'LATEST' on https://openlayers.org/).
- [ ] If reporting a bug, I have created a [CodePen](https://codepen.io) or prepared a stack trace (using the latest version and unminified code, so e.g. `ol-debug.js`, not `ol.js`) that shows the issue.

I am working on reproducting it with a codepen example, but given the nature of the bug - i am hoping to get some more information from the dev team 

We are using a example very similar to https://openlayers.org/en/latest/examples/sea-level.html to show penetrations of a protective surface and have invested a fair amount of time into our project. So basically we are showing a red layer when the height is > 0.

```
function penetratesImagePx(pixels,data) {
    var pixel = pixels[0];

    if (pixel[3]) {
        var height = -10000 + ((pixel[0] * 256 * 256 + pixel[1] * 256 + pixel[2]) * 0.01);
        if (height >0) {
            pixel[0] = 255;
            pixel[1] = 0;
            pixel[2] = 0;
            pixel[3] = 255;
        } else {
            pixel[3] = 0;
        }
    }
    return pixel;
}
```

We recently discovered some artifacts (wronge red pixels) showing for some clients and I started digging down if it was our tiles. I located an area of interest and found one tile.

![image](https://user-images.githubusercontent.com/2718591/33190423-e0b92e12-d0ac-11e7-934b-ce35ef1c2ddf.png)

In the image above, we see the tile recalculated back to elevation data ranging from -136 to -170meter and the actual tile looking like this:
![image](https://user-images.githubusercontent.com/2718591/33190440-0b0e9968-d0ad-11e7-88f1-431df61551a9.png)

and what the client is seeing
![image](https://user-images.githubusercontent.com/2718591/33190445-16921a58-d0ad-11e7-9b9f-b60a5815ccf0.png)

One should see that the cyan colors in the tile image bands are similar to the artifacts. 

**Verification of encoded bands.**
In one of the cyan pixel values from the encoded image, we read out the pixel value to be R:14, G:255, and B:254
(-10000 + ((14 * 256 * 256 + 255 * 256 + 254) * 0.01)) = -169.61999999999898
So clearly, theres nothing wrong with this. Lets calculate one of the bluish pixels right next to a cyan colored pixel, which reads R:15,G:0 and B:0. Already here we might get an idea why we see the color jump in RGB space, since the encoded bands now jumped 1 in the red band but going from 255 to 0 in the green and blue bands. 
(-10000 + ((15 * 256 * 256 + 0 * 256 + 0) * 0.01)) = -169.60000000000036

So, the encoded tile image is correct, we just see the cyan color due to the elevation hitting the boundary of G band. 

**Image Sampling – our theory**
So somewhere deep into the machine of openlayers, something happens with these pixel values that we cannot control. 
So looking at the two prior examples of pixel values and assume that some sampling is happening, the mean value of those two pixels means the resulting elevation would be 159 and get colored as being > 0 in our example.

15 | 128 | 127 = 159.35

I have tried using both "image" and "pixel" operationType of the raster calc with same result. 

What do you guys think - is there any way to tell ol that it cannot sample this tilelayer before doing calculations?

**Comment by tschaub** [comment]
I agree that this looks like interpolation in RGB space which doesn't map back to correctly interpolated values in your elevation space.  It would be nice to have a bit more material to try to reproduce the issue.  Can you provide any more detail on your tile size and source projection, the view projection, and device pixel ratio?

**Comment by pksorensen** [comment]
I still have to make a small minimal reproduction - but we did some tests
We made sure that view and raster projections was the same, so that the issue is not from reprojection.
We have experienced that the artifacts are smaller/removed on some resolutions.

Thinking about it, as i experienced with both pixel and image operation that it seems that pixel opperation is just looping over the same pixels that image operation uses. And when in image opperation the image size fits the viewport size. So I am guessing that ol resamples between tile zoom lvls which could be the issue.

Given these, i am considering if it will be possible to create a reproduction using the mapbox elevation raster tiles that is already used in some examples.

**Comment by sk-** [comment]
I'm seeing the same issues when using elevation data. Mostly with fractional zoom levels, but also when the zoom level is higher than the maximum zoom level of the elevation data. It also happens when you transition from one integral zoom level to the next one.

Below are some images showing the problem, in which it's plotted the areas with a slope greater than certain threshold.

Image with no artifacts
<img width="765" alt="screen shot 2018-06-05 at 7 05 36 pm" src="https://user-images.githubusercontent.com/911768/40997839-4dcbd94a-6906-11e8-9629-a03eeb9cdf50.png">

After zooming in a little with the scrolling wheel to get a fractional zoom level the result is as follows
<img width="766" alt="screen shot 2018-06-05 at 7 05 20 pm" src="https://user-images.githubusercontent.com/911768/40997838-4db03ad2-6906-11e8-81d5-602d457167f2.png">
You can see in this image how the artifacts are spaced 256m, which is perfectly aligned with the data encoding which is 256*r + g + b/256.

The image below is at one plus the maximum zoom level.
<img width="827" alt="screen shot 2018-06-05 at 8 17 32 pm" src="https://user-images.githubusercontent.com/911768/40997840-4dea69a0-6906-11e8-9c4c-9cd14a8ae0ac.png">

The image below is at the maximum zoom level and shows some artifacts around the tiles.
<img width="825" alt="screen shot 2018-06-05 at 8 17 47 pm" src="https://user-images.githubusercontent.com/911768/40997842-4e01cdac-6906-11e8-8f89-6f2ac0c44965.png">

Note that this happens with the elevation data from mapbox and also with the one from mapzen/nextzen.
