### ISSUE TITLE
The snap interaction is not effective while using the translate interaction?

### ISSUE THREAD

**Issue by vicky8989** [openlayers/openlayers#7662]
i use the translate interaction to move features, i want to the snap interaction while moving feature. but the snap interaction is noneffective .The code is below:
```
this.translateInteraction_ = new ol.interaction.Translate({
			features: this.selectedFeatures,
			layers: [this.modelLayer_, this.labelLayer_]
			//hitTolerance: this.defaultSnapTolerance_
		});

		this.olMap_.addInteraction(this.translateInteraction_);

		this.olmapsnap_ = new ol.interaction.Snap({
			source: this.modelLayerSource_,
			//features: new ol.Collection(snapFeatures_), //添加测量元素吸附
			pixelTolerance: this.defaultSnapTolerance_,
		});
		this.olMap_.addInteraction(this.olmapsnap_);
```

Is openlayers latest version support this function?

**Comment by polar** [comment]
In researching this issue: https://github.com/openlayers/openlayers/issues/6716
I found that the Snap interaction rounds the pixel to an integer. I don't know why it does that, but in conjunction with the Modify interaction, it makes the Modify interaction miss the snapped vertexes because the map.getCoordinateFromPixel(evt.pixel) doesn't exactly represent the coordinate since the pixel was rounded to an integer. The Translate interaction uses featuresAtPixel_(), which relies on the pixel that was rounded by the Snap interaction. We either have to fix the Snap interaction not to round the pixel to integers (not sure why it's doing that), or make the interaction use a featuresAtCoordinate function instead.

**Comment by jalik** [comment]
@polar I think that since the snap interaction is working with approximation it needs to be rounded, so any coordinate within a pixel results to the same pixel, thus allowing the snap to work.

I think that the Snap is not working because currently the Snap is working (IMO) by using the mouse position, so it's easy for calculation, but in your case you are moving a whole (maybe complex).
Either the snap does not handle this case, either there is a bug in the calculations.
But this deserves an investigation, OL is so fantastic having this to work is gonna add some great possibilities.
