### ISSUE TITLE
consolidate url options

### ISSUE THREAD

**Issue by bartvde** [openlayers/openlayers#7706]
Currently we have url, urls and tileUrlFunction

It might make sense to have a single configuration option (url), that can take all three forms?

**Comment by bartvde** [comment]
@TDesjardins what are your thoughts?

**Comment by TDesjardins** [comment]
@bartvde Some thougts: In terms of consistency I think this is a good/right action 👍
I see the problem in the API usage when allowing different types for one property/attribute. In ol this is common (for example the style attribute). This results in code bloating because every time the client code wants to access this properties it have to check the type. This is also true for the implementation code behind the API.
If you have different setters or getters you don't have to care about that because you know what you will get. Internally you could use one property though that holds the information.

**Comment by tschaub** [comment]
This is definitely the right way to go, but we are not going to block 5.0 on it, so I'll remove the milestone.  Let's add better url functionality in one of the 5.x releases, deprecate what we don't want, and then remove stuff in 6.
