### ISSUE TITLE
Crossing 180° Meridian Line

### ISSUE THREAD

**Issue by iMilad** [openlayers/openlayers#7859]
Hi,

This is more a question than an issue, Is this crossing 180° meridian line fixed in new version or still doesn't count as a bug!

I know the workaround is using beyond 180°, but to handle huge file would be really costly, maybe anyone has an new idea, or even new package is already outside.

KR

**Comment by raiyni** [comment]
If you are are talking about automatically crossing the dateline, no. Because it's technically not a bug. The projection doesn't know if you want to cross the dateline or draw a literal line between two points.

If you are talking about shapes disappearing across the dateline, no. https://github.com/openlayers/openlayers/issues/6088
