### ISSUE TITLE
Update type annotations

### ISSUE THREAD

**Issue by tschaub** [openlayers/openlayers#7970]
We need to update all of the legacy type annotations from the old `ol.foo.Bar` style to the new `module:ol/foo/Bar~Bar` style.

**Comment by tschaub** [comment]
@ahocevar - I'm curious about default exports.  Do we always repeat the module name?  For example:
```js
/**
 * @module ol/geom/GeometryType
 */

/**
 * @enum
 */
export default {
  POINT: 'Point' // ...
};
```

Will `module:ol/geom/GeometryType~GeometryType` be right here?  Or is `module:ol/geom/GeometryType` right?

**Comment by ahocevar** [comment]
For babel-plugin-jsdoc-closure and type checking it does not matter. For JSDoc there is a difference: the shorter will link to the module page (which also contains typedefs and named exports of that module, if any). The longer will link to the enum directly.

I also went a bit back and forth on this, and in the end decided to use the long version because we do the same for all other default exports, e.g. classes.

**Comment by ger-benjamin** [comment]
A `git grep 'ol[.]render' src/` (for instance) still give me results like: 
 - https://github.com/openlayers/openlayers/blob/master/src/ol/render/canvas.js#L67 (link)
 - https://github.com/openlayers/openlayers/blob/master/src/ol/render/webgl/Immediate.js#L359 (type)
 - https://github.com/openlayers/openlayers/blob/master/src/ol/render/webgl/Immediate.js#L91 (param)
- and other ref.

I'll improve what I can.
Should we care about things outside of the "src/" ? because there is a lot of these notations in examples and the doc folders.

It mainly concerns:
 - [ ] ol.format
 - [ ] ol.pointer
 - [ ] ol.render
 - [ ] ol.DeclutterGroup
 - [ ] ol.Canvas* (mutiples)
 - [ ] ol.structs
 - [ ] ol.source
 - [ ] ol.ImageLoadFunctionType

**Comment by ahocevar** [comment]
@ger-benjamin Thanks for any help you can provide. Examples and docs should also no longer use the `ol.*` notation.

**Comment by ger-benjamin** [comment]
But what do you want for the documentation ? Like here: https://github.com/openlayers/openlayers/blob/master/doc/faq.md, for instance, for a `new ol.Map({...})`. Do you want that, in the code section, we add a line `import Map from ol.Map`, then use `new Map({...})` ?

**Comment by ahocevar** [comment]
@ger-benjamin: Yes, adding the imports in code examples like the FAQ is the way to go. I've done that in some inline docs already. Also note that you can now use the re-exported modules, e.g.
```js
import * as layer from 'ol/layer';

const tileLayer = new layer.Tile({
  //...
});
```
Thanks again for your help!

**Comment by tschaub** [comment]
I think we should avoid suggesting that people use * imports.  To benefit from tree shaking, import just what you need.

import {Tile as TileLayer} from 'ol/layer';

Or

import TileLayer from 'ol/layer/Tile';

These are two equivalent ways of getting the TileLayer constructor.  The first is useful if you want to import more than one layer constructor in a single statement.
