### ISSUE TITLE
How can I modify view's extent

### ISSUE THREAD

**Issue by supermap-gaoziyang** [openlayers/openlayers#8074]
I init ol.View with a extent, how can I change the extent。
```
 let view = new ol.View({
                    center: [0, 0],
                    zoom: 1,
                    projection: 'EPSG:4326' ,
                    extent: [-180, -90, 180, 90]
                });
```
I want to change  view's extent to [114, 37, 115, 39], how can I do that ? should I recreate a ol.View?

**Comment by ahocevar** [comment]
Yes, creating a new view is the way to go.

**Comment by supermap-gaoziyang** [comment]
thank you ~~
Ask one more, Why not add a method like this ?

**Comment by ahocevar** [comment]
All constraints are designed to be defined at construction time. It would probably require a lot of code and many new tests to ensure that the view continues to work as expected after constraints are changed. The reason is just that there has not been enough interest in such a change to justify the effort.

**Comment by supermap-gaoziyang** [comment]
ok~ I see, thank you~~~
