### ISSUE TITLE
Text overflow fails with line placement & a textAlign property

### ISSUE THREAD

**Issue by glenselle** [openlayers/openlayers#8236]
Thank you for your interest in making OpenLayers better!

To keep this project manageable for maintainers, we ask you to please check all boxes below before submitting an issue.

- [x] I am submitting a bug or feature request, not a usage question. Go to https://stackoverflow.com/questions/tagged/openlayers for questions.
- [x] I have searched GitHub to see if a similar bug or feature request has already been reported.
- [x] I have verified that the issue is present in the latest version of OpenLayers (see 'LATEST' on https://openlayers.org/).
- [x] If reporting a bug, I have created a [CodePen](https://codepen.io) or prepared a stack trace (using the latest version and unminified code, so e.g. `ol-debug.js`, not `ol.js`) that shows the issue.

Whenever you set `placement` to `line` and `overflow` to `true` for an `ol.style.Text` style, a long piece of text will show properly. However, if you add `textAlign` and attempt to set it to any of the documented values the text will disappear and never render. I'm assuming this is a bug? I need to left-align some text, but when I do, long text (which is user-inputed) disappears.

The codepen below shows the behavior in OL v6.5.0. Simply comment out the `textAlign` property to have it render properly. Add it back in and it disappears.

https://codepen.io/anon/pen/zjVZwX?editors=0010

**Comment by glenselle** [comment]
BTW, since this is significantly impacting our users, I wouldn't mind submitting a PR if someone could point me in the right direction as to where this issue might originate. No promises I can figure it out, but I'd be willing to look at it--unless it's a quick bug fix for the maintainers.

**Comment by ahocevar** [comment]
Actually there is a bug, but none that will solve your issue when fixed. Even with no `textAlign` set, your text should not be rendered, because it does not fit on any segment of your geometry.

That said, you have two options:

1. Set `maxAngle: Infinity` as additonal text style property. With that, your text will be rendered, but will make sharp turns along your geometry.

2. Configure your style with a custom geometry, which could be the first segment of your geometry.

**Comment by ahocevar** [comment]
Actually whether the current behavior is a bug or intentional depends on the interpretation of the `overflow` property in combination with `maxAngle`. If `overflow` means to overflow the path part of a geometry that satisfies the `maxAngle` restriction (which is a valid assumption), we'd accept a pull request that makes your code pen work.

The code section that causes the current behavior is https://github.com/openlayers/openlayers/blob/26b84f09bd8f958c3dacd8c5abb6b3ae08652973/src/ol/render/canvas/TextReplay.js#L202-L208: it identifies the part of a path that satisfies the `maxAngle` rule, but only if no `textAlign` is set (which means determine placement automatically). A pull request would have to change this segment selection process.

**Comment by venugopal-rao** [comment]
Placement:line is not working for linestring to align the text on the line.the text is very large in that case how i need to handle.

**Comment by ahocevar** [comment]
@venugopal-rao Try configuring the text style with
```js
{
  overflow: true,
  maxAngle: Infinity
}
```
