### ISSUE TITLE
https://openlayers.org/en/v4.6.4/build/ol.js is now 5.0.0

### ISSUE THREAD

**Issue by novumcoder** [openlayers/openlayers#8331]
Hey guys,

we just got a report that our mapping stopped working. After spending some time we found out that the JS file behind https://openlayers.org/en/v4.6.4/build/ol.js is actually version 5.0.0 looking at the content.

**Comment by u-jung** [comment]
I can confirm! We've got a 404 error when asking for https://openlayers.org/en/v4.6.4/build/ol.js

**Comment by pbalyx** [comment]
I confirm too. But replacing 4.6.4 by 5.0.0 is not sufficient. Many things have changed...
For instance I got the error "ol.Sphere is not a constructor" for a script that work fine before this update.
How can I manage that ?

**Comment by raiyni** [comment]
I'm not entirely sure you should be serving those files straight from the github.io repo anyway. There's https://cdnjs.com/libraries/openlayers for that.

**Comment by u-jung** [comment]
Sorry, this doesn't work. The behavior is absolutely strange. Whatever version I will load (3,4 or5), every time I will get the same massage "Laden fehlgeschlagen für das <script> mit der Quelle "https://openlayers.org/en/v4.6.4/build/ol.js?_=1530447020356"" ( Failure on loading the script  with source https://openlayers.org/en/v4.6.4/build/ol.js ...) I have checked the html code ever and ever again. There is no other call for ol.js. I have also tried to load the ol.js locally. Nothing helps. So why the site tries to load v4.6.4 if there is no such a command?
On the other hand I tried the examples from the ol page and there are working. This let me think about a problem with php7 or nginx-server which are used to make the site running. But the same problem suddenly came also with the mirror test site, where nothing has been changed.

**Comment by RalphLAtGitHub** [comment]
Have you checked your JavaScript for import operations?
https://stackoverflow.com/questions/950087/how-do-i-include-a-javascript-file-in-another-javascript-file

**Comment by u-jung** [comment]
Well, there was still some call for 4.6.4 inside the site script. The problem has been resolved.

Thanks

UJ

**Comment by pbalyx** [comment]
Thanks RalphLAtGitHub for your fast answer. I tried 4.6.5 and it works. I will certainly upgrade to 5.0.0 when the documentation will be more detailed. 
But a few questions :
I began to work with OpenLayers with version 3. I upgraded to version 4 because I saw it in the examples but old version was still working. Why does 4.6.4 has been abruptly suppressed ?
Is there any way to be informed of such changes to avoid wasting time, first to understand what is wrong with a page that suddenly does not work any more, then to search forums for a solution which is finally quite simple.

**Comment by ThomasG77** [comment]
It seems failure to serve v4.6.4 is due to a cahnge due to v4.6.4 symlink on OpenLayers hosting side.

You can see it and check the branch that host OpenLayers.org website files at https://github.com/openlayers/openlayers.github.io/tree/master/en to understand

Anyways, URLs like https://openlayers.org/en/v4.6.4/build/ol.js are not intended for production.
If using them this way, you are already doing things wrong although I can understand that taking a "shortcut" can be appealing.
You should host your own version of the files (`ol.js` and `ol.css`) or use a proper cdn like https://cdnjs.com

**Comment by ahocevar** [comment]
Restored v4.6.4 symlink to v4.6.5. And I second what ThomasG77 said, adding that we strongly recommend using the [ol package](https://npmjs.com/package/ol) instead of the full build.
