### ISSUE TITLE
Missing https://openlayers.org/en/v5.0.0/build/ol-debug.js

### ISSUE THREAD

**Issue by RalphLAtGitHub** [openlayers/openlayers#8334]
The debug version was very helpful. Does a new link exist?

**Comment by ThomasG77** [comment]
No, because https://github.com/openlayers/openlayers/issues/8330#issuecomment-401536821
You should instead use source maps ([Chrome recipe](https://developers.google.com/web/tools/chrome-devtools/javascript/source-maps), [Firefox recipe](https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Use_a_source_map))
