### ISSUE TITLE
add opt_fast param to Collection.clear()

### ISSUE THREAD

**Issue by aberenyi** [openlayers/openlayers#8359]
Hi,

If you have a number of features (>1k) in a `Collection` it can take literally ages to run `clear()`, because of the dispatched events.

I've implemented the proposed solution here https://github.com/aberenyi/openlayers/commit/7d3880fb784345fed6c2c9f7ca8d5a07856d6692 (inspired by https://github.com/openlayers/openlayers/blob/v5.0.2/src/ol/source/Vector.js#L463).

Happy to open a PR.

Cheers

**Comment by aberenyi** [comment]
Fair point, however, I need an Observable, hence the Collection. The use case is pretty simple: animated display of point features over a given time period. Once the animation is finished and the user restarts it, I clear out the collection and re-add the original features.

I guess I can just hide and un-hide the features, but the current solution is much cleaner.

**Comment by ahocevar** [comment]
Hard to tell what's cleaner without seeing the code, but personally I do not use `ol/Collection` in my applications. I'm even pushing for removing it from OpenLayers in one of the next major releases. Why? Because wherever we modify an array in the library, we know when we do it, and can use other means of doing whatever listeners for add/remove events of the Collection do.

**Comment by aberenyi** [comment]
I see where you're coming from, but I think `ol/Collection` is a nice and easy way of managing dynamic data streams.
Anyway, I'm gonna close this as it seems this won't be implemented.
