### ISSUE TITLE
GeoJSON Feature inheritance in 5.0.3

### ISSUE THREAD

**Issue by sookoll** [openlayers/openlayers#8377]
After updating to 5.0.3 features created from geojson source are not identified as ol/Feature objects with instanceof function.

```
import Feature from 'ol/feature'
import GeoJSON from 'ol/format/geojson'

const parser = new GeoJSON()
let feature = parser.readFeature(geojson)
console.log(feature instanceof Feature) // output false

feature = new Feature()
console.log(feature instanceof Feature) // output true
```
... not to mention that now examples do not contain links to jsfiddle, so it is hard to make working examples, es6-only is against npm official policy and broke most of test runners and API documentation is now useless piece of crap. Most of the links to the ol API docs You find from internet lead to Github 404 page. Where is consistency? Can't say, that openlayers last developments are improvements from users side.

**Comment by ThomasG77** [comment]
See [this demo](https://codesandbox.io/s/ryonvpvoxn) that show there is no issues (or at least the way I'm doing)
As you can see my imports end with the `.js` extension e.g

```
import Feature from "ol/Feature.js";
import GeoJSON from "ol/format/GeoJSON.js";
```

You can download the demo sample code doing "Download", then uncompressing in a directory, doing `npm install` and `npm start` (that should open your browser at the "right" page)

**Comment by ahocevar** [comment]
Sorry you're having trouble updating to the latest release. The following hints should help you complete the task:

 * Import paths have changed between v4 and v5. Class modules now have CamelCase file names. Please refer to the [API documentation](https://openlayers.org/en/v5.0.3/apidoc/) for the correct import path. In the case of [`ol/Feature`](http://openlayers.org/en/latest/apidoc/module-ol_Feature-Feature.html), it is `import Feature from 'ol/Feature'`, and for [`ol/format/GeoJSON`](http://openlayers.org/en/latest/apidoc/module-ol_format_GeoJSON-GeoJSON.html), it is `import GeoJSON from 'ol/format/GeoJSON'`.
 * Make sure you don't mix OpenLayers versions in your dependency tree. You can check that with `npm ls`. If you still have dependencies that use v4.x, there might be a beta version of the dependency for v5.x available already. 
 * We are working on a new website, with new API documentation and examples. There will also be an option to live edit examples when that is completed. Watch out for tickets over the course of the next weeks if you are willing to contribute. In the meantime, you can use the hosted build as mentioned in the [quick start](http://openlayers.org/en/v5.0.3/doc/quickstart.html) for JSFiddle or CodePen. Or you can use imports as shown in the current examples with https://codesandbox.io/.
 * API documentation for all 4.x releases is still available on https://openlayers.org/en/v{version}/apidoc/ (replace {version} with the version you are looking for), and is also included in the downloads provided on the [release page](https://github.com/openlayers/openlayers/releases).
 * We understand that it is not yet common practice to publish packages with ES modules. However, we expect that to change very fast because ES modules get more widely adopted now that all bundlers can handle them, some (like https://parceljs.org/) even with zero configuration. npm's [policies](https://www.npmjs.com/policies) do not prohibit publishing packages with ES modules.
 * Most test frameworks (mocha, jest, karma) can handle ES modules, but might require to modify configurations. If you have trouble configuring your test framework to work with the ol package, feel free to create a ticket and we'll try to help.

**Comment by ahocevar** [comment]
@sookoll, can we close this?

**Comment by sookoll** [comment]
Yes. I had to change all imports declarations, now it works again.
