### ISSUE TITLE
@types/ol out of date (has no exported member)

### ISSUE THREAD

**Issue by josepgomes** [openlayers/openlayers#8388]
Hello,

I'm using ol@5.03. The last @types/ol's version is 4.6.2. This @types version does not have modules like "click" in "ol/events/condition".

Is there a new repository?
Is there a current @types for ol@5.0.3?

Many Thanks.

**Comment by tschaub** [comment]
Those types are provided by the [DefinitelyTyped project](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/ol).  I'm not sure how they are generated, but perhaps @yairtawil could comment - they are not published as a part of our releases.

We are working toward proper TypeScript support in the library (see #8345 for example).  Our goal is to get to the place where people can use types directly from our releases instead of relying on DefinitelyTyped.

**Comment by Ailrun** [comment]
The typing is depends on `openlayers` (yes, that 4.* package) typing, so it's not easy to update it. I want to update `ol` typing, but recently I have no time to do that.
However, I also worry about the case that releasing of TS supported version is not so far so that my work become useless. @tschaub, could you give me any clue for release data? Any opaque information would be thankful.

**Comment by Ailrun** [comment]
@tschaub Any idea?

**Comment by tschaub** [comment]
I've been keeping #8345 up to date and adding comments about the issues we are uncovering.  There are a number of upstream issues that are out of our control, so guessing about a release date is tough.  For example, Microsoft/TypeScript#26528 has been open for close to three weeks.  I'm not pointing this out because I think it is unreasonable (and very much appreciate what the TypeScript team are doing to support type checking JavaScript), but just to illustrate that it is not really possible to make estimates with these kinds of unknowns.

We were hoping to have a TypeScript-compatible release a month or so ago.  Maybe another month?

**Comment by Ailrun** [comment]
@tschaub Thank you for your comment :smile: I got what openlayers currently facing. How about adding index.d.ts for `ol` package to this repo directly? I'm willing to build a typing and send a PR.

**Comment by tschaub** [comment]
@Ailrun how would that `index.d.ts` be generated?

**Comment by Ailrun** [comment]
@tschaub I meant creating it manually :)

**Comment by Ailrun** [comment]
@tschaub Do you hate this idea?

**Comment by tschaub** [comment]
No, but it seems like a lot of work, and I’m not sure if we will end up needing an index.d.ts file if our next release includes type annotations in the sources.

Personally, I find it frustrating when vs code jumps to an index.d.ts file instead of a source file when gluing to the source of a function.  Ideally, tools would work well with our published js sources (and those will include typescript-friendly JSDoc annotations).

**Comment by gimerstedt** [comment]
is there any way to get the JSDoc annotations to work with tsserver? i'm currently stuck on 4.6.5 using the @types/ol package. looking forward to being able to upgrade!
