### ISSUE TITLE
Performance dropping steeply by raising number of styled features

### ISSUE THREAD

**Issue by hyperknot** [openlayers/openlayers#8392]
I'm writing an article about Google Maps API alternatives, and I'm comparing Mapbox GL, OpenLayers and Leaflet for performance.

I wrote an example, hoping that it'll be highly performant in OL, but what I'm experiencing is a very steep performance drop after 1000 features. Up till 1000 features are still perfectly smooth experience, 10000 is almost frozen.

Am I using the styling function wrong? Is it possible to make style functions zoom independent?
I tried using setStyle on individual features, hoping that it will not be zoom dependent, but it's way more slow actually.

Example on codesandbox (using 5.0.3): https://codesandbox.io/s/n0yoww61ml

**Comment by ahocevar** [comment]
You are indeed using a very inefficient style function. I have updated your sandbox: https://codesandbox.io/s/6vq49zxq3. The main difference is that I'm caching Style objects once I have created them, so I end up with one style per color, and I can reuse them. With this change. the map runs perfectly smooth with 10000 features.

**Comment by ahocevar** [comment]
Since you have 10000 distinct styles and no resolution dependent styles, it is better to store the style on the feature, instead of using a style function on the layer. With this change alone, you will see a significant performance gain.

If you are still not happy with the result, you can configure the vector layer with `renderMode: 'image'`. In that mode, an image with the whole scene is generated for the current resolution, and there will be no vector rendering during zooming and panning.

I have made these two changes in a fork of your sandbox: https://codesandbox.io/s/24mqlm5k9j.

Also note that OpenLayers only renders the features that are visible in the viewport, and simplifies lines and polygons to match the resolution. So as you zoom in, you will notice faster rendering.

OpenLayers does many other optimizations to improve rendering performance, but none works with your random data. In real world examples, you e.g. often have the same color for subsequent lines, and OpenLayers will group them and reduce the amount of stroke() instructions on the canvas.

**Comment by hyperknot** [comment]
Thanks it does improve rendering performance a lot!

**Comment by hyperknot** [comment]
Hi, I've finished the final draft of my article, planning to submit it next week. 
Can you check if there is anything what you think isn't right? You can also answer by email, my contact details are visible on my profile.
https://medium.com/@hyperknot/google-maps-api-alternatives-mapbox-vs-openlayers-vs-leaflet-401295c21939

**Comment by ahocevar** [comment]
Thanks for the heads-up @hyperknot. I'll look into it over the weekend.

**Comment by ahocevar** [comment]
@hyperknot Can we close this?

**Comment by hyperknot** [comment]
Absolutely, thanks for all the help!
