### ISSUE TITLE
Very slow performance on hover features in ff & ie

### ISSUE THREAD

**Issue by fibonaki** [openlayers/openlayers#8592]
We just have realised that exists a problem that affects on the performance of rendering hovered features in map. That only happens when browser is Firefox or Internet Explorer. It seems that this is an old issue refered in other old threads: [4232](https://github.com/openlayers/openlayers/issues/4232) and [5196](https://github.com/openlayers/openlayers/pull/5196).

We would like to know if maybe there is any solution from time to time. We have been searching also some workarounds about that but we still have some problems.

Here it is an example: [http://jsfiddle.net/7nx3hrwa/1/](http://jsfiddle.net/7nx3hrwa/1/)
* It is working very well on Chrome (super fast)
* On Firefox and IE hover is very slow

Anyone knows how to fix that?

**Comment by ahocevar** [comment]
This is an updated example: http://jsfiddle.net/7nx3hrwa/12/

It uses the latest version of OpenLayers and adds a few tweaks to make it much faster on all browsers:
 * Set the `renderBuffer` of the vector layer to `2` instead of `100` pixels, to make hit detection faster
 * Set the `renderMode` of the vector layer to `image` instead of `vector`, to avoid replaying when the highlighted feature changes
 * Set `useSpatialIndex` on the feature overlay to false, to make addition and removal of the highlighted feature faster.

**Comment by ketill1** [comment]
Thank you very much @ahocevar. The provided fix worked very well. I use OpenLayers 9.19. Is this still the recommended fix or has anything else changed by now?

**Comment by ahocevar** [comment]
Doing the above is still good practice. However, you may want to upgrade to a more recent version - we have made many performance optimisations since.
