### ISSUE TITLE
Legacy build is broken

### ISSUE THREAD

**Issue by gberaudo** [openlayers/openlayers#8601]
Following the merging of the typescript branch the `build-legacy` target is broken:

$ `npm run build-legacy`
```
Controls.": Invalid type expression "import("../Collection.js").default<import("./Control.js").default>": Expected "!", "=", "?", "[]", "|" or end of input but "(" found.
ERROR: Unable to parse a tag's type expression for source file /home/gberaudo/dev/ol3/src/ol/control/util.js in line 42 with tag title "return" and text "{import("../Collection.js").default<import("./Control.js").default>}
Controls.": Invalid type expression "import("../Collection.js").default<import("./Control.js").default>": Expected "!", "=", "?", "[]", "|" or end of input but "(" found.
/home/gberaudo/dev/ol3/config/jsdoc/info/publish.js:98
          paramInfo.types = getTypes(param.type.names);
                                                ^

TypeError: Cannot read property 'names' of undefined
    at /home/gberaudo/dev/ol3/config/jsdoc/info/publish.js:98:49
    at Array.forEach (<anonymous>)
    at /home/gberaudo/dev/ol3/config/jsdoc/info/publish.js:93:20
```

Proposed fix:

I am currently working on a generic tool to generate a legacy library from the `default exports` and `named exports` of an ES6 modules library. That tool could be used by OpenLayers.
In a second step I plan to add `custom build` support, similar to what we had with our GCC custom builds.

Implementation details:

The code would be a simplification of current code, see draft at https://github.com/openlayers/openlayers/compare/v5.2.0...gberaudo:generate_all_exports_library.

Please let me know if there is interest / new ideas / or if someone is already working on this.

**Comment by tschaub** [comment]
I know this isn't going to be popular, but I think we should stop generating the legacy build altogether.

The reality is that a single file full build of OpenLayers hasn't made sense since 2.x.  The position taken during 3.x development was essentially "the compiler will get rid of unused stuff, so its okay to add very seldom used things to the library."  This means that it became a worse and worse idea to use a single file build as the 3.x releases progressed (full build users were burdened with the addition of a half functioning renderer in addition to a working renderer, format parsers and more functionality than they were ever going to use).  The problem was that the tools to create custom builds were too much of a hassle for most people to use.

With the introduction of the `ol` package during 4.x development, and now with our full commitment to modules in 5.x, we are trying to reduce the hassle of building a portion of the library together with an application.  For this to succeed, we need to make significant improvements to the documentation - including far more usage examples throughout the API docs and well written guides.  Focusing on a single way to use the library (as modules) will make our jobs easier (generating documentation) and will reduce confusion for users.

I understand that there are people who may want to try OpenLayers and are unwilling to use a module bundler.  Given the amount of work that we still need to do to document the library for those that do use a module bundler, I think our energies are better focused in that direction.  And it would be especially unfortunate if a commitment to generating the legacy full build tied us to legacy tools that made it harder to move forward with the rest of the build tooling.

**Comment by richnic** [comment]
@tschaub, from other programming interfaces you are used to the following behaviour: In your HTML file just link to a third party library file and add your custom code (or an open source snippet found somewhere in the internet), then it works. And in the case of runtime errors the browser messages point to your readable JavaScript lines, and you can easily inject console log statements or alert popups for debugging purposes.

Have a look at #8415: Within hours of publishing a buggy full build you had received three reports about that issue because ol.js is used by lots of webmasters. Also notice the complaints in #8496 and #8416: It seems to me that a majority of users prefers the easy handling I described above (for that you only need a standard text editor but no other tool and without any compiling/linking step in a command shell). Therefore OpenLayers shouldn't give up the single file build.

Maybe you can additionally offer a reduced build containing only most used functionality (e.g. classes/functions to display and control the map, load or drag&drop data, style tracks and waypoints) but without high-end features (e.g. freehand drawing).

**Comment by gberaudo** [comment]
I have published the tool to https://github.com/geoblocks/legacylib.
See documentation about how to use it for building OpenLayers5 (full build).

I agree the Openlayers team should go forward with ES6 modules: the Javascript ecosystem is moving and we must be part of it.  What has been done so far with typechecking/typescript is awesome but there is still a lot to do and that is where the energy is the most needed.

Regarding legacy builds, I think people requiring them can use the external tool above. Maybe there could be a link to the tool in the OpenLayers documentation.

@tschaub will the code base continue to use the `@module` annotation? I believe it is the only requirement for the tool to work.

**Comment by ca0v** [comment]
There are cases where you don't always know what part of the API you're going to need until runtime.  Based on your current progress you can probably already transpile these modules into amd.  Once you do that, instead of a single legacy file, we can have a core file and use amd to load the missing pieces at runtime.  Forgive me if I'm stating the obvious, I can't keep up with all your great progress.  AMD is the solution when you don't know what you need but you know you don't need it all at once.
