### ISSUE TITLE
Trying to load PNG32 on arcgis ImageServer that doesnt support it

### ISSUE THREAD

**Issue by elunty** [openlayers/openlayers#8608]
Some ImageServer urls dont have png32 support, but we still try to load them when using an ImageServer url and ImageArcGISRest

Example (valid server):
https://jsfiddle.net/kpetw84h/1/

Example (server with only png/png8/png24 support)
https://jsfiddle.net/72ux4c1w/

Edit: I've just noticed that you can update this with params, but maybe we should use lowercase 'png' as the default, rather than PNG32 ?

**Comment by ahocevar** [comment]
According to the WMS spec, OpenLayers uses a MIME type (default: `image/png`) as value of the `FORMAT` param. If you want to use a different format, configure your WMS source with e.g.
```js
params: {
  FORMAT: 'image/png8'
}
```

**Comment by elunty** [comment]
https://openlayers.org/en/latest/apidoc/module-ol_source_TileArcGISRest.html uses PNG32 as default, I'm just suggesting changing to png (or png8 like you say) as the default, in an attempt for better compatability with arcgis ImageServers

**Comment by ahocevar** [comment]
Ah sorry, for some reason I thought you were takling about `ol/source/ImageWMS`, despite seeing `ol/source/ImageArcGISRest` in your fiddle.

The reason why png32 is the default is because in many scenarios, layers from these servers are used as overlays, so transparency is important, which you don't get from png24. And with png8, palettes are applied, which can result in changing colors when a new image is loaded after panning.

If you can think of documentation improvements that make it easier for users to find out why they don't get the expected result with servers that do not support png32, we'd appreciate a pull request.

**Comment by elunty** [comment]
Ah.. interesting.  I just stumbled into some map server stuff for work, so maybe "normal" users of this stuff would know better.  Its a shame ?f=pjson doesn't return supported types. My only thought would be to add some small warning such as "be aware that not all servers support png32" or something in the docs for params.
