### ISSUE TITLE
Older API documentation no longer available?

### ISSUE THREAD

**Issue by getDOKI** [openlayers/openlayers#8896]
Where I can find API documentation for older versions of Openlayers e.x. 3.10?
http://openlayers.org/en/v3.10.1/apidoc/ - 404 not found. 3 days ago everything was ok.

**Comment by bartvde** [comment]
just download the archive locally: https://github.com/openlayers/openlayers/releases/download/v3.10.1/v3.10.1.zip

**Comment by ahocevar** [comment]
Due to storage limitations on GitHub Pages, we had to delete all legacy documentation except for the versions linked directly from https://openlayers.org/ (at the bottom). For v3.x, this would be http://openlayers.org/en/v3.20.1/apidoc/.

If you need API docs for a specific version, you can download the full zip from the releases page, in your case [v3.10.1.zip](https://github.com/openlayers/openlayers/releases/download/v3.10.1/v3.10.1.zip) from https://github.com/openlayers/openlayers/releases/tag/v3.10.1, which contains an `apidoc` folder.
