### ISSUE TITLE
Visualizing raw raster data

### ISSUE THREAD

**Issue by GaborFarkas** [openlayers/openlayers#8965]
There is currently no raster support in OpenLayers. Would you consider merging a working a raster module based on geotiff.js if I rework #7978? It would only have a texture-based canvas raster renderer with the necessary base classes.

**Comment by gberaudo** [comment]
Hi @GaborFarkas,

First of all, thanks for your renewed interest and contributions to the library.

You may have seen that the library has been in a hot storm last week with most of the WebGL work gone. I feel very sad about it, notably because I (and others like you) spent lots of time contributing that WebGL code. :(

The fact is that there is not enough knowledge/contribution to the WebGL code base for making it production ready and maintaining it. In addition, the performance has not been as awesome as expected.

OpenLayers used to require all layers of a map to use the same technology: either canvas 2d OR WebGL; it was not possible to use a mix of them. I think it is the main reason why few persons are using WebGL in production and the lack of financing of WebGL features.

The new CompositeMap which landed last week in OpenLayers allows to mix canvas 2d layers and WebGL layers in the same map. This is a great opportunity to focus WebGL contributions to domains where WebGL outperforms the canvas 2d API: heatmap, relief maps, particule systems, huge number of points...

Our full WebGL code is in the git history and could be a source of inspiration for a new start of WebGL (and soon WebGPU?) in OpenLayers.
I think it makes sense to have WebGL raster, point, line, polygon helper functions in the core of OpenLayers.
For an example of current use of WebGL functionalities, see the WebGL heatmap example https://github.com/openlayers/openlayers/blob/master/src/ol/layer/Heatmap.js.

Regarding the visualization of raw raster data, I think it is a nice feature. If the core maintainers of OpenLayers are confident in maintaining it it should enter the review process and at some point be merged. Otherwise it would be perfect as a separate project, eventually advertised from the main OpenLayers page. See https://github.com/openlayers/ol-cesium or https://github.com/Viglino/ol-ext for examples of such separate projects.

Ping @tschaub, @ahocevar, @fredj.

**Comment by GaborFarkas** [comment]
Thank you for your response @gberaudo.

I saw the recent changes, and don't worry about the WebGL removal. I already created a basis for a WebGL plugin called ol-webgl, and now waiting for the new version to come out, so I can start rewriting the WebGL renderers on the top of it.

**Comment by gberaudo** [comment]
@GaborFarkas, OL6 will come out beginning next spring.
If you have a branch somewhere I am curious to see what you are building.

For information, it is not required anymore to use replay groups. A layer can handle its rendering as it pleases.

**Comment by GaborFarkas** [comment]
Yes I saw that and I consider it as an opportunity for faster rendering. Recently during writing a study about the Canvas and WebGL technologies in 2D mapping, I found out that this whole replay mechanism adds a lot of overhead to hardware accelerating, constraining the maximum achievable performance in OL. Furthermore, RTE rendering is another big actor in lower than expected performance. I'm quite confident that this way a WebGL plugin will be closer to libraries focusing on fast rendering (such as Mapbox GL JS).

**Comment by GaborFarkas** [comment]
Oh, and the WebGL plugin won't be in an OL branch, it will get its own package, and can be used and bundled along with OL in Node. The repo is now quite blank and will be until the next OL release, but nevertheless it can be reached at https://github.com/GaborFarkas/ol-webgl.

**Comment by jahow** [comment]
Hi @GaborFarkas,

IMO your contribution for visualizing raw raster data (as was your work on the webgl renderer) is quite impressive. Obviously a *lot* of work went into it. I personally have no knowledge of any use case where WCS services are used in web interactive maps, I thought these services were more used by backend/desktop applications. Adding such a feature would bring a lot of code in OL, but it is also something that others library do not support (I think).

Just wanted to say that I share your view on the overhead brought by the replay group mechanism. You may have seen it, but while the webgl renderers were removed, I strived to make a simple to use `WebGLHelper` class for those who have some knowledge in 3D rendering & GLSL to be able to keep doing webgl on custom layers without the verbosity of the native API. It is a public class so please feel free to use it/improve it in your ol-webgl plugin if relevant. Thanks!

**Comment by GaborFarkas** [comment]
Hi @jahow,

I saw those changes as well, and thank you for the low level WebGL interface, it will be more convenient to rebuild the engine on the top of it. If I find a way to improve it during the development process, I'll create a PR.

Yes, WCS is still used by backends and desktop apps, but I think mostly because there are only a few libraries or plugins capable of client side rendering, most of them focusing on loading rasters from popular data exchange formats. There are use cases, like dynamic restyling, reclassification, or band compositing. Traditionally, when the basic principles and concepts of web mapping were laid down, client side machines and web technologies were simply not adequate for outsourcing such tasks. Consequently, geospatial web servers still prerender rasters according to predefined representation model rules (styles), and rarely style rasters on demand (using user provided SLDs). Nowadays dynamic styling is achievable on the client side, putting less burden on the server, and they can concentrate on serving raw raster data with minimal traffic (e.g. in GeoTIFF). I suspect there will be more demand for client side raster handling, but we will see.

For a more practical example, think of NASA's Landsat and ESA's Sentinel portals. Both of them offer not only footprints of downloadable satellite images, but the actual images in a downscaled, RGB format. What if the user could actually see the overviews in arbitrary band compositions besides the RGBs before downloading or ordering large amounts of data.
