### ISSUE TITLE
npm es6 module

### ISSUE THREAD

**Issue by GISerWYJ** [openlayers/openlayers#8974]
can i use ol es6 source code in angular projects? why does the npm ol is es5 not es6? 
or is there any way to use code completion in webstrom when using ol as node_modules?

**Comment by fredj** [comment]
yes, you can use es6 modules in your project, see:
https://github.com/openlayers/openlayers#getting-started

The [openlayers](https://www.npmjs.com/package/openlayers) package was in es5 but the [ol](https://www.npmjs.com/package/ol) package is in es6

**Comment by GISerWYJ** [comment]
> yes, you can use es6 modules in your project, see:
> https://github.com/openlayers/openlayers#getting-started
> 
> The [openlayers](https://www.npmjs.com/package/openlayers) package was in es5 but the [ol](https://www.npmjs.com/package/ol) package is in es6

@fredj  thank you for the reply.  I found the npm version of ol source code was es5 (screenshorts below),however the source code on github is es6. seems like the npm version of ol is the compiled version of github one ?
source code in node_modules
![image](https://user-images.githubusercontent.com/12789732/48776848-e360df80-ed0b-11e8-878f-833281d963d8.png)
![image](https://user-images.githubusercontent.com/12789732/48776965-3fc3ff00-ed0c-11e8-8c5a-4650561583c8.png)
Did I miss something?

**Comment by ahocevar** [comment]
OpenLayers uses ES modules (i.e. module loading with `import`), and not CommonJS modules (i.e. module loading with `require()`). At the moment, the code in the `ol` package is transpiled to ES5. We are planning to provide two different packages in the future, one as a set of ES6 modules, and one as ES5 modules. But both with ES module loading.

**Comment by GISerWYJ** [comment]
@ahocevar Thank you for the explanation！looking forward to the ol es6 modules .

**Comment by larsgk** [comment]
why was this closed? - still not fixed

**Comment by ahocevar** [comment]
Duplicate of #8999.

**Comment by larsgk** [comment]
#8999 seems to be about VS Code (but I guess having proper ES6 modules in build will fix that ;))

**Comment by petabyteboy** [comment]
Now #8999 is fixed but importing ol as an es6 module is still broken without a transpiler that supports CommonJS modules.

**Comment by ahocevar** [comment]
@petabyteboy Can you share a setup that you would expect to work, and explain in detail what does not work?

**Comment by petabyteboy** [comment]
> @petabyteboy Can you share a setup that you would expect to work, and explain in detail what does not work?

Take the https://github.com/openlayers/ol-rollup example and remove the commonjs from rollup.config.js. 

Since #10385 rbush is imported as a CommonJS module and thus it will complain about rbush.js not exporting a default.

IMO the correct solution for #10379 would have been to keep the es6 import and then transpile dependencies to es5 in the openlayers bundle build.

**Comment by ahocevar** [comment]
@petabyteboy A few remarks:

> IMO the correct solution for #10379 would have been to keep the es6 import and then transpile dependencies to es5 in the openlayers bundle build.

That is not really practical, because it means we'd have to publish dependencies with our package.

> I also noticed there is no es6 module version of openlayers itself in the npm package.

The untranspiled es6 modules are packaged in `src/`, if you want to use them.

**Comment by petabyteboy** [comment]
> That is not really practical, because it means we'd have to publish dependencies with our package.

Okay I guess I see the problem. The whole thing is not really something I think about because I import, transpile and bundle all the dependencies for my project with rollup, so I don't have to worry about dependencies, and I don't have to support legacy browsers.
I'm not sure if there is another way to solve the problems I am seeing when using modern tooling that expects all dependencies to be ES6 modules, while not making it more complicated for those who need to support ES5 browsers. Anyways I think this issue should be reopened since importing openlayers as an ES6 module creates some problems at the moment.

> The untranspiled es6 modules are packaged in src/, if you want to use them.

Importing "ol/src/ol/..." breaks the typescript type descriptions.

**Comment by ahocevar** [comment]
> Importing "ol/src/ol/..." breaks the typescript type descriptions and the rbush issue still exists.

Yes and yes. The former, you can solve with the [alias](https://www.npmjs.com/package/@rollup/plugin-alias) plugin, the latter is pretty much standard in JavaScript project with dependencies, and the commonjs plugin does not hurt. This will improve as more and more libraries publish ES modules.

That said, tree shaking works with both `src/´ and the transpiled modules. They both use ES import/export. The difference in size you are seeing is because the transpiled code is larger.

**Comment by dhavalc-complitech** [comment]
Must use import to load ES Module: C:\xampp\htdocs\vue\BijlesNodigJoep\node_modules\ol\Map.js require() of ES modules is not supported. require() of C:\xampp\htdocs\vue\BijlesNodigJoep\node_modules\ol\Map.js from C:\xampp\htdocs\vue\BijlesNodigJoep\node_modules\vue-server-renderer\build.dev.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules. Instead rename Map.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from C:\xampp\htdocs\vue\BijlesNodigJoep\node_modules\ol\package.json.

Can you help me on this @ahocevar

**Comment by ahocevar** [comment]
@dhavalc-complitech Looks like you are using some Vue tooling that uses CommonJS modules. If nothing else works, try installing `esm` and run your Vue tool with `node -r esm whateverscript.js`.
