### ISSUE TITLE
webgl vector tile ?

### ISSUE THREAD

**Issue by Farkal** [openlayers/openlayers#8991]
I am trying to switch from canvas map to webgl map (because of iOS 12 canvas memory issue -_-)

I use VectorTileLayer with VectorTileSource but webgl map don't find a render for this so I am asking if there is any reason why it's not implemented ?

I can make a pull request if needed ;)

**Comment by jahow** [comment]
Hi, I guess the reason is no one never proposed an implementation that was complete and production-ready. I for one have done an attempt at such a renderer that you can see here: https://github.com/jahow/openlayers/commits/poc-webgl-vectortiles

Notable issues were a few memory leaks (my fault entirely), the need to reimplement decluttering, making the text rendering on par with canvas, and performance generally pretty low (inferior to canvas).

Please note that there is work in progress on the master branch to improve the performance of VT rendering and to restrict the use of WebGL to a few edge cases only.

**Comment by Wendzand** [comment]
https://docs.geoserver.org/stable/en/user/data/database/sqlview.html?fbclid=IwAR2vVWbr5NHmQrO8RzWmHDEn6HSQMM-AE4yiytQtDXQzSzR7_tcAqwXjbRs

**Comment by jahow** [comment]
> https://docs.geoserver.org/stable/en/user/data/database/sqlview.html?fbclid=IwAR2vVWbr5NHmQrO8RzWmHDEn6HSQMM-AE4yiytQtDXQzSzR7_tcAqwXjbRs

Not sure how that has anything to do here...?

**Comment by Farkal** [comment]
Ok I find a workaround with canvas to reduce memory usage with my vector tiles (using the render mode vector).
So it's not urgent for me but I am interested on this implementation. Do you plan to continue your work on this ?

**Comment by jahow** [comment]
> So it's not urgent for me but I am interested on this implementation. Do you plan to continue your work on this ?

No, this path was abandoned as it would require too much work to have something at least as performant as the canvas implementation. Besides the whole rendering/replay group system is being reworked for version 6 so the code I linked above is probably mostly obsolete.

**Comment by Farkal** [comment]
So I will wait for v6 and see if it's interesting to dev this feature.

**Comment by Rahim373** [comment]
Hello, Any update on this?

**Comment by jahow** [comment]
A simple webgl-based vector renderer is under development here: https://github.com/openlayers/openlayers/pull/13461

Next step will most likely be a vector tile renderer using the same approach. Things are moving forward, slowly but steadily!
