### ISSUE TITLE
import 'ol' from 'ol'

### ISSUE THREAD

**Issue by xuqingxi** [openlayers/openlayers#9021]
**need a lot import expressions in each Vue component**
when we have a project with multiple component pages use the map,it need to import all modules it needs,it feels duplicate
**export modules in ol that we can use one imoprt like '' import 'ol' from 'ol' ''**
i just compare with the old ol to add the export modules we need,
in ''tilegrid.js'' :
    import TileGrid from './tilegrid/TileGrid.js';
    import WMTS from './tilegrid/WMTS.js';
in ''ol/index.js'':
    import * as proj from './proj';
    import * as geom from './geom';
    import * as layer from './layer';
    import * as format from './format';
    import * as sphere from './sphere';
    import * as source from './source';
    import * as style from './style';
    import * as render from './render';
    import * as coordinate from './coordinate';
    import * as interaction from './interaction';
    import * as size from './size';
    import * as array from './array';
    import * as color from './color';
    import * as colorlike from './colorlike';
    import * as control from './control';
    import * as easing from './easing';
    import * as events from './events';
    import * as extent from './extent';
    import * as featureloader from './featureloader';
    import * as has from './has';
    import * as loadingstrategy from './loadingstrategy';
    import * as tilegrid from './tilegrid';
    import * as xml from './xml';
export {
  proj,
  geom,
  layer,
  format,
  sphere,
  source,
  style,
  render,
  coordinate,
  interaction,
  size,
  array,
  color,
  colorlike,
  control,
  easing,
  events,
  featureloader,
  extent,
  has,
  loadingstrategy,
  tilegrid,
  xml
}
that is it,i wonder if it has a better way to duel with the problem,it feels not good if i have to import too much in each page. thanks!

**Comment by jalik** [comment]
Maybe you should write modular code and reuse the logic between your components so the imports are not in each components but only in the file containing the logic.
OpenLayers did a hard work to make everything modulable as we can now import only slices of OL, thus having smaller bundles, I don't think returning back to the big one monolothic lib is a good thing..

**Comment by xuqingxi** [comment]
thanks for you answer,i may think too one-sidely.

**Comment by ibbignerd** [comment]
@jalik While it is great that they moved to a modular implementation, I don't like being forced to import every single slice of code. If you look at Lodash, you have a couple different options. You can get all of Lodash or the modular code with lodash/fp. The biggest difference between Lodash and OpenLayers is that Lodash is structured in modules, but you can import the whole thing. This allows us to use babel packages like [babel-plugin-lodash](https://www.npmjs.com/package/babel-plugin-lodash) to only import the specific slices we need after we transpile. While we are developing, it is very easy to read, understand, and work with. 

I think this could be resolved in the future, but by currently not exporting the class as a whole, it results in code like this.

```js
import { transform } from 'ol/proj';

// somewhere deep in our code
transform(pos[0], pos[1]), 'EPSG:4326', 'EPSG:3857');
```

Where as before, it was very easy to see I am accessing `ol.proj.transform()`, now I have to go back up to my imports to see what function this actually is. This structure also muddies the namespace. I have no idea whether `transform()` is my function or OpenLayers. Others that are potential issues include `Map`, `Object`, `Image`, `Feature`, `Array`, etc.

**Comment by jalik** [comment]
@ibbignerd I understand your concerns as they are mine too, I am talking about usability, comfort and readability for the developers.

About lodash, the biggest difference is that OL have functions and objects nested into modules, whereas in lodash you just have all functions into a flat object, (I am not sure since I used underscore instead of lodash but they're almost the same), so it's more simple to manage like this.

I see babel-plugin-lodash as a workaround that avoids to rewrite a full app using sliced imports, not very much a "standard" way to go.. but still useful unless you start writing a new app with module imports.

This could be resolved as you said by having a single file with all the "wires" in it, allowing to have a single root object to pick inside, but still it's the old fashion way to do things, in the reverse of how it's going today.

I've rewriten an app with a lot of `ol.module.function`, I can say that now it's more readable without all that prefixes, by the way your problem can be solved in 2 ways:
- import * as proj from 'ol/proj'
- import {proj as olProj} from 'ol/proj'

**Comment by xuqingxi** [comment]
thanks for you answers.But you may mistake my mean,with you solutions,if i need multiple modules in different pages,it will be like this:
```javascript
// in compontent 1
import TileGrid from './tilegrid/TileGrid.js';
import WMTS from './tilegrid/WMTS.js';
import ''ol/index.js'':
import * as proj from './proj';
import * as geom from './geom';
import * as layer from './layer';
import * as format from './format';
import * as sphere from './sphere';
import * as source from './source';
import * as style from './style';
//...
```
```javascript
// in compontent 2
import TileGrid from './tilegrid/TileGrid.js';
import WMTS from './tilegrid/WMTS.js';
import ''ol/index.js'':
import * as proj from './proj';
import * as geom from './geom';
import * as layer from './layer';
import * as format from './format';
import * as sphere from './sphere';
import * as source from './source';
import * as style from './style';
//...
```
i want  not just the functions ,but the different modules,so i want this are all in one object like the  external js ,and now i just use it by use `<script src ="../ol"></script>`,but in tis way my IDE throw me a inspection
![image](https://user-images.githubusercontent.com/38125259/49559899-5c3a7b00-f94b-11e8-81a8-4be5255bed48.png)
really sighed

**Comment by jalik** [comment]
@xuqingxi I was answering to @ibbignerd.

In my opinion, the code you want to achieve is hybrid, it contains old syntax used during decades like `ol.module.function` and the new one with `import ...`. While it would certainly work, I think you have to move to the new syntax and be used to it because a lot of libs are working like this nowadays.
If you look at some other OOL, it's a common thing to have all the required imports at the top of the file (like in java), any decent IDE would hide all of this imports by collapsing them into a single line make code smaller (visually).

Well just saying, I am not part of the OL team, but I really think you guys would gain something by follow how things were made to be used.
