### ISSUE TITLE
ol5 ReplayGroup

### ISSUE THREAD

**Issue by ParnDeedlit** [openlayers/openlayers#9215]
**Is your feature request related to a problem? Please describe.**
in openlayers 4.6 i use 
``` js
var _replayGroup = new ol.render.canvas.ReplayGroup(0, extent, 8,true,100);
```
but the ReplayGroup disapear in ol5 ? is there other method instead of ReplayGroup ?

thanks?

**Comment by gberaudo** [comment]
Hi @ParnDeedlit, the replay group mechanism was split:
- BuilderGroup to create the instructions;
- ExecutorGroup to run them.

**Comment by ahocevar** [comment]
@ParnDeedlit Where did you need access to the replay group? It was never part of the public API, so it would be interesting to hear about your use case.

**Comment by ParnDeedlit** [comment]
thanks for all of you, english is not my home language, my english description will easy.

# Result

* BuilderGroup to create the instructions;
* ExecutorGroup to run them.

acroding your help i finish my base work. thank you,

# Where I use it?

## Intent Cesium VectorTile

Due to Cesium don not support mapbox vectortile , i deside to work it out.

## Inspiration
First i use the leaflet.vectorgrid & ol.vectortile. when i compare the two method of vectortile. I think both of two are very hard to transfrom to cesium.

Until i find this [ol-mapbox-style](https://github.com/openlayers/ol-mapbox-style) && [ol-cesium](https://github.com/openlayers/ol-cesium)

The **ol-mapbox-style** is so cool, I think it the best unfical (mapbox) way to draw vectortile.  Perfect display effect & smooth load process

When i see these code, I find i can use the **ol-mapbox-style** as vt-parse to draw canvas. And I use the code to draw vt in canvas tile.
``` js
var replayGroup = new ReplayGroup(0, extent, buffer, true, 100);

for(...){
    // loop vector tile styles to every feature to draw 
    renderFeature(_replayGroup, feature, styles[j], 16);
}

replayGroup.finish();
replayGroup.replay(canvas, transform, ratote, hash,replays); 
``` 

when draw over the tile, then take this to cesium tile ImageProvider, then finish the all method.

> this is my first test to conbine openlayers & cesium & vectortile, i see the source code **stylefunction** is perfect to render vectortile in canvas.  other code to translate mvt-style is simple to convert font/width/color, but this code conside very deep to detail sush as filter & source-layer & font & sprite (especially sprite, these show the high level code)

![viewfile](https://user-images.githubusercontent.com/23654117/52914844-385ec280-3308-11e9-83ff-3e0712e92e91.png)


## Bug & Disavantage
I use Cesium-ImageProvider & ol-mapbox-style/stylefunction to render vectortile, It indeed to draw the vectortile in cesium. but when some tile is on loading , some tile is over load, the mouse slide process is hard or delay.

> i find **ol-mapbox-style** show me a new method to translate `mapbox vectortile style` to ol-vectortile-style, and this code avoid slide process block.   

I will try to use the idea to deal with the block, thank you again。 you help me a lot, this code `ol-mapbox-style/stylefunction` is so cool.

**Comment by ParnDeedlit** [comment]
> Hi @ParnDeedlit, the replay group mechanism was split:
> 
> * BuilderGroup to create the instructions;
> * ExecutorGroup to run them.

Thank you , it works

**Comment by zhuxiaomengjj** [comment]
@ParnDeedlit 
Did you solve the block issue?

**Comment by yiwenzhang666999** [comment]
@ParnDeedlit 
你好，我想问一下你在ol5中怎么解决这个问题的，我也遇到了相同的问题
var _replayGroup = new ol.render.canvas.ReplayGroup(0, extent, 8,true,100);

**Comment by yiwenzhang666999** [comment]
hi @gberaudo  I don't quite understand the instructions below. After I upgraded from ol4 to ol5, something went wrong with ol.render.canvas.ReplayGroup, and the map couldn't come out.Can you tell me how to use ReplayGroup in ol5?


BuilderGroup to create the instructions，
ExecutorGroup to run them.

   var _replayGroup = new ol.render.canvas.ReplayGroup(0, extent,
                            8,that._pixelRatio, true, null,100);

                        for (var i = 0; i < features.length; i++) {
                            var feature = features[i];
                            var styles = styleFun(features[i], that._resolutions[level]);
                            if (styles) {
                                for (var j = 0; j < styles.length; j++) {
                                    ol.renderer.vector.renderFeature(_replayGroup, feature, styles[j], 16);
                                }
                            }
                            
                        }
                        _replayGroup.finish();

                        _replayGroup.replay(vectorContext, that._pixelRatio, that._transform, 0, {}, that._replays, true);

**Comment by gberaudo** [comment]
Hi @yiwenzhang666999, see the tests: https://github.com/openlayers/openlayers/blob/master/test/spec/ol/renderer/canvas/builder.test.js#L34-L38

**Comment by yiwenzhang666999** [comment]
hi @gberaudo  thank you very much,i will try

**Comment by yiwenzhang666999** [comment]
hi @gberaudo When calling replayGroup.replay in ol5, the annotations will not be overwritten by passing in the last two parameters, but how should the last two parameters of executor.execute be handled in ol6, because the annotations will overwrite each other if not passed in, and look forward to your reply

////////////////////////////ol5///////////////////////////////////////////////////
this._replays = ["Default", "Image", "Polygon", "LineString", "Text"];
var _replayGroup = new ol.render.canvas.ReplayGroup(0, extent,
    8, true, 100);

for (var i = 0; i < features.length; i++) {
    var feature = features[i];
    var styles = styleFun(features[i], that._resolutions[level]);
    for (var j = 0; j < styles.length; j++) {
        ol.renderer.vector.renderFeature_(_replayGroup, feature, styles[j], 16);
    }
}
_replayGroup.finish();

_replayGroup.replay(vectorContext, that._pixelRatio, that._transform, 0, {}, that._replays, true);

///////////////////////////////////////////ol6/////////////////////////////////////////
var builderGroup = new ol.render.canvas.BuilderGroup(0, extent,
    8, that._pixelRatio, 100);
for (var i = 0; i < features.length; i++) {
    var feature = features[i];
    var styles = styleFun(features[i], that._resolutions[level]);
    if (styles) {
        for (var j = 0; j < styles.length; j++) {
            ol.renderer.vector.renderFeature(builderGroup, feature, styles[j], 16, null);
        }
    }
}
const executor = new ol.render.canvas.ExecutorGroup(null, 1,
    that._pixelRatio || 1, true, builderGroup.finish());
executor.execute(vectorContext, that._transform, 0, false);

**Comment by gberaudo** [comment]
Hi @yiwenzhang666999, what do you mean with  "annotations will overwrite each other"?

**Comment by yiwenzhang666999** [comment]
hi @gberaudo The situation I encountered is this, if the vector layer is called in two dimensions, by setting declutter to true, the label of the vector layer will not be messy, but I do n’t know when I use ol.render.canvas.ExecutorGroup How about the reduction of annotations, because there are too many now and they seem to cover each other?
![image](https://user-images.githubusercontent.com/31643589/72145059-a4409280-33d4-11ea-9ca4-c1cb8490522e.png)

**Comment by gberaudo** [comment]
@yiwenzhang666999, to prevent overlaps you need to use decluttering. I don't remember the details; it is probably triggered by the `opt_declutterReplays` parameter of `ExecutorGroup.execute`.

**Comment by yiwenzhang666999** [comment]
hi@gberaudo Thank you very much for your reply, I will try

**Comment by yiwenzhang666999** [comment]
hi@gberaudo I refer to ol.renderer.canvas.VectorTileLayer to build the last two parameters opt_builderTypes, opt_declutterReplays in ExecutorGroup.execute, but it doesn't work, I really don't know how to build these two parameters, there are examples or methods to build these two parameters ? Looking forward to your reply
![image](https://user-images.githubusercontent.com/31643589/72235552-c7a25200-360d-11ea-8c2e-b567eaf8150c.png)
var builderTypes = ['Image', 'Text', 'Default'];
const executor = new ol.render.canvas.ExecutorGroup(extemtMer, 1,
    that._pixelRatio || 1, true, builderGroup.finish(),100);
executor.execute(vectorContext, that._transform, 0, false,builderTypes,{});

**Comment by yiwenzhang666999** [comment]
hi@gberaudo I probably know how to construct the last two parameters of the ExecutorGroup.execute method (the code is as follows), but the annotations will still be overwritten, and I found that when the last parameter of ol.render.canvas.BuilderGroup is set to true, the annotations are not displayed. So I set it to false, I do n’t know where the problem is, the underlying code does n’t understand it clearly, I look forward to your reply

var builderGroup = new ol.render.canvas.BuilderGroup(0, extemtMer,8, that._pixelRatio, false);
   . . .  // process code
var _replays = ["Default", "Image", "Polygon", "LineString", "Text"];
var declutterReplays = {};
const executorGroup = new ol.render.canvas.ExecutorGroup(null, 1,that._pixelRatio || 1, true, builderGroup.finish(),100);
executorGroup.execute(vectorContext, that._transform, 0, false,_replays,declutterReplays);
if (declutterReplays) {
    ol.render.canvas.ExecutorGroup.replayDeclutter(declutterReplays, vectorContext, 0, 1, true, []);
}

**Comment by luckuny** [comment]
请问下这个问题解决了吗？我也是在cesium上展示，
但一直是错位的：
![image](https://github.com/openlayers/openlayers/assets/3285112/a065bd50-b67a-4dd1-96be-73c584316a0c)
正确的应该是这样：
![image](https://github.com/openlayers/openlayers/assets/3285112/c8236b60-1264-4670-86d3-65bbe8d2f819)

**Comment by luckuny** [comment]
> hi @gberaudo When calling replayGroup.replay in ol5, the annotations will not be overwritten by passing in the last two parameters, but how should the last two parameters of executor.execute be handled in ol6, because the annotations will overwrite each other if not passed in, and look forward to your reply
> 
> ////////////////////////////ol5/////////////////////////////////////////////////// this._replays = ["Default", "Image", "Polygon", "LineString", "Text"]; var _replayGroup = new ol.render.canvas.ReplayGroup(0, extent, 8, true, 100);
> 
> for (var i = 0; i < features.length; i++) { var feature = features[i]; var styles = styleFun(features[i], that._resolutions[level]); for (var j = 0; j < styles.length; j++) { ol.renderer.vector.renderFeature_(_replayGroup, feature, styles[j], 16); } } _replayGroup.finish();
> 
> _replayGroup.replay(vectorContext, that._pixelRatio, that._transform, 0, {}, that._replays, true);
> 
> ///////////////////////////////////////////ol6///////////////////////////////////////// var builderGroup = new ol.render.canvas.BuilderGroup(0, extent, 8, that._pixelRatio, 100); for (var i = 0; i < features.length; i++) { var feature = features[i]; var styles = styleFun(features[i], that._resolutions[level]); if (styles) { for (var j = 0; j < styles.length; j++) { ol.renderer.vector.renderFeature(builderGroup, feature, styles[j], 16, null); } } } const executor = new ol.render.canvas.ExecutorGroup(null, 1, that._pixelRatio || 1, true, builderGroup.finish()); executor.execute(vectorContext, that._transform, 0, false);
在cesium上加载MVT矢量数据一直是错位，
var _resolutions = ol.tilegrid.resolutionsFromExtent(mapExtent, 21, 256);
的mapExtent参数

_replayGroup.replay(vectorContext, _pixelRatio, _transform, 0, {}, _replays, true);
的参数怎样设置的？
