### ISSUE TITLE
View.center seems not work

### ISSUE THREAD

**Issue by JulioJu** [openlayers/openlayers#9228]
Actually, as https://openlayers.org/en/latest/apidoc/module-ol_View-View.html says and as https://openlayers.org/en/latest/doc/tutorials/bundle.html show, View.center should accept an array like `[5, 45]`

**To Reproduce**
1. Simply test with https://openlayers.org/en/latest/doc/tutorials/bundle.html
2. Change
```javascript
 center: [0, 0], zoom: 0
```
by something like 
```javascript
// longitude 5.72, latitude 45.17 : you must be in France Alpes, in Grenoble city
 center: [5.72, 45.17], zoom: 11 
```
Result : your are not in France Alpes !

Tested today, either with the last npm version of `ol` : 5.3.0

Note: it works well with 
```javascript
            center: proj.fromLonLat([5.72, 45.17]),
            zoom: 11
```

Thanks in advance ;-)

**Comment by ahocevar** [comment]
If you have a suggestion to improve the documentation to make it clearer that the center is to be provided in view coordinates, a pull request would be greatly appreciated.

**Comment by worc** [comment]
i mean, the docs are extremely unclear. coordinates are never well defined, and they way they have to be transformed from projection to projection is never said outright. and then on top of that there's no working example of a transformation. and then worse, completely out of step with everyone else it's LonLat intead of LatLon.

there are a lot of things here that need to be said up front instead of implied and implicit.
