### ISSUE TITLE
Incorrect vector tile rendering when source tile grid and render tile grid do not align

### ISSUE THREAD

**Issue by ahocevar** [openlayers/openlayers#9296]
**Describe the bug**
When a vector tile source has a tile grid that does not align with the standard Web Mercator tile grid, tiles are rendered incorrectly (i.e. with gaps or overlaps)

**To Reproduce**
1. Use the `mapbox-style` example as a starting point
2. Change the code to something like
```js
import apply from 'ol-mapbox-style';
import TileGrid from '../src/ol/tilegrid/TileGrid';
import {getTopLeft} from '../src/ol/extent';

apply('map', 'https://api.mapbox.com/styles/v1/mapbox/bright-v9?access_token=[my-token]').then(function(map) {
  const resolutions = [];
  for (let i = 0; i < 36; ++i) {
    resolutions.push(78271.51696402048 / Math.pow(1.5, i));
  }
  map.getLayers().item(0).getSource().tileGrids_['EPSG:3857'] = new TileGrid({
    origin: getTopLeft(map.getView().getProjection().getExtent()),
    resolutions: resolutions
  });
});
```
3. See error

![untitled](https://user-images.githubusercontent.com/211514/53909128-41ae9580-4051-11e9-9af1-b9415651f758.png)

**Expected behavior**
Map with tiles that align properly, because the renderer was design to work with render tile grids that are completely different from source tile grids.

**Comment by ahocevar** [comment]
@jahow Did you get a chance to look at this already? Let me know if you feel comfortable taking this on.

**Comment by ahocevar** [comment]
@jahow Working on this now, assuming you're swamped with other work anyway since you haven't replied.

**Comment by ahocevar** [comment]
This issue only occurs when `wrapX` is set to `true` on the source, and is caused by a til grid that does not align with the world.

**Comment by jahow** [comment]
@ahocevar yes, sorry, I've looked into it. This is actually caused by 3 separate issues (at least):
* TileImage renderer not offsetting the tiles correctly for "mirrored worlds" (it assumes the tile grid is regular, ie only composed of full tiles)
* wrapX computation in tilegrid.js is wrong, also assuming the tile grid is regular
* Vector features are wrongly positioned by the VectorTileLayer, meaning the position of the points and labels is also wrong

Not trivial to fix but doable for sure. Will update this issue as I go

**Comment by ahocevar** [comment]
Ok @jahow, I came more or less to the same conclusion, but did not observe the third issue you mentioned. As long as `wrapX` is set to false, the results are good.

In order to keep `wrapX` working, a simpler solution would be to use different tile sizes for the fractional zooms, ensuring that the tile grid extents for each zoom level still align. The ´TileGrid` already supports different tile sizes for different zoom levels.

That said, I think we should try the different tile sizes approach, and close this issue if it works.

**Comment by jahow** [comment]
Oh, also I noticed the tile selection logic (to determine which tiles are to be loaded) does assume the grid is regular too, so I think this should be fixed as well.

> In order to keep wrapX working, a simpler solution would be to use different tile sizes for the fractional zooms, ensuring that the tile grid extents for each zoom level still align. The ´TileGrid` already supports different tile sizes for different zoom levels.

I'm not sure I understand what you're saying. For me this is how tiles should be rendered in case of an irregular grid:
![image](https://user-images.githubusercontent.com/10629150/54369417-32919e00-4676-11e9-9f4a-ffbc5d813812.png)

Do you mean we should introduce another tile grid for the part on the right where the regular grid does not fit?

**Comment by ahocevar** [comment]
@jahow I created a draft of what I had in mind in #9336, but it also has issues. Do you see a way to get either solution to work without unnecessarily complicating the tile grid and renderer code?

**Comment by jahow** [comment]
Okay, got it. I cannot answer your question yet, still have to try a few things. To me this is mainly related to how offsets with x-wrapped coordinates are computed, so I hope that adjusting the computations at low level will be enough to fix this without actually adding new logic.

I'll report here tomorrow whether I found something simple enough, or else we can follow your suggestion and be done with this (IMO this is kind of an edge case and may not justify spending ages on it).

**Comment by ahocevar** [comment]
Agreed, thanks a lot!

**Comment by jahow** [comment]
@ahocevar I could not manage to have something final, some progress were made but it is overall tricky to add support for fractional tile grids without touching much of the code:

* https://github.com/jahow/openlayers/commit/4a175b0a1edd8beddf6fb4a0e30b9fa1780d7b89: this commit "fixes" the `wrapX` function to work with non aligned tile grids; I've added tests as well, so this part is clean IMO

* https://github.com/jahow/openlayers/commit/6f952133e7e1ddb13bffee10490dcb2c6e687b55: this commit adds some logic in the `CanvasTileLayerRenderer` to correctly offset tiles outside of the projection extent; this does not feel right and should be handled elsewhere (esp. since the issue remains with features e.g. labels in vector tiles)

* https://github.com/jahow/openlayers/commit/4ccda62773931c330b4b3c0f23a27c04240c2bba: last commit was an attempt to standardize the transformation from tile coordinate space to (world) coordinate space; not nice either, since the `TileGrid` class is not the right place for this (tile grids have no knowledge of the projection extent)

My conclusion is that this could be handled in a *clean* way by moving the logic of transforming world coordinates from/to tile coordinates in a single place. This transformation would have to be fed the tile grid and projection objects and then would be able to correctly compute things in case of irregular grids.

This is not trivial, although I think it would benefit the codebase and make the rendering code simpler. Seeing how the deadline for v6 is creeping on us, I'd say your proposal sounds better for now.

**Comment by ahocevar** [comment]
I think we can close this as won't fix. The whole purpose of tile grids is to align.
