### ISSUE TITLE
When I put 20,000 features on Layer,what could I do to improve the fluency of map dragging

### ISSUE THREAD

**Issue by vampire1995** [openlayers/openlayers#9372]
`import VectorImageLayer from 'ol/layer/VectorImage';`</br>
I put these features on the VectorImageLayer .</br>
Style:
```
 function shipStyle_judge(feature, resolution) {
    if (resolution > 700) {
      return new Style({
        image: new Icon(
          /** @type {module:ol/style/Icon~Options} */
          ({
            src: 'data:image/svg+xml;utf8,<svg width="0.41em" height="0.8em" style= "padding-left:1" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><circle xmlns="http://www.w3.org/2000/svg" cx="3" cy="5" r="1.5" stroke="' + feature.values_.color1 + '" stroke-width="0.35" fill="' + feature.values_.color2 + '"/></svg>',
            scale: 1.3,
            anchor: [0.5, 0.5],
            anchorXUnits: "fraction",
            anchorYUnits: "fraction",
          })
        )
      })
    }
  }
  feature.setStyle(shipStyle_judge)
```

**Comment by ahocevar** [comment]
Two things:
* Avoid returning a new `ol/Style` instance for every style function call. Instead, reuse the `ol/Style instance`.
* Do not set the style on the feature. Instead, set it on the layer.

**Comment by vampire1995** [comment]
Thank you !It works for me.

**Comment by Stevenjohnlally** [comment]
I am doing something similar with SVG Icon features but with each feature being able to have one of a few styles.

Each feature is a representation of a road sign and can display one of multiple aspects. As below:
![Screenshot from 2022-04-21 10-22-05](https://user-images.githubusercontent.com/20048771/164358929-46a3c545-8af5-4d07-828b-91f4ae3d2301.png)
![Screenshot from 2022-04-21 10-22-45](https://user-images.githubusercontent.com/20048771/164358958-d85dae29-2d11-4b21-8238-d47d1c8efa8e.png)

I cache each style in a Map<string, Style>. However, even with only 1000 features on the layer, the map is pretty unusable due to the performance. Is there anything else I can do to improve the performance even with 10,000+ features?

**Comment by ahocevar** [comment]
If you have performance problems with 1000 features, you must be doing something wrong. Please share your code.
