### ISSUE TITLE
can you provide the ol.debug.js? we need it!

### ISSUE THREAD

**Issue by jackletter** [openlayers/openlayers#9391]
can you provide the ol.debug.js? we need it!
or how can i generate the ol.debug.js from source code?

**Comment by ThomasG77** [comment]
See https://github.com/openlayers/openlayers/issues/8330 it explains the "why" and give you a way a recipe to generate an ol-debug.js file.
Try it but be cautious as Rollup build has been replaced by Webpack to create legacy OpenLayers ol.js e.g https://github.com/openlayers/openlayers/blob/master/config/webpack-config-legacy-build.js
I didn't see a new recipe since using Webpack to output ol-debug.js.
