### ISSUE TITLE
OpenLayers 6 performance issues with large number of layers.

### ISSUE THREAD

**Issue by mike-000** [openlayers/openlayers#9397]
In OpenLayers 3/4/5 performance remains acceptable when there are a large number of layers due to use of multiple ImageStatic sources, for example this test script https://stackoverflow.com/questions/55379570/openlayers-multiple-georeferenced-images/55380903#55380903 and this KML ground overlay parser (first snippet) in https://stackoverflow.com/questions/52082468/kml-openlayers-groundoverlay-element-that-doesnt-have-document-tags-not-loadi/52093649#52093649  However, when substituting the OL5 build with OL6 beta 3 neither of those perform well enough to be usable.

**Comment by ahocevar** [comment]
This is correct, but only in the rare corner case where the source images of all layers are much smaller than the world extent. In all other cases, v6 will perform better than v5.

The reason is that in v6, a canvas with the full map viewport size is created for each layer, whereas in v5, all images are rendered directly to the map's target canvas. The reason for this is to continue to allow canvas manipulation with prerender and postrender events.

**Comment by mike-000** [comment]
I can't imagine why the questioner needed 200.  40 ground overlay images from a KML is a more realistic limit.  When those have been cut into tiles from a single image a single tile layer will be more efficient in any version, but identifying a potential grid is a bit ambitious for parser blindly reading a KML file (although given a url template for the tiles I think it could do it, but that's a TODO).

**Comment by jeroenvheel** [comment]
@ahocevar if all Layers gets it’s own canvas how can this perform on a tablet or mobile device where the memory it can use is much smaller than a desktop browser.

**Comment by ahocevar** [comment]
Fixed with #9584.
