### ISSUE TITLE
Major stuttering on Edge when panning

### ISSUE THREAD

**Issue by FINDarkside** [openlayers/openlayers#9403]
**Describe the bug**
There seems to be a big performance issue on Edge. When panning the map, the panning isn't smooth at all and stutters for long periods of time. I've done performance profiling on Edge and there's 3 things that stand out:
### pointermove event is handled very often. 
Sometimes multiple times in a millisecond. In the image you can see, how it's supposedly handled 29 times in just 50ms.  
![Pic](https://i.gyazo.com/9653dcca1bd4873ead1058d1ae73c8be.PNG)

### Paint and animation frame callback happens rarely

Despite (or because of) the huge number of these pointermove events, paint and animation frame callback is fired very rarely, about 11 times a second when I profiled it.

### Big empty gaps
Now this is not very scientific as I did manually pan the map. But given that the gaps are on consistent intervals I'm suspect it might not be because I would have stopped panning for a short period of time. In addition these gaps are usually either preceded or followed by unusually long pointermove event.
![Image](https://i.gyazo.com/4920711f0252be003557e8f58c52edf5.png)
![Closeup](https://i.gyazo.com/edb59a079251210d54a73801f1ebe085.png)
This might not be related to the issue though, since the repaint would have still been about 11 times a second even without these gaps.

**To Reproduce**
This issue can be produced on [demo page](https://openlayers.org/en/latest/examples/mobile-full-screen.html) with Edge 42 on Windows 10.

I also profiled the same map on Chrome, and on Chrome animation frame and repaint happened every time after pointermove event.

**Comment by ahocevar** [comment]
Can you please try if this also happens with the [v6 beta version](https://openlayers.org/en/latest/examples/mobile-full-screen.html) of the example? The renderers got a significant overhaul in the meantime.

**Comment by FINDarkside** [comment]
Yes, happens in the link provided as well.

**Comment by jeroenvheel** [comment]
I have alsp problems with the speed of the map with the latest beta verion (6).
i created a new Map with VectorImageLayers.and with drag and drop i add layers 30 layers based on (gpx) files and with each layer the performace of the map get worse until you can't pan the map
![ol-6b6 performance](https://user-images.githubusercontent.com/228655/56460137-34016500-639e-11e9-90b4-57afb6617c54.png)

**Comment by FINDarkside** [comment]
I doubt these are related. The original issue should be reproducible on demo pages without many layers, and is only problem on Edge.

**Comment by FINDarkside** [comment]
Bump. I can still reproduce this.

**Comment by alihuber** [comment]
Hello, we are experiencing the same behaviour, but not just in Edge, and with ol5 & 6.
The profiles look like this:  

![perf](https://user-images.githubusercontent.com/1455187/63703448-4b0f0280-c829-11e9-996a-83bcb951c6a8.PNG)

I also can see that the most time is spent in "pointerover" event handling, despite no such event registered.
It goes that far that merely constant moving the mouse cursor over an idle map will spike the CPU to a constant 10-25%, and this is not even while moving the map.

I tracked it down to `ol/events/Target.js` and `PluggableMap.js`. In `Target.js#dispatchEvent` in line 88 (https://github.com/openlayers/openlayers/blob/master/src/ol/events/Target.js#L88) it checks for registered listeners. If there are none, the method returns `undefined`. In `PluggableMap.js#handleMapBrowserEvent` on line 933 (https://github.com/openlayers/openlayers/blob/master/src/ol/PluggableMap.js#L933-L945) however it will check for `dispatchEvent() !== false`, but it will be `true` because `undefined !== false` and the whole following block including looping over all interactions and calling `handleEvent` and whatnot will be executed over and over. Could this have something to do with the problem? Or am I missing something important, like defining `pointer-events: none` on certain elements etc.?

**Comment by ahocevar** [comment]
Thanks for reporting this @alihuber. I have started a pull request (#9883) that should improve the situation.

**Comment by flexjoly** [comment]
Hi, 
We are implementing osm/openlayers (v5.3) in our application. (coming from google.maps)

I found this constant rendering of pointerover (not documented)  and pointermove. (see: [#9881](https://github.com/openlayers/openlayers/issues/9881#issuecomment-525716895))

I don't see the purpose of always capturing those events. I think those are only needed when drawing lines, freehand etc, zooming, panning. That is mostly after a click/keyboard/touch. 

is it possible to disable these events? Or can these be disabled by default and only activated when needed?

**Comment by alihuber** [comment]
I did some more digging. In the screenshots above, the left one is taken from embedding Openlayers in an React application, the right profile was taken from the demo page (mobile-full-screen.html). What is particularly strange about this is in an React app it will have major performance issues, e.g. with the giantic 500ms "pointerover" event that does effectively nothing but gobbles up all CPU time. No matter what I do with the map I see 95 - 99% spent in "pointerover", just by moving the cursor, and no matter how long I record the profile. On the right side however the "pointerover" event is also there, but of the few seconds of recording it spends only 50ms there which I think is normal (but the event does absolutely nothig as well).

With Edge and my React app the profile is like the one mentioned by @FINDarkside, with all those scattered pointermove AND mousemove events, but no huge initial pointerover. The map is stuttering nontheless, any interaction like moving the map is extremely sluggish, but I can't find out why because all JS execution seems normal.
With the mobile-full-screen example on Edge I experience absolutely no stuttering, despite having also scattered pointermove events in the profile, but everything JavaScript-related looks ok.

At first I thought it might be some browser extension like React devtools or whatever, ore there is something wrong with the way I setup Openlayers and React, or React does something funny with pointer events.

On Firefox however the huge initial pointerover event is not happening on either application (react or mobile full-screen), and the events are about the same as in Edge and I have no stuttering or (visible) performance issues at all.

I have no idea where to go from there, since all other apps I worked on have Openlayers 4x within an non-React app and have none of these issues. Furthermore, all browsers seem to do something different; Edge will fire both 'pointermove' and 'mousemove' events, Chrome is spending all its time in 'pointerover', but only when I use Openlayers with React, and Firefox does not have any issues at all.

**Comment by flexjoly** [comment]
What if OL would set far less event-triggers by default?
Maybe it is stupid of me (being quite new to OL) suggesting this 😬  but I give it a try, as a plain-vanilla-divaeloper 🙈 😆 

For example: every small object has listeners to: onchange, onadd etc. Most of the listener are never needed or used. Maybe only 10% of the listeners is used. Maybe 20%.
But all of them are constantly monitored and that costs performance. 
What if most event-listeners are off by default, but can be easily activated...?

**Comment by FINDarkside** [comment]
Bump. I can still reproduce this with Edge 44.
This is what the fps graph looks like when I start dragging: <img src="https://i.gyazo.com/9df5b73b1b6d892698a5c3b258d9c840.png">

Chrome looks smoother even with 6x cpu throttling.

**Comment by FINDarkside** [comment]
Actually, can't reproduce with Edge 44, it only stutters when recording performance profile now. Not sure if it's because something is different on my laptop, update for ol or because of the updated Edge.

**Comment by alihuber** [comment]
On my part this can be closed. It had something to do with React and a component re-rendering relentlessly.

**Comment by FINDarkside** [comment]
I'll close this then. Hard to say if the lags were simply because Edge has worse performance than Chrome. Edge performance profiling cripples the performance so badly it makes all the results useless. So even though the performance profile has some oddities they could be caused by the performance profiling tool.
