### ISSUE TITLE
Precision Problem with WebGLPointsLayerRenderer and large Coordinates

### ISSUE THREAD

**Issue by Kai-W** [openlayers/openlayers#9479]
In the Following exampel im using EPSG:3857 and a coordiante at 7 *10^6. When Mooving the Map the point is jumping in y direction.
https://codesandbox.io/embed/qv8zlqpzkq
This is effect appears to be a floating point precison problem with large numbers. In the x direction with a smaller coordinate the effect is present but smaller.

**Comment by jahow** [comment]
Good catch! I'll try to look into it asap. Thanks

**Comment by jahow** [comment]
After a bit of research, fixing this would be non trivial:
* either data isn't spread all over the world and it isbe possible to define a relative origin for the geometries in order to use smaller coordinates
* if the data is wide spread, another solution might be to periodically regenerate the buffers when zooming in and use a relative origin for the data subset, again allowing the use of lower coordinates
* a third solution might be to tile the data straight away instead of using one buffer for every points; this might be enough to lower the threshold at which the precision issue appears and make it invisible to the user (in my tests jittering appears at zoom level 24, I think if it appeared at zoom >28 the issue might be considered fixed)

**Comment by ahocevar** [comment]
Thanks for the research @jahow. I would not worry about jitter appearing at zoom 24. Going beyond 23 usually makes no sense anyway.

**Comment by jahow** [comment]
> I would not worry about jitter appearing at zoom 24. Going beyond 23 usually makes no sense anyway.

Actually I've checked @Kai-W's codepen again and there jittering is really noticeable at zoom 20 and beyond. Splitting the data straight away before generating the buffers might be a good option, and it might also fix the fact that a layer having a lot of points (eg 80,000) will sometimes fail to render on mobile.

**Comment by Kai-W** [comment]
Using the view center as an relative origin will probably be the most efficient way of removing the Jitter for all Zoom Levels. The disadvantage is the constant regeneration of the buffers. 
The number of recreations could be reduced by introducing a distance Metric between the datasetCenter and the viewCenter. If the distance is to big for a specific Zoom Level the buffer gets regenerated with the current viewCenter

**Comment by jahow** [comment]
Yep, that would work too (regenerating buffers can be done once in a while and should not kill FPS). 

Anyway, one of the big advantages of webGL was that we didn't have to select a subset of features before rendering, thus requiring spatial computations such as rbush etc. Even if we have to abandon this disadvantage, I'd strongly recommend chosing an approach as simple as possible to keep the webgl code easy to maintain and performant, maybe at the cost of some imprecision.

**Comment by Kai-W** [comment]
I made a quick Test. i think dividing the Data is more complicated than adding the Center Point
https://github.com/Kai-W/openlayers/commit/4efe4a84e133d8f9afdc3a9d0fd0acf198c0344f
