### ISSUE TITLE
Browser detection and feature activation

### ISSUE THREAD

**Issue by mea-alexanm** [openlayers/openlayers#9506]
Hi all,

we are using OpenLayers in an windows application by embedding a browser control and opening the map. But we also support opening our map just in the normal browser. For embedding the browser we use the IE activeX control. The issue we now have is that although we set to use the EDGE rendering engine there is a different behavior when using the ActiveX control and the standalone IE11. This seems to be because detecting which features should be available is done by the browser version reported. And while IE11 standalone reports IE11 and everything is fine, the activeX control reports IE9 and therfore many advanced features are disabled there.

In order to have a consistent set of features it would be nice to detect supported features of the browser instead of enabling them by the browser version reported.

What do you think about this?

Thx
Markus

**Comment by ThomasG77** [comment]
> This seems to be because detecting which features should be available is done by the browser version reported.

You are right but OpenLayers does not manage this part. It's in the application code by using https://polyfill.io web service like illustrated in samples e.g the excerpt below:
```html
    <!-- The line below is only needed for old environments like Internet Explorer and Android 4.x -->
    <script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=requestAnimationFrame,Element.prototype.classList,URL"></script>
```
If you want features detection, use [modernizr](https://modernizr.com) and load polyfills on demand instead of using polyfill.io webservice to avoid the issue you got with browser detection. I don't think things has to change at OpenLayers level: it's the application developer responsibility IMHO.

**Comment by fredj** [comment]
OpenLayers runs on all modern browsers that support HTML5 and ECMAScript 5.
For older browsers, use the polyfill.io and modernizr as suggested by @ThomasG77 

See https://github.com/openlayers/openlayers#supported-browsers
