### ISSUE TITLE
Tutorials not working

### ISSUE THREAD

**Issue by maristhek** [openlayers/openlayers#9588]
The code in the OpenLayers tutorials, Getting started, Basics etc. does not work.
It opens a web page and shows a blank page.

**Comment by ahocevar** [comment]
Thanks for your bug report. Please post the links to the pages containing code samples that do not work for you.

**Comment by milahu** [comment]
same here, we also use [the tutorial](https://openlayers.org/en/latest/doc/tutorials/bundle.html)

error is

    index.js:1:7: Cannot resolve dependency 'ol/ol.css'
    index.js:3:22: Cannot resolve dependency 'ol/layer/Tile'

maybe we forget to run `npm init`?

our fix: install `ol` and `parcel-bundler` globally with

    sudo npm install -g ol
    sudo npm install -g --save-dev parcel-bundler

to quote the [npm docs](https://docs.npmjs.com/files/folders):

> Local install (default): puts stuff in ./node_modules of the current package root.
Global install (with -g): puts stuff in /usr/local or wherever node is installed.
Install it locally if you’re going to require() it.
Install it globally if you’re going to run it on the command line.
If you need both, then install it in both places, or use npm link.

**Comment by ahocevar** [comment]
It should not be necessary to install anything globally. Can you double-check if you followed every single step? Also at which step exactly do you get the above error?

**Comment by ThomasG77** [comment]
@milahu IMHO, it's because you don't exactly follow the tutorial at least for Parcel.
I wonder how you were able to run the task `npm start` that would make failed the build step as you don't have a `package.json`. If you only tried to run directly `parcel index.html` or `parcel build --public-url . index.html`, it will not work due to Node behaviour and you will get the mentioned error.

You need absolutely to use `npm init`. When you run it, it generates a `package.json` in the directory. Without it, Node is unable to guess the root to search npm packages, nor the projects dependencies in node_modules. It's what cause the error you mentioned.
```
index.js:1:7: Cannot resolve dependency 'ol/ol.css'
index.js:3:22: Cannot resolve dependency 'ol/layer/Tile'
```

To illustrate the role of `npm init`. After both `npm install ol` and `npm install --save-dev parcel-bundler`, you will that the content of `package.json` has changed from

```
  "name": "new-project",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}
```
to
```
{
  "name": "new-project",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "ol": "^5.3.2"
  },
  "devDependencies": {
    "parcel-bundler": "^1.12.3"
  }
}
```

PS: I've reproduced the mentioned error before answering

**Comment by milahu** [comment]
> at which step exactly do you get the above error?

at `npm start`, but we cant reproduce any more
now node is using the local install as expected

we really just forgot to run `npm init`

please consider to change text format in the tutorial
from inline code to code block

**Comment by maristhek** [comment]
A copy of my package.json :
{
  "name": "currentlocation",
  "version": "1.0.0",
  "description": "OL Map",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "parcel index.html",
    "build": "parcel build --public-url . index.html"
  },
  "author": "Em the K",
  "license": "ISC",
  "dependencies": {
    "ol": "^5.3.2"
  },
  "devDependencies": {
    "parcel-bundler": "^1.12.3"
  }

**Comment by ThomasG77** [comment]
@maristhek I clearly don't see why it's not working on your side. The content I get following parcel tutorial (excluding generated `node_modules` and `dist` directories) is available at https://gist.github.com/ThomasG77/15e944386eb641db4217d1ebcf074e33
You may find out your issue by doing a diff on my clone repo and your project using a software like "meld" (there are others)
You can also use the [official available repo for parcel](https://github.com/openlayers/ol-parcel) to directly get a working project
PS: this repo uses OpenLayers 5.1.2 instead of 5.3.x and `main.js` file instead of `index.js` like in the tutorial otherwise, no difference.

**Comment by fredj** [comment]
> we really just forgot to run `npm init`
> 
> please consider to change text format in the tutorial
> from inline code to code block

@milahu it was changed in #9109
