### ISSUE TITLE
GeoJSON.readFeature does not use projection options passed to constructor

### ISSUE THREAD

**Issue by bkoot** [openlayers/openlayers#9661]
**Description**
When creating an instance of ol/format/GeoJSON it is possible to specify dataProjection and featureProjection.

The documentation states:
dataProjection: Default data projection.
featureProjection: Projection for features read or written by the format. Options passed to read or write methods will take precedence.

When specifying these options and using the readFeature function, I would expect that the dataProjection and featureProjection options of the format instance would be used.

The documentation of the readFeature function states:
dataProjection: Projection of the data we are reading. **If not provided**, the projection will be derived from the data (where possible) or **the dataProjection of the format is assigned (where set)**. If the projection can not be derived from the data and if no dataProjection is set for a format, the features will not be reprojected.

**The problem**
In the latest version of OpenLayers the readFeature function ignores the projection settings passed to the constructor of ol/format/GeoJSON. So it is necessary to specify the same projection settings when calling the readFeature method.

I noticed that setting only the featureProjection (and thus omitting the dataProjection) when calling readFeature does work. 

**Example**
I created a small example in codesandbox: [https://codesandbox.io/s/featureselection-m2wes](https://codesandbox.io/s/featureselection-m2wes)

Comment out lines 44 and 45 in index.js to see that the point in the center is no longer showing up on the map.

**Comment by mike-000** [comment]
What you are seeing is in documentation, but perhaps the documentation could be better.

`dataProjection` is working as you expected.

For the constructor the documentation states:

`featureProjection`: Projection for features read or written by the format. Options passed to read or write methods will take precedence.

Under `readFeature `the documentation states:

`featureProjection`: Projection of the feature geometries created by the format reader. If not provided, features will be returned in the `dataProjection`.

Which implies you would always need to pass `featureProjection `to `readFeature `if you need the feature reprojected (otherwise it will appear in the Gulf of Guinea)


`featureProjection `in the constructor is used in vector sources:
```
var geoJsonFeature = {
  type: "Feature",
  geometry: {
    type: "Point",
    coordinates: [162395, 492192]
  }
};

var vectorSource2 = new VectorSource({
  url: "data:text/plain;charset=utf-8," + encodeURIComponent( JSON.stringify(geoJsonFeature) ),
  format: new GeoJSON({
    dataProjection: "EPSG:28992",
    featureProjection: "EPSG:3857"
  })
})
```
If vectorSource2 is used as the source of another vector layer in your map the feature will show where expected.

**Comment by bkoot** [comment]
Ah, I did not notice that the readFeature method will ignore the featureProjection passed to the constructor. 

I didn't expect this behavior when reading 'Projection for features read or written by the format. Options passed to read or write methods will take precedence.' in the documentation of the featureProjection option of the constructor.

Closing the issue as it works as documented.
