### ISSUE TITLE
Update export pdf example to include scalebar

### ISSUE THREAD

**Issue by hutch120** [openlayers/openlayers#9674]
Hi All,

The example code below exports visible layers to an image (dataURL). However, it doesn't include controls like the scalebar or north arrow.

```
var map = new Map({...})
map.once('rendercomplete', function (event) {
  const mapDataURL = event.context.canvas.toDataURL('image/png')
  // mapDataURL includes visible layers but no scale or north arrow.
})
map.renderSync()
```

Firstly, is it possible to include the scalebar and or other controls, and if so, can we include this in the export pdf example? Or is there another example I haven't seen that covers this?

References:
https://openlayers.org/en/latest/examples/export-pdf.html
https://github.com/openlayers/openlayers/issues/8898

**Comment by mike-000** [comment]
It's because it exports the canvas and controls are not rendered on the canvas.  In the OpenLayers 6 version https://openlayers.org/en/master/examples/export-pdf.html where each layer has its own canvas the example exports the map div, so if wanted the controls you would simply remove the filter from the `exportOptions` (although #9665 will need to be resolved).  `html-to-image` should also work with an OpenLayers 5 map div.  Alternatively the ol-ext library https://viglino.github.io/ol-ext/ has canvas controls including scaleline and compass.

**Comment by hutch120** [comment]
@mike-000 Legend... thanks for the tip on ol-ext. This is what I ended up with.

```
import OLScaleLine from 'ol-ext/control/CanvasScaleLine'
import OLStyleStyle from 'ol/style/Style'
import OLStyleText from 'ol/style/Text'
import OLStyleStroke from 'ol/style/Stroke'
import OLStyleFill from 'ol/style/Fill'

export default function (map) {
    const ctrl = new OLScaleLine()
    ctrl.setStyle(
      new OLStyleStyle({
        text: new OLStyleText({
          font: '14px Roboto',
          fill: new OLStyleFill({
            color: 'grey'
          })
        }),
        stroke: new OLStyleStroke({ width: 2, color: 'grey' })
      })
    )
    ctrl.element.style.left = '20px'
    ctrl.element.style.bottom = '30px'
    ctrl.setMap(map)
}
```
