### ISSUE TITLE
TileWMS cacheSize

### ISSUE THREAD

**Issue by gligi** [openlayers/openlayers#9716]
**Describe the bug**
Tiles (WMS) are not cached locally after they are fetched from the geoserver web cache.

**To Reproduce**
Pan the map forth and back. During the drag the tiles outside the view (boundary) are not visible although previously fetched.

**Expected behavior**
Tile already fetched should be rendered instantly and only replaced if they actually changed

What is the function of the cacheSize anyway? Other than the description about the default size, there is no description whatsoever about the functionality.

**Comment by EduardTrutsyk** [comment]
I guess, I have the same issue with `VectorTile` source. I investigate the issue a bit, and from my point of view it happens when `Tile` was disposed but still in `TileQueue`, and when `ol` calls `dequeue` the `keyFunction_` returns incorrect key for the tile(because the tile was disposed): https://github.com/openlayers/openlayers/blob/v5.3.x/src/ol/structs/PriorityQueue.js#L93
In this case, it will not delete the element from `queuedElements_` but `pop` the element from `elements_` and `isKeyQueued` method will returns incorrect value: https://github.com/openlayers/openlayers/blob/v5.3.x/src/ol/structs/PriorityQueue.js#L184
This method used to define to load the tile or not: https://github.com/openlayers/openlayers/blob/v5.3.x/src/ol/renderer/Layer.js#L226

I hope you understand what I mean :smile:
Unfortunately, for now I have no idea how to fix it.
