### ISSUE TITLE
geojson is not displayed on the map

### ISSUE THREAD

**Issue by welltothebone** [openlayers/openlayers#9832]
**Describe the bug**
geojson from the example below is not displayed on the map. If I for example go to http://geojsonlint.com/ and paste the very same geojson from the sample it gets displayed. 

**To Reproduce**
import 'ol/ol.css';
import {Map, View} from 'ol';
import {Tile as TileLayer, Vector as VectorLayer} from 'ol/layer.js';
import {OSM, Vector as VectorSource} from 'ol/source.js';
import GeoJSON from 'ol/format/GeoJSON.js';

let geoJson = {
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "properties": {},
            "geometry": {
                "type": "Polygon",
                "coordinates": [
                    [
                        [-50.0, 80.0],
                        [50.0, 80.0],
                        [50.0, 91.0],
                        [-50.0, 91.0],
                        [-50.0, 80.0]
                    ]
                ]
            }
        }
    ]
};

let vectorSource = new VectorSource({
    features: (new GeoJSON()).readFeatures(geoJson, {featureProjection: 'EPSG:3857'})
});

let vectorLayer = new VectorLayer({
    source: vectorSource
});

const map = new Map({
    target: 'map',
    layers: [
        new TileLayer({
            source: new OSM()
        }),
        vectorLayer
    ],
    view: new View({
        center: [0, 0],
        zoom: 0
    })
});

**Expected behavior**
geojson is displayed on the map.

**Comment by mike-000** [comment]
Latitude 91 is invalid.  It will work with 90.0

**Comment by welltothebone** [comment]
Thanks. Can you please explain why i can draw outside (See official draw example: https://openlayers.org/en/latest/examples/draw-features.html) of the bounds but not add features (in this case as geojson) having coordinates outside of the bounds. This is not very convenient.

Is there an easy way to prevent drawing outside? Thanks!

**Comment by mike-000** [comment]
In OpenLayers 6 that will be easy as by default the view will be constrained to the defined extent of the view projection if it is a global projection.

There is however nothing wrong with being able to draw outside the defined extent since that ends at an arbitrary line just above 85 degrees north used by tile grids such as Google and OSM and the real world ends at the pole at 90 degrees.  Since version 3.19.0 OpenLayers transforms from LonLat to EPSG:3857 have reduced the latitude of points outside that extent, but transforms using proj4 work as expected (although proj4 won't transform 90 degrees as that is infinite in web mercator).  Here is an example of your geojson (using 89.9999 instead of 90 degrees) using proj4 https://codesandbox.io/s/draw-features-yh2qe
