### ISSUE TITLE
Multi line geometry (one feature) with 1 milion of lines is too slow (event with 100 000)

### ISSUE THREAD

**Issue by MarianKai** [openlayers/openlayers#9835]
Drawing so many lines into canvas directly is super-fast, so why openlayer cannot handle it? I would understand if it would be features.. but it is just one.
[feature.txt](https://github.com/openlayers/openlayers/files/3481423/feature.txt)

**Comment by MarianKai** [comment]
Drawing so many lines into canvas directly is super-fast, so why openlayer cannot handle it? I would understand if it would be features.. but it is just one.

[geom.txt](https://github.com/openlayers/openlayers/files/3481416/geom.txt)

**Comment by ahocevar** [comment]
Can you please provide codesandbox.io (or similar) examples to show how you render that file with OpenLayers and how you render it directly to the canvas?

**Comment by MarianKai** [comment]
Example of drawing approx 100 thousand lines using openlayer (one multi line geometry):
https://codesandbox.io/embed/mystifying-clarke-8g0jy

And here is basically the same thing regarding how many lines have to be drawn using canvas
https://codesandbox.io/embed/gallant-curie-ofj7g

I tested canvas, it could handle 10 milions of lines, it took like 2 seconds to draw, but still. It's obviously not the canvas who is slow. So I wonder what am I missing? Is the transformation from lat/long to x/y on canvas so expensive?

**Comment by MarianKai** [comment]
Anything to say?

**Comment by jahow** [comment]
Hi,

I've looked into your example but the problem is that the drawing step locks the browser up. So I've made a few experiments on my side:
* Drawing one long line with 100k vertices: https://codesandbox.io/embed/wild-night-pjm2r?fontsize=14
  This works well, also similarly to your test with the Canvas API it takes around 2 seconds to draw
* Drawing a multi line string with 100k lines in it: https://codesandbox.io/s/stupefied-albattani-hocvk
  Also works pretty well

My conclusion is that there may be something wrong with the dataset you use, although I must admit I did not dig into it much further.

**Comment by MarianKai** [comment]
Hi,
thank you, well I don't know why it locks up for you, for me it works fine. Anyway I also managed to make it faster by just combining lines into multilines whenever possible, so e.g. rather than having 100k lines, I have 1000 multilines.  I will do more test and get back with some new info.
