### ISSUE TITLE
Openlayers 5: Drag&Drop dom element somewhere on map

### ISSUE THREAD

**Issue by novumcoder** [openlayers/openlayers#9841]
**Describe the bug**
Not really sure if this is a bug: i use Openlayers 5 showing a simple map and now placed a simple icon on the bottom left of the map allowing the user to drag it somewhere on the map, drop it, in order to place a feature at that location.

Looking at the API Openlayers 5 does only offer drag functions for features, but i want to drag a simple DOM element onto the map in order to get the coordinate and place a feature.

**To Reproduce**
Added attribute draggable="true" to my DIV element making it draggable
added attribute ondrop="ondrop" eventhandler but also map.on('drop', ...) on my map object but also on my draggable element in order to see if it gets fired when i drop the DIV element onto map. Nope, not working.
Then i tried to implement my own drag&drop by using mousedown, mousemove and mouseup events. Everything works fine except my mouseup event. When i release the mouse button, no mouseup event is triggered, no matter if i put the event listener to my document ($(document).on('mouseup'...) or my map object or the DIV element itself.
How can i do that. It is very similar to Google Map's Street View where you drag the small yellow figure somewhere on the map to open the street view at that location. In my case i simply want to put a basic feature at that location.

**Expected behavior**
Problem is getting the drop event. Nothing happens when i drop the dom element somewhere on the map. I expected to get my drop event fired providing me the event object either with pixel coordinates or even better with EPSG coordinates so i can put a feature at that location.
Looks like drop events are prevented?

Some code of mine i tried with a :

`<div id="map" class="map" ondrop="ondrop">`

`<div id="dragdrop" draggable="true"><img src="dragme.png"/></div>`

`function ondrop(e) {
  console.log(e);
}
`

**Comment by jahow** [comment]
It looks like more of an issue with the drag and drop HTML5 API:
https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API

Doing `map.on('drop')` will not work because the OL map does not support this kind of event, but the containing div should, just like any other HTML element. So, picking up from your sample code, something like (untested code):
```js
document.getElementById('map').addEventListener('drop', ondrop);
```

You can then read the X and Y of the drop position using `evt.clientX` and `evt.clientY`, and from the use `map.getCoordinateFromPixel` to transform that to a set of world coordinates, and create your feature from this.
