### ISSUE TITLE
React project import ol，add geojson fail

### ISSUE THREAD

**Issue by zf329398320** [openlayers/openlayers#9854]
![image](https://user-images.githubusercontent.com/14149569/62939452-e3f25680-be03-11e9-90ee-8e28390c113e.png)

![image](https://user-images.githubusercontent.com/14149569/62939510-0d12e700-be04-11e9-928a-8ad076f4d117.png)
![image](https://user-images.githubusercontent.com/14149569/62939755-91656a00-be04-11e9-85a0-10a5e4d002c8.png)
![image](https://user-images.githubusercontent.com/14149569/62939676-61b66200-be04-11e9-9b1a-dcdc85b29fa6.png)
![image](https://user-images.githubusercontent.com/14149569/62939477-ff5d6180-be03-11e9-92fe-e88be63a8938.png)
![image](https://user-images.githubusercontent.com/14149569/62939526-1439f500-be04-11e9-8b66-0d8cf380c5fe.png)
在react项目中引入ol，加载高德矢量地图为什么请求不到

**Comment by tschaub** [comment]
From the pictures above, it isn't clear if the problem you are seeing is about rendering GeoJSON data in a map or about using OpenLayers with React.

If the problem is about using OpenLayers with React, you'll need to use a "ref" for a React element as the target for the map.  Here is an example using the `useRef` hook: https://codesandbox.io/embed/reactol-dxblt 
And here is an example with a class that extends React Component (using `createRef` for the ref): https://codesandbox.io/embed/reactol-class-exlgu

(In those examples, there is just a one way binding set up for the center state - setting up a two way binding is a bit more involved.)
