### ISSUE TITLE
how to rotate overlay

### ISSUE THREAD

**Issue by pravinmitta** [openlayers/openlayers#9884]
Hi i've place image overlay (image reprojection) in openlayer, but based on the state(placement) of the building i need to rotate the image. if anyone have idea regarding the issue can you guys help me out on it. 

Here is the code for placing the image overlay on the map

proj4.defs(
      "EPSG:18111",
      "+proj=tmerc +lat_0=" + latlng.lat + " +lon_0=" + latlng.lng +
      '+ellps=airy ');
    
    register(proj4);

    var imageExtet = [2,2, 50, 50];
    var image = new ImageLayer({
      source: new Static({
        url: '../../assets/tv.svg',
        crossOrigin: "",
        projection: "EPSG:18111",
        imageExtent: imageExtet
      })
    });

    this.map.addLayer(image);

    this.map.getView().setCenter(transform(getCenter(imageExtet), 'EPSG:18111', 'EPSG:3857'));

If any help regarding this it'll be helpful

**Comment by mike-000** [comment]
See #4949  Since you are already reprojecting defining a rotated EPSG:18111 projection similar to https://codepen.io/anon/pen/LomLYe would be the simplest way.

**Comment by pravinmitta** [comment]
i didn't get you @mike-000, Can you give me brief about it

**Comment by mike-000** [comment]
> i didn't get you @mike-000, Can you give me brief about it

Here is the OpenLayers ImageStatic example rotated 45 degrees https://codesandbox.io/s/reprojection-image-z0uit  All the addition setup is done in the rotateProjection function

**Comment by pravinmitta** [comment]
Thanks Mike, Your suggestion resolved my rotation issue, i've one doubt i'm uploading and plotting image on the map using leaflet and from the api also i'm getting the bounds which is generated by leaflet while placing the overlay in openlayer i'm getting the below issue. if you are not clear with my explanation can you tell me
![indoor](https://user-images.githubusercontent.com/35287775/63832805-33ea2500-c98f-11e9-8223-a60707c40852.png)

**Comment by mike-000** [comment]
My approach was intended to be compatible with KML ground overlays.  The extent is what the image would occupy when unrotated in its native projection (note the OSM is reprojected)
![image](https://user-images.githubusercontent.com/49240900/63843895-0d23f280-c97f-11e9-830c-2de675a90470.png)

then  it is rotated around its center
![image](https://user-images.githubusercontent.com/49240900/63843915-1b720e80-c97f-11e9-9e4c-8070c870526d.png)

and only then is it reprojected (with the OSM now in native projection)
![image](https://user-images.githubusercontent.com/49240900/63843935-2462e000-c97f-11e9-9765-3e72ca770ef7.png)

Other platforms such as Leaflet might take a different approach and therefore any extents they define could be different, for example it could be the bounding extent of the rotated image (in red above) or the image might be rotated around a corner instead of its center.  It might even be rotated after reprojection as below (although I would consider that to be wrong!)
![image](https://user-images.githubusercontent.com/49240900/63845207-87557680-c981-11e9-918c-2a8e892ca029.png)

**Comment by pravinmitta** [comment]
Thanks Mike :)
