### ISSUE TITLE
Animation stop on click

### ISSUE THREAD

**Issue by Malgier** [openlayers/openlayers#9917]
Within my web application I have found if a user clicks whilst the zoom animation is in progress, the animation/zoom will stop. I noticed that similar behavior is found within the animation example section of openlayers site, https://openlayers.org/en/latest/examples/animation.html if you select an animation and then click the map whilst its still going the same bug happens. Is there a fix for this, or any way to work around it.

Thanks

**Comment by tschaub** [comment]
This is intentional behavior, if the user tries to zoom, pan, rotate, or stop the map during an animation, the animation stops to let the user interact with the map.

If you want to disable user interaction during an animation (or any other time), you can deactivate the map interactions using a function like this:
```js
function freeze() {
  map.getInteractions().forEach(interaction => {
    interaction.setActive(false);
  });
}
```

Then to reactivate the interactions, you could run a function like this:
```js
function thaw() {
  map.getInteractions().forEach(interaction => {
    interaction.setActive(true);
  });
}
```

So your overall animation would go something like this:
```js
freeze();
view.animate({center: someNewCenter, zoom: someNewZoom}, thaw);
```

If you have a more complex animation, just call `thaw` when all the parts are done.

Here is a full example:  https://codesandbox.io/embed/unstoppable-animation-vbk1s?fontsize=14 (click the "fly" button to start an unstoppable animation).
