### ISSUE TITLE
WMTS.createFromCapabilitiesMatrixSet does not create TileGrids with TileRanges that respect TileMatrixSetLimits from capabilities.

### ISSUE THREAD

**Issue by jasontk19** [openlayers/openlayers#9949]
**Describe the bug**
The name of this function and its parameters give the indication that a WMTS TileGrid will be created that respects the `TileMatrixSetLimits` defined in the capabilities document.  It accepts an `opt_matrixLimits` parameter which is defined as _"An optional object representing the available matrices for tileGrid"_.  However, the MinTileRow/MaxTileRow and MinTileCol/MaxTileCol values are not even looked at to determine appropriate TileRanges.

Perhaps I am misunderstanding what this function is supposed to do but, it appears to either be partially implemented or, not fully documented in order to make clear what should be possible given the current implementation.

**Expected behavior**
When invoking `createFromCapabilitiesMatrixSet` with `opt_matrixLimits`, a WMTS TIleGrid should be created with TileRanges that respect the limits defined in the `opt_matrixLimits` parameter.

**Comment by jahow** [comment]
I think the `matrixLimits` parameter is just used as a kind of filter for the matrix sets to be used; all the matrix sets that are not in the `matrixLimits` object will not be included in the tile grid.

This is just a rough reasoning based on the code here:
https://github.com/openlayers/openlayers/blob/346cd562ee000a015f26d8e651a43b03829962ff/src/ol/tilegrid/WMTS.js#L147-L161

The issue here is IMO with the documentation. Would you agree on that? Thanks

**Comment by jasontk19** [comment]
@jahow I think you're right.  I was hopeful that there would be support for set limits, so that we could avoid requesting tiles that we know don't exist, but agree that based on the current implementation this does not appear to be the intended behavior.

**Comment by Feofilakt** [comment]
Hello! I've just encountered a bug where WMTS requests are sent with wrong TileCol and TileRow beyond the limits specified in TileMatrixLimits.
